var searchData=
[
  ['»_0',['»',['../spec-architecture.html#autotoc_md272',1,'10. Contrainte « éditeur intégré »'],['../guide-boucle.html#autotoc_md61',1,'La « spirale de la mort »'],['../lot-91.html#autotoc_md809',1,'La revue (neuf « oui »)'],['../lot-02.html#autotoc_md419',1,'Le découpage retenu — et pourquoi il n&apos;est pas « une seule &lt;span class=&quot;tt&quot;&gt;HmiLib&lt;/span&gt; »'],['../guide-editeur.html#autotoc_md132',1,'Le panneau « Plans »'],['../manuel-partager-niveau.html#autotoc_md961',1,'Mélanger plusieurs tailles de caméra dans un même niveau (mode « Par salle »)'],['../namespacecore.html#autotoc_md1004',1,'Une seule règle pour « se tenir ici »'],['../lot-19.html#autotoc_md548',1,'Une seule source de vérité pour « peut-on se tenir ici »'],['../classcore_1_1BattleGrid.html#autotoc_md981',1,'Une seule source de vérité pour « peut-on se tenir ici »']]],
  ['»_20_3a_20auditer_20les_20calques_20sans_20les_20confondre_20avec_20f8_20lot_2051_1',['Le mode « définition des textures » : auditer les calques sans les confondre avec &lt;span class=&quot;tt&quot;&gt;F8&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;LOT-51&lt;/span&gt;)',['../guide-editeur.html#autotoc_md130',1,'']]],
  ['»_20_3a_20dessiner_20la_20route_20d_20un_20élément_20mobile_2',['L&apos;outil « Parcours » : dessiner la route d&apos;un élément mobile',['../guide-editeur.html#autotoc_md122',1,'']]],
  ['»_20_3a_20le_20monde_20une_20région_20une_20ville_20lot_2094_3',['12. L&apos;écran « Carte » : le monde, une région, une ville (LOT-94)',['../spec-interface-ihm.html#ihm-carte',1,'']]],
  ['»_20_3a_20un_20échafaudage_20et_20il_20est_20écrit_4',['« Nouvelle partie » : un échafaudage, et il est écrit',['../lot-68.html#autotoc_md718',1,'']]],
  ['»_20devient_20«_20carte_20»_20partout_5',['Le vocabulaire : « niveau » devient « carte », partout',['../lot-67.html#autotoc_md711',1,'']]],
  ['»_20partout_6',['Le vocabulaire : « niveau » devient « carte », partout',['../lot-67.html#autotoc_md711',1,'']]],
  ['»_20plutôt_20que_20dessiner_20un_20sprite_20à_20la_20fois_7',['Pourquoi « batcher » plutôt que dessiner un sprite à la fois',['../guide-rendu.html#autotoc_md224',1,'']]],
  ['»_20revient_20sur_20les_20cartes_20de_20l_20auteur_20_3a_20monde_20région_20ville_8',['LOT-94 — Les images du corpus quittent le dépôt ; l&apos;écran « Carte » revient sur les cartes de l&apos;auteur : monde, région, ville',['../lot-94.html',1,'lots']]],
  ['»_20se_20vérifie_20sur_20le_20diff_20pas_20sur_20l_20intention_9',['« Aucune valeur de règle dans le C++ » se vérifie sur le diff, pas sur l&apos;intention',['../lot-13.html#autotoc_md503',1,'']]],
  ['»_20une_20touche_20dans_20le_20gameplay_10',['Le principe : ne jamais coder « en dur » une touche dans le gameplay',['../guide-entrees.html#autotoc_md138',1,'']]]
];
