var searchData=
[
  ['jadg_5fassert_20jadg_5fassert_20un_20outil_20différent_0',['Assertions : &lt;a class=&quot;el&quot; href=&quot;Assert_8h.html#a2811f3d423b22f1a90179b4ed095f054&quot; title=&quot;JADG_ASSERT&quot;&gt;JADG_ASSERT&lt;/a&gt;, un outil différent',['../guide-journalisation.html#autotoc_md155',1,'']]],
  ['jadg_5fassert_20un_20outil_20différent_1',['Assertions : &lt;a class=&quot;el&quot; href=&quot;Assert_8h.html#a2811f3d423b22f1a90179b4ed095f054&quot; title=&quot;JADG_ASSERT&quot;&gt;JADG_ASSERT&lt;/a&gt;, un outil différent',['../guide-journalisation.html#autotoc_md155',1,'']]],
  ['jalon_2',['Jalon',['../lot-07.html#autotoc_md435',1,'']]],
  ['jamais_20coder_20«_20en_20dur_20»_20une_20touche_20dans_20le_20gameplay_3',['Le principe : ne jamais coder « en dur » une touche dans le gameplay',['../guide-entrees.html#autotoc_md122',1,'']]],
  ['jamais_20de_20cadrage_4',['Densité : un compromis de mémoire, jamais de cadrage',['../guide-rendu.html#autotoc_md228',1,'']]],
  ['jamais_20dessus_5',['Un seuil de corps se pose sous la valeur, jamais dessus',['../lot-36.html#autotoc_md513',1,'']]],
  ['jamais_20l_20inverse_6',['Enregistrer : valider avant d&apos;écrire, jamais l&apos;inverse',['../guide-editeur.html#autotoc_md111',1,'']]],
  ['jamais_20laisser_20de_20fichier_20tronqué_7',['Écrire un PNG sans jamais laisser de fichier tronqué',['../guide-atelier-pixel-art.html#autotoc_md34',1,'']]],
  ['jamais_20perdu_20de_20vue_8',['Le focus n&apos;est jamais perdu de vue',['../lot-66.html#autotoc_md531',1,'']]],
  ['jamais_20solide_9',['Pourquoi une pente (ou un arrondi) n&apos;est jamais solide',['../guide-physique.html#autotoc_md193',1,'']]],
  ['jamais_20un_20singleton_20joueur_10',['&lt;span class=&quot;tt&quot;&gt;CharacterSheet&lt;/span&gt; est un objet autonome, jamais un singleton joueur',['../lot-13.html#autotoc_md465',1,'']]],
  ['jet_11',['1. Le jet',['../spec-regles-dnd.html#autotoc_md361',1,'']]],
  ['jetons_20_3a_20une_20seule_20source_20deux_20portées_20étanches_12',['Les jetons : une seule source, deux portées étanches',['../guide-design-ihm.html#autotoc_md61',1,'']]],
  ['jetons_20purs_20à_20une_20application_20habillée_13',['De jetons purs à une application habillée',['../guide-design-ihm.html#autotoc_md62',1,'']]],
  ['jets_14',['LOT-12 — Dés, caractéristiques, jets',['../lot-12.html',1,'lots']]],
  ['jets_20trois_20usages_15',['3. Trois jets, trois usages',['../spec-regles-dnd.html#autotoc_md363',1,'']]],
  ['jeu_16',['jeu',['../guide-ecrans.html',1,'Écrans, navigation et boucle de jeu'],['../spec-gameplay.html#autotoc_md335',1,'5. États de jeu'],['../manuel-jouer.html#autotoc_md695',1,'Contrôles en jeu'],['../guide-ecrans.html#autotoc_md81',1,'Le viewport partagé : éditeur &lt;b&gt;et&lt;/b&gt; jeu'],['../lot-05.html',1,'LOT-05 — Modes de jeu'],['../guide-boucle.html#autotoc_md50',1,'Qu&apos;est-ce qu&apos;une boucle de jeu ?'],['../manuel-telecharger.html',1,'Télécharger et lancer le jeu']]],
  ['jeu_20et_20observabilité_17',['2. Pont avec le jeu et observabilité',['../spec-ia.html#autotoc_md338',1,'']]],
  ['jeu_20et_20outillage_18',['5. Intégration au jeu et outillage',['../spec-ia.html#autotoc_md341',1,'']]],
  ['jeu_20et_20pas_20de_20temps_20fixe_19',['Boucle de jeu et pas de temps fixe',['../guide-boucle.html',1,'guide']]],
  ['jeu_20f9_20',['Compteur de diagnostic en jeu (&lt;span class=&quot;tt&quot;&gt;F9&lt;/span&gt;)',['../guide-rendu.html#autotoc_md246',1,'']]],
  ['jeu_20lot_20h_2068_21',['8. Identité visuelle des écrans du jeu (LOT-H-68)',['../spec-interface-ihm.html#autotoc_md349',1,'']]],
  ['jeu_20mapping_20logique_22',['2. Actions du jeu (mapping logique)',['../spec-controles.html#autotoc_md276',1,'']]],
  ['jeu_20vidéo_23',['Pourquoi journaliser dans un jeu vidéo',['../guide-journalisation.html#autotoc_md145',1,'']]],
  ['jouer_24',['Jouer',['../manuel-jouer.html',1,'manuel']]],
  ['jouer_25',['Regarder l&apos;IA jouer',['../manuel-mode-ia.html',1,'manuel']]],
  ['jouer_20sans_20quitter_20l_20éditeur_26',['Essai immédiat : jouer sans quitter l&apos;éditeur',['../guide-editeur.html#autotoc_md110',1,'']]],
  ['jouer_20un_20niveau_20_3a_20hmi_3a_3agamesession_20réutilisée_27',['Jouer un niveau : &lt;span class=&quot;tt&quot;&gt;hmi::GameSession&lt;/span&gt; réutilisée',['../guide-ihm-qt.html#autotoc_md138',1,'']]],
  ['joueur_28',['joueur',['../lot-13.html#autotoc_md465',1,'&lt;span class=&quot;tt&quot;&gt;CharacterSheet&lt;/span&gt; est un objet autonome, jamais un singleton joueur'],['../manuel-partager-niveau.html#autotoc_md715',1,'Choisir comment la caméra suit le joueur']]],
  ['joueurs_20est_20un_20scan_20et_20sa_20graisse_20ment_29',['Le &lt;em&gt;Manuel des Joueurs&lt;/em&gt; est un scan, et sa graisse ment',['../lot-36.html#autotoc_md506',1,'']]],
  ['jour_30',['jour',['../lot-33.html#autotoc_md489',1,'Cinq défauts du lexique que les 94 noms ont mis au jour'],['../lot-43.html#autotoc_md519',1,'Trois défauts du corpus que ce lot a mis au jour']]],
  ['jour_20nuit_31',['&lt;span class=&quot;tt&quot;&gt;LOT-70&lt;/span&gt; — Horloge de partie et cycle jour/nuit',['../roadmap-010.html#lot-70',1,'']]],
  ['journal_20c_20est_20une_20exigence_32',['La restitution n&apos;est pas un journal, c&apos;est une exigence',['../lot-12.html#autotoc_md457',1,'']]],
  ['journal_20de_20combat_33',['Le journal de combat',['../roadmap-010.html#autotoc_md645',1,'']]],
  ['journalisation_34',['10. Assertions &amp;amp; journalisation',['../spec-conventions.html#autotoc_md296',1,'']]],
  ['journalisation_20et_20assertions_35',['Journalisation et assertions',['../guide-journalisation.html',1,'guide']]],
  ['journalisation_20par_20catégorie_36',['Les macros de journalisation, par catégorie',['../guide-journalisation.html#autotoc_md149',1,'']]],
  ['journaliser_20dans_20un_20jeu_20vidéo_37',['Pourquoi journaliser dans un jeu vidéo',['../guide-journalisation.html#autotoc_md145',1,'']]],
  ['json_38',['Chargement JSON',['../guide-niveaux.html#autotoc_md169',1,'']]],
  ['json_20liste_20de_20tuiles_20objets_39',['Format retenu (JSON, liste de tuiles-objets)',['../spec-niveaux.html#autotoc_md356',1,'']]],
  ['jump_20et_20wall_20slide_40',['6. Wall jump et wall slide',['../guide-physique.html#autotoc_md201',1,'']]],
  ['jusqu_20au_20vertical_20slice_41',['Le chemin critique jusqu&apos;au &lt;em&gt;vertical slice&lt;/em&gt;',['../roadmap-010.html#autotoc_md573',1,'']]],
  ['justanotherdndgame_42',['JustAnotherDnDGame',['../index.html',1,'']]]
];
