var searchData=
[
  ['gèle_20et_20pourquoi_0',['Ce que le mode combat gèle, et pourquoi',['../lot-18.html#autotoc_md425',1,'']]],
  ['général_1',['&lt;span class=&quot;tt&quot;&gt;LOT-83&lt;/span&gt; — Compagnie : rangs de Guilde, niveau d&apos;équipe et quartier général',['../roadmap.html#lot-83',1,'']]],
  ['générateur_20de_20terrain_2',['&lt;span class=&quot;tt&quot;&gt;LOT-40&lt;/span&gt; — Générateur de terrain',['../roadmap.html#lot-40',1,'']]],
  ['génération_3',['génération',['../lot-91-poc.html#autotoc_md722',1,'8. Les tours 2 et 3 (nouvelle génération)'],['../lot-33.html#autotoc_md506',1,'Deux contrôles qui arrêtent la génération'],['../lot-33.html#autotoc_md509',1,'Le test lit le livre, pas la génération']]],
  ['génération_20assistée_4',['LOT-EDITOR-11 — Génération assistée',['../roadmap-editeur.html#lot-editor-11',1,'']]],
  ['géométrie_5',['géométrie',['../lot-19.html#autotoc_md432',1,'L&apos;altitude est un attribut, jamais une géométrie'],['../namespacecore.html#autotoc_md911',1,'L&apos;altitude est un attribut, jamais une géométrie']]],
  ['gérer_20ses_20fichiers_20de_20niveaux_6',['Gérer ses fichiers de niveaux',['../guide-editeur.html#autotoc_md96',1,'']]],
  ['gabarits_7',['Les deux gabarits',['../lot-93.html#autotoc_md737',1,'']]],
  ['gagner_8',['3. Gagner',['../spec-inventaire.html#autotoc_md263',1,'']]],
  ['gameplay_9',['Gameplay',['../spec-gameplay.html',1,'specifications']]],
  ['gameplay_10',['gameplay',['../spec-vision.html#autotoc_md291',1,'Boucle de gameplay'],['../guide-entrees.html#autotoc_md98',1,'Le principe : ne jamais coder « en dur » une touche dans le gameplay']]],
  ['gameplay_209_11',['Gameplay (9)',['../cahiertest.html#autotoc_md10',1,'']]],
  ['gardé_12',['Ce qui est gardé',['../lot-87.html#autotoc_md661',1,'']]],
  ['garde_20en_20ci_13',['LOT-EDITOR-12 — Le format v4 et sa garde en CI',['../roadmap-editeur.html#lot-editor-12',1,'']]],
  ['garde_20fous_20contre_20la_20perte_20de_20travail_14',['Garde-fous contre la perte de travail',['../guide-editeur.html#autotoc_md94',1,'']]],
  ['gelé_15',['Le monde gelé',['../lot-15.html#autotoc_md411',1,'']]],
  ['geste_20à_20plus_20fort_20levier_20du_20programme_16',['9.3 L&apos;allègement est le geste à plus fort levier du programme',['../roadmap.html#autotoc_md807',1,'']]],
  ['gestes_17',['Les gestes',['../lot-11.html#autotoc_md376',1,'']]],
  ['gestion_20des_20cartes_18',['3. Gestion des cartes',['../spec-interface-ihm.html#autotoc_md248',1,'']]],
  ['gestion_20des_20erreurs_19',['9. Gestion des erreurs',['../spec-conventions.html#autotoc_md217',1,'']]],
  ['gestion_20des_20ressources_20',['9. Gestion des ressources',['../spec-architecture.html#autotoc_md182',1,'']]],
  ['gouttière_20bouge_20d_20une_20page_20à_20l_20autre_21',['Sa gouttière bouge d&apos;une page à l&apos;autre',['../lot-36.html#autotoc_md527',1,'']]],
  ['gouverne_20cette_20classe_22',['La règle qui gouverne cette classe',['../classhmi_1_1OptionsModel.html#autotoc_md987',1,'']]],
  ['gpu_20pas_20un_20changement_20de_20cible_23',['QRhi : une couche d&apos;accès au GPU, pas un changement de cible',['../guide-rendu.html#autotoc_md150',1,'']]],
  ['gpu_20swap_20chain_20back_20buffer_24',['Vocabulaire de base : GPU, swap chain, back buffer',['../guide-rendu.html#autotoc_md149',1,'']]],
  ['graine_20fixée_20_3a_20ce_20que_20cela_20achète_25',['Rejouable à graine fixée : ce que cela achète',['../lot-50.html#autotoc_md575',1,'']]],
  ['graisse_20ment_26',['Le &lt;em&gt;Manuel des Joueurs&lt;/em&gt; est un scan, et sa graisse ment',['../lot-36.html#autotoc_md525',1,'']]],
  ['grande_20que_20la_20fenêtre_27',['Cadrer une carte plus grande que la fenêtre',['../guide-editeur.html#autotoc_md95',1,'']]],
  ['graphe_20de_20cartes_28',['LOT-37 — Atlas des régions et graphe de cartes',['../lot-37.html',1,'lots']]],
  ['graphe_20des_20dépendances_29',['Le graphe des dépendances',['../roadmap.html#autotoc_md794',1,'']]],
  ['graphe_20des_20quartiers_30',['LOT-96 — Martpart et Arenarea se parcourent : le graphe des quartiers',['../lot-96.html',1,'lots']]],
  ['graphe_20ne_20porte_20aucun_20texte_31',['Le graphe ne porte aucun texte',['../lot-15.html#autotoc_md407',1,'']]],
  ['graphics_20128_32',['Graphics (128)',['../cahiertest.html#autotoc_md20',1,'']]],
  ['graphiques_33',['Crédits graphiques',['../md__2home_2runner_2work_2JustAnotherRpgGame_2JustAnotherRpgGame_2Source_2Elements_2Assets_2CREDITS.html',1,'']]],
  ['gravée_20_3a_20une_20piste_20ouverte_20puis_20refermée_34',['La planche gravée : une piste ouverte, puis refermée',['../lot-38.html#autotoc_md547',1,'']]],
  ['gravité_20_3a_20core_3a_3aloglevel_20core_3a_3aloglevel_35',['Les niveaux de gravité : &lt;a class=&quot;el&quot; href=&quot;namespacecore.html#aa9b5a444ee11933c91d5e3235aa5b5e3&quot; title=&quot;core::LogLevel&quot;&gt;core::LogLevel&lt;/a&gt;',['../guide-journalisation.html#autotoc_md119',1,'']]],
  ['grille_36',['&lt;a class=&quot;el&quot; href=&quot;classcore_1_1TileMap.html&quot; title=&quot;core::TileMap&quot;&gt;core::TileMap&lt;/a&gt; : la grille',['../guide-niveaux.html#autotoc_md140',1,'']]],
  ['grille_20_3a_20hmi_3a_3aeditortool_20editortool_37',['Quatre outils, une même grille : &lt;a class=&quot;el&quot; href=&quot;namespacehmi.html#a02048ad8ad69a87a10e8307ac2bd68dd&quot; title=&quot;hmi::EditorTool&quot;&gt;EditorTool&lt;/a&gt;',['../guide-editeur.html#autotoc_md89',1,'']]],
  ['grille_20_3a_20la_20moitié_20d_20une_20case_38',['Sur la grille : la moitié d&apos;une case',['../AreaOfEffect_8h.html#autotoc_md903',1,'']]],
  ['grille_20compte_39',['L&apos;abri : ce que la grille compte',['../lot-22.html#autotoc_md467',1,'']]],
  ['grille_20laissait_20ouverts_40',['Les trois points que la grille laissait ouverts',['../lot-20.html#autotoc_md443',1,'']]],
  ['grille_20le_20mesure_41',['Comment la grille le mesure',['../Flanking_8h.html#autotoc_md927',1,'']]],
  ['grille_20tactique_20et_20déplacement_42',['LOT-19 — Grille tactique et déplacement',['../lot-19.html',1,'lots']]],
  ['groupés_20et_20qui_20suivent_20l_20outil_43',['Des panneaux groupés, et qui suivent l&apos;outil',['../guide-design-ihm.html#autotoc_md63',1,'']]],
  ['groupe_20d_20une_20arme_20n_20est_20pas_20dans_20sa_20rangée_44',['Le groupe d&apos;une arme n&apos;est pas dans sa rangée',['../lot-34.html#autotoc_md515',1,'']]],
  ['groupe_20de_20quatre_20personnages_45',['LOT-29 — Groupe de quatre personnages',['../roadmap.html#lot-29',1,'']]],
  ['groupes_46',['Ordre des groupes',['../spec-conventions.html#autotoc_md207',1,'']]],
  ['guerrier_20comme_20preuve_47',['&lt;span class=&quot;tt&quot;&gt;LOT-47&lt;/span&gt; — Socle de classe, et le guerrier comme preuve',['../roadmap.html#lot-47',1,'']]],
  ['guide_48',['Ce que dit le Guide',['../Flanking_8h.html#autotoc_md926',1,'']]],
  ['guide_49',['guide',['../guide.html#autotoc_md171',1,'Comment lire ce guide'],['../guide.html#autotoc_md173',1,'Plan du guide']]],
  ['guide_20dessine_20ses_20titres_20deux_20fois_50',['Le &lt;em&gt;Player&apos;s Guide&lt;/em&gt; dessine ses titres deux fois',['../lot-36.html#autotoc_md528',1,'']]],
  ['guide_20du_20développeur_51',['Guide du développeur',['../guide.html',1,'index']]],
  ['guide_20du_20maître_20en_20dit_52',['Ce que le &lt;em&gt;Guide du Maître&lt;/em&gt; en dit',['../EnemyAi_8h.html#autotoc_md923',1,'']]],
  ['guide_20et_20où_20chacune_20vit_53',['Les règles du Guide, et où chacune vit',['../lot-23.html#autotoc_md475',1,'']]],
  ['guide_20ne_20dit_20pas_54',['Ce que ce fichier décide, et que le Guide ne dit pas',['../EnemyAi_8h.html#autotoc_md924',1,'']]],
  ['guides_20manuel_55',['4. Spécifications, guides, manuel',['../lot-88.html#autotoc_md698',1,'']]],
  ['guilde_20des_20aventuriers_20_3a_20rangs_20et_20contrats_56',['&lt;span class=&quot;tt&quot;&gt;LOT-45&lt;/span&gt; — Guilde des Aventuriers : rangs et contrats',['../roadmap.html#lot-45',1,'']]],
  ['guilde_20niveau_20d_20équipe_20et_20quartier_20général_57',['&lt;span class=&quot;tt&quot;&gt;LOT-83&lt;/span&gt; — Compagnie : rangs de Guilde, niveau d&apos;équipe et quartier général',['../roadmap.html#lot-83',1,'']]]
];
