var searchData=
[
  ['échanger_0',['2. Échanger',['../spec-inventaire.html#autotoc_md367',1,'']]],
  ['échantillonner_20plutôt_20que_20réagir_20_3a_20hmi_3a_3ainputstate_20hmi_3a_3ainputstate_1',['Échantillonner plutôt que réagir : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1InputState.html&quot; title=&quot;hmi::InputState&quot;&gt;hmi::InputState&lt;/a&gt;',['../guide-entrees.html#autotoc_md135',1,'']]],
  ['échelles_2',['6. Échelles',['../spec-regles-dnd.html#autotoc_md379',1,'']]],
  ['écrans_20navigation_20et_20boucle_20de_20jeu_3',['Écrans, navigation et boucle de jeu',['../guide-ecrans.html',1,'guide']]],
  ['écrire_20un_20png_20sans_20jamais_20laisser_20de_20fichier_20tronqué_4',['Écrire un PNG sans jamais laisser de fichier tronqué',['../guide-atelier-pixel-art.html#autotoc_md36',1,'']]],
  ['éditer_20un_20écran_20sans_20rien_20reconstruire_5',['Éditer un écran sans rien reconstruire',['../guide-ihm-qt.html#autotoc_md148',1,'']]],
  ['éditeur_6',['2. Éditeur',['../spec-interface-ihm.html#autotoc_md351',1,'']]],
  ['éditeur_20de_20niveaux_7',['Éditeur de niveaux',['../guide-editeur.html',1,'Éditeur de niveaux'],['../spec-editeur.html',1,'Éditeur de niveaux']]],
  ['éditeur_20de_20niveaux_20—_20test_5fparcours_5fedition_20cpp_202_8',['Éditeur de niveaux — &lt;span class=&quot;tt&quot;&gt;test_parcours_edition.cpp&lt;/span&gt; (2)',['../cahiertest.html#autotoc_md34',1,'']]],
  ['éditeur_20multi_20couches_20et_20placement_20d_20entités_9',['LOT-11 — Éditeur multi-couches et placement d&apos;entités',['../roadmap-010.html#lot-11',1,'']]],
  ['édition_10',['2. Édition',['../spec-decors.html#autotoc_md310',1,'']]],
  ['égalité_20approchée_11',['Égalité approchée',['../guide-maths.html#autotoc_md169',1,'']]],
  ['équilibrage_12',['Équilibrage',['../roadmap-010.html#autotoc_md778',1,'']]],
  ['équipement_20monnaie_20objets_20magiques_13',['LOT-34 — Équipement, monnaie, objets magiques',['../lot-34.html',1,'lots']]],
  ['étapes_14',['Étapes',['../manuel-telecharger.html#autotoc_md816',1,'']]],
  ['état_20d_20avancement_15',['État d&apos;avancement',['../roadmap-010.html#roadmap-avancement',1,'']]],
  ['états_20de_20jeu_16',['4. États de jeu',['../spec-gameplay.html#autotoc_md343',1,'']]],
  ['évaluation_20et_20robustesse_17',['4. Évaluation et robustesse',['../spec-ia.html#autotoc_md348',1,'']]],
  ['évolutif_18',['Comment fonctionne la population (algorithme Évolutif)',['../manuel-mode-ia.html#autotoc_md800',1,'']]],
  ['écarté_19',['Le piège, et la façon dont il est écarté',['../lot-14.html#autotoc_md484',1,'']]],
  ['écartées_20et_20pourquoi_20',['Les deux directions écartées, et pourquoi',['../lot-86.html#autotoc_md637',1,'']]],
  ['échafaudage_20assumé_21',['Le personnage affiché : une donnée, et un échafaudage assumé',['../lot-38.html#autotoc_md564',1,'']]],
  ['échafaudage_20et_20il_20est_20écrit_22',['« Nouvelle partie » : un échafaudage, et il est écrit',['../lot-68.html#autotoc_md607',1,'']]],
  ['échantillonnage_20nearest_23',['Sommets, shaders, et échantillonnage &lt;em&gt;nearest&lt;/em&gt;',['../guide-rendu.html#autotoc_md222',1,'']]],
  ['échelle_24',['2. Repères d&apos;échelle',['../spec-exploration.html#autotoc_md336',1,'']]],
  ['échelle_20d_20affichage_25',['Netteté à toute échelle d&apos;affichage',['../guide-design-ihm.html#autotoc_md81',1,'']]],
  ['échelle_20lot_2066_26',['Deux identités, deux règles d&apos;échelle (LOT-66)',['../guide-design-ihm.html#autotoc_md89',1,'']]],
  ['économie_27',['économie',['../spec-inventaire.html',1,'Inventaire et économie'],['../roadmap-010.html#lot-26',1,'LOT-26 — Butin, marchands, économie']]],
  ['écran_28',['écran',['../guide-rendu.html#autotoc_md230',1,'&lt;a class=&quot;el&quot; href=&quot;classhmi_1_1SpriteRenderer.html&quot; title=&quot;hmi::SpriteRenderer&quot;&gt;hmi::SpriteRenderer&lt;/a&gt; : le pont ECS → écran'],['../lot-14.html#autotoc_md487',1,'L&apos;écran'],['../guide-rendu.html',1,'Rendu 2D : de l&apos;ECS à l&apos;écran'],['../lot-68.html#autotoc_md608',1,'Trois défauts d&apos;agencement, trouvés en regardant l&apos;écran']]],
  ['écran_20à_20honorer_29',['Décisions d&apos;écran à honorer',['../lot-86.html#autotoc_md638',1,'']]],
  ['écran_20est_20donc_20aujourd_20hui_30',['Ce que l&apos;écran est donc aujourd&apos;hui',['../lot-38.html#autotoc_md562',1,'']]],
  ['écran_20et_20non_20par_20l_20appelant_31',['La règle de superposition, portée par l&apos;écran et non par l&apos;appelant',['../lot-68.html#autotoc_md606',1,'']]],
  ['écran_20hmi_3a_3acamera2d_32',['Le rendu (&lt;span class=&quot;tt&quot;&gt;hmi::ParticleRenderer&lt;/span&gt;) et la secousse d&apos;écran (&lt;span class=&quot;tt&quot;&gt;hmi::Camera2D&lt;/span&gt;)',['../guide-rendu.html#autotoc_md247',1,'']]],
  ['écran_20lot_2053_33',['Particules et secousse d&apos;écran (&lt;span class=&quot;tt&quot;&gt;LOT-53&lt;/span&gt;)',['../guide-rendu.html#autotoc_md244',1,'']]],
  ['écran_20sans_20rien_20reconstruire_34',['Éditer un écran sans rien reconstruire',['../guide-ihm-qt.html#autotoc_md148',1,'']]],
  ['écrans_35',['Le titre devient son bandeau, sur les six écrans',['../lot-76.html#autotoc_md616',1,'']]],
  ['écrans_20écrits_20à_20la_20main_36',['Une table, et non huit écrans écrits à la main',['../RpgScreens_8h.html#autotoc_md828',1,'']]],
  ['écrans_20dans_20qt_20design_20studio_37',['Concevoir les écrans dans Qt Design Studio',['../guide-conception-qds.html',1,'guide']]],
  ['écrans_20dessinés_20mais_20pas_20encore_20alimentés_38',['Les écrans dessinés mais pas encore alimentés',['../guide-conception-qds.html#autotoc_md68',1,'']]],
  ['écrans_20du_20jeu_20lot_20h_2068_39',['8. Identité visuelle des écrans du jeu (LOT-H-68)',['../spec-interface-ihm.html#autotoc_md357',1,'']]],
  ['écrans_20du_20rpg_40',['LOT-68 — Le châssis des écrans du RPG',['../lot-68.html',1,'lots']]],
  ['écrans_20du_20rpg_20lot_2068_41',['10. Le châssis des écrans du RPG (LOT-68)',['../spec-interface-ihm.html#autotoc_md359',1,'']]],
  ['écrans_20pour_20les_20dessiner_42',['Ouvrir les écrans pour les dessiner',['../guide-ihm-qt.html#autotoc_md149',1,'']]],
  ['écrire_43',['T1.1 — Le diagnostic, avant d&apos;écrire',['../lot-87.html#autotoc_md647',1,'']]],
  ['écrire_20jamais_20l_20inverse_44',['Enregistrer : valider avant d&apos;écrire, jamais l&apos;inverse',['../guide-editeur.html#autotoc_md123',1,'']]],
  ['écrit_45',['écrit',['../lot-68.html#autotoc_md607',1,'« Nouvelle partie » : un échafaudage, et il est écrit'],['../lot-37.html#autotoc_md552',1,'Le voisinage est déclaré, et c&apos;est écrit']]],
  ['écrit_20comme_20non_20alimenté_46',['Un champ affiché, ou écrit comme non alimenté',['../lot-38.html#autotoc_md558',1,'']]],
  ['écrit_20de_20classdefinition_20_3a_20elle_20existait_20déjà_47',['Le lot n&apos;a pas écrit de &lt;span class=&quot;tt&quot;&gt;ClassDefinition&lt;/span&gt; : elle existait déjà',['../lot-13.html#autotoc_md476',1,'']]],
  ['écrit_20et_20qu_20un_20schéma_20refusait_48',['Trois cas que le livre écrit et qu&apos;un schéma refusait',['../lot-34.html#autotoc_md528',1,'']]],
  ['écrit_20une_20couleur_49',['Les jetons : le seul endroit où s&apos;écrit une couleur',['../guide-conception-qds.html#autotoc_md65',1,'']]],
  ['écrite_50',['Ce que la règle dit, et où elle est écrite',['../lot-14.html#autotoc_md485',1,'']]],
  ['écrites_20là_20où_20on_20les_20lit_51',['Trois décisions de règle, écrites là où on les lit',['../lot-13.html#autotoc_md480',1,'']]],
  ['écrits_20à_20la_20main_52',['Une table, et non huit écrans écrits à la main',['../RpgScreens_8h.html#autotoc_md828',1,'']]],
  ['éditer_20un_20niveau_20sans_20re_20coder_20le_20moteur_53',['Le problème : éditer un niveau sans (re)coder le moteur',['../guide-editeur.html#autotoc_md111',1,'']]],
  ['éditeur_54',['éditeur',['../manuel-partager-niveau.html#autotoc_md808',1,'2. Lancer l&apos;éditeur'],['../spec-decors.html#autotoc_md311',1,'3. Pipeline photo → pixel art (intégré à l&apos;éditeur)'],['../spec-editeur.html#autotoc_md319',1,'4bis. Décors &amp;amp; pixel art (post-MVP, intégré à l&apos;éditeur)'],['../guide-editeur.html#autotoc_md122',1,'Essai immédiat : jouer sans quitter l&apos;éditeur']]],
  ['éditeur_20et_20jeu_55',['Le viewport partagé : éditeur &lt;b&gt;et&lt;/b&gt; jeu',['../guide-ecrans.html#autotoc_md97',1,'']]],
  ['éditeur_20intégré_20»_56',['10. Contrainte « éditeur intégré »',['../spec-architecture.html#autotoc_md268',1,'']]],
  ['éditeur_20lot_2037_20ex_20ihm_20030_20ex_20ihm_20031_57',['Lier des mécanismes dans l&apos;éditeur (&lt;span class=&quot;tt&quot;&gt;LOT-37&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;EX-IHM-030&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;EX-IHM-031&lt;/span&gt;)',['../guide-editeur.html#autotoc_md114',1,'']]],
  ['éditeur_20lot_20h_2057_58',['7. Architecture de l&apos;information de l&apos;éditeur (LOT-H-57)',['../spec-interface-ihm.html#autotoc_md356',1,'']]],
  ['éditeur_20mvp_59',['5. Non-objectifs (éditeur, MVP)',['../spec-editeur.html#autotoc_md320',1,'']]],
  ['édition_20lot_20h_2015_60',['6. Robustesse et confort d&apos;édition (LOT-H-15)',['../spec-editeur.html#autotoc_md321',1,'']]],
  ['égalité_20stricte_20est_20dangereuse_61',['Comparaison flottante : pourquoi l&apos;égalité stricte est dangereuse',['../guide-maths.html#autotoc_md172',1,'']]],
  ['élément_20mobile_62',['L&apos;outil « Parcours » : dessiner la route d&apos;un élément mobile',['../guide-editeur.html#autotoc_md118',1,'']]],
  ['émetteur_20dans_20core_20déterministe_20core_3a_3aparticlesystem_63',['L&apos;émetteur, dans &lt;span class=&quot;tt&quot;&gt;Core&lt;/span&gt;, déterministe (&lt;span class=&quot;tt&quot;&gt;core::ParticleSystem&lt;/span&gt;)',['../guide-rendu.html#autotoc_md245',1,'']]],
  ['énumération_20et_20non_20un_20nom_20de_20fichier_64',['Pourquoi une énumération et non un nom de fichier',['../classhmi_1_1ScreenRouter.html#autotoc_md842',1,'']]],
  ['équipement_65',['LOT-14 — Inventaire et équipement',['../lot-14.html',1,'']]],
  ['été_20fait_66',['T1.2 à T1.4 — Ce qui a été fait',['../lot-87.html#autotoc_md648',1,'']]],
  ['été_20faite_67',['Comment la classification a été faite',['../lot-78.html#autotoc_md625',1,'']]],
  ['été_20retiré_20du_20code_68',['Ce qui a été retiré du code',['../lot-67.html#autotoc_md598',1,'']]],
  ['étaient_20consommées_20sans_20être_20produites_69',['9.2 Six mécaniques étaient consommées sans être produites',['../roadmap-010.html#autotoc_md691',1,'']]],
  ['était_20périmé_70',['Attention : le texte des maquettes était périmé',['../lot-86.html#autotoc_md636',1,'']]],
  ['étanches_71',['Les jetons : une seule source, deux portées étanches',['../guide-design-ihm.html#autotoc_md77',1,'']]],
  ['état_72',['Détecter les fronts, pas seulement l&apos;état',['../guide-entrees.html#autotoc_md136',1,'']]],
  ['état_20du_20dépôt_73',['9. Ce que l&apos;audit a révélé sur l&apos;état du dépôt',['../roadmap-010.html#autotoc_md689',1,'']]],
  ['état_20en_20intention_20_3a_20hmi_3a_3atoplayerinput_20hmi_3a_3atoplayerinput_74',['Traduire l&apos;état en intention : &lt;a class=&quot;el&quot; href=&quot;namespacehmi.html#a2c3341857c60f0bef0a01a6cd10ce5f7&quot; title=&quot;hmi::toPlayerInput&quot;&gt;hmi::toPlayerInput&lt;/a&gt;',['../guide-entrees.html#autotoc_md139',1,'']]],
  ['état_20structurée_75',['Une barre d&apos;état structurée',['../guide-design-ihm.html#autotoc_md84',1,'']]],
  ['état_20un_20contrôle_76',['Un état, un contrôle',['../guide-design-ihm.html#autotoc_md86',1,'']]],
  ['états_77',['états',['../roadmap-010.html#lot-35',1,'&lt;span class=&quot;tt&quot;&gt;LOT-35&lt;/span&gt; — Sorts et états'],['../roadmap-010.html#lot-21',1,'LOT-21 — Attaques, dégâts et états']]],
  ['états_20_3a_20hmi_3a_3ascreenflow_78',['La machine à états : &lt;span class=&quot;tt&quot;&gt;hmi::ScreenFlow&lt;/span&gt;',['../guide-ecrans.html#autotoc_md94',1,'']]],
  ['éviter_20la_20racine_20carrée_79',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Vector2.html#a5f3517fe219407f73a3ed5542091c31c&quot; title=&quot;core::Vector2::lengthSquared&quot;&gt;lengthSquared&lt;/a&gt; : éviter la racine carrée',['../guide-maths.html#autotoc_md168',1,'']]]
];
