var searchData=
[
  ['où_20ça_20s_20insère_20dans_20la_20boucle_0',['Où ça s&apos;insère dans la boucle',['../guide-ecrans.html#autotoc_md85',1,'']]],
  ['où_20finissent_20les_20messages_1',['Les sinks : où finissent les messages',['../guide-journalisation.html#autotoc_md145',1,'']]],
  ['où_20la_20caméra_20défile_2',['Parallaxe : portée par le plan, bornée, et seulement là où la caméra défile',['../guide-rendu.html#autotoc_md227',1,'']]],
  ['objectif_3',['Objectif',['../spec-editeur.html#autotoc_md302',1,'Objectif'],['../lot-01.html#autotoc_md385',1,'Objectif'],['../lot-02.html#autotoc_md395',1,'Objectif'],['../lot-03.html#autotoc_md402',1,'Objectif'],['../lot-04.html#autotoc_md408',1,'Objectif'],['../lot-05.html#autotoc_md415',1,'Objectif'],['../lot-06.html#autotoc_md422',1,'Objectif'],['../lot-07.html#autotoc_md429',1,'Objectif'],['../lot-08.html#autotoc_md435',1,'Objectif'],['../lot-77.html#autotoc_md441',1,'Objectif'],['../lot-78.html#autotoc_md445',1,'Objectif'],['../roadmap-010.html#autotoc_md489',1,'Objectif'],['../roadmap-010.html#autotoc_md494',1,'Objectif'],['../roadmap-010.html#autotoc_md500',1,'Objectif'],['../roadmap-010.html#autotoc_md506',1,'Objectif'],['../roadmap-010.html#autotoc_md512',1,'Objectif'],['../roadmap-010.html#autotoc_md517',1,'Objectif'],['../roadmap-010.html#autotoc_md522',1,'Objectif'],['../roadmap-010.html#autotoc_md527',1,'Objectif'],['../roadmap-010.html#autotoc_md532',1,'Objectif'],['../roadmap-010.html#autotoc_md538',1,'Objectif'],['../roadmap-010.html#autotoc_md544',1,'Objectif'],['../roadmap-010.html#autotoc_md550',1,'Objectif'],['../roadmap-010.html#autotoc_md555',1,'Objectif'],['../roadmap-010.html#autotoc_md561',1,'Objectif'],['../roadmap-010.html#autotoc_md566',1,'Objectif'],['../roadmap-010.html#autotoc_md572',1,'Objectif'],['../roadmap-010.html#autotoc_md577',1,'Objectif'],['../roadmap-010.html#autotoc_md582',1,'Objectif'],['../roadmap-010.html#autotoc_md587',1,'Objectif'],['../roadmap-010.html#autotoc_md592',1,'Objectif'],['../roadmap-010.html#autotoc_md601',1,'Objectif']]],
  ['objectif_20d_20un_20niveau_4',['Objectif d&apos;un niveau',['../manuel-jouer.html#autotoc_md609',1,'']]],
  ['objectifs_20éditeur_20mvp_5',['5. Non-objectifs (éditeur, MVP)',['../spec-editeur.html#autotoc_md308',1,'']]],
  ['objectifs_20produit_20au_20delà_20du_20moteur_6',['Objectifs produit (au-delà du moteur)',['../spec-vision.html#autotoc_md381',1,'']]],
  ['objectifs_20vertical_20slice_7',['Objectifs (&lt;em&gt;vertical slice&lt;/em&gt;)',['../spec-vision.html#autotoc_md380',1,'']]],
  ['objets_8',['Format retenu (JSON, liste de tuiles-objets)',['../spec-niveaux.html#autotoc_md353',1,'']]],
  ['objets_20magiques_9',['&lt;span class=&quot;tt&quot;&gt;LOT-34&lt;/span&gt; — Équipement, monnaie, objets magiques',['../roadmap-010.html#lot-34',1,'']]],
  ['obligatoire_10',['RAII obligatoire',['../spec-conventions.html#autotoc_md286',1,'']]],
  ['observabilité_11',['2. Pont avec le jeu et observabilité',['../spec-ia.html#autotoc_md335',1,'']]],
  ['ombres_20du_20plan_20physique_20lot_2055_12',['Ombres du plan physique (&lt;span class=&quot;tt&quot;&gt;LOT-55&lt;/span&gt;)',['../guide-rendu.html#autotoc_md232',1,'']]],
  ['on_20peut_20défaire_13',['&lt;a class=&quot;el&quot; href=&quot;classcore_1_1LevelDraft.html&quot; title=&quot;core::LevelDraft&quot;&gt;core::LevelDraft&lt;/a&gt; : un niveau qu&apos;on peut défaire',['../guide-editeur.html#autotoc_md97',1,'']]],
  ['onglet_20entraînement_14',['Les réglages de l&apos;onglet Entraînement',['../manuel-mode-ia.html#autotoc_md617',1,'']]],
  ['onglets_15',['Les trois onglets',['../manuel-mode-ia.html#autotoc_md615',1,'']]],
  ['options_16',['Le menu d&apos;options',['../manuel-jouer.html#autotoc_md612',1,'']]],
  ['options_20_3a_20hmi_3a_3aoptionspage_20hmi_3a_3aoptionspage_17',['Le menu d&apos;options : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1OptionsPage.html&quot; title=&quot;hmi::OptionsPage&quot;&gt;hmi::OptionsPage&lt;/a&gt;',['../guide-entrees.html#autotoc_md126',1,'']]],
  ['options_20de_20personnage_18',['5. Options de personnage',['../spec-rpg.html#autotoc_md374',1,'']]],
  ['options_20de_20personnage_20_3a_20dons_20multiclassage_20compétences_20langues_19',['&lt;span class=&quot;tt&quot;&gt;LOT-43&lt;/span&gt; — Options de personnage : dons, multiclassage, compétences, langues',['../roadmap-010.html#lot-43',1,'']]],
  ['options_20unification_20',['5. Menus, options, unification',['../spec-interface-ihm.html#autotoc_md343',1,'']]],
  ['or_20une_20fois_20de_20plus_21',['La règle d&apos;or, une fois de plus',['../guide-audio.html#autotoc_md41',1,'']]],
  ['ordre_20d_20exécution_22',['Les systèmes et l&apos;ordre d&apos;exécution',['../guide-ecs.html#autotoc_md94',1,'']]],
  ['ordre_20d_20exécution_20recommandé_23',['6. Ordre d&apos;exécution recommandé',['../roadmap-010.html#autotoc_md468',1,'']]],
  ['ordre_20d_20un_20pas_20résumé_24',['Ordre d&apos;un pas (résumé)',['../guide-physique.html#autotoc_md199',1,'']]],
  ['ordre_20des_20groupes_25',['Ordre des groupes',['../spec-conventions.html#autotoc_md282',1,'']]],
  ['organisée_20par_20catégories_20lot_20h_2027_26',['8. Palette organisée par catégories (LOT-H-27)',['../spec-editeur.html#autotoc_md311',1,'']]],
  ['organisations_27',['&lt;span class=&quot;tt&quot;&gt;LOT-80&lt;/span&gt; — Factions, panthéon et organisations',['../roadmap-010.html#lot-80',1,'']]],
  ['orienté_20liens_20de_20mécanismes_20lot_2037_28',['&lt;a class=&quot;el&quot; href=&quot;structhmi_1_1LineQuad.html&quot; title=&quot;hmi::LineQuad&quot;&gt;LineQuad&lt;/a&gt; : un segment orienté (liens de mécanismes, &lt;span class=&quot;tt&quot;&gt;LOT-37&lt;/span&gt;)',['../guide-rendu.html#autotoc_md212',1,'']]],
  ['origine_29',['Origine',['../index.html#autotoc_md2',1,'Origine'],['../spec-vision.html#autotoc_md383',1,'Origine']]],
  ['ou_20un_20arrondi_20n_20est_20jamais_20solide_30',['Pourquoi une pente (ou un arrondi) n&apos;est jamais solide',['../guide-physique.html#autotoc_md190',1,'']]],
  ['ou_20une_20direction_20dans_20le_20monde_31',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Vector2.html&quot; title=&quot;core::Vector2&quot;&gt;Vector2&lt;/a&gt; : un point ou une direction dans le monde',['../guide-maths.html#autotoc_md154',1,'']]],
  ['oublié_32',['Le critère qui est souvent oublié',['../roadmap-010.html#autotoc_md574',1,'']]],
  ['outil_33',['outil',['../guide-design-ihm.html#autotoc_md67',1,'Des panneaux groupés, et qui suivent l&apos;outil'],['../guide-design-ihm.html#autotoc_md70',1,'Le Mode IA : enveloppe d&apos;identité, contenu d&apos;outil']]],
  ['outil_20«_20parcours_20»_20_3a_20dessiner_20la_20route_20d_20un_20élément_20mobile_34',['L&apos;outil « Parcours » : dessiner la route d&apos;un élément mobile',['../guide-editeur.html#autotoc_md103',1,'']]],
  ['outil_20différent_35',['Assertions : &lt;a class=&quot;el&quot; href=&quot;Assert_8h.html#a2811f3d423b22f1a90179b4ed095f054&quot; title=&quot;JADG_ASSERT&quot;&gt;JADG_ASSERT&lt;/a&gt;, un outil différent',['../guide-journalisation.html#autotoc_md152',1,'']]],
  ['outillage_36',['Outillage',['../roadmap-010.html#autotoc_md589',1,'']]],
  ['outillage_37',['5. Intégration au jeu et outillage',['../spec-ia.html#autotoc_md338',1,'']]],
  ['outillage_20qualité_20automatisé_38',['11. Outillage qualité (automatisé)',['../spec-conventions.html#autotoc_md294',1,'']]],
  ['outils_20_3a_20des_20fonctions_20pures_20sur_20un_20tampon_20de_20pixels_39',['Les outils : des fonctions pures sur un tampon de pixels',['../guide-atelier-pixel-art.html#autotoc_md33',1,'']]],
  ['outils_20_3a_20des_20panneaux_20qt_20séparés_20du_20canevas_40',['La palette et les outils : des panneaux Qt séparés du canevas',['../guide-editeur.html#autotoc_md102',1,'']]],
  ['outils_20une_20même_20grille_20_3a_20hmi_3a_3aeditortool_20editortool_41',['Trois outils, une même grille : &lt;a class=&quot;el&quot; href=&quot;namespacehmi.html#a02048ad8ad69a87a10e8307ac2bd68dd&quot; title=&quot;hmi::EditorTool&quot;&gt;EditorTool&lt;/a&gt;',['../guide-editeur.html#autotoc_md104',1,'']]]
];
