var searchData=
[
  ['jadg_5fassert_20jadg_5fassert_20un_20outil_20différent_0',['Assertions : &lt;a class=&quot;el&quot; href=&quot;Assert_8h.html#a2811f3d423b22f1a90179b4ed095f054&quot; title=&quot;JADG_ASSERT&quot;&gt;JADG_ASSERT&lt;/a&gt;, un outil différent',['../guide-journalisation.html#autotoc_md166',1,'']]],
  ['jadg_5fassert_20un_20outil_20différent_1',['Assertions : &lt;a class=&quot;el&quot; href=&quot;Assert_8h.html#a2811f3d423b22f1a90179b4ed095f054&quot; title=&quot;JADG_ASSERT&quot;&gt;JADG_ASSERT&lt;/a&gt;, un outil différent',['../guide-journalisation.html#autotoc_md166',1,'']]],
  ['jalon_2',['Jalon',['../lot-07.html#autotoc_md449',1,'']]],
  ['jamais_20coder_20«_20en_20dur_20»_20une_20touche_20dans_20le_20gameplay_3',['Le principe : ne jamais coder « en dur » une touche dans le gameplay',['../guide-entrees.html#autotoc_md135',1,'']]],
  ['jamais_20de_20cadrage_4',['Densité : un compromis de mémoire, jamais de cadrage',['../guide-rendu.html#autotoc_md237',1,'']]],
  ['jamais_20dessus_5',['Un seuil de corps se pose sous la valeur, jamais dessus',['../lot-36.html#autotoc_md545',1,'']]],
  ['jamais_20l_20inverse_6',['Enregistrer : valider avant d&apos;écrire, jamais l&apos;inverse',['../guide-editeur.html#autotoc_md124',1,'']]],
  ['jamais_20laisser_20de_20fichier_20tronqué_7',['Écrire un PNG sans jamais laisser de fichier tronqué',['../guide-atelier-pixel-art.html#autotoc_md37',1,'']]],
  ['jamais_20où_8',['Une rencontre dit QUI, jamais OÙ',['../lot-18.html#autotoc_md498',1,'']]],
  ['jamais_20perdu_20de_20vue_9',['Le focus n&apos;est jamais perdu de vue',['../lot-66.html#autotoc_md592',1,'']]],
  ['jamais_20solide_10',['Pourquoi une pente (ou un arrondi) n&apos;est jamais solide',['../guide-physique.html#autotoc_md202',1,'']]],
  ['jamais_20tenu_20à_20la_20main_11',['Le manifeste est dérivé, jamais tenu à la main',['../lot-39.html#autotoc_md572',1,'']]],
  ['jamais_20un_20chemin_12',['Une clé, jamais un chemin',['../lot-39.html#autotoc_md570',1,'']]],
  ['jamais_20un_20singleton_20joueur_13',['&lt;span class=&quot;tt&quot;&gt;CharacterSheet&lt;/span&gt; est un objet autonome, jamais un singleton joueur',['../lot-13.html#autotoc_md479',1,'']]],
  ['jamais_20une_20chaîne_14',['Une statistique est une liste, jamais une chaîne',['../lot-37.html#autotoc_md552',1,'']]],
  ['jauges_15',['Jauges',['../lot-87-cahier-assets.html#lot-87-cahier-gauge',1,'']]],
  ['jet_16',['1. Le jet',['../spec-regles-dnd.html#autotoc_md375',1,'']]],
  ['jetons_17',['jetons',['../guide-conception-qds.html#autotoc_md70',1,'Les contrôles Qt prennent la couleur des jetons'],['../lot-87.html#autotoc_md668',1,'T2.2 — Les jetons']]],
  ['jetons_20_3a_20le_20seul_20endroit_20où_20s_20écrit_20une_20couleur_18',['Les jetons : le seul endroit où s&apos;écrit une couleur',['../guide-conception-qds.html#autotoc_md66',1,'']]],
  ['jetons_20_3a_20une_20seule_20source_20deux_20portées_20étanches_19',['Les jetons : une seule source, deux portées étanches',['../guide-design-ihm.html#autotoc_md78',1,'']]],
  ['jetons_20purs_20à_20une_20application_20habillée_20',['De jetons purs à une application habillée',['../guide-design-ihm.html#autotoc_md79',1,'']]],
  ['jets_21',['LOT-12 — Dés, caractéristiques, jets',['../lot-12.html',1,'lots']]],
  ['jets_20trois_20usages_22',['3. Trois jets, trois usages',['../spec-regles-dnd.html#autotoc_md377',1,'']]],
  ['jeu_23',['jeu',['../guide-ecrans.html',1,'Écrans, navigation et boucle de jeu'],['../spec-gameplay.html#autotoc_md344',1,'4. États de jeu'],['../manuel-jouer.html#autotoc_md824',1,'Contrôles en jeu'],['../guide-ecrans.html#autotoc_md98',1,'Le viewport partagé : éditeur &lt;b&gt;et&lt;/b&gt; jeu'],['../guide-ihm-qt.html#autotoc_md147',1,'Les trois couches du jeu'],['../lot-05.html',1,'LOT-05 — Modes de jeu'],['../guide-boucle.html#autotoc_md53',1,'Qu&apos;est-ce qu&apos;une boucle de jeu ?'],['../manuel-telecharger.html',1,'Télécharger et lancer le jeu']]],
  ['jeu_20et_20observabilité_24',['2. Pont avec le jeu et observabilité',['../spec-ia.html#autotoc_md347',1,'']]],
  ['jeu_20et_20outillage_25',['5. Intégration au jeu et outillage',['../spec-ia.html#autotoc_md350',1,'']]],
  ['jeu_20et_20pas_20de_20temps_20fixe_26',['Boucle de jeu et pas de temps fixe',['../guide-boucle.html',1,'guide']]],
  ['jeu_20f9_27',['Compteur de diagnostic en jeu (&lt;span class=&quot;tt&quot;&gt;F9&lt;/span&gt;)',['../guide-rendu.html#autotoc_md255',1,'']]],
  ['jeu_20lot_20h_2068_28',['8. Identité visuelle des écrans du jeu (LOT-H-68)',['../spec-interface-ihm.html#autotoc_md358',1,'']]],
  ['jeu_20mapping_20logique_29',['2. Actions du jeu (mapping logique)',['../spec-controles.html#autotoc_md286',1,'']]],
  ['jeu_20vidéo_30',['Pourquoi journaliser dans un jeu vidéo',['../guide-journalisation.html#autotoc_md156',1,'']]],
  ['jouer_31',['Jouer',['../manuel-jouer.html',1,'manuel']]],
  ['jouer_32',['Regarder l&apos;IA jouer',['../manuel-mode-ia.html',1,'manuel']]],
  ['jouer_20sans_20quitter_20l_20éditeur_33',['Essai immédiat : jouer sans quitter l&apos;éditeur',['../guide-editeur.html#autotoc_md123',1,'']]],
  ['joueur_34',['joueur',['../lot-13.html#autotoc_md479',1,'&lt;span class=&quot;tt&quot;&gt;CharacterSheet&lt;/span&gt; est un objet autonome, jamais un singleton joueur'],['../manuel-partager-niveau.html#autotoc_md844',1,'Choisir comment la caméra suit le joueur']]],
  ['joueur_20voit_35',['joueur voit',['../lot-67.html#autotoc_md597',1,'Ce que le joueur voit'],['../lot-68.html#autotoc_md605',1,'Ce que le joueur voit']]],
  ['joueurs_20est_20un_20scan_20et_20sa_20graisse_20ment_36',['Le &lt;em&gt;Manuel des Joueurs&lt;/em&gt; est un scan, et sa graisse ment',['../lot-36.html#autotoc_md538',1,'']]],
  ['jour_37',['jour',['../lot-33.html#autotoc_md521',1,'Cinq défauts du lexique que les 94 noms ont mis au jour'],['../lot-43.html#autotoc_md580',1,'Trois défauts du corpus que ce lot a mis au jour']]],
  ['jour_20nuit_38',['&lt;span class=&quot;tt&quot;&gt;LOT-70&lt;/span&gt; — Horloge de partie et cycle jour/nuit',['../roadmap-010.html#lot-70',1,'']]],
  ['journal_20_3a_20restylés_39',['T3.9 — Pause, dialogue, marchand, journal : restylés',['../lot-87.html#autotoc_md683',1,'']]],
  ['journal_20c_20est_20une_20exigence_40',['La restitution n&apos;est pas un journal, c&apos;est une exigence',['../lot-12.html#autotoc_md471',1,'']]],
  ['journal_20de_20combat_41',['Le journal de combat',['../roadmap-010.html#autotoc_md774',1,'']]],
  ['journalisation_42',['10. Assertions &amp;amp; journalisation',['../spec-conventions.html#autotoc_md306',1,'']]],
  ['journalisation_20et_20assertions_43',['Journalisation et assertions',['../guide-journalisation.html',1,'guide']]],
  ['journalisation_20par_20catégorie_44',['Les macros de journalisation, par catégorie',['../guide-journalisation.html#autotoc_md160',1,'']]],
  ['journaliser_20dans_20un_20jeu_20vidéo_45',['Pourquoi journaliser dans un jeu vidéo',['../guide-journalisation.html#autotoc_md156',1,'']]],
  ['json_46',['Chargement JSON',['../guide-niveaux.html#autotoc_md180',1,'']]],
  ['json_20liste_20de_20tuiles_20objets_47',['Format retenu (JSON, liste de tuiles-objets)',['../spec-niveaux.html#autotoc_md371',1,'']]],
  ['jumeau_20qt_20quick_20de_20qrhiwidget_48',['Le jumeau Qt Quick de &lt;span class=&quot;tt&quot;&gt;QRhiWidget&lt;/span&gt;',['../classhmi_1_1GameViewportItem.html#autotoc_md866',1,'']]],
  ['jump_20et_20wall_20slide_49',['6. Wall jump et wall slide',['../guide-physique.html#autotoc_md210',1,'']]],
  ['jusqu_20au_20vertical_20slice_50',['Le chemin critique jusqu&apos;au &lt;em&gt;vertical slice&lt;/em&gt;',['../roadmap-010.html#autotoc_md713',1,'']]],
  ['justanotherdndgame_51',['JustAnotherDnDGame',['../index.html',1,'']]]
];
