var searchData=
[
  ['négociable_0',['Pourquoi le déterminisme du chemin n&apos;est pas négociable',['../lot-19.html#autotoc_md466',1,'']]],
  ['n_20est_20jamais_20solide_1',['Pourquoi une pente (ou un arrondi) n&apos;est jamais solide',['../guide-physique.html#autotoc_md190',1,'']]],
  ['n_20est_20pas_20«_20une_20seule_20hmilib_20»_2',['Le découpage retenu — et pourquoi il n&apos;est pas « une seule &lt;span class=&quot;tt&quot;&gt;HmiLib&lt;/span&gt; »',['../lot-02.html#autotoc_md368',1,'']]],
  ['n_20est_20pas_20négociable_3',['Pourquoi le déterminisme du chemin n&apos;est pas négociable',['../lot-19.html#autotoc_md466',1,'']]],
  ['n_20invente_20rien_4',['Typographie : une police embarquée, un repli qui n&apos;invente rien',['../guide-design-ihm.html#autotoc_md61',1,'']]],
  ['navigation_5',['Navigation',['../index.html#autotoc_md4',1,'']]],
  ['navigation_20et_20boucle_20de_20jeu_6',['Écrans, navigation et boucle de jeu',['../guide-ecrans.html',1,'guide']]],
  ['ne_20contraint_20la_20fenêtre_20lot_2073_7',['La taille : aucun écran ne contraint la fenêtre (LOT-73)',['../guide-ihm-qt.html#autotoc_md139',1,'']]],
  ['ne_20couvre_20pas_8',['Ce que cette page ne couvre pas',['../guide-ihm-qt.html#autotoc_md140',1,'']]],
  ['ne_20dessiner_20que_20ce_20qui_20se_20voit_20_3a_20le_20culling_20lot_2040_9',['Ne dessiner que ce qui se voit : le culling (&lt;span class=&quot;tt&quot;&gt;LOT-40&lt;/span&gt;)',['../guide-rendu.html#autotoc_md220',1,'']]],
  ['ne_20faut_20pas_20réécrire_10',['Ce qui existe déjà, et qu&apos;il ne faut pas réécrire',['../lot-06.html#autotoc_md392',1,'']]],
  ['ne_20jamais_20coder_20«_20en_20dur_20»_20une_20touche_20dans_20le_20gameplay_11',['Le principe : ne jamais coder « en dur » une touche dans le gameplay',['../guide-entrees.html#autotoc_md119',1,'']]],
  ['ne_20pas_20confondre_12',['Deux systèmes de coordonnées à ne pas confondre',['../guide-niveaux.html#autotoc_md162',1,'']]],
  ['ne_20pas_20réécrire_13',['Ce qui existe déjà — à ne pas réécrire',['../lot-19.html#autotoc_md464',1,'']]],
  ['ne_20pas_20rater_14',['Le point à ne pas rater',['../lot-04.html#autotoc_md382',1,'']]],
  ['ne_20pas_20se_20tromper_15',['Les règles à ne pas se tromper',['../lot-21.html#autotoc_md476',1,'']]],
  ['ne_20sait_20pas_20faire_16',['Ce qu&apos;une feuille de style ne sait pas faire',['../guide-design-ihm.html#autotoc_md72',1,'']]],
  ['nearest_17',['Sommets, shaders, et échantillonnage &lt;em&gt;nearest&lt;/em&gt;',['../guide-rendu.html#autotoc_md211',1,'']]],
  ['netteté_20à_20toute_20échelle_20d_20affichage_18',['Netteté à toute échelle d&apos;affichage',['../guide-design-ihm.html#autotoc_md63',1,'']]],
  ['newtonienne_20ex_20gp_20019_19',['Vitesse terminale newtonienne (EX-GP-019)',['../guide-physique.html#autotoc_md195',1,'']]],
  ['niveau_20',['niveau',['../manuel-partager-niveau.html#autotoc_md548',1,'3. Créer un niveau'],['../spec-gameplay.html#autotoc_md317',1,'4. Conditions de fin de niveau'],['../manuel-partager-niveau.html#autotoc_md551',1,'4. Publier votre niveau'],['../manuel-jouer.html#autotoc_md530',1,'Objectif d&apos;un niveau'],['../manuel-jouer.html#autotoc_md532',1,'Progression et sélection de niveau']]],
  ['niveau_20_3a_20hmi_3a_3agamesession_20réutilisée_21',['Jouer un niveau : &lt;span class=&quot;tt&quot;&gt;hmi::GameSession&lt;/span&gt; réutilisée',['../guide-ihm-qt.html#autotoc_md135',1,'']]],
  ['niveau_20_3a_20trois_20modes_20lot_2064_22',['Le cadrage choisi par le niveau : trois modes (&lt;span class=&quot;tt&quot;&gt;LOT-64&lt;/span&gt;)',['../guide-rendu.html#autotoc_md206',1,'']]],
  ['niveau_20assemblé_23',['&lt;a class=&quot;el&quot; href=&quot;classcore_1_1Level.html&quot; title=&quot;core::Level&quot;&gt;core::Level&lt;/a&gt; : le niveau assemblé',['../guide-niveaux.html#autotoc_md165',1,'']]],
  ['niveau_20ecs_20—_20test_5fniveau_5fecs_20cpp_201_24',['Niveau Ecs — &lt;span class=&quot;tt&quot;&gt;test_niveau_ecs.cpp&lt;/span&gt; (1)',['../cahiertest.html#autotoc_md28',1,'']]],
  ['niveau_20et_20c_20est_20tout_20le_20problème_25',['Coût : constant en taille de niveau, et c&apos;est tout le problème',['../guide-rendu.html#autotoc_md228',1,'']]],
  ['niveau_20et_20fin_20de_20séquence_26',['Fin de niveau et fin de séquence',['../guide-ecrans.html#autotoc_md80',1,'']]],
  ['niveau_20et_20progression_20persistée_20lot_2059_20tache_2005_2006_27',['Sélection de niveau et progression persistée (&lt;span class=&quot;tt&quot;&gt;LOT-59&lt;/span&gt; TACHE-05/06)',['../guide-ecrans.html#autotoc_md81',1,'']]],
  ['niveau_20lot_2069_28',['Le mode création : peindre le décor du niveau (&lt;span class=&quot;tt&quot;&gt;LOT-69&lt;/span&gt;)',['../guide-editeur.html#autotoc_md112',1,'']]],
  ['niveau_20minimal_20au_20lancement_29',['Configurer le niveau minimal au lancement',['../guide-journalisation.html#autotoc_md150',1,'']]],
  ['niveau_20mode_20«_20par_20salle_20»_30',['Mélanger plusieurs tailles de caméra dans un même niveau (mode « Par salle »)',['../manuel-partager-niveau.html#autotoc_md550',1,'']]],
  ['niveau_20plus_20grand_20que_20la_20fenêtre_31',['Cadrer un niveau plus grand que la fenêtre',['../guide-editeur.html#autotoc_md110',1,'']]],
  ['niveau_20qu_20on_20peut_20défaire_32',['&lt;a class=&quot;el&quot; href=&quot;classcore_1_1LevelDraft.html&quot; title=&quot;core::LevelDraft&quot;&gt;core::LevelDraft&lt;/a&gt; : un niveau qu&apos;on peut défaire',['../guide-editeur.html#autotoc_md97',1,'']]],
  ['niveau_20sans_20ligne_20de_20commande_33',['Créer et partager un niveau (sans ligne de commande)',['../manuel-partager-niveau.html',1,'manuel']]],
  ['niveau_20sans_20re_20coder_20le_20moteur_34',['Le problème : éditer un niveau sans (re)coder le moteur',['../guide-editeur.html#autotoc_md96',1,'']]],
  ['niveaux_35',['niveaux',['../spec-editeur.html',1,'Éditeur de niveaux'],['../spec-niveaux.html#autotoc_md335',1,'1. Représentation des niveaux'],['../spec-interface-ihm.html#autotoc_md327',1,'3. Gestion des niveaux'],['../guide-editeur.html#autotoc_md117',1,'Gérer ses fichiers de niveaux']]],
  ['niveaux_20à_20salles_20lot_2032_36',['10. Niveaux à salles (&lt;span class=&quot;tt&quot;&gt;LOT-32&lt;/span&gt;)',['../spec-editeur.html#autotoc_md301',1,'']]],
  ['niveaux_20—_20test_5fparcours_5fedition_20cpp_202_37',['Éditeur de niveaux — &lt;span class=&quot;tt&quot;&gt;test_parcours_edition.cpp&lt;/span&gt; (2)',['../cahiertest.html#autotoc_md30',1,'']]],
  ['niveaux_20_3a_20modèle_20chargement_20mécanismes_20budgets_38',['Niveaux : modèle, chargement, mécanismes, budgets',['../guide-niveaux.html',1,'guide']]],
  ['niveaux_20contenu_39',['Niveaux &amp;amp; contenu',['../spec-niveaux.html',1,'specifications']]],
  ['niveaux_20de_20grande_20taille_20lot_2016_40',['7. Niveaux de grande taille (LOT-16)',['../spec-editeur.html#autotoc_md298',1,'']]],
  ['niveaux_20de_20gravité_20_3a_20core_3a_3aloglevel_20core_3a_3aloglevel_41',['Les niveaux de gravité : &lt;a class=&quot;el&quot; href=&quot;namespacecore.html#aa9b5a444ee11933c91d5e3235aa5b5e3&quot; title=&quot;core::LogLevel&quot;&gt;core::LogLevel&lt;/a&gt;',['../guide-journalisation.html#autotoc_md143',1,'']]],
  ['niveaux_20des_20autres_42',['5. Récupérer les niveaux des autres',['../manuel-partager-niveau.html#autotoc_md552',1,'']]],
  ['niveaux_20donnée_20de_20contenu_20lot_2059_43',['Séquence de niveaux (donnée de contenu, &lt;span class=&quot;tt&quot;&gt;LOT-59&lt;/span&gt;)',['../guide-niveaux.html#autotoc_md179',1,'']]],
  ['niveaux_20intégré_44',['Éditeur de niveaux intégré',['../guide-editeur.html',1,'guide']]],
  ['niveaux_20lot_2036_45',['Gestion des niveaux (LOT-36)',['../guide-ihm-qt.html#autotoc_md137',1,'']]],
  ['nommé_46',['L&apos;historique : local au canevas, et nommé',['../guide-atelier-pixel-art.html#autotoc_md34',1,'']]],
  ['nommage_47',['2. Nommage',['../spec-conventions.html#autotoc_md266',1,'']]],
  ['non_20fonctionnelles_48',['Exigences non fonctionnelles',['../spec-exigences.html',1,'specifications']]],
  ['non_20objectifs_20éditeur_20mvp_49',['5. Non-objectifs (éditeur, MVP)',['../spec-editeur.html#autotoc_md296',1,'']]],
  ['non_20régression_20du_20volume_20source_20test_20unit_20hmi_20graphics_20test_5frender_5fbudget_20cpp_50',['Le test de non-régression du volume (&lt;span class=&quot;tt&quot;&gt;Source/Test/Unit/HMI/Graphics/test_render_budget.cpp&lt;/span&gt;)',['../guide-rendu.html#autotoc_md240',1,'']]],
  ['note_20de_20conception_51',['Note de conception',['../lot-08.html#autotoc_md405',1,'Note de conception'],['../lot-16.html#autotoc_md448',1,'Note de conception'],['../lot-25.html#autotoc_md498',1,'Note de conception']]],
  ['note_20de_20méthode_52',['Note de méthode',['../lot-28.html#autotoc_md517',1,'']]],
  ['nu_53',['LOT-01 — Fork, purge et remise à nu',['../lot-01.html',1,'lots']]],
  ['numériques_54',['1. Fondations numériques',['../spec-ia.html#autotoc_md320',1,'']]]
];
