var searchData=
[
  ['aériennes_20avancées_20au_20delà_20du_20mvp_0',['Mécaniques aériennes avancées (au-delà du MVP)',['../spec-gameplay.html#autotoc_md330',1,'']]],
  ['a_20été_20faite_1',['Comment la classification a été faite',['../lot-78.html#autotoc_md502',1,'']]],
  ['a_20appris_2',['4. Ce que l&apos;extraction a appris',['../roadmap-010.html#autotoc_md522',1,'']]],
  ['a_20démenti_3',['Ce que la réalisation a vérifié, et ce qu&apos;elle a démenti',['../lot-30.html#autotoc_md454',1,'']]],
  ['a_20le_20droit_20de_20se_20lier_20à_20qui_4',['Mécanismes : qui a le droit de se lier à qui',['../guide-editeur.html#autotoc_md100',1,'']]],
  ['a_20mis_20au_20jour_5',['Trois défauts du corpus que ce lot a mis au jour',['../lot-43.html#autotoc_md491',1,'']]],
  ['a_20révélé_6',['Ce que l&apos;ordre a révélé',['../roadmap-010.html#autotoc_md533',1,'']]],
  ['a_20révélé_20sur_20l_20état_20du_20dépôt_7',['9. Ce que l&apos;audit a révélé sur l&apos;état du dépôt',['../roadmap-010.html#autotoc_md544',1,'']]],
  ['a_20sa_20propre_20catégorie_8',['Chaque module a sa propre catégorie',['../guide-journalisation.html#autotoc_md149',1,'']]],
  ['a_20tranché_9',['a tranché',['../lot-04.html#autotoc_md416',1,'Ce que la réalisation a tranché'],['../lot-05.html#autotoc_md423',1,'Ce que la réalisation a tranché'],['../lot-06.html#autotoc_md430',1,'Ce que la réalisation a tranché'],['../lot-08.html#autotoc_md442',1,'Ce que la réalisation a tranché'],['../lot-32.html#autotoc_md462',1,'Ce que la réalisation a tranché'],['../lot-79.html#autotoc_md508',1,'Ce que la réalisation a tranché'],['../lot-77.html#autotoc_md498',1,'Ce que la rédaction a tranché']]],
  ['a_20vérifié_20et_20ce_20qu_20elle_20a_20démenti_10',['Ce que la réalisation a vérifié, et ce qu&apos;elle a démenti',['../lot-30.html#autotoc_md454',1,'']]],
  ['aabb_11',['1. Collision par balayage continu (swept AABB)',['../guide-physique.html#autotoc_md185',1,'']]],
  ['aabb_20_3a_20la_20boîte_20englobante_20alignée_20aux_20axes_12',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Aabb.html&quot; title=&quot;core::Aabb&quot;&gt;Aabb&lt;/a&gt; : la boîte englobante alignée aux axes',['../guide-maths.html#autotoc_md159',1,'']]],
  ['abord_20le_20widget_20ensuite_13',['Le canevas : la géométrie d&apos;abord, le widget ensuite',['../guide-atelier-pixel-art.html#autotoc_md37',1,'']]],
  ['abstraction_20de_20rendu_14',['6. Abstraction de rendu',['../spec-architecture.html#autotoc_md255',1,'']]],
  ['accès_20au_20gpu_20pas_20un_20changement_20de_20cible_15',['QRhi : une couche d&apos;accès au GPU, pas un changement de cible',['../guide-rendu.html#autotoc_md204',1,'']]],
  ['acceptation_16',['acceptation',['../lot-01.html#autotoc_md396',1,'Critères d&apos;acceptation'],['../lot-02.html#autotoc_md403',1,'Critères d&apos;acceptation'],['../lot-03.html#autotoc_md409',1,'Critères d&apos;acceptation'],['../lot-04.html#autotoc_md415',1,'Critères d&apos;acceptation'],['../lot-05.html#autotoc_md422',1,'Critères d&apos;acceptation'],['../lot-06.html#autotoc_md429',1,'Critères d&apos;acceptation'],['../lot-07.html#autotoc_md436',1,'Critères d&apos;acceptation'],['../lot-08.html#autotoc_md441',1,'Critères d&apos;acceptation'],['../lot-12.html#autotoc_md451',1,'Critères d&apos;acceptation'],['../lot-30.html#autotoc_md458',1,'Critères d&apos;acceptation'],['../lot-32.html#autotoc_md465',1,'Critères d&apos;acceptation'],['../lot-33.html#autotoc_md474',1,'Critères d&apos;acceptation'],['../lot-36.html#autotoc_md487',1,'Critères d&apos;acceptation'],['../lot-43.html#autotoc_md495',1,'Critères d&apos;acceptation'],['../lot-77.html#autotoc_md499',1,'Critères d&apos;acceptation'],['../lot-78.html#autotoc_md504',1,'Critères d&apos;acceptation'],['../lot-79.html#autotoc_md509',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md558',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md564',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md570',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md575',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md580',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md585',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md590',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md596',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md602',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md608',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md613',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md619',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md624',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md630',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md635',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md640',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md645',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md650',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md659',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md665',1,'Critères d&apos;acceptation']]],
  ['accommodation_20dimensionnante_17',['11. Décors dynamiques (accommodation dimensionnante)',['../spec-architecture.html#autotoc_md260',1,'']]],
  ['accumulateur_20_3a_20core_3a_3afixedtimestep_20core_3a_3afixedtimestep_18',['L&apos;accumulateur : &lt;a class=&quot;el&quot; href=&quot;classcore_1_1FixedTimestep.html&quot; title=&quot;core::FixedTimestep&quot;&gt;core::FixedTimestep&lt;/a&gt;',['../guide-boucle.html#autotoc_md53',1,'']]],
  ['actions_20du_20jeu_20mapping_20logique_19',['2. Actions du jeu (mapping logique)',['../spec-controles.html#autotoc_md275',1,'']]],
  ['actions_20logiques_20',['Entrées et actions logiques',['../guide-entrees.html',1,'guide']]],
  ['adjacent_20correction_20du_20balayage_20horizontal_21',['Le piège du mur adjacent (correction du balayage horizontal)',['../guide-physique.html#autotoc_md194',1,'']]],
  ['adversaire_22',['6. L&apos;adversaire',['../spec-combat.html#autotoc_md267',1,'']]],
  ['affichage_23',['Netteté à toute échelle d&apos;affichage',['../guide-design-ihm.html#autotoc_md65',1,'']]],
  ['agonie_20et_20mort_24',['5. Agonie et mort',['../spec-combat.html#autotoc_md266',1,'']]],
  ['agonie_20et_20mort_25',['&lt;span class=&quot;tt&quot;&gt;LOT-72&lt;/span&gt; — Conditions, agonie et mort',['../roadmap-010.html#lot-72',1,'']]],
  ['agrégat_20leveldata_26',['LOT-03 — Agrégat `LevelData`',['../lot-03.html',1,'lots']]],
  ['ailleurs_20qu_20en_20dur_27',['Ce qui est figé ailleurs qu&apos;en dur',['../lot-12.html#autotoc_md449',1,'']]],
  ['ajout_20et_20suppression_20_3a_20swap_20and_20pop_28',['Ajout et suppression : &lt;em&gt;swap-and-pop&lt;/em&gt;',['../guide-ecs.html#autotoc_md93',1,'']]],
  ['ajout_20pas_20une_20refonte_29',['Pourquoi ce lot est un lot d&apos;&lt;b&gt;ajout&lt;/b&gt;, pas une refonte',['../roadmap-010.html#autotoc_md661',1,'']]],
  ['aléatoires_20et_20contenu_20d_20ambiance_30',['&lt;span class=&quot;tt&quot;&gt;LOT-44&lt;/span&gt; — Noms, tables aléatoires et contenu d&apos;ambiance',['../roadmap-010.html#lot-44',1,'']]],
  ['algorithme_20évolutif_31',['Comment fonctionne la population (algorithme Évolutif)',['../manuel-mode-ia.html#autotoc_md677',1,'']]],
  ['algorithmes_20d_20apprentissage_32',['3. Algorithmes d&apos;apprentissage',['../spec-ia.html#autotoc_md338',1,'']]],
  ['alignée_20aux_20axes_33',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Aabb.html&quot; title=&quot;core::Aabb&quot;&gt;Aabb&lt;/a&gt; : la boîte englobante alignée aux axes',['../guide-maths.html#autotoc_md159',1,'']]],
  ['allègement_20est_20le_20geste_20à_20plus_20fort_20levier_20du_20programme_34',['9.3 L&apos;allègement est le geste à plus fort levier du programme',['../roadmap-010.html#autotoc_md547',1,'']]],
  ['ambiance_35',['&lt;span class=&quot;tt&quot;&gt;LOT-44&lt;/span&gt; — Noms, tables aléatoires et contenu d&apos;ambiance',['../roadmap-010.html#lot-44',1,'']]],
  ['and_20pop_36',['Ajout et suppression : &lt;em&gt;swap-and-pop&lt;/em&gt;',['../guide-ecs.html#autotoc_md93',1,'']]],
  ['animation_20_3a_20des_20clips_20en_20données_20une_20progression_20générale_20lot_2046_37',['L&apos;animation : des clips en données, une progression générale (&lt;span class=&quot;tt&quot;&gt;LOT-46&lt;/span&gt;)',['../guide-rendu.html#autotoc_md220',1,'']]],
  ['animation_20personnage_20—_20test_5fanimation_5fpersonnage_20cpp_206_38',['Animation Personnage — &lt;span class=&quot;tt&quot;&gt;test_animation_personnage.cpp&lt;/span&gt; (6)',['../cahiertest.html#autotoc_md27',1,'']]],
  ['annuler_20refaire_20_3a_20pourquoi_20des_20instantanés_20complets_39',['Annuler/refaire : pourquoi des instantanés complets',['../guide-editeur.html#autotoc_md108',1,'']]],
  ['annuler_20refaire_20deux_20cibles_40',['Une seule paire Annuler/Refaire, deux cibles',['../guide-atelier-pixel-art.html#autotoc_md41',1,'']]],
  ['anticiper_20tant_20que_20rien_20n_20est_20construit_41',['10. Ce qu&apos;il faut anticiper, tant que rien n&apos;est construit',['../roadmap-010.html#autotoc_md551',1,'']]],
  ['aperçu_42',['La référence : un repère géométrique, pas un aperçu',['../guide-editeur.html#autotoc_md118',1,'']]],
  ['applicatif_43',['1. Socle applicatif',['../spec-interface-ihm.html#autotoc_md341',1,'']]],
  ['applicatif_20viewport_20direct3d_2011_44',['IHM Qt (refonte) — socle applicatif &amp;amp; viewport Direct3D 11',['../guide-ihm-qt.html',1,'guide']]],
  ['application_20habillée_45',['De jetons purs à une application habillée',['../guide-design-ihm.html#autotoc_md62',1,'']]],
  ['application_20pour_20changer_20un_20pixel_46',['Le problème : quitter l&apos;application pour changer un pixel',['../guide-atelier-pixel-art.html#autotoc_md33',1,'']]],
  ['application_20qt_47',['Une seule cible : l&apos;application Qt',['../guide-ihm-qt.html#autotoc_md133',1,'']]],
  ['apporte_20chiffré_48',['Ce que chaque document apporte, chiffré',['../roadmap-010.html#autotoc_md518',1,'']]],
  ['apprentissage_49',['3. Algorithmes d&apos;apprentissage',['../spec-ia.html#autotoc_md338',1,'']]],
  ['appris_50',['4. Ce que l&apos;extraction a appris',['../roadmap-010.html#autotoc_md522',1,'']]],
  ['approchée_51',['Égalité approchée',['../guide-maths.html#autotoc_md158',1,'']]],
  ['approche_20d_20implémentation_20décidée_52',['4. Approche d&apos;implémentation (décidée)',['../spec-editeur.html#autotoc_md308',1,'']]],
  ['arête_20n_20est_20contrôlée_20qu_20une_20fois_53',['Le triangle, et pourquoi chaque arête n&apos;est contrôlée qu&apos;une fois',['../lot-32.html#autotoc_md461',1,'']]],
  ['arborescence_20cible_54',['7. Arborescence cible',['../roadmap-010.html#autotoc_md538',1,'']]],
  ['architecture_20décisions_20dimensionnantes_55',['Architecture (décisions dimensionnantes)',['../spec-architecture.html',1,'specifications']]],
  ['architecture_20dépendances_20entre_20modules_56',['5. Architecture (dépendances entre modules)',['../spec-conventions.html#autotoc_md285',1,'']]],
  ['architecture_20de_20l_20information_57',['Système de design et architecture de l&apos;information',['../guide-design-ihm.html',1,'guide']]],
  ['architecture_20de_20l_20information_20_3a_20ce_20qui_20informe_20reste_20ce_20qui_20commande_20est_20unique_58',['Architecture de l&apos;information : ce qui informe reste, ce qui commande est unique',['../guide-design-ihm.html#autotoc_md67',1,'']]],
  ['architecture_20de_20l_20information_20de_20l_20éditeur_20lot_20h_2057_59',['7. Architecture de l&apos;information de l&apos;éditeur (LOT-H-57)',['../spec-interface-ihm.html#autotoc_md347',1,'']]],
  ['architecture_20en_20deux_20couches_60',['Architecture en deux couches',['../guide.html#autotoc_md248',1,'']]],
  ['architecture_20maintenabilité_61',['2. Architecture &amp;amp; maintenabilité',['../spec-exigences.html#autotoc_md319',1,'']]],
  ['arrêtent_20la_20génération_62',['Deux contrôles qui arrêtent la génération',['../lot-33.html#autotoc_md469',1,'']]],
  ['arrivée_63',['La solution : tester tout le trajet, pas seulement l&apos;arrivée',['../guide-physique.html#autotoc_md187',1,'']]],
  ['arrondi_20_3a_20tangente_20verticale_20à_20une_20extrémité_64',['Particularité de l&apos;arrondi : tangente verticale à une extrémité',['../guide-physique.html#autotoc_md195',1,'']]],
  ['arrondi_20ex_20gp_20003_20ex_20gp_20004_65',['2. Suivi de pente et d&apos;arrondi (EX-GP-003, EX-GP-004)',['../guide-physique.html#autotoc_md191',1,'']]],
  ['arrondi_20n_20est_20jamais_20solide_66',['Pourquoi une pente (ou un arrondi) n&apos;est jamais solide',['../guide-physique.html#autotoc_md192',1,'']]],
  ['arrondis_20qui_20ne_20se_20voient_20pas_67',['Deux arrondis qui ne se voient pas',['../lot-12.html#autotoc_md446',1,'']]],
  ['art_68',['art',['../roadmap-010.html#lot-66',1,'&lt;span class=&quot;tt&quot;&gt;LOT-66&lt;/span&gt; — Charte visuelle : sortir de l&apos;identité pixel art'],['../roadmap-010.html#lot-69',1,'&lt;span class=&quot;tt&quot;&gt;LOT-69&lt;/span&gt; — Retrait de l&apos;atelier pixel art'],['../spec-decors.html',1,'Plans picturaux &amp; pipeline pixel art']]],
  ['art_20intégré_69',['Atelier pixel art intégré',['../guide-atelier-pixel-art.html',1,'guide']]],
  ['art_20intégré_20à_20l_20éditeur_70',['3. Pipeline photo → pixel art (intégré à l&apos;éditeur)',['../spec-decors.html#autotoc_md301',1,'']]],
  ['art_20post_20mvp_20intégré_20à_20l_20éditeur_71',['4bis. Décors &amp;amp; pixel art (post-MVP, intégré à l&apos;éditeur)',['../spec-editeur.html#autotoc_md309',1,'']]],
  ['assemblé_72',['&lt;a class=&quot;el&quot; href=&quot;classcore_1_1Level.html&quot; title=&quot;core::Level&quot;&gt;core::Level&lt;/a&gt; : le niveau assemblé',['../guide-niveaux.html#autotoc_md167',1,'']]],
  ['assembler_20la_20frame_20complète_73',['Assembler la frame complète',['../guide-rendu.html#autotoc_md239',1,'']]],
  ['assertions_74',['Journalisation et assertions',['../guide-journalisation.html',1,'guide']]],
  ['assertions_20_3a_20jadg_5fassert_20jadg_5fassert_20un_20outil_20différent_75',['Assertions : &lt;a class=&quot;el&quot; href=&quot;Assert_8h.html#a2811f3d423b22f1a90179b4ed095f054&quot; title=&quot;JADG_ASSERT&quot;&gt;JADG_ASSERT&lt;/a&gt;, un outil différent',['../guide-journalisation.html#autotoc_md154',1,'']]],
  ['assertions_20journalisation_76',['10. Assertions &amp;amp; journalisation',['../spec-conventions.html#autotoc_md295',1,'']]],
  ['asset_20à_20une_20taille_20forcément_20conforme_77',['Créer un asset à une taille forcément conforme',['../guide-atelier-pixel-art.html#autotoc_md39',1,'']]],
  ['assets_78',['5. Assets',['../spec-contenu.html#autotoc_md272',1,'']]],
  ['assets_79',['&lt;span class=&quot;tt&quot;&gt;LOT-39&lt;/span&gt; — Plomberie des clés d&apos;assets',['../roadmap-010.html#lot-39',1,'']]],
  ['assets_20_3a_20convention_20et_20régénération_80',['&lt;span class=&quot;tt&quot;&gt;Source/Elements/Assets/&lt;/span&gt; : convention et régénération',['../guide-rendu.html#autotoc_md217',1,'']]],
  ['assumée_81',['Conséquence assumée',['../lot-01.html#autotoc_md393',1,'']]],
  ['atelier_20pixel_20art_82',['&lt;span class=&quot;tt&quot;&gt;LOT-69&lt;/span&gt; — Retrait de l&apos;atelier pixel art',['../roadmap-010.html#lot-69',1,'']]],
  ['atelier_20pixel_20art_20intégré_83',['Atelier pixel art intégré',['../guide-atelier-pixel-art.html',1,'guide']]],
  ['atlas_84',['Les images du personnage : pourquoi elles vivent dans le même atlas',['../guide-rendu.html#autotoc_md218',1,'']]],
  ['atlas_20des_20régions_20et_20graphe_20de_20cartes_85',['&lt;span class=&quot;tt&quot;&gt;LOT-37&lt;/span&gt; — Atlas des régions et graphe de cartes',['../roadmap-010.html#lot-37',1,'']]],
  ['attaque_20et_20dégâts_86',['4. Attaque et dégâts',['../spec-combat.html#autotoc_md265',1,'']]],
  ['attaques_20dégâts_20et_20états_87',['LOT-21 — Attaques, dégâts et états',['../roadmap-010.html#lot-21',1,'']]],
  ['attente_20—_20deux_20décisions_88',['Conservé contre l&apos;attente — deux décisions',['../lot-01.html#autotoc_md392',1,'']]],
  ['attesté_20pas_20saisi_89',['Le complément des &lt;em&gt;Basic Rules&lt;/em&gt; est attesté, pas saisi',['../lot-30.html#autotoc_md455',1,'']]],
  ['au_20canevas_20et_20nommé_90',['L&apos;historique : local au canevas, et nommé',['../guide-atelier-pixel-art.html#autotoc_md36',1,'']]],
  ['au_20delà_20de_200_201_200_91',['Ressenti (game feel) — ⚠️ réglage fin reporté au-delà de &lt;span class=&quot;tt&quot;&gt;0.1.0&lt;/span&gt;',['../spec-gameplay.html#autotoc_md331',1,'']]],
  ['au_20delà_20du_20moteur_92',['Objectifs produit (au-delà du moteur)',['../spec-vision.html#autotoc_md383',1,'']]],
  ['au_20delà_20du_20mvp_93',['Mécaniques aériennes avancées (au-delà du MVP)',['../spec-gameplay.html#autotoc_md330',1,'']]],
  ['au_20gpu_20pas_20un_20changement_20de_20cible_94',['QRhi : une couche d&apos;accès au GPU, pas un changement de cible',['../guide-rendu.html#autotoc_md204',1,'']]],
  ['au_20jeu_20et_20outillage_95',['5. Intégration au jeu et outillage',['../spec-ia.html#autotoc_md340',1,'']]],
  ['au_20jour_96',['au jour',['../lot-33.html#autotoc_md471',1,'Cinq défauts du lexique que les 94 noms ont mis au jour'],['../lot-43.html#autotoc_md491',1,'Trois défauts du corpus que ce lot a mis au jour']]],
  ['au_20lancement_97',['Configurer le niveau minimal au lancement',['../guide-journalisation.html#autotoc_md152',1,'']]],
  ['au_20vertical_20slice_98',['Le chemin critique jusqu&apos;au &lt;em&gt;vertical slice&lt;/em&gt;',['../roadmap-010.html#autotoc_md534',1,'']]],
  ['aucun_20écran_20ne_20contraint_20la_20fenêtre_20lot_2073_99',['La taille : aucun écran ne contraint la fenêtre (LOT-73)',['../guide-ihm-qt.html#autotoc_md141',1,'']]],
  ['audio_100',['Audio',['../spec-rendu-technique.html#autotoc_md370',1,'5. Audio'],['../guide-audio.html',1,'Audio'],['../roadmap-010.html#autotoc_md653',1,'Audio']]],
  ['audio_101',['Crédits audio',['../md__2home_2runner_2work_2JustAnotherDnDGame_2JustAnotherDnDGame_2Source_2Elements_2Audio_2CREDITS.html',1,'']]],
  ['audio_2014_102',['Audio (14)',['../cahiertest.html#autotoc_md18',1,'']]],
  ['audio_20effets_20et_20version_200_202_200_103',['LOT-28 — Audio, effets et version &lt;span class=&quot;tt&quot;&gt;0.2.0&lt;/span&gt;',['../roadmap-010.html#lot-28',1,'']]],
  ['audit_20_3a_20hmi_3a_3alayervisibility_20lot_2051_104',['Isoler un calque pour l&apos;audit : &lt;span class=&quot;tt&quot;&gt;hmi::LayerVisibility&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;LOT-51&lt;/span&gt;)',['../guide-rendu.html#autotoc_md224',1,'']]],
  ['audit_20a_20révélé_20sur_20l_20état_20du_20dépôt_105',['9. Ce que l&apos;audit a révélé sur l&apos;état du dépôt',['../roadmap-010.html#autotoc_md544',1,'']]],
  ['auditer_20les_20calques_20sans_20les_20confondre_20avec_20f8_20lot_2051_106',['Le mode « définition des textures » : auditer les calques sans les confondre avec &lt;span class=&quot;tt&quot;&gt;F8&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;LOT-51&lt;/span&gt;)',['../guide-editeur.html#autotoc_md113',1,'']]],
  ['aurait_20pas_20vu_107',['Le défaut que les tests ont trouvé, et que la relecture n&apos;aurait pas vu',['../lot-12.html#autotoc_md445',1,'']]],
  ['aussi_108',['aussi',['../guide-atelier-pixel-art.html#autotoc_md42',1,'Voir aussi'],['../guide-audio.html#autotoc_md49',1,'Voir aussi'],['../guide-boucle.html#autotoc_md59',1,'Voir aussi'],['../guide-design-ihm.html#autotoc_md76',1,'Voir aussi'],['../guide-ecrans.html#autotoc_md88',1,'Voir aussi'],['../guide-ecs.html#autotoc_md97',1,'Voir aussi'],['../guide-editeur.html#autotoc_md120',1,'Voir aussi'],['../guide-entrees.html#autotoc_md131',1,'Voir aussi'],['../guide-ihm-qt.html#autotoc_md143',1,'Voir aussi'],['../guide-journalisation.html#autotoc_md155',1,'Voir aussi'],['../guide-maths.html#autotoc_md162',1,'Voir aussi'],['../guide-niveaux.html#autotoc_md184',1,'Voir aussi'],['../guide-physique.html#autotoc_md202',1,'Voir aussi'],['../guide-rendu.html#autotoc_md246',1,'Voir aussi']]],
  ['autant_109',['Ce que le schéma ne peut pas dire, et qui n&apos;est pas perdu pour autant',['../lot-33.html#autotoc_md470',1,'']]],
  ['auto_20teste_110',['Ce que le contrôle vérifie, et pourquoi il s&apos;auto-teste',['../lot-30.html#autotoc_md456',1,'']]],
  ['auto_20teste_20faute_20de_20données_20à_20valider_111',['Le validateur s&apos;auto-teste, faute de données à valider',['../lot-32.html#autotoc_md463',1,'']]],
  ['automatisé_112',['11. Outillage qualité (automatisé)',['../spec-conventions.html#autotoc_md296',1,'']]],
  ['autre_113',['Sa gouttière bouge d&apos;une page à l&apos;autre',['../lot-36.html#autotoc_md480',1,'']]],
  ['autrement_114',['Ce que le corpus dit, et que la feuille de route disait autrement',['../lot-36.html#autotoc_md482',1,'']]],
  ['autres_115',['5. Récupérer les niveaux des autres',['../manuel-partager-niveau.html#autotoc_md690',1,'']]],
  ['aux_20axes_116',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Aabb.html&quot; title=&quot;core::Aabb&quot;&gt;Aabb&lt;/a&gt; : la boîte englobante alignée aux axes',['../guide-maths.html#autotoc_md159',1,'']]],
  ['aux_20entités_20_3a_20core_3a_3abuildlevelscene_20buildlevelscene_117',['De la grille aux entités : &lt;a class=&quot;el&quot; href=&quot;namespacecore.html#a69ac6b2c5ca32686a14824d1f1c04b2a&quot; title=&quot;core::buildLevelScene&quot;&gt;buildLevelScene&lt;/a&gt;',['../guide-niveaux.html#autotoc_md172',1,'']]],
  ['avancées_20au_20delà_20du_20mvp_118',['Mécaniques aériennes avancées (au-delà du MVP)',['../spec-gameplay.html#autotoc_md330',1,'']]],
  ['avancés_20lot_2031_119',['Dangers avancés (&lt;span class=&quot;tt&quot;&gt;LOT-31&lt;/span&gt;)',['../guide-niveaux.html#autotoc_md179',1,'']]],
  ['avancés_20lot_20h_2031_120',['avancés LOT H 31',['../spec-editeur.html#autotoc_md314',1,'9. Dangers avancés (&lt;span class=&quot;tt&quot;&gt;LOT-H-31&lt;/span&gt;)'],['../spec-gameplay.html#autotoc_md328',1,'Dangers avancés (&lt;span class=&quot;tt&quot;&gt;LOT-H-31&lt;/span&gt;)']]],
  ['avancement_121',['Avancement',['../index.html#autotoc_md3',1,'']]],
  ['avancement_122',['État d&apos;avancement',['../roadmap-010.html#roadmap-avancement',1,'']]],
  ['avant_20d_20écrire_20jamais_20l_20inverse_123',['Enregistrer : valider avant d&apos;écrire, jamais l&apos;inverse',['../guide-editeur.html#autotoc_md110',1,'']]],
  ['avant_20de_20l_20avoir_20posé_124',['Voir le raccord avant de l&apos;avoir posé',['../guide-atelier-pixel-art.html#autotoc_md40',1,'']]],
  ['avant_20données_125',['2. Contrats avant données',['../spec-contenu.html#autotoc_md269',1,'']]],
  ['avec_20clamp_20direct_126',['Méthode retenue : balayage &lt;b&gt;par axe&lt;/b&gt; avec clamp direct',['../guide-physique.html#autotoc_md188',1,'']]],
  ['avec_20f8_20lot_2051_127',['Le mode « définition des textures » : auditer les calques sans les confondre avec &lt;span class=&quot;tt&quot;&gt;F8&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;LOT-51&lt;/span&gt;)',['../guide-editeur.html#autotoc_md113',1,'']]],
  ['avec_20le_20jeu_20et_20observabilité_128',['2. Pont avec le jeu et observabilité',['../spec-ia.html#autotoc_md337',1,'']]],
  ['avec_20un_20piège_129',['&lt;a class=&quot;el&quot; href=&quot;classcore_1_1LevelWriter.html&quot; title=&quot;core::LevelWriter&quot;&gt;core::LevelWriter&lt;/a&gt; : l&apos;inverse du chargement, avec un piège',['../guide-editeur.html#autotoc_md102',1,'']]],
  ['aventuriers_20_3a_20rangs_20et_20contrats_130',['&lt;span class=&quot;tt&quot;&gt;LOT-45&lt;/span&gt; — Guilde des Aventuriers : rangs et contrats',['../roadmap-010.html#lot-45',1,'']]],
  ['avoir_20posé_131',['Voir le raccord avant de l&apos;avoir posé',['../guide-atelier-pixel-art.html#autotoc_md40',1,'']]],
  ['axe_20_3a_20la_20mémoire_20de_20texture_20des_20plans_20lot_2069_132',['Le second axe : la mémoire de texture des plans (&lt;span class=&quot;tt&quot;&gt;LOT-69&lt;/span&gt;)',['../guide-rendu.html#autotoc_md243',1,'']]],
  ['axe_20avec_20clamp_20direct_133',['Méthode retenue : balayage &lt;b&gt;par axe&lt;/b&gt; avec clamp direct',['../guide-physique.html#autotoc_md188',1,'']]],
  ['axes_134',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Aabb.html&quot; title=&quot;core::Aabb&quot;&gt;Aabb&lt;/a&gt; : la boîte englobante alignée aux axes',['../guide-maths.html#autotoc_md159',1,'']]]
];
