var searchData=
[
  ['sélection_20de_20niveau_0',['Progression et sélection de niveau',['../manuel-jouer.html#autotoc_md755',1,'']]],
  ['séparés_20du_20canevas_1',['La palette et les outils : des panneaux Qt séparés du canevas',['../guide-editeur.html#autotoc_md103',1,'']]],
  ['séquencement_2',['4. Périmètre &amp;amp; séquencement',['../spec-decors.html#autotoc_md300',1,'']]],
  ['s_20auto_20teste_3',['Ce que le contrôle vérifie, et pourquoi il s&apos;auto-teste',['../lot-30.html#autotoc_md488',1,'']]],
  ['s_20auto_20teste_20faute_20de_20données_20à_20valider_4',['Le validateur s&apos;auto-teste, faute de données à valider',['../lot-32.html#autotoc_md495',1,'']]],
  ['s_20guide_20dessine_20ses_20titres_20deux_20fois_5',['Le &lt;em&gt;Player&apos;s Guide&lt;/em&gt; dessine ses titres deux fois',['../lot-36.html#autotoc_md523',1,'']]],
  ['s_20insère_20dans_20la_20boucle_6',['Où ça s&apos;insère dans la boucle',['../guide-ecrans.html#autotoc_md86',1,'']]],
  ['sa_20gouttière_20bouge_20d_20une_20page_20à_20l_20autre_7',['Sa gouttière bouge d&apos;une page à l&apos;autre',['../lot-36.html#autotoc_md522',1,'']]],
  ['sa_20graisse_20ment_8',['Le &lt;em&gt;Manuel des Joueurs&lt;/em&gt; est un scan, et sa graisse ment',['../lot-36.html#autotoc_md520',1,'']]],
  ['sa_20propre_20catégorie_9',['Chaque module a sa propre catégorie',['../guide-journalisation.html#autotoc_md148',1,'']]],
  ['sa_20rangée_10',['Le groupe d&apos;une arme n&apos;est pas dans sa rangée',['../lot-34.html#autotoc_md510',1,'']]],
  ['sable_20dans_20l_20univers_20entier_11',['La cible : un bac à sable dans l&apos;univers entier',['../roadmap-010.html#autotoc_md633',1,'']]],
  ['sable_20de_20combat_12',['&lt;span class=&quot;tt&quot;&gt;LOT-50&lt;/span&gt; — Le Colisée : bac à sable de combat',['../roadmap-010.html#lot-50',1,'']]],
  ['saisi_13',['Le complément des &lt;em&gt;Basic Rules&lt;/em&gt; est attesté, pas saisi',['../lot-30.html#autotoc_md487',1,'']]],
  ['sait_20pas_20faire_14',['Ce qu&apos;une feuille de style ne sait pas faire',['../guide-design-ihm.html#autotoc_md77',1,'']]],
  ['salle_20»_15',['Mélanger plusieurs tailles de caméra dans un même niveau (mode « Par salle »)',['../manuel-partager-niveau.html#autotoc_md773',1,'']]],
  ['salles_20lot_20h_2032_16',['10. Niveaux à salles (&lt;span class=&quot;tt&quot;&gt;LOT-H-32&lt;/span&gt;)',['../spec-editeur.html#autotoc_md313',1,'']]],
  ['sans_20être_20produites_17',['9.2 Six mécaniques étaient consommées sans être produites',['../roadmap-010.html#autotoc_md653',1,'']]],
  ['sans_20dupliquer_20la_20logique_20de_20peinture_20_3a_20core_3a_3aleveldraft_3a_3apaintregion_20leveldraft_3a_3apaintregion_18',['Peindre par lot sans dupliquer la logique de peinture : &lt;a class=&quot;el&quot; href=&quot;classcore_1_1LevelDraft.html#a7fb667e044067f5e9bf16f747d3f5f8e&quot; title=&quot;core::LevelDraft::paintRegion&quot;&gt;LevelDraft::paintRegion&lt;/a&gt;',['../guide-editeur.html#autotoc_md106',1,'']]],
  ['sans_20jamais_20laisser_20de_20fichier_20tronqué_19',['Écrire un PNG sans jamais laisser de fichier tronqué',['../guide-atelier-pixel-art.html#autotoc_md36',1,'']]],
  ['sans_20les_20confondre_20avec_20f8_20lot_2051_20',['Le mode « définition des textures » : auditer les calques sans les confondre avec &lt;span class=&quot;tt&quot;&gt;F8&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;LOT-51&lt;/span&gt;)',['../guide-editeur.html#autotoc_md112',1,'']]],
  ['sans_20ligne_20de_20commande_21',['Créer et partager un niveau (sans ligne de commande)',['../manuel-partager-niveau.html',1,'manuel']]],
  ['sans_20pas_20de_20simulation_20et_20les_20entrées_22',['Les frames sans pas de simulation et les entrées',['../guide-boucle.html#autotoc_md59',1,'']]],
  ['sans_20perdre_20un_20pas_23',['Pause : suspendre sans perdre un pas',['../guide-ecrans.html#autotoc_md84',1,'']]],
  ['sans_20quitter_20l_20éditeur_24',['Essai immédiat : jouer sans quitter l&apos;éditeur',['../guide-editeur.html#autotoc_md108',1,'']]],
  ['sans_20re_20coder_20le_20moteur_25',['Le problème : éditer un niveau sans (re)coder le moteur',['../guide-editeur.html#autotoc_md97',1,'']]],
  ['saut_20et_20game_20feel_26',['4. Saut et &lt;em&gt;game feel&lt;/em&gt;',['../guide-physique.html#autotoc_md195',1,'']]],
  ['sauvegarde_27',['Validation &amp;amp; sauvegarde',['../manuel-mode-ia.html#autotoc_md766',1,'']]],
  ['sauvegarde_20riche_28',['LOT-17 — Sauvegarde riche',['../roadmap-010.html#lot-17',1,'']]],
  ['scène_20_3a_20hmi_3a_3abitmapfont_20et_20hmi_3a_3atextrenderer_20lot_2052_29',['Le texte dans la scène : &lt;span class=&quot;tt&quot;&gt;hmi::BitmapFont&lt;/span&gt; et &lt;span class=&quot;tt&quot;&gt;hmi::TextRenderer&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;LOT-52&lt;/span&gt;)',['../guide-rendu.html#autotoc_md230',1,'']]],
  ['scan_20et_20sa_20graisse_20ment_30',['Le &lt;em&gt;Manuel des Joueurs&lt;/em&gt; est un scan, et sa graisse ment',['../lot-36.html#autotoc_md520',1,'']]],
  ['schéma_20ne_20peut_20pas_20dire_31',['Ce que le schéma ne peut pas dire',['../lot-36.html#autotoc_md525',1,'']]],
  ['schéma_20ne_20peut_20pas_20dire_20et_20qui_20n_20est_20pas_20perdu_20pour_20autant_32',['Ce que le schéma ne peut pas dire, et qui n&apos;est pas perdu pour autant',['../lot-33.html#autotoc_md502',1,'']]],
  ['schéma_20refusait_33',['Trois cas que le livre écrit et qu&apos;un schéma refusait',['../lot-34.html#autotoc_md511',1,'']]],
  ['schémas_20de_20données_20rpg_34',['LOT-32 — Schémas de données RPG',['../lot-32.html',1,'lots']]],
  ['se_20déduit_20le_20champ_20asset_20sert_20à_20déroger_35',['La clé se déduit ; le champ &lt;span class=&quot;tt&quot;&gt;asset&lt;/span&gt; sert à déroger',['../lot-39.html#autotoc_md553',1,'']]],
  ['se_20fait_20sur_20la_20typographie_20pas_20sur_20des_20expressions_20régulières_36',['L&apos;extraction se fait sur la typographie, pas sur des expressions régulières',['../lot-33.html#autotoc_md500',1,'']]],
  ['se_20lier_20à_20qui_37',['Mécanismes : qui a le droit de se lier à qui',['../guide-editeur.html#autotoc_md99',1,'']]],
  ['se_20lit_20par_20son_20cadre_20pas_20à_20l_20estime_38',['L&apos;encart se lit par son cadre, pas à l&apos;estime',['../lot-37.html#autotoc_md533',1,'']]],
  ['se_20paie_39',['C&apos;est le lot où le §4 se paie',['../lot-34.html#autotoc_md509',1,'']]],
  ['se_20pose_20sous_20la_20valeur_20jamais_20dessus_40',['Un seuil de corps se pose sous la valeur, jamais dessus',['../lot-36.html#autotoc_md527',1,'']]],
  ['se_20tromper_41',['Les règles à ne pas se tromper',['../roadmap-010.html#autotoc_md701',1,'']]],
  ['se_20vérifie_20sur_20le_20diff_20pas_20sur_20l_20intention_42',['« Aucune valeur de règle dans le C++ » se vérifie sur le diff, pas sur l&apos;intention',['../lot-13.html#autotoc_md460',1,'']]],
  ['se_20voient_20pas_43',['Deux arrondis qui ne se voient pas',['../lot-12.html#autotoc_md451',1,'']]],
  ['se_20voit_20_3a_20le_20culling_20lot_2040_44',['Ne dessiner que ce qui se voit : le culling (&lt;span class=&quot;tt&quot;&gt;LOT-40&lt;/span&gt;)',['../guide-rendu.html#autotoc_md219',1,'']]],
  ['second_20axe_20_3a_20la_20mémoire_20de_20texture_20des_20plans_20lot_2069_45',['Le second axe : la mémoire de texture des plans (&lt;span class=&quot;tt&quot;&gt;LOT-69&lt;/span&gt;)',['../guide-rendu.html#autotoc_md240',1,'']]],
  ['seconde_20source_20fusionnée_20en_20lecture_20ex_20ctrl_20002_20lot_2020_46',['La manette : une seconde source, fusionnée en lecture (EX-CTRL-002, LOT-20)',['../guide-entrees.html#autotoc_md126',1,'']]],
  ['secousse_20d_20écran_20hmi_3a_3acamera2d_47',['Le rendu (&lt;span class=&quot;tt&quot;&gt;hmi::ParticleRenderer&lt;/span&gt;) et la secousse d&apos;écran (&lt;span class=&quot;tt&quot;&gt;hmi::Camera2D&lt;/span&gt;)',['../guide-rendu.html#autotoc_md235',1,'']]],
  ['secousse_20d_20écran_20lot_2053_48',['Particules et secousse d&apos;écran (&lt;span class=&quot;tt&quot;&gt;LOT-53&lt;/span&gt;)',['../guide-rendu.html#autotoc_md232',1,'']]],
  ['segment_20orienté_20liens_20de_20mécanismes_20lot_2037_49',['&lt;a class=&quot;el&quot; href=&quot;structhmi_1_1LineQuad.html&quot; title=&quot;hmi::LineQuad&quot;&gt;LineQuad&lt;/a&gt; : un segment orienté (liens de mécanismes, &lt;span class=&quot;tt&quot;&gt;LOT-37&lt;/span&gt;)',['../guide-rendu.html#autotoc_md211',1,'']]],
  ['seize_20exigences_20_3a_20retirées_20pour_20douze_20refondues_20pour_20trois_50',['Les seize exigences : retirées pour douze, refondues pour trois',['../lot-67.html#autotoc_md582',1,'']]],
  ['septembre_202026_51',['Les ressources de table virtuelle (ajoutées le 7 septembre 2026)',['../roadmap-010.html#autotoc_md624',1,'']]],
  ['sert_20à_20déroger_52',['La clé se déduit ; le champ &lt;span class=&quot;tt&quot;&gt;asset&lt;/span&gt; sert à déroger',['../lot-39.html#autotoc_md553',1,'']]],
  ['ses_20fichiers_20de_20niveaux_53',['Gérer ses fichiers de niveaux',['../guide-editeur.html#autotoc_md118',1,'']]],
  ['ses_20titres_20deux_20fois_54',['Le &lt;em&gt;Player&apos;s Guide&lt;/em&gt; dessine ses titres deux fois',['../lot-36.html#autotoc_md523',1,'']]],
  ['set_20core_3a_3acomponentpool_55',['Le stockage : sparse set (core::ComponentPool&amp;lt;T&amp;gt;)',['../guide-ecs.html#autotoc_md91',1,'']]],
  ['seuil_20de_20corps_20se_20pose_20sous_20la_20valeur_20jamais_20dessus_56',['Un seuil de corps se pose sous la valeur, jamais dessus',['../lot-36.html#autotoc_md527',1,'']]],
  ['seule_20cible_20_3a_20l_20application_20qt_57',['Une seule cible : l&apos;application Qt',['../guide-ihm-qt.html#autotoc_md132',1,'']]],
  ['seule_20couleur_20de_20texte_20et_20elle_20vient_20des_20jetons_58',['Une seule couleur de texte, et elle vient des jetons',['../TitleBanner_8h.html#autotoc_md795',1,'']]],
  ['seule_20fois_59',['Deux unités, converties une seule fois',['../lot-34.html#autotoc_md513',1,'']]],
  ['seule_20hmilib_20»_60',['Le découpage retenu — et pourquoi il n&apos;est pas « une seule &lt;span class=&quot;tt&quot;&gt;HmiLib&lt;/span&gt; »',['../lot-02.html#autotoc_md396',1,'']]],
  ['seule_20paire_20annuler_20refaire_20deux_20cibles_61',['Une seule paire Annuler/Refaire, deux cibles',['../guide-atelier-pixel-art.html#autotoc_md43',1,'']]],
  ['seule_20source_20deux_20portées_20étanches_62',['Les jetons : une seule source, deux portées étanches',['../guide-design-ihm.html#autotoc_md63',1,'']]],
  ['seule_20une_20victoire_20l_20acquiert_63',['Seule une victoire l&apos;acquiert',['../lot-18.html#autotoc_md478',1,'']]],
  ['seulement_20là_20où_20la_20caméra_20défile_64',['Parallaxe : portée par le plan, bornée, et seulement là où la caméra défile',['../guide-rendu.html#autotoc_md226',1,'']]],
  ['seulement_20l_20état_65',['Détecter les fronts, pas seulement l&apos;état',['../guide-entrees.html#autotoc_md122',1,'']]],
  ['seulement_20l_20arrivée_66',['La solution : tester tout le trajet, pas seulement l&apos;arrivée',['../guide-physique.html#autotoc_md184',1,'']]],
  ['shaders_20et_20échantillonnage_20nearest_67',['Sommets, shaders, et échantillonnage &lt;em&gt;nearest&lt;/em&gt;',['../guide-rendu.html#autotoc_md210',1,'']]],
  ['signaux_68',['Qui déclenche les transitions : les signaux',['../guide-ecrans.html#autotoc_md82',1,'']]],
  ['simples_20dans_20le_20cpp_69',['Doxygen dans le header, commentaires simples // dans le .cpp',['../spec-conventions.html#autotoc_md288',1,'']]],
  ['simulation_70',['Conséquence pratique pour tout le code de simulation',['../guide-boucle.html#autotoc_md60',1,'']]],
  ['simulation_20—_20test_5fboucle_5fsimulation_20cpp_202_71',['Boucle Simulation — &lt;span class=&quot;tt&quot;&gt;test_boucle_simulation.cpp&lt;/span&gt; (2)',['../cahiertest.html#autotoc_md30',1,'']]],
  ['simulation_20↔_20rendu_72',['4. Frontière simulation ↔ rendu',['../spec-architecture.html#autotoc_md250',1,'']]],
  ['simulation_20et_20les_20entrées_73',['Les frames sans pas de simulation et les entrées',['../guide-boucle.html#autotoc_md59',1,'']]],
  ['singleton_20joueur_74',['&lt;span class=&quot;tt&quot;&gt;CharacterSheet&lt;/span&gt; est un objet autonome, jamais un singleton joueur',['../lot-13.html#autotoc_md461',1,'']]],
  ['sinks_20_3a_20où_20finissent_20les_20messages_75',['Les sinks : où finissent les messages',['../guide-journalisation.html#autotoc_md146',1,'']]],
  ['sinks_20différents_20en_20développement_20et_20en_20release_76',['Bootstrap réel : sinks différents en développement et en Release',['../guide-journalisation.html#autotoc_md152',1,'']]],
  ['six_20écrans_77',['Le titre devient son bandeau, sur les six écrans',['../lot-76.html#autotoc_md599',1,'']]],
  ['six_20mécaniques_20étaient_20consommées_20sans_20être_20produites_78',['9.2 Six mécaniques étaient consommées sans être produites',['../roadmap-010.html#autotoc_md653',1,'']]],
  ['slice_79',['slice',['../spec-vision.html#autotoc_md381',1,'Hors périmètre (&lt;em&gt;vertical slice&lt;/em&gt;)'],['../roadmap-010.html#autotoc_md641',1,'Le chemin critique jusqu&apos;au &lt;em&gt;vertical slice&lt;/em&gt;'],['../roadmap-010.html#lot-27',1,'LOT-27 — Contenu du &lt;em&gt;vertical slice&lt;/em&gt;'],['../spec-vision.html#autotoc_md379',1,'Objectifs (&lt;em&gt;vertical slice&lt;/em&gt;)']]],
  ['slide_80',['6. Wall jump et wall slide',['../guide-physique.html#autotoc_md197',1,'']]],
  ['socle_20_3a_20hmi_3a_3aaudioengine_81',['Le socle : &lt;span class=&quot;tt&quot;&gt;hmi::AudioEngine&lt;/span&gt;',['../guide-audio.html#autotoc_md46',1,'']]],
  ['socle_20applicatif_82',['1. Socle applicatif',['../spec-interface-ihm.html#autotoc_md338',1,'']]],
  ['socle_20applicatif_20viewport_20direct3d_2011_83',['IHM Qt (refonte) — socle applicatif &amp;amp; viewport Direct3D 11',['../guide-ihm-qt.html',1,'guide']]],
  ['socle_20de_20chargement_20de_20données_84',['LOT-79 — Socle de chargement de données',['../lot-79.html',1,'lots']]],
  ['socle_20de_20classe_20et_20le_20guerrier_20comme_20preuve_85',['&lt;span class=&quot;tt&quot;&gt;LOT-47&lt;/span&gt; — Socle de classe, et le guerrier comme preuve',['../roadmap-010.html#lot-47',1,'']]],
  ['socle_20technique_20tient_20mais_20trois_20préconditions_20manquent_86',['9.4 Le socle technique tient, mais trois préconditions manquent',['../roadmap-010.html#autotoc_md655',1,'']]],
  ['solide_87',['Pourquoi une pente (ou un arrondi) n&apos;est jamais solide',['../guide-physique.html#autotoc_md189',1,'']]],
  ['solution_20_3a_20tester_20tout_20le_20trajet_20pas_20seulement_20l_20arrivée_88',['La solution : tester tout le trajet, pas seulement l&apos;arrivée',['../guide-physique.html#autotoc_md184',1,'']]],
  ['solveur_20ia_89',['Solveur IA',['../spec-ia.html',1,'specifications']]],
  ['sombre_90',['Thème clair/sombre',['../guide-design-ihm.html#autotoc_md68',1,'']]],
  ['sommeil_91',['3. Licences : contrainte en sommeil',['../roadmap-010.html#autotoc_md627',1,'']]],
  ['sommets_20shaders_20et_20échantillonnage_20nearest_92',['Sommets, shaders, et échantillonnage &lt;em&gt;nearest&lt;/em&gt;',['../guide-rendu.html#autotoc_md210',1,'']]],
  ['son_20bandeau_20sur_20les_20six_20écrans_93',['Le titre devient son bandeau, sur les six écrans',['../lot-76.html#autotoc_md599',1,'']]],
  ['son_20cadre_20pas_20à_20l_20estime_94',['L&apos;encart se lit par son cadre, pas à l&apos;estime',['../lot-37.html#autotoc_md533',1,'']]],
  ['son_20repli_20procédural_95',['Le pipeline de textures depuis fichiers, et son repli procédural',['../guide-rendu.html#autotoc_md213',1,'']]],
  ['sont_20fantômes_20—_20le_20lint_20le_20dit_20désormais_96',['9.1 Cinq familles d&apos;exigences sont fantômes — le lint le dit désormais',['../roadmap-010.html#autotoc_md652',1,'']]],
  ['sont_20livrés_20provisoires_20et_20le_20disent_97',['Les dons sont livrés provisoires, et le disent',['../lot-43.html#autotoc_md564',1,'']]],
  ['sont_20provisoires_20et_20le_20déclarent_98',['Les quatre classes sont provisoires, et le déclarent',['../lot-36.html#autotoc_md526',1,'']]],
  ['sortie_20du_20pixel_20art_99',['Pourquoi le facteur reste entier après la sortie du pixel art',['../guide-design-ihm.html#autotoc_md76',1,'']]],
  ['sortir_20de_20l_20identité_20pixel_20art_100',['LOT-66 — Charte visuelle : sortir de l&apos;identité pixel art',['../lot-66.html',1,'lots']]],
  ['sorts_101',['6. Sorts',['../spec-rpg.html#autotoc_md374',1,'']]],
  ['sorts_20et_20états_102',['&lt;span class=&quot;tt&quot;&gt;LOT-35&lt;/span&gt; — Sorts et états',['../roadmap-010.html#lot-35',1,'']]],
  ['sorts_20et_20capacités_20de_20classe_103',['LOT-25 — Sorts et capacités de classe',['../roadmap-010.html#lot-25',1,'']]],
  ['source_104',['Chemins complets depuis Source/',['../spec-conventions.html#autotoc_md281',1,'']]],
  ['source_20deux_20portées_20étanches_105',['Les jetons : une seule source, deux portées étanches',['../guide-design-ihm.html#autotoc_md63',1,'']]],
  ['source_20elements_20assets_20_3a_20convention_20et_20régénération_106',['&lt;span class=&quot;tt&quot;&gt;Source/Elements/Assets/&lt;/span&gt; : convention et régénération',['../guide-rendu.html#autotoc_md214',1,'']]],
  ['source_20est_20la_20moitié_20du_20travail_107',['Le choix de la source est la moitié du travail',['../lot-43.html#autotoc_md561',1,'']]],
  ['source_20fusionnée_20en_20lecture_20ex_20ctrl_20002_20lot_2020_108',['La manette : une seconde source, fusionnée en lecture (EX-CTRL-002, LOT-20)',['../guide-entrees.html#autotoc_md126',1,'']]],
  ['source_20nommées_20plutôt_20que_20contournées_109',['Trois irrégularités de la source, nommées plutôt que contournées',['../lot-37.html#autotoc_md536',1,'']]],
  ['source_20test_20unit_20hmi_20graphics_20test_5frender_5fbudget_20cpp_110',['Le test de non-régression du volume (&lt;span class=&quot;tt&quot;&gt;Source/Test/Unit/HMI/Graphics/test_render_budget.cpp&lt;/span&gt;)',['../guide-rendu.html#autotoc_md239',1,'']]],
  ['sous_20la_20valeur_20jamais_20dessus_111',['Un seuil de corps se pose sous la valeur, jamais dessus',['../lot-36.html#autotoc_md527',1,'']]],
  ['sous_20tables_20côte_20à_20côte_112',['La table du matériel est composée en deux sous-tables côte à côte',['../lot-34.html#autotoc_md514',1,'']]],
  ['souvent_20oublié_113',['Le critère qui est souvent oublié',['../roadmap-010.html#autotoc_md718',1,'']]],
  ['spécification_114',['LOT-77 — La moitié RPG de la spécification',['../lot-77.html',1,'lots']]],
  ['spécifications_115',['Spécifications',['../specifications.html',1,'index']]],
  ['sparse_20set_20core_3a_3acomponentpool_116',['Le stockage : sparse set (core::ComponentPool&amp;lt;T&amp;gt;)',['../guide-ecs.html#autotoc_md91',1,'']]],
  ['spirale_20de_20la_20mort_20»_117',['La « spirale de la mort »',['../guide-boucle.html#autotoc_md57',1,'']]],
  ['sprite_20à_20la_20fois_118',['Pourquoi « batcher » plutôt que dessiner un sprite à la fois',['../guide-rendu.html#autotoc_md208',1,'']]],
  ['spritequad_20_3a_20un_20rectangle_20texturé_119',['&lt;a class=&quot;el&quot; href=&quot;structhmi_1_1SpriteQuad.html&quot; title=&quot;hmi::SpriteQuad&quot;&gt;SpriteQuad&lt;/a&gt; : un rectangle texturé',['../guide-rendu.html#autotoc_md209',1,'']]],
  ['sprites_20_3a_20hmi_3a_3aspritebatch_20hmi_3a_3aspritebatch_120',['Le pipeline de dessin de sprites : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1SpriteBatch.html&quot; title=&quot;hmi::SpriteBatch&quot;&gt;hmi::SpriteBatch&lt;/a&gt;',['../guide-rendu.html#autotoc_md207',1,'']]],
  ['spritesheet_20chargé_20depuis_20un_20fichier_121',['&lt;a class=&quot;el&quot; href=&quot;classhmi_1_1TextureAtlas.html&quot; title=&quot;hmi::TextureAtlas&quot;&gt;hmi::TextureAtlas&lt;/a&gt; : un spritesheet, chargé depuis un fichier',['../guide-rendu.html#autotoc_md212',1,'']]],
  ['spritesheet_20externe_20et_20découplage_20image_20hitbox_122',['&lt;span class=&quot;tt&quot;&gt;LOT-48&lt;/span&gt; : spritesheet externe et découplage image/hitbox',['../guide-rendu.html#autotoc_md216',1,'']]],
  ['standard_123',['1. Langage &amp;amp; standard',['../spec-conventions.html#autotoc_md277',1,'']]],
  ['statistique_20est_20une_20liste_20jamais_20une_20chaîne_124',['Une statistique est une liste, jamais une chaîne',['../lot-37.html#autotoc_md534',1,'']]],
  ['statistique_20n_20est_20stockée_20ici_125',['Aucune statistique n&apos;est stockée ici',['../structcore_1_1Inventory.html#autotoc_md783',1,'']]],
  ['stats_20csv_126',['Le fichier &lt;span class=&quot;tt&quot;&gt;stats.csv&lt;/span&gt;',['../manuel-mode-ia.html#autotoc_md764',1,'']]],
  ['stockée_20ici_127',['Aucune statistique n&apos;est stockée ici',['../structcore_1_1Inventory.html#autotoc_md783',1,'']]],
  ['stockage_20_3a_20sparse_20set_20core_3a_3acomponentpool_128',['Le stockage : sparse set (core::ComponentPool&amp;lt;T&amp;gt;)',['../guide-ecs.html#autotoc_md91',1,'']]],
  ['stricte_20est_20dangereuse_129',['Comparaison flottante : pourquoi l&apos;égalité stricte est dangereuse',['../guide-maths.html#autotoc_md160',1,'']]],
  ['structurée_130',['Une barre d&apos;état structurée',['../guide-design-ihm.html#autotoc_md70',1,'']]],
  ['structure_20de_20champs_131',['Pourquoi une table de chaînes, et non une structure de champs',['../structhmi_1_1CharacterSheetContext.html#autotoc_md788',1,'']]],
  ['style_20ne_20sait_20pas_20faire_132',['Ce qu&apos;une feuille de style ne sait pas faire',['../guide-design-ihm.html#autotoc_md77',1,'']]],
  ['subi_133',['Le renversement est assumé, pas subi',['../lot-66.html#autotoc_md575',1,'']]],
  ['suit_20le_20joueur_134',['Choisir comment la caméra suit le joueur',['../manuel-partager-niveau.html#autotoc_md772',1,'']]],
  ['suite_135',['Où lire la suite',['../roadmap-010.html#autotoc_md638',1,'']]],
  ['suivent_20l_20outil_136',['Des panneaux groupés, et qui suivent l&apos;outil',['../guide-design-ihm.html#autotoc_md71',1,'']]],
  ['suivi_20de_20pente_20et_20d_20arrondi_20ex_20gp_20003_20ex_20gp_20004_137',['2. Suivi de pente et d&apos;arrondi (EX-GP-003, EX-GP-004)',['../guide-physique.html#autotoc_md188',1,'']]],
  ['suivi_20réglable_20ex_20lvl_20007_20ex_20ren_20017_138',['Mélanger plusieurs tailles de caméra : zones dessinées à la main et taille de suivi réglable (&lt;span class=&quot;tt&quot;&gt;EX-LVL-007&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;EX-REN-017&lt;/span&gt;)',['../guide-rendu.html#autotoc_md206',1,'']]],
  ['sujet_20du_20lot_139',['Pas de &lt;span class=&quot;tt&quot;&gt;.ui&lt;/span&gt;, et c&apos;est le sujet du lot',['../classhmi_1_1RpgScreenFrame.html#autotoc_md791',1,'']]],
  ['superposition_20portée_20par_20l_20écran_20et_20non_20par_20l_20appelant_140',['La règle de superposition, portée par l&apos;écran et non par l&apos;appelant',['../lot-68.html#autotoc_md589',1,'']]],
  ['suppression_20_3a_20swap_20and_20pop_141',['Ajout et suppression : &lt;em&gt;swap-and-pop&lt;/em&gt;',['../guide-ecs.html#autotoc_md92',1,'']]],
  ['suppressions_142',['Une déviation assumée sur la liste de suppressions',['../lot-66.html#autotoc_md573',1,'']]],
  ['supprimé_143',['Supprimé',['../lot-01.html#autotoc_md388',1,'']]],
  ['sur_20des_20expressions_20régulières_144',['L&apos;extraction se fait sur la typographie, pas sur des expressions régulières',['../lot-33.html#autotoc_md500',1,'']]],
  ['sur_20l_20état_20du_20dépôt_145',['9. Ce que l&apos;audit a révélé sur l&apos;état du dépôt',['../roadmap-010.html#autotoc_md651',1,'']]],
  ['sur_20l_20intention_146',['« Aucune valeur de règle dans le C++ » se vérifie sur le diff, pas sur l&apos;intention',['../lot-13.html#autotoc_md460',1,'']]],
  ['sur_20la_20liste_20de_20suppressions_147',['Une déviation assumée sur la liste de suppressions',['../lot-66.html#autotoc_md573',1,'']]],
  ['sur_20la_20typographie_20pas_20sur_20des_20expressions_20régulières_148',['L&apos;extraction se fait sur la typographie, pas sur des expressions régulières',['../lot-33.html#autotoc_md500',1,'']]],
  ['sur_20le_20diff_20pas_20sur_20l_20intention_149',['« Aucune valeur de règle dans le C++ » se vérifie sur le diff, pas sur l&apos;intention',['../lot-13.html#autotoc_md460',1,'']]],
  ['sur_20les_20six_20écrans_150',['Le titre devient son bandeau, sur les six écrans',['../lot-76.html#autotoc_md599',1,'']]],
  ['sur_20un_20tampon_20de_20pixels_151',['Les outils : des fonctions pures sur un tampon de pixels',['../guide-atelier-pixel-art.html#autotoc_md37',1,'']]],
  ['surface_20de_20dessin_20_3a_20le_20viewport_20qt_20hmi_3a_3agameviewport_152',['La surface de dessin : le viewport Qt (&lt;span class=&quot;tt&quot;&gt;hmi::GameViewport&lt;/span&gt;)',['../guide-rendu.html#autotoc_md202',1,'']]],
  ['surfaces_153',['Les commandes : une définition, trois surfaces',['../guide-design-ihm.html#autotoc_md66',1,'']]],
  ['surfaces_20et_20espaces_20de_20travail_20lot_2068_154',['Hiérarchie des surfaces, et espaces de travail (LOT-68)',['../guide-design-ihm.html#autotoc_md78',1,'']]],
  ['suspendre_20sans_20perdre_20un_20pas_155',['Pause : suspendre sans perdre un pas',['../guide-ecrans.html#autotoc_md84',1,'']]],
  ['swap_20and_20pop_156',['Ajout et suppression : &lt;em&gt;swap-and-pop&lt;/em&gt;',['../guide-ecs.html#autotoc_md92',1,'']]],
  ['swap_20chain_20back_20buffer_157',['Vocabulaire de base : GPU, swap chain, back buffer',['../guide-rendu.html#autotoc_md200',1,'']]],
  ['swept_20aabb_158',['1. Collision par balayage continu (swept AABB)',['../guide-physique.html#autotoc_md182',1,'']]],
  ['système_202_159',['Tests système (2)',['../cahiertest.html#autotoc_md33',1,'']]],
  ['système_20de_20design_160',['Pourquoi un système de design',['../guide-design-ihm.html#autotoc_md62',1,'']]],
  ['système_20de_20design_20et_20architecture_20de_20l_20information_161',['Système de design et architecture de l&apos;information',['../guide-design-ihm.html',1,'guide']]],
  ['système_20de_20design_20et_20habillage_20lot_20h_2056_162',['6. Système de design et habillage (LOT-H-56)',['../spec-interface-ihm.html#autotoc_md343',1,'']]],
  ['systèmes_163',['systèmes',['../spec-architecture.html#autotoc_md254',1,'8. Communication inter-systèmes'],['../guide-ecs.html',1,'ECS : entités, composants, systèmes']]],
  ['systèmes_20de_20coordonnées_20à_20ne_20pas_20confondre_164',['Deux systèmes de coordonnées à ne pas confondre',['../guide-niveaux.html#autotoc_md163',1,'']]],
  ['systèmes_20et_20l_20ordre_20d_20exécution_165',['Les systèmes et l&apos;ordre d&apos;exécution',['../guide-ecs.html#autotoc_md95',1,'']]]
];
