var searchData=
[
  ['pénombral_0',['&lt;span class=&quot;tt&quot;&gt;LOT-90&lt;/span&gt; — Le plan pénombral',['../roadmap.html#lot-90',1,'']]],
  ['pénombre_1',['Pénombre',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2penumbra_2preparation.html',1,'Pénombre'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2penumbra_2preparation.html#autotoc_md820',1,'Première série proposée — Pénombre']]],
  ['périmètre_2',['Périmètre',['../lot-01.html#autotoc_md300',1,'Périmètre'],['../lot-02.html#autotoc_md311',1,'Périmètre'],['../lot-03.html#autotoc_md317',1,'Périmètre'],['../lot-04.html#autotoc_md323',1,'Périmètre'],['../lot-05.html#autotoc_md330',1,'Périmètre'],['../lot-06.html#autotoc_md337',1,'Périmètre'],['../lot-07.html#autotoc_md344',1,'Périmètre'],['../lot-08.html#autotoc_md349',1,'Périmètre'],['../lot-09.html#autotoc_md361',1,'Périmètre'],['../lot-77.html#autotoc_md622',1,'Périmètre'],['../lot-78.html#autotoc_md626',1,'Périmètre'],['../roadmap.html#autotoc_md950',1,'Périmètre'],['../roadmap.html#autotoc_md956',1,'Périmètre'],['../roadmap.html#autotoc_md961',1,'Périmètre'],['../roadmap.html#autotoc_md966',1,'Périmètre'],['../roadmap.html#autotoc_md971',1,'Périmètre'],['../roadmap.html#autotoc_md981',1,'Périmètre'],['../roadmap.html#autotoc_md991',1,'Périmètre']]],
  ['périmètre_3',['Vision &amp;amp; périmètre',['../spec-vision.html',1,'specifications']]],
  ['périmètre_20et_20provenance_4',['Périmètre et provenance',['../md__2home_2runner_2work_2JustAnotherRpgGame_2JustAnotherRpgGame_2Tools_2AssetFactory_2bilan-poc.html#autotoc_md1153',1,'']]],
  ['périmètre_20vertical_20slice_5',['Hors périmètre (&lt;em&gt;vertical slice&lt;/em&gt;)',['../spec-vision.html#autotoc_md296',1,'']]],
  ['périmé_6',['Attention : le texte des maquettes était périmé',['../lot-86.html#autotoc_md638',1,'']]],
  ['périphériques_7',['1. Périphériques',['../spec-controles.html#autotoc_md197',1,'']]],
  ['pack_20de_20maquettes_8',['T5.1 — Le pack de maquettes',['../lot-87.html#autotoc_md689',1,'']]],
  ['page_20à_20l_20autre_9',['Sa gouttière bouge d&apos;une page à l&apos;autre',['../lot-36.html#autotoc_md529',1,'']]],
  ['page_20hors_20code_20pour_20le_20jeu_20en_20code_20pour_20l_20éditeur_10',['IHM Qt : la mise en page hors code pour le jeu, en code pour l&apos;éditeur',['../spec-conventions.html#autotoc_md209',1,'']]],
  ['pages_11',['Pages',['../manuel.html#autotoc_md1030',1,'']]],
  ['paie_12',['C&apos;est le lot où le §4 se paie',['../lot-34.html#autotoc_md516',1,'']]],
  ['palette_20est_20relevée_20pas_20choisie_13',['La palette est relevée, pas choisie',['../lot-66.html#autotoc_md588',1,'']]],
  ['palette_20et_20les_20outils_20_3a_20des_20panneaux_20qt_20séparés_20du_20canevas_14',['La palette et les outils : des panneaux Qt séparés du canevas',['../guide-editeur.html#autotoc_md88',1,'']]],
  ['palette_20relevée_15',['La palette relevée',['../lot-87.html#autotoc_md666',1,'']]],
  ['panneaux_20groupés_20et_20qui_20suivent_20l_20outil_16',['Des panneaux groupés, et qui suivent l&apos;outil',['../guide-design-ihm.html#autotoc_md63',1,'']]],
  ['panneaux_20qt_20séparés_20du_20canevas_17',['La palette et les outils : des panneaux Qt séparés du canevas',['../guide-editeur.html#autotoc_md88',1,'']]],
  ['panthéon_20et_20expressions_20matérielles_18',['Panthéon et expressions matérielles',['../md_Lot_2LOT-CREATION-ASSETS_2preparation-regionale.html#autotoc_md777',1,'']]],
  ['panthéon_20et_20organisations_19',['&lt;span class=&quot;tt&quot;&gt;LOT-80&lt;/span&gt; — Factions, panthéon et organisations',['../roadmap.html#lot-80',1,'']]],
  ['par_20case_20',['La règle, case par case',['../CollisionDerivation_8h.html#autotoc_md1080',1,'']]],
  ['par_20catégorie_21',['Les macros de journalisation, par catégorie',['../guide-journalisation.html#autotoc_md122',1,'']]],
  ['par_20construction_22',['par construction',['../lot-22.html#autotoc_md468',1,'La symétrie, par construction'],['../LineOfSight_8h.html#autotoc_md1072',1,'La symétrie, par construction']]],
  ['par_20critère_23',['Trois règles de désignation, une par critère',['../lot-10.html#autotoc_md368',1,'']]],
  ['par_20instantané_24',['Lecture seule, et par instantané',['../ArenaSceneComposer_8h.html#autotoc_md1107',1,'']]],
  ['par_20instantané_20comme_20l_20arène_25',['Par instantané, comme l&apos;arène',['../WorldSceneComposer_8h.html#autotoc_md1115',1,'']]],
  ['par_20l_20écran_20et_20non_20par_20l_20appelant_26',['La règle de superposition, portée par l&apos;écran et non par l&apos;appelant',['../lot-68.html#autotoc_md608',1,'']]],
  ['par_20l_20appelant_27',['La règle de superposition, portée par l&apos;écran et non par l&apos;appelant',['../lot-68.html#autotoc_md608',1,'']]],
  ['par_20l_20auteur_28',['Ce que la migration a trouvé, à trancher par l&apos;auteur',['../lot-editor-12.html#autotoc_md1023',1,'']]],
  ['par_20la_20donnée_29',['Deux natures de déclencheur, distinguées par la donnée',['../lot-18.html#autotoc_md425',1,'']]],
  ['par_20le_20pied_20lot_2007_30',['La profondeur : trier par le pied (&lt;span class=&quot;tt&quot;&gt;LOT-07&lt;/span&gt;)',['../guide-rendu.html#autotoc_md166',1,'']]],
  ['par_20lieu_31',['LOT-92 — Atelier des textures : le style de la scène par maquette, une planche par lieu',['../lot-92.html',1,'']]],
  ['par_20lot_32',['&lt;span class=&quot;tt&quot;&gt;LOT-51&lt;/span&gt; à &lt;span class=&quot;tt&quot;&gt;LOT-65&lt;/span&gt; — une classe par lot',['../roadmap.html#lot-51',1,'']]],
  ['par_20lot_20sans_20dupliquer_20la_20logique_20de_20peinture_20_3a_20core_3a_3aleveldraft_3a_3apaintregion_20leveldraft_3a_3apaintregion_33',['Peindre par lot sans dupliquer la logique de peinture : &lt;a class=&quot;el&quot; href=&quot;classcore_1_1LevelDraft.html#a7fb667e044067f5e9bf16f747d3f5f8e&quot; title=&quot;core::LevelDraft::paintRegion&quot;&gt;LevelDraft::paintRegion&lt;/a&gt;',['../guide-editeur.html#autotoc_md90',1,'']]],
  ['par_20maquette_20une_20planche_20par_20lieu_34',['LOT-92 — Atelier des textures : le style de la scène par maquette, une planche par lieu',['../lot-92.html',1,'']]],
  ['par_20qstr_35',['Pourquoi ceux-là ne passent pas par &lt;span class=&quot;tt&quot;&gt;qsTr&lt;/span&gt;',['../namespacehmi.html#autotoc_md1140',1,'']]],
  ['par_20rapport_20au_20texte_20de_20la_20feuille_20de_20route_36',['Écarts par rapport au texte de la feuille de route',['../lot-88.html#autotoc_md701',1,'']]],
  ['par_20son_20cadre_20pas_20à_20l_20estime_37',['L&apos;encart se lit par son cadre, pas à l&apos;estime',['../lot-37.html#autotoc_md540',1,'']]],
  ['par_20son_20pied_38',['Un relief haut se désigne par son pied',['../CanvasPicking_8h.html#autotoc_md1094',1,'']]],
  ['par_20tour_39',['LOT-20 — Initiative et tour par tour',['../lot-20.html',1,'lots']]],
  ['par_20une_40',['Quatre corruptions d&apos;OCR déclarées, une par une',['../lot-36.html#autotoc_md528',1,'']]],
  ['par_20une_20règle_20écrite_41',['L&apos;initiative : jetée une fois, départagée par une règle écrite',['../lot-20.html#autotoc_md446',1,'']]],
  ['par_20vision_20contre_20une_20liste_20fermée_42',['7. La revue par vision, contre une liste fermée',['../lot-91-poc.html#autotoc_md723',1,'']]],
  ['par_20y_43',['LOT-07 — Rendu top-down et tri par Y',['../lot-07.html',1,'lots']]],
  ['parchemin_20pixel_44',['Pourquoi les maquettes remplacent la charte parchemin pixel',['../lot-87.html#autotoc_md653',1,'']]],
  ['parcourent_20_3a_20le_20graphe_20des_20quartiers_45',['LOT-96 — Martpart et Arenarea se parcourent : le graphe des quartiers',['../lot-96.html',1,'lots']]],
  ['parcourir_20le_20monde_46',['Parcourir le monde',['../manuel-jouer.html#autotoc_md1026',1,'']]],
  ['parcours_20en_20largeur_47',['La règle du Manuel, et pourquoi elle n&apos;est pas un parcours en largeur',['../classcore_1_1ReachableArea.html#autotoc_md1074',1,'']]],
  ['parcourt_20_3a_20exploration_20dans_20le_20jeu_20et_20première_20carte_48',['LOT-09 — Le Colisée se parcourt : exploration dans le jeu et première carte',['../lot-09.html',1,'lots']]],
  ['part_49',['part',['../classhmi_1_1ArenaViewportItem.html#autotoc_md1121',1,'Pourquoi un item à part'],['../ExplorationSession_8h.html#autotoc_md1091',1,'Pourquoi une session à part']]],
  ['partagent_20jamais_20une_20case_50',['Deux créatures ne partagent jamais une case',['../lot-19.html#autotoc_md435',1,'']]],
  ['partager_20une_20carte_20sans_20ligne_20de_20commande_51',['Créer et partager une carte (sans ligne de commande)',['../manuel-partager-niveau.html',1,'manuel']]],
  ['partie_20»_20_3a_20un_20échafaudage_20et_20il_20est_20écrit_52',['« Nouvelle partie » : un échafaudage, et il est écrit',['../lot-68.html#autotoc_md609',1,'']]],
  ['partie_20dans_20la_20capitale_20_3a_20sauvegarde_20riche_53',['LOT-17 — Reprendre sa partie dans la Capitale : sauvegarde riche',['../roadmap.html#lot-17',1,'']]],
  ['partout_54',['Le vocabulaire : « niveau » devient « carte », partout',['../lot-67.html#autotoc_md602',1,'']]],
  ['pas_55',['pas',['../classcore_1_1BattleGrid.html#autotoc_md1055',1,'Ce qu&apos;elle ne fait pas'],['../classhmi_1_1CharacterSheetModel.html#autotoc_md1126',1,'Ce qu&apos;elle ne refait pas'],['../namespacecore.html#autotoc_md1077',1,'Ce qu&apos;elle ne vérifie pas'],['../classhmi_1_1ArenaModel.html#autotoc_md1119',1,'Ce qu&apos;elle tient, et ce qu&apos;elle ne décide pas'],['../classhmi_1_1WorldModel.html#autotoc_md1143',1,'Ce qu&apos;elle tient, et ce qu&apos;elle ne décide pas'],['../classhmi_1_1GamepadNavigator.html#autotoc_md1131',1,'Ce qu&apos;il fait, et ce qu&apos;il ne fait pas'],['../classhmi_1_1ScreenRouter.html#autotoc_md1141',1,'Ce qu&apos;il n&apos;est pas'],['../structcore_1_1ExplorationSnapshot.html#autotoc_md1062',1,'Ce qu&apos;il porte, et ce qu&apos;il ne porte pas'],['../EnemyAi_8h.html#autotoc_md1065',1,'Ce que ce fichier décide, et que le Guide ne dit pas'],['../lot-15.html#autotoc_md408',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas'],['../lot-18.html#autotoc_md420',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas'],['../lot-19.html#autotoc_md431',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas'],['../lot-20.html#autotoc_md444',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas'],['../lot-21.html#autotoc_md457',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas'],['../lot-22.html#autotoc_md466',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas'],['../lot-23.html#autotoc_md476',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas'],['../lot-50.html#autotoc_md575',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas'],['../lot-87.html#autotoc_md654',1,'Ce que Claude ne produit pas'],['../lot-50.html#autotoc_md580',1,'Ce que l&apos;écran compose, et ce qu&apos;il ne compose pas'],['../Arena_8h.html#autotoc_md1047',1,'Ce que l&apos;arène est, et ce qu&apos;elle n&apos;est pas'],['../lot-18.html#autotoc_md422',1,'Ce que l&apos;instantané porte, et ce qu&apos;il ne porte pas'],['../lot-14.html#autotoc_md403',1,'Ce que le lot n&apos;invente pas'],['../lot-10.html#autotoc_md370',1,'Ce que le lot ne fait pas'],['../lot-12.html#autotoc_md389',1,'Ce que le lot ne fait pas'],['../lot-13.html#autotoc_md398',1,'Ce que le lot ne fait pas'],['../lot-14.html#autotoc_md405',1,'Ce que le lot ne fait pas'],['../lot-30.html#autotoc_md496',1,'Ce que le lot ne fait pas'],['../lot-32.html#autotoc_md503',1,'Ce que le lot ne fait pas'],['../lot-33.html#autotoc_md512',1,'Ce que le lot ne fait pas'],['../lot-34.html#autotoc_md522',1,'Ce que le lot ne fait pas'],['../lot-36.html#autotoc_md535',1,'Ce que le lot ne fait pas'],['../lot-38.html#autotoc_md556',1,'Ce que le lot ne fait pas'],['../lot-39.html#autotoc_md564',1,'Ce que le lot ne fait pas'],['../lot-43.html#autotoc_md572',1,'Ce que le lot ne fait pas'],['../lot-66.html#autotoc_md595',1,'Ce que le lot ne fait pas'],['../lot-67.html#autotoc_md603',1,'Ce que le lot ne fait pas'],['../lot-68.html#autotoc_md611',1,'Ce que le lot ne fait pas'],['../lot-76.html#autotoc_md619',1,'Ce que le lot ne fait pas'],['../ArenaSceneComposer_8h.html#autotoc_md1106',1,'Ce qui n&apos;y est pas'],['../lot-12.html#autotoc_md385',1,'Deux arrondis qui ne se voient pas'],['../guide-ecs.html#autotoc_md80',1,'Exemple pas à pas'],['../guide-conception-qds.html#autotoc_md56',1,'Les ornements se tracent, ils ne se collent pas'],['../CombatPreview_8h.html#autotoc_md1056',1,'Une prévisualisation qui ne ment pas']]],
  ['pas_20«_20une_20seule_20hmilib_20»_56',['Le découpage retenu — et pourquoi il n&apos;est pas « une seule &lt;span class=&quot;tt&quot;&gt;HmiLib&lt;/span&gt; »',['../lot-02.html#autotoc_md310',1,'']]],
  ['pas_20à_20l_20estime_57',['L&apos;encart se lit par son cadre, pas à l&apos;estime',['../lot-37.html#autotoc_md540',1,'']]],
  ['pas_20à_20pas_58',['Exemple pas à pas',['../guide-ecs.html#autotoc_md80',1,'']]],
  ['pas_20écrit_20de_20classdefinition_20_3a_20elle_20existait_20déjà_59',['Le lot n&apos;a pas écrit de &lt;span class=&quot;tt&quot;&gt;ClassDefinition&lt;/span&gt; : elle existait déjà',['../lot-13.html#autotoc_md393',1,'']]],
  ['pas_20ce_20qui_20bloque_60',['Couches : ce qu&apos;on voit n&apos;est pas ce qui bloque',['../guide-niveaux.html#autotoc_md142',1,'']]],
  ['pas_20choisie_61',['La palette est relevée, pas choisie',['../lot-66.html#autotoc_md588',1,'']]],
  ['pas_20confondre_62',['Deux systèmes de coordonnées à ne pas confondre',['../guide-niveaux.html#autotoc_md138',1,'']]],
  ['pas_20dans_20sa_20rangée_63',['Le groupe d&apos;une arme n&apos;est pas dans sa rangée',['../lot-34.html#autotoc_md517',1,'']]],
  ['pas_20de_20l_20algorithme_64',['Le départage est une règle, et elle ne dépend pas de l&apos;algorithme',['../lot-19.html#autotoc_md433',1,'']]],
  ['pas_20de_20la_20prose_65',['La donnée : des propriétés, pas de la prose',['../lot-22.html#autotoc_md471',1,'']]],
  ['pas_20de_20simulation_20et_20les_20entrées_66',['Les frames sans pas de simulation et les entrées',['../guide-boucle.html#autotoc_md43',1,'']]],
  ['pas_20de_20temps_20fixe_67',['pas de temps fixe',['../guide-boucle.html',1,'Boucle de jeu et pas de temps fixe'],['../guide-boucle.html#autotoc_md38',1,'Le principe du pas de temps fixe']]],
  ['pas_20dire_68',['Ce que le schéma ne peut pas dire',['../lot-36.html#autotoc_md532',1,'']]],
  ['pas_20dire_20et_20qui_20n_20est_20pas_20perdu_20pour_20autant_69',['Ce que le schéma ne peut pas dire, et qui n&apos;est pas perdu pour autant',['../lot-33.html#autotoc_md509',1,'']]],
  ['pas_20directement_20dans_20l_20item_20qt_20quick_70',['Pourquoi pas directement dans l&apos;item Qt Quick',['../classhmi_1_1ArenaSceneRenderer.html#autotoc_md1108',1,'']]],
  ['pas_20dix_71',['Treize régions, pas dix',['../lot-37.html#autotoc_md539',1,'']]],
  ['pas_20encore_72',['Ce qu&apos;il ne fait pas encore',['../classhmi_1_1GameViewportItem.html#autotoc_md1134',1,'']]],
  ['pas_20encore_20alimentés_73',['Les écrans dessinés mais pas encore alimentés',['../guide-conception-qds.html#autotoc_md52',1,'']]],
  ['pas_20et_20pourquoi_74',['Ce que le lot ne fait pas, et pourquoi',['../lot-37.html#autotoc_md544',1,'']]],
  ['pas_20faire_20seule_75',['Ce que la conception ne peut pas faire seule',['../spec-interface-ihm.html#autotoc_md260',1,'']]],
  ['pas_20la_20fiche_20il_20la_20désigne_76',['Le composant ECS ne porte pas la fiche, il la désigne',['../lot-13.html#autotoc_md396',1,'']]],
  ['pas_20la_20génération_77',['Le test lit le livre, pas la génération',['../lot-33.html#autotoc_md511',1,'']]],
  ['pas_20la_20matière_78',['Ce que le corpus donne encore : la mesure, pas la matière',['../lot-76.html#autotoc_md615',1,'']]],
  ['pas_20liste_20de_20production_79',['pas liste de production',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2darkall_2preparation.html#autotoc_md788',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2magocracy-of-mage-tower_2preparation.html#autotoc_md806',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2mystical-wasteland_2preparation.html#autotoc_md813',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2penumbra_2preparation.html#autotoc_md819',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2seashores_2preparation.html#autotoc_md831',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2sindile-forest_2preparation.html#autotoc_md837',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2storm-islands_2preparation.html#autotoc_md843',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2stravian-domains_2preparation.html#autotoc_md849',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2taii-maku-city-states_2preparation.html#autotoc_md855',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2theocracy-of-kepesh_2preparation.html#autotoc_md861',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2tsvetan_2preparation.html#autotoc_md867',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2undertanares_2preparation.html#autotoc_md874',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2yama_2preparation.html#autotoc_md880',1,'PNJ — localisateurs, pas liste de production']]],
  ['pas_20livré_80',['Ce que le lot a livré, et ce qu&apos;il n&apos;a pas livré',['../lot-09.html#autotoc_md358',1,'']]],
  ['pas_20par_20qstr_81',['Pourquoi ceux-là ne passent pas par &lt;span class=&quot;tt&quot;&gt;qsTr&lt;/span&gt;',['../namespacehmi.html#autotoc_md1140',1,'']]],
  ['pas_20perdu_20pour_20autant_82',['Ce que le schéma ne peut pas dire, et qui n&apos;est pas perdu pour autant',['../lot-33.html#autotoc_md509',1,'']]],
  ['pas_20plus_20tard_83',['Pourquoi maintenant, et pas plus tard',['../lot-04.html#autotoc_md322',1,'']]],
  ['pas_20produire_84',['Ce que le cahier ne fait pas produire',['../lot-87-cahier-assets.html#lot-87-cahier-exclusions',1,'']]],
  ['pas_20réécrire_85',['Ce qui existe déjà, et qu&apos;il ne faut pas réécrire',['../lot-06.html#autotoc_md336',1,'']]],
  ['pas_20rater_86',['Le point à ne pas rater',['../lot-04.html#autotoc_md324',1,'']]],
  ['pas_20s_20arrêter_87',['Traverser n&apos;est pas s&apos;arrêter',['../lot-19.html#autotoc_md436',1,'']]],
  ['pas_20saisi_88',['Le complément des &lt;em&gt;Basic Rules&lt;/em&gt; est attesté, pas saisi',['../lot-30.html#autotoc_md494',1,'']]],
  ['pas_20se_20cacher_89',['Ce qui change vraiment, et qu&apos;il ne faut pas se cacher',['../classhmi_1_1GameViewportItem.html#autotoc_md1133',1,'']]],
  ['pas_20seulement_20l_20état_90',['Détecter les fronts, pas seulement l&apos;état',['../guide-entrees.html#autotoc_md101',1,'']]],
  ['pas_20subi_91',['Le renversement est assumé, pas subi',['../lot-66.html#autotoc_md594',1,'']]],
  ['pas_20sur_20des_20expressions_20régulières_92',['L&apos;extraction se fait sur la typographie, pas sur des expressions régulières',['../lot-33.html#autotoc_md507',1,'']]],
  ['pas_20sur_20l_20intention_93',['« Aucune valeur de règle dans le C++ » se vérifie sur le diff, pas sur l&apos;intention',['../lot-13.html#autotoc_md394',1,'']]],
  ['pas_20tenu_94',['Ce que la feuille de route supposait, et qui n&apos;a pas tenu',['../lot-19.html#autotoc_md432',1,'']]],
  ['pas_20un_20booléen_95',['Un ennemi vaincu est un drapeau de monde, pas un booléen',['../lot-18.html#autotoc_md423',1,'']]],
  ['pas_20un_20changement_20de_20cible_96',['QRhi : une couche d&apos;accès au GPU, pas un changement de cible',['../guide-rendu.html#autotoc_md150',1,'']]],
  ['pas_20un_20hasard_97',['Le départage est une règle, pas un hasard',['../classcore_1_1ReachableArea.html#autotoc_md1075',1,'']]],
  ['pas_20un_20indice_98',['pas un indice',['../lot-20.html#autotoc_md447',1,'Le tour : une place, pas un indice'],['../classcore_1_1TurnOrder.html#autotoc_md1079',1,'Une place, pas un indice']]],
  ['pas_20un_20journal_20c_20est_20une_20exigence_99',['La restitution n&apos;est pas un journal, c&apos;est une exigence',['../lot-12.html#autotoc_md387',1,'']]],
  ['pas_20un_20oubli_100',['L&apos;accentué reste tracé à l&apos;ancienne, et ce n&apos;est pas un oubli',['../lot-76.html#autotoc_md617',1,'']]],
  ['pas_20un_20parcours_20en_20largeur_101',['La règle du Manuel, et pourquoi elle n&apos;est pas un parcours en largeur',['../classcore_1_1ReachableArea.html#autotoc_md1074',1,'']]],
  ['pas_20un_20produit_102',['L&apos;éditeur : un outil, pas un produit',['../guide-design-ihm.html#autotoc_md60',1,'']]],
  ['pas_20un_20total_20de_2020_103',['Un 20 naturel n&apos;est pas un total de 20',['../lot-12.html#autotoc_md386',1,'']]],
  ['pas_20une_20refonte_104',['Pourquoi ce lot est un lot d&apos;&lt;b&gt;ajout&lt;/b&gt;, pas une refonte',['../roadmap.html#autotoc_md990',1,'']]],
  ['pas_20une_20soustraction_105',['pas une soustraction',['../Damage_8h.html#autotoc_md1063',1,'Pourquoi un pipeline, et pas une soustraction'],['../lot-21.html#autotoc_md460',1,'Un pipeline, pas une soustraction']]],
  ['pas_20versionné_106',['1. Le corpus n&apos;est pas versionné',['../roadmap.html#autotoc_md904',1,'']]],
  ['pas_20vu_107',['Le défaut que les tests ont trouvé, et que la relecture n&apos;aurait pas vu',['../lot-12.html#autotoc_md384',1,'']]],
  ['passé_20le_2012_20septembre_202026_108',['T1.5 — Le test de l&apos;artiste, passé le 12 septembre 2026',['../lot-87.html#autotoc_md659',1,'']]],
  ['passe_20la_20frontière_109',['Où passe la frontière',['../classhmi_1_1CharacterSheetModel.html#autotoc_md1125',1,'']]],
  ['passent_20pas_20par_20qstr_110',['Pourquoi ceux-là ne passent pas par &lt;span class=&quot;tt&quot;&gt;qsTr&lt;/span&gt;',['../namespacehmi.html#autotoc_md1140',1,'']]],
  ['patch_111',['Cadres 9-patch',['../lot-87-cahier-assets.html#lot-87-cahier-frame',1,'']]],
  ['pause_112',['Pause',['../guide-ecrans.html#autotoc_md71',1,'Pause'],['../manuel-jouer.html#autotoc_md1028',1,'Pause']]],
  ['pause_20dialogue_20marchand_20journal_20_3a_20restylés_113',['T3.9 — Pause, dialogue, marchand, journal : restylés',['../lot-87.html#autotoc_md684',1,'']]],
  ['peindre_20avec_20les_20pièces_20du_20lieu_114',['LOT-EDITOR-03 — Peindre avec les pièces du lieu',['../roadmap-editeur.html#lot-editor-03',1,'']]],
  ['peindre_20c_20est_20convertir_20un_20pixel_20en_20case_115',['Peindre, c&apos;est convertir un pixel en case',['../guide-editeur.html#autotoc_md87',1,'']]],
  ['peindre_20par_20lot_20sans_20dupliquer_20la_20logique_20de_20peinture_20_3a_20core_3a_3aleveldraft_3a_3apaintregion_20leveldraft_3a_3apaintregion_116',['Peindre par lot sans dupliquer la logique de peinture : &lt;a class=&quot;el&quot; href=&quot;classcore_1_1LevelDraft.html#a7fb667e044067f5e9bf16f747d3f5f8e&quot; title=&quot;core::LevelDraft::paintRegion&quot;&gt;LevelDraft::paintRegion&lt;/a&gt;',['../guide-editeur.html#autotoc_md90',1,'']]],
  ['peintre_117',['peintre',['../classhmi_1_1ArenaViewportItem.html#autotoc_md1123',1,'Ce que fait le peintre'],['../roadmap-editeur.html#lot-editor-04',1,'LOT-EDITOR-04 — Les outils du peintre']]],
  ['peinture_20_3a_20core_3a_3aleveldraft_3a_3apaintregion_20leveldraft_3a_3apaintregion_118',['Peindre par lot sans dupliquer la logique de peinture : &lt;a class=&quot;el&quot; href=&quot;classcore_1_1LevelDraft.html#a7fb667e044067f5e9bf16f747d3f5f8e&quot; title=&quot;core::LevelDraft::paintRegion&quot;&gt;LevelDraft::paintRegion&lt;/a&gt;',['../guide-editeur.html#autotoc_md90',1,'']]],
  ['perdent_20leur_20porteur_119',['Exigences qui perdent leur porteur',['../lot-88.html#autotoc_md702',1,'']]],
  ['perdu_20de_20vue_120',['Le focus n&apos;est jamais perdu de vue',['../lot-66.html#autotoc_md593',1,'']]],
  ['perdu_20pour_20autant_121',['Ce que le schéma ne peut pas dire, et qui n&apos;est pas perdu pour autant',['../lot-33.html#autotoc_md509',1,'']]],
  ['performance_122',['1. Performance',['../spec-exigences.html#autotoc_md233',1,'']]],
  ['performance_20à_20respecter_123',['Une règle de performance à respecter',['../guide-journalisation.html#autotoc_md124',1,'']]],
  ['personnage_124',['personnage',['../spec-rpg.html#autotoc_md287',1,'5. Options de personnage'],['../lot-13.html',1,'LOT-13 — Fiche de personnage']]],
  ['personnage_20_3a_20dons_20multiclassage_20compétences_20langues_125',['LOT-43 — Options de personnage : dons, multiclassage, compétences, langues',['../lot-43.html',1,'lots']]],
  ['personnage_20_3a_20maquette_20et_20interface_126',['LOT-38 — Fiche de personnage : maquette et interface',['../lot-38.html',1,'lots']]],
  ['personnage_20affiché_20_3a_20une_20donnée_20et_20un_20échafaudage_20assumé_127',['Le personnage affiché : une donnée, et un échafaudage assumé',['../lot-38.html#autotoc_md554',1,'']]],
  ['personnage_20de_20démonstration_128',['Le personnage de démonstration',['../lot-18.html#autotoc_md428',1,'']]],
  ['personnage_20et_20progression_129',['Personnage et progression',['../spec-rpg.html',1,'specifications']]],
  ['personnage_20maquette_2003_130',['T3.4 — La fiche de personnage (maquette 03)',['../lot-87.html#autotoc_md679',1,'']]],
  ['personnages_131',['LOT-29 — Groupe de quatre personnages',['../roadmap.html#lot-29',1,'']]],
  ['personne_20n_20y_20meurt_20et_20c_20est_20la_20fiction_20qui_20l_20explique_132',['Personne n&apos;y meurt, et c&apos;est la fiction qui l&apos;explique',['../lot-50.html#autotoc_md578',1,'']]],
  ['perte_20de_20travail_133',['Garde-fous contre la perte de travail',['../guide-editeur.html#autotoc_md94',1,'']]],
  ['peuplement_20_3a_20rencontres_20et_20créatures_134',['&lt;span class=&quot;tt&quot;&gt;LOT-41&lt;/span&gt; — Peuplement : rencontres et créatures',['../roadmap.html#lot-41',1,'']]],
  ['peuplement_20civil_20_3a_20pnj_20marchands_20et_20quêtes_135',['&lt;span class=&quot;tt&quot;&gt;LOT-82&lt;/span&gt; — Peuplement civil : PNJ, marchands et quêtes',['../roadmap.html#lot-82',1,'']]],
  ['peut_20défaire_136',['&lt;a class=&quot;el&quot; href=&quot;classcore_1_1LevelDraft.html&quot; title=&quot;core::LevelDraft&quot;&gt;core::LevelDraft&lt;/a&gt; : une carte qu&apos;on peut défaire',['../guide-editeur.html#autotoc_md85',1,'']]],
  ['peut_20on_20se_20tenir_20ici_20»_137',['peut on se tenir ici »',['../lot-19.html#autotoc_md439',1,'Une seule source de vérité pour « peut-on se tenir ici »'],['../classcore_1_1BattleGrid.html#autotoc_md1053',1,'Une seule source de vérité pour « peut-on se tenir ici »']]],
  ['peut_20pas_20dire_138',['Ce que le schéma ne peut pas dire',['../lot-36.html#autotoc_md532',1,'']]],
  ['peut_20pas_20dire_20et_20qui_20n_20est_20pas_20perdu_20pour_20autant_139',['Ce que le schéma ne peut pas dire, et qui n&apos;est pas perdu pour autant',['../lot-33.html#autotoc_md509',1,'']]],
  ['peut_20pas_20faire_20seule_140',['Ce que la conception ne peut pas faire seule',['../spec-interface-ihm.html#autotoc_md260',1,'']]],
  ['phase_200_141',['Critères d&apos;acceptation de la phase 0',['../lot-87.html#autotoc_md693',1,'']]],
  ['phase_201_142',['Où en est la phase 1',['../lot-87.html#autotoc_md660',1,'']]],
  ['phase_201_20—_20le_20module_20de_20conception_143',['Phase 1 — le module de conception',['../lot-87.html#autotoc_md656',1,'']]],
  ['phase_202_20—_20charte_20v2_20et_20matière_20première_144',['Phase 2 — charte v2 et matière première',['../lot-87.html#autotoc_md661',1,'']]],
  ['phase_202_20—_20vérifié_20le_2013_20septembre_202026_145',['Où en est la phase 2 — vérifié le 13 septembre 2026',['../lot-87.html#autotoc_md674',1,'']]],
  ['phase_203_146',['Où en est la phase 3',['../lot-87.html#autotoc_md685',1,'']]],
  ['phase_203_20—_20les_20écrans_147',['Phase 3 — les écrans',['../lot-87.html#autotoc_md675',1,'']]],
  ['phase_204_20—_20le_20cadre_20du_20hud_148',['Phase 4 — le cadre du HUD',['../lot-87.html#autotoc_md686',1,'']]],
  ['phase_205_20—_20retirer_20ce_20qui_20ne_20sert_20plus_149',['Phase 5 — retirer ce qui ne sert plus',['../lot-87.html#autotoc_md688',1,'']]],
  ['phases_150',['phases',['../lot-96.html#autotoc_md763',1,'Les phases'],['../lot-09.html#autotoc_md357',1,'Les six phases'],['../lot-87.html#autotoc_md655',1,'Programme, en six phases']]],
  ['phrase_151',['En une phrase',['../guide-conception-qds.html#autotoc_md46',1,'']]],
  ['pièce_20format_20v4_20lot_20editor_2012_20ex_20lvl_20019_152',['Une case = un type et une pièce (format v4, &lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-12&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;EX-LVL-019&lt;/span&gt;)',['../structcore_1_1TileLayer.html#autotoc_md1083',1,'']]],
  ['pièces_20du_20lieu_153',['LOT-EDITOR-03 — Peindre avec les pièces du lieu',['../roadmap-editeur.html#lot-editor-03',1,'']]],
  ['piège_20classique_154',['Le piège classique',['../lot-06.html#autotoc_md338',1,'']]],
  ['piège_20du_20framerate_20variable_155',['Le piège du framerate variable',['../guide-boucle.html#autotoc_md37',1,'']]],
  ['piège_20du_20lot_20_3a_20un_20coffre_20ouvert_20deux_20fois_156',['Le piège du lot : un coffre ouvert deux fois',['../lot-10.html#autotoc_md366',1,'']]],
  ['piège_20du_20tirage_157',['Le piège du tirage',['../roadmap.html#autotoc_md967',1,'']]],
  ['piège_20et_20la_20façon_20dont_20il_20est_20écarté_158',['Le piège, et la façon dont il est écarté',['../lot-14.html#autotoc_md401',1,'']]],
  ['picturaux_20ex_20dec_159',['Décors et plans picturaux (&lt;span class=&quot;tt&quot;&gt;EX-DEC-*&lt;/span&gt;)',['../spec-retirees.html#autotoc_md241',1,'']]],
  ['pied_160',['Un relief haut se désigne par son pied',['../CanvasPicking_8h.html#autotoc_md1094',1,'']]],
  ['pied_20lot_2007_161',['La profondeur : trier par le pied (&lt;span class=&quot;tt&quot;&gt;LOT-07&lt;/span&gt;)',['../guide-rendu.html#autotoc_md166',1,'']]],
  ['pile_20d_20écrans_162',['Le routeur et la pile d&apos;écrans',['../guide-ecrans.html#autotoc_md69',1,'']]],
  ['pilotage_163',['Le pilotage',['../ArenaAnimationDriver_8h.html#autotoc_md1102',1,'']]],
  ['pilote_164',['pilote',['../lot-91-poc.html#autotoc_md717',1,'1. Les cinq PNJ du pilote'],['../md__2home_2runner_2work_2JustAnotherRpgGame_2JustAnotherRpgGame_2Tools_2AssetFactory_2CREDITS.html',1,'Provenance des candidats du pilote']]],
  ['pilote_20pnj_165',['Fabrique d’assets — pilote PNJ',['../dir_52c08823cef41a3df195c0648e30f2b3.html#autotoc_md1144',1,'']]],
  ['pipeline_20de_20dessin_20de_20sprites_20_3a_20hmi_3a_3aspritebatch_20hmi_3a_3aspritebatch_166',['Le pipeline de dessin de sprites : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1SpriteBatch.html&quot; title=&quot;hmi::SpriteBatch&quot;&gt;hmi::SpriteBatch&lt;/a&gt;',['../guide-rendu.html#autotoc_md154',1,'']]],
  ['pipeline_20et_20pas_20une_20soustraction_167',['Pourquoi un pipeline, et pas une soustraction',['../Damage_8h.html#autotoc_md1063',1,'']]],
  ['pipeline_20pas_20une_20soustraction_168',['Un pipeline, pas une soustraction',['../lot-21.html#autotoc_md460',1,'']]],
  ['piste_20du_20repaire_169',['CE-01 — Martpart, Myr et la piste du repaire',['../md_Lot_2LOT-CREATION-ASSETS_2tache-ce-01-martpart-myr.html',1,'']]],
  ['piste_20ouverte_20puis_20refermée_170',['La planche gravée : une piste ouverte, puis refermée',['../lot-38.html#autotoc_md549',1,'']]],
  ['pistes_20écartées_171',['8. Risques et pistes écartées',['../roadmap-editeur.html#roadmap-editeur-risques',1,'']]],
  ['pixel_172',['Pourquoi les maquettes remplacent la charte parchemin pixel',['../lot-87.html#autotoc_md653',1,'']]],
  ['pixel_20art_173',['pixel art',['../lot-66.html',1,'LOT-66 — Charte visuelle : sortir de l&apos;identité pixel art'],['../guide-design-ihm.html#autotoc_md66',1,'Pourquoi le facteur reste entier après la sortie du pixel art'],['../lot-92.html#autotoc_md733',1,'Risque : l&apos;angle 0,62 en pixel art']]],
  ['pixel_20en_20case_174',['Peindre, c&apos;est convertir un pixel en case',['../guide-editeur.html#autotoc_md87',1,'']]],
  ['pixels_20_3a_20hmi_3a_3acamera2d_20hmi_3a_3acamera2d_175',['Unités monde et pixels : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1Camera2D.html&quot; title=&quot;hmi::Camera2D&quot;&gt;hmi::Camera2D&lt;/a&gt;',['../guide-rendu.html#autotoc_md152',1,'']]],
  ['place_176',['Ce que l&apos;agonie trouvera en place',['../lot-21.html#autotoc_md461',1,'']]],
  ['place_20pas_20un_20indice_177',['place pas un indice',['../lot-20.html#autotoc_md447',1,'Le tour : une place, pas un indice'],['../classcore_1_1TurnOrder.html#autotoc_md1079',1,'Une place, pas un indice']]],
  ['placement_20d_20entités_178',['LOT-11 — Éditeur multi-couches et placement d&apos;entités',['../lot-11.html',1,'']]],
  ['plan_179',['Les cartes — quatre, tracées depuis le plan',['../roadmap.html#autotoc_md972',1,'']]],
  ['plan_20d_20intégration_20_3a_20la_20capitale_20lot_20après_20lot_180',['Le plan d&apos;intégration : la Capitale, lot après lot',['../roadmap.html#roadmap-capitale',1,'']]],
  ['plan_20du_20guide_181',['Plan du guide',['../guide.html#autotoc_md173',1,'']]],
  ['plan_20pénombral_182',['&lt;span class=&quot;tt&quot;&gt;LOT-90&lt;/span&gt; — Le plan pénombral',['../roadmap.html#lot-90',1,'']]],
  ['planche_20chacun_183',['Les textures — trois jeux, une planche chacun',['../roadmap.html#autotoc_md974',1,'']]],
  ['planche_20gravée_20_3a_20une_20piste_20ouverte_20puis_20refermée_184',['La planche gravée : une piste ouverte, puis refermée',['../lot-38.html#autotoc_md549',1,'']]],
  ['planche_20par_20lieu_185',['LOT-92 — Atelier des textures : le style de la scène par maquette, une planche par lieu',['../lot-92.html',1,'']]],
  ['planche_20retenue_186',['9. La découpe d&apos;une planche retenue',['../lot-91-poc.html#autotoc_md725',1,'']]],
  ['planches_20à_20la_20main_187',['LOT-91 — Preuve de concept : cinq planches à la main',['../lot-91-poc.html',1,'lot-91']]],
  ['planches_20et_20ce_20qu_20on_20relève_20dessus_188',['La maquette : cinq planches, et ce qu&apos;on relève dessus',['../lot-38.html#autotoc_md547',1,'']]],
  ['plans_20picturaux_20ex_20dec_189',['Décors et plans picturaux (&lt;span class=&quot;tt&quot;&gt;EX-DEC-*&lt;/span&gt;)',['../spec-retirees.html#autotoc_md241',1,'']]],
  ['plaques_20et_20bandeaux_190',['Plaques et bandeaux',['../lot-87-cahier-assets.html#lot-87-cahier-plate',1,'']]],
  ['plates_191',['&lt;a class=&quot;el&quot; href=&quot;classhmi_1_1TextureAtlas.html&quot; title=&quot;hmi::TextureAtlas&quot;&gt;hmi::TextureAtlas&lt;/a&gt; : l&apos;atlas des couleurs plates',['../guide-rendu.html#autotoc_md160',1,'']]],
  ['platform_205_192',['Platform (5)',['../cahiertest.html#autotoc_md24',1,'']]],
  ['plausibilité_193',['6. Contrôle de plausibilité',['../spec-contenu.html#autotoc_md195',1,'']]],
  ['player_20s_20guide_20dessine_20ses_20titres_20deux_20fois_194',['Le &lt;em&gt;Player&apos;s Guide&lt;/em&gt; dessine ses titres deux fois',['../lot-36.html#autotoc_md530',1,'']]],
  ['plomberie_20des_20clés_20d_20assets_195',['LOT-39 — Plomberie des clés d&apos;assets',['../lot-39.html',1,'lots']]],
  ['plus_196',['plus',['../guide-audio.html#autotoc_md31',1,'La règle d&apos;or, une fois de plus'],['../lot-87.html#autotoc_md688',1,'Phase 5 — retirer ce qui ne sert plus']]],
  ['plus_20facile_20d_20implémenter_20de_20travers_197',['Le multiclassage, la règle qu&apos;il est le plus facile d&apos;implémenter de travers',['../lot-43.html#autotoc_md570',1,'']]],
  ['plus_20fort_20levier_20du_20programme_198',['9.3 L&apos;allègement est le geste à plus fort levier du programme',['../roadmap.html#autotoc_md940',1,'']]],
  ['plus_20grande_20que_20la_20fenêtre_199',['Cadrer une carte plus grande que la fenêtre',['../guide-editeur.html#autotoc_md95',1,'']]],
  ['plus_20large_20qu_20estimé_200',['9.5 La collision de numéros est bloquante, et bien plus large qu&apos;estimé',['../roadmap.html#autotoc_md942',1,'']]],
  ['plus_20que_20le_20rpg_201',['2. Le modèle de carte ne porte plus que le RPG',['../lot-88.html#autotoc_md698',1,'']]],
  ['plus_20tard_202',['Pourquoi maintenant, et pas plus tard',['../lot-04.html#autotoc_md322',1,'']]],
  ['plus_20une_20cible_203',['Un coffre vidé n&apos;est plus une cible',['../lot-10.html#autotoc_md367',1,'']]],
  ['plutôt_20qu_20une_20image_20manquante_204',['Pourquoi un marqueur plutôt qu&apos;une image manquante',['../namespacecore.html#autotoc_md1084',1,'']]],
  ['plutôt_20que_20contournées_205',['Trois irrégularités de la source, nommées plutôt que contournées',['../lot-37.html#autotoc_md543',1,'']]],
  ['plutôt_20que_20dessiner_20un_20sprite_20à_20la_20fois_206',['Pourquoi « batcher » plutôt que dessiner un sprite à la fois',['../guide-rendu.html#autotoc_md155',1,'']]],
  ['plutôt_20que_20fonctions_20libres_207',['Classes plutôt que fonctions libres',['../spec-conventions.html#autotoc_md210',1,'']]],
  ['plutôt_20que_20la_20table_20brute_208',['Pourquoi des propriétés nommées plutôt que la table brute',['../classhmi_1_1CharacterSheetModel.html#autotoc_md1127',1,'']]],
  ['plutôt_20que_20réagir_20_3a_20hmi_3a_3ainputstate_20hmi_3a_3ainputstate_209',['Échantillonner plutôt que réagir : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1InputState.html&quot; title=&quot;hmi::InputState&quot;&gt;hmi::InputState&lt;/a&gt;',['../guide-entrees.html#autotoc_md100',1,'']]],
  ['pnj_210',['PNJ',['../lot-91-poc.html#lot-91-methode',1,'4bis. La méthode standard, pour un PNJ'],['../md_Lot_2LOT-CREATION-ASSETS_2epic.html#autotoc_md771',1,'Contrat de qualité PNJ'],['../dir_52c08823cef41a3df195c0648e30f2b3.html#autotoc_md1144',1,'Fabrique d’assets — pilote PNJ'],['../lot-91.html#autotoc_md710',1,'La méthode, pour un PNJ'],['../lot-91.html#autotoc_md713',1,'Les PNJ']]],
  ['pnj_20—_2019_20septembre_202026_211',['Premier essai PNJ — 19 septembre 2026',['../md__2home_2runner_2work_2JustAnotherRpgGame_2JustAnotherRpgGame_2Tools_2AssetFactory_2bilan-poc.html',1,'']]],
  ['pnj_20—_20localisateurs_20pas_20liste_20de_20production_212',['PNJ — localisateurs pas liste de production',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2darkall_2preparation.html#autotoc_md788',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2magocracy-of-mage-tower_2preparation.html#autotoc_md806',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2mystical-wasteland_2preparation.html#autotoc_md813',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2penumbra_2preparation.html#autotoc_md819',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2seashores_2preparation.html#autotoc_md831',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2sindile-forest_2preparation.html#autotoc_md837',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2storm-islands_2preparation.html#autotoc_md843',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2stravian-domains_2preparation.html#autotoc_md849',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2taii-maku-city-states_2preparation.html#autotoc_md855',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2theocracy-of-kepesh_2preparation.html#autotoc_md861',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2tsvetan_2preparation.html#autotoc_md867',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2undertanares_2preparation.html#autotoc_md874',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2yama_2preparation.html#autotoc_md880',1,'PNJ — localisateurs, pas liste de production']]],
  ['pnj_20_3a_20les_20figurines_20du_20character_20compendium_213',['LOT-91 — Atelier des PNJ : les figurines du Character Compendium',['../lot-91.html',1,'lots']]],
  ['pnj_20du_20pilote_214',['1. Les cinq PNJ du pilote',['../lot-91-poc.html#autotoc_md717',1,'']]],
  ['pnj_20du_20poc_215',['T00 — Socle et reprise des cinq PNJ du PoC',['../md_Lot_2LOT-CREATION-ASSETS_2tache-00-socle-pilote-pnj.html',1,'']]],
  ['pnj_20et_20dialogues_216',['LOT-15 — PNJ et dialogues',['../lot-15.html',1,'lots']]],
  ['pnj_20marchands_20et_20quêtes_217',['&lt;span class=&quot;tt&quot;&gt;LOT-82&lt;/span&gt; — Peuplement civil : PNJ, marchands et quêtes',['../roadmap.html#lot-82',1,'']]],
  ['poc_218',['PoC',['../dir_52c08823cef41a3df195c0648e30f2b3.html#autotoc_md1147',1,'Acceptation finale du PoC'],['../md_Lot_2LOT-CREATION-ASSETS_2tache-00-socle-pilote-pnj.html',1,'T00 — Socle et reprise des cinq PNJ du PoC']]],
  ['poc_20fabrique_20d’assets_20—_20état_20de_20production_219',['PoC Fabrique d’assets — état de production',['../md__2home_2runner_2work_2JustAnotherRpgGame_2JustAnotherRpgGame_2Tools_2AssetFactory_2rapport-poc.html',1,'']]],
  ['point_220',['Déterministe, et c&apos;est le point',['../namespacecore.html#autotoc_md1085',1,'']]],
  ['point_20à_20ne_20pas_20rater_221',['Le point à ne pas rater',['../lot-04.html#autotoc_md324',1,'']]],
  ['point_20délicat_222',['Le point délicat',['../roadmap.html#autotoc_md992',1,'']]],
  ['point_20ou_20une_20direction_20dans_20le_20monde_223',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Vector2.html&quot; title=&quot;core::Vector2&quot;&gt;Vector2&lt;/a&gt; : un point ou une direction dans le monde',['../guide-maths.html#autotoc_md130',1,'']]],
  ['points_20de_20contact_20avec_20le_20jeu_224',['7. Points de contact avec le jeu',['../roadmap-editeur.html#roadmap-editeur-contacts',1,'']]],
  ['points_20de_20vigilance_225',['Points de vigilance',['../lot-02.html#autotoc_md312',1,'']]],
  ['points_20ouverts_226',['Points ouverts',['../lot-96.html#autotoc_md765',1,'']]],
  ['points_20que_20la_20grille_20laissait_20ouverts_227',['Les trois points que la grille laissait ouverts',['../lot-20.html#autotoc_md445',1,'']]],
  ['pop_228',['Ajout et suppression : &lt;em&gt;swap-and-pop&lt;/em&gt;',['../guide-ecs.html#autotoc_md79',1,'']]],
  ['portée_229',['Les mémoires à portée',['../lot-20.html#autotoc_md451',1,'']]],
  ['portée_20ligne_20de_20vue_20et_20zones_20d_20effet_230',['LOT-22 — Portée, ligne de vue et zones d&apos;effet',['../lot-22.html',1,'lots']]],
  ['portée_20par_20l_20écran_20et_20non_20par_20l_20appelant_231',['La règle de superposition, portée par l&apos;écran et non par l&apos;appelant',['../lot-68.html#autotoc_md608',1,'']]],
  ['portabilité_20reproductibilité_232',['4. Portabilité &amp;amp; reproductibilité',['../spec-exigences.html#autotoc_md236',1,'']]],
  ['portails_20ville_233',['LOT-EDITOR-09 — Le monde : onglets, portails, ville',['../roadmap-editeur.html#lot-editor-09',1,'']]],
  ['porte_20aucun_20texte_234',['Le graphe ne porte aucun texte',['../lot-15.html#autotoc_md409',1,'']]],
  ['porte_20et_20ce_20qu_20il_20ne_20porte_20pas_235',['porte et ce qu il ne porte pas',['../structcore_1_1ExplorationSnapshot.html#autotoc_md1062',1,'Ce qu&apos;il porte, et ce qu&apos;il ne porte pas'],['../lot-18.html#autotoc_md422',1,'Ce que l&apos;instantané porte, et ce qu&apos;il ne porte pas']]],
  ['porte_20le_20lot_236',['La décision qui porte le lot',['../lot-03.html#autotoc_md318',1,'']]],
  ['porte_20pas_237',['porte pas',['../structcore_1_1ExplorationSnapshot.html#autotoc_md1062',1,'Ce qu&apos;il porte, et ce qu&apos;il ne porte pas'],['../lot-18.html#autotoc_md422',1,'Ce que l&apos;instantané porte, et ce qu&apos;il ne porte pas']]],
  ['porte_20pas_20la_20fiche_20il_20la_20désigne_238',['Le composant ECS ne porte pas la fiche, il la désigne',['../lot-13.html#autotoc_md396',1,'']]],
  ['porte_20plus_20que_20le_20rpg_239',['2. Le modèle de carte ne porte plus que le RPG',['../lot-88.html#autotoc_md698',1,'']]],
  ['portent_20le_20soldat_240',['Les sentinelles portent le soldat',['../lot-93.html#autotoc_md744',1,'']]],
  ['porter_241',['1. Porter',['../spec-inventaire.html#autotoc_md262',1,'']]],
  ['porteur_242',['Exigences qui perdent leur porteur',['../lot-88.html#autotoc_md702',1,'']]],
  ['pose_20sous_20la_20valeur_20jamais_20dessus_243',['Un seuil de corps se pose sous la valeur, jamais dessus',['../lot-36.html#autotoc_md534',1,'']]],
  ['poste_244',['0. Le poste',['../lot-91-poc.html#autotoc_md716',1,'']]],
  ['pour_20«_20peut_20on_20se_20tenir_20ici_20»_245',['pour « peut on se tenir ici »',['../lot-19.html#autotoc_md439',1,'Une seule source de vérité pour « peut-on se tenir ici »'],['../classcore_1_1BattleGrid.html#autotoc_md1053',1,'Une seule source de vérité pour « peut-on se tenir ici »']]],
  ['pour_20«_20se_20tenir_20ici_20»_246',['Une seule règle pour « se tenir ici »',['../namespacecore.html#autotoc_md1076',1,'']]],
  ['pour_20autant_247',['Ce que le schéma ne peut pas dire, et qui n&apos;est pas perdu pour autant',['../lot-33.html#autotoc_md509',1,'']]],
  ['pour_20douze_20refondues_20pour_20trois_248',['Les seize exigences : retirées pour douze, refondues pour trois',['../lot-67.html#autotoc_md601',1,'']]],
  ['pour_20durer_249',['5. Cinq règles pour durer',['../roadmap-editeur.html#roadmap-editeur-perennite',1,'']]],
  ['pour_20l_20éditeur_250',['IHM Qt : la mise en page hors code pour le jeu, en code pour l&apos;éditeur',['../spec-conventions.html#autotoc_md209',1,'']]],
  ['pour_20le_20jeu_20en_20code_20pour_20l_20éditeur_251',['IHM Qt : la mise en page hors code pour le jeu, en code pour l&apos;éditeur',['../spec-conventions.html#autotoc_md209',1,'']]],
  ['pour_20les_20dessiner_252',['Ouvrir les écrans pour les dessiner',['../guide-ihm-qt.html#autotoc_md112',1,'']]],
  ['pour_20tout_20le_20code_20de_20simulation_253',['Conséquence pratique pour tout le code de simulation',['../guide-boucle.html#autotoc_md44',1,'']]],
  ['pour_20trois_254',['Les seize exigences : retirées pour douze, refondues pour trois',['../lot-67.html#autotoc_md601',1,'']]],
  ['pour_20un_20pnj_255',['pour un PNJ',['../lot-91-poc.html#lot-91-methode',1,'4bis. La méthode standard, pour un PNJ'],['../lot-91.html#autotoc_md710',1,'La méthode, pour un PNJ']]],
  ['pour_20une_20autre_20raison_256',['Le facteur d&apos;agrandissement reste entier, pour une autre raison',['../lot-66.html#autotoc_md591',1,'']]],
  ['pour_20une_20créature_257',['La méthode, pour une créature',['../lot-93.html#autotoc_md741',1,'']]],
  ['pourquoi_258',['pourquoi',['../lot-09.html#autotoc_md360',1,'Écarté, et pourquoi'],['../lot-37.html#autotoc_md544',1,'Ce que le lot ne fait pas, et pourquoi'],['../lot-18.html#autotoc_md427',1,'Ce que le mode combat gèle, et pourquoi'],['../spec-interface-ihm.html#autotoc_md256',1,'Ce qui a changé, et pourquoi'],['../lot-87.html#autotoc_md665',1,'Ce qui est écarté, et pourquoi'],['../lot-86.html#autotoc_md639',1,'Les deux directions écartées, et pourquoi']]],
  ['pourquoi_20«_20batcher_20»_20plutôt_20que_20dessiner_20un_20sprite_20à_20la_20fois_259',['Pourquoi « batcher » plutôt que dessiner un sprite à la fois',['../guide-rendu.html#autotoc_md155',1,'']]],
  ['pourquoi_20ce_20lot_20est_20un_20lot_20d_20ajout_20pas_20une_20refonte_260',['Pourquoi ce lot est un lot d&apos;&lt;b&gt;ajout&lt;/b&gt;, pas une refonte',['../roadmap.html#autotoc_md990',1,'']]],
  ['pourquoi_20ceux_20là_20ne_20passent_20pas_20par_20qstr_261',['Pourquoi ceux-là ne passent pas par &lt;span class=&quot;tt&quot;&gt;qsTr&lt;/span&gt;',['../namespacehmi.html#autotoc_md1140',1,'']]],
  ['pourquoi_20chaque_20arête_20n_20est_20contrôlée_20qu_20une_20fois_262',['Le triangle, et pourquoi chaque arête n&apos;est contrôlée qu&apos;une fois',['../lot-32.html#autotoc_md500',1,'']]],
  ['pourquoi_20des_20instantanés_20complets_263',['Annuler/refaire : pourquoi des instantanés complets',['../guide-editeur.html#autotoc_md91',1,'']]],
  ['pourquoi_20des_20propriétés_20nommées_20plutôt_20que_20la_20table_20brute_264',['Pourquoi des propriétés nommées plutôt que la table brute',['../classhmi_1_1CharacterSheetModel.html#autotoc_md1127',1,'']]],
  ['pourquoi_20deux_20binaires_265',['Pourquoi deux binaires',['../guide-ihm-qt.html#autotoc_md108',1,'']]],
  ['pourquoi_20elle_20n_20est_20pas_20un_20parcours_20en_20largeur_266',['La règle du Manuel, et pourquoi elle n&apos;est pas un parcours en largeur',['../classcore_1_1ReachableArea.html#autotoc_md1074',1,'']]],
  ['pourquoi_20il_20est_20déterministe_267',['Le marqueur, et pourquoi il est déterministe',['../lot-39.html#autotoc_md562',1,'']]],
  ['pourquoi_20il_20fallait_20l_20écrire_268',['Pourquoi il fallait l&apos;écrire',['../classhmi_1_1GamepadNavigator.html#autotoc_md1130',1,'']]],
  ['pourquoi_20il_20n_20est_20pas_20«_20une_20seule_20hmilib_20»_269',['Le découpage retenu — et pourquoi il n&apos;est pas « une seule &lt;span class=&quot;tt&quot;&gt;HmiLib&lt;/span&gt; »',['../lot-02.html#autotoc_md310',1,'']]],
  ['pourquoi_20il_20s_20auto_20teste_270',['Ce que le contrôle vérifie, et pourquoi il s&apos;auto-teste',['../lot-30.html#autotoc_md495',1,'']]],
  ['pourquoi_20il_20valait_20mieux_271',['Le renversement du milieu du lot, et pourquoi il valait mieux',['../lot-76.html#autotoc_md614',1,'']]],
  ['pourquoi_20journaliser_20dans_20un_20jeu_20vidéo_272',['Pourquoi journaliser dans un jeu vidéo',['../guide-journalisation.html#autotoc_md118',1,'']]],
  ['pourquoi_20l_20égalité_20stricte_20est_20dangereuse_273',['Comparaison flottante : pourquoi l&apos;égalité stricte est dangereuse',['../guide-maths.html#autotoc_md135',1,'']]],
  ['pourquoi_20le_20facteur_20reste_20entier_20après_20la_20sortie_20du_20pixel_20art_274',['Pourquoi le facteur reste entier après la sortie du pixel art',['../guide-design-ihm.html#autotoc_md66',1,'']]],
  ['pourquoi_20les_20maquettes_20remplacent_20la_20charte_20parchemin_20pixel_275',['Pourquoi les maquettes remplacent la charte parchemin pixel',['../lot-87.html#autotoc_md653',1,'']]],
  ['pourquoi_20maintenant_20et_20pas_20plus_20tard_276',['Pourquoi maintenant, et pas plus tard',['../lot-04.html#autotoc_md322',1,'']]],
  ['pourquoi_20pas_20directement_20dans_20l_20item_20qt_20quick_277',['Pourquoi pas directement dans l&apos;item Qt Quick',['../classhmi_1_1ArenaSceneRenderer.html#autotoc_md1108',1,'']]],
  ['pourquoi_20purger_20en_20premier_278',['Pourquoi purger en premier',['../lot-01.html#autotoc_md299',1,'']]],
  ['pourquoi_20un_20item_20à_20part_279',['Pourquoi un item à part',['../classhmi_1_1ArenaViewportItem.html#autotoc_md1121',1,'']]],
  ['pourquoi_20un_20marqueur_20plutôt_20qu_20une_20image_20manquante_280',['Pourquoi un marqueur plutôt qu&apos;une image manquante',['../namespacecore.html#autotoc_md1084',1,'']]],
  ['pourquoi_20un_20pipeline_20et_20pas_20une_20soustraction_281',['Pourquoi un pipeline, et pas une soustraction',['../Damage_8h.html#autotoc_md1063',1,'']]],
  ['pourquoi_20un_20tiret_20cadratin_20et_20non_20de_20fausses_20données_282',['Pourquoi un tiret cadratin et non de fausses données',['../classhmi_1_1PendingData.html#autotoc_md1138',1,'']]],
  ['pourquoi_20une_20énumération_20et_20non_20un_20nom_20de_20fichier_283',['Pourquoi une énumération et non un nom de fichier',['../classhmi_1_1ScreenRouter.html#autotoc_md1142',1,'']]],
  ['pourquoi_20une_20liste_284',['Pourquoi une liste',['../classcore_1_1ActionEconomy.html#autotoc_md1040',1,'']]],
  ['pourquoi_20une_20session_20à_20part_285',['Pourquoi une session à part',['../ExplorationSession_8h.html#autotoc_md1091',1,'']]],
  ['pourquoi_20une_20table_20de_20chaînes_20et_20non_20une_20structure_20de_20champs_286',['Pourquoi une table de chaînes, et non une structure de champs',['../structhmi_1_1CharacterSheetContext.html#autotoc_md1116',1,'']]],
  ['pourquoi_20une_20zone_20et_20non_20la_20carte_20entière_287',['Pourquoi une zone, et non la carte entière',['../CombatZone_8h.html#autotoc_md1090',1,'']]],
  ['pouvez_20importer_288',['Les modules que vous pouvez importer',['../guide-conception-qds.html#autotoc_md55',1,'']]],
  ['pouvoirs_20et_20menaces_20documentés_289',['pouvoirs et menaces documentés',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2central-empire_2preparation.html#autotoc_md780',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2darkall_2preparation.html#autotoc_md786',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2imperial-benenet_2preparation.html#autotoc_md793',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2kingdom-of-kolbjorn_2preparation.html#autotoc_md799',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2magocracy-of-mage-tower_2preparation.html#autotoc_md805',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2mystical-wasteland_2preparation.html#autotoc_md811',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2penumbra_2preparation.html#autotoc_md818',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2republic-of-freelands_2preparation.html#autotoc_md824',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2seashores_2preparation.html#autotoc_md830',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2sindile-forest_2preparation.html#autotoc_md836',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2storm-islands_2preparation.html#autotoc_md842',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2stravian-domains_2preparation.html#autotoc_md848',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2taii-maku-city-states_2preparation.html#autotoc_md854',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2theocracy-of-kepesh_2preparation.html#autotoc_md860',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2tsvetan_2preparation.html#autotoc_md866',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2undertanares_2preparation.html#autotoc_md872',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2yama_2preparation.html#autotoc_md879',1,'Lieux, cultures, pouvoirs et menaces documentés']]],
  ['pouvoirs_20factions_20et_20organisations_290',['Pouvoirs, factions et organisations',['../md_Lot_2LOT-CREATION-ASSETS_2preparation-regionale.html#autotoc_md776',1,'']]],
  ['préalable_20tranchée_291',['La décision préalable, tranchée',['../lot-11.html#autotoc_md373',1,'']]],
  ['préconditions_20manquent_292',['9.4 Le socle technique tient, mais trois préconditions manquent',['../roadmap.html#autotoc_md941',1,'']]],
  ['préfabriqués_293',['LOT-EDITOR-08 — Tampons et préfabriqués',['../roadmap-editeur.html#lot-editor-08',1,'']]],
  ['préparation_294',['préparation',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2central-empire_2preparation.html#autotoc_md784',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2darkall_2preparation.html#autotoc_md791',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2imperial-benenet_2preparation.html#autotoc_md797',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2kingdom-of-kolbjorn_2preparation.html#autotoc_md803',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2magocracy-of-mage-tower_2preparation.html#autotoc_md809',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2mystical-wasteland_2preparation.html#autotoc_md816',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2penumbra_2preparation.html#autotoc_md822',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2republic-of-freelands_2preparation.html#autotoc_md828',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2seashores_2preparation.html#autotoc_md834',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2sindile-forest_2preparation.html#autotoc_md840',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2storm-islands_2preparation.html#autotoc_md846',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2stravian-domains_2preparation.html#autotoc_md852',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2taii-maku-city-states_2preparation.html#autotoc_md858',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2theocracy-of-kepesh_2preparation.html#autotoc_md864',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2tsvetan_2preparation.html#autotoc_md870',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2undertanares_2preparation.html#autotoc_md877',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2yama_2preparation.html#autotoc_md883',1,'Limites de la préparation']]],
  ['préparation_20production_20et_20acceptation_295',['Préparation production et acceptation',['../md_Lot_2LOT-CREATION-ASSETS_2tache-ce-01-martpart-myr.html#autotoc_md892',1,'Préparation, production et acceptation'],['../md_Lot_2LOT-CREATION-ASSETS_2tache-ce-02-arenarea-galender.html#autotoc_md894',1,'Préparation, production et acceptation']]],
  ['préparation_20régionale_296',['Références communes et préparation régionale',['../md_Lot_2LOT-CREATION-ASSETS_2preparation-regionale.html',1,'']]],
  ['prérequis_297',['Prérequis',['../manuel-telecharger.html#autotoc_md1037',1,'']]],
  ['prévenir_20et_20comment_298',['Les deux défauts à prévenir, et comment',['../lot-23.html#autotoc_md479',1,'']]],
  ['prévisualisation_20qui_20ne_20ment_20pas_299',['Une prévisualisation qui ne ment pas',['../CombatPreview_8h.html#autotoc_md1056',1,'']]],
  ['prévue_300',['Intégration technique prévue',['../md_Lot_2LOT-CREATION-ASSETS_2tache-01-carte-test-textures.html#autotoc_md890',1,'']]],
  ['pratique_20pour_20tout_20le_20code_20de_20simulation_301',['Conséquence pratique pour tout le code de simulation',['../guide-boucle.html#autotoc_md44',1,'']]],
  ['pratiques_302',['7. Bonnes pratiques',['../spec-conventions.html#autotoc_md215',1,'']]],
  ['première_303',['Phase 2 — charte v2 et matière première',['../lot-87.html#autotoc_md661',1,'']]],
  ['première_20carte_304',['LOT-09 — Le Colisée se parcourt : exploration dans le jeu et première carte',['../lot-09.html',1,'lots']]],
  ['première_20série_20proposée_20—_20central_20empire_305',['Première série proposée — Central Empire',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2central-empire_2preparation.html#autotoc_md782',1,'']]],
  ['première_20série_20proposée_20—_20darkall_306',['Première série proposée — Darkall',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2darkall_2preparation.html#autotoc_md789',1,'']]],
  ['première_20série_20proposée_20—_20imperial_20ben’net_307',['Première série proposée — Imperial Ben’net',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2imperial-benenet_2preparation.html#autotoc_md795',1,'']]],
  ['première_20série_20proposée_20—_20kingdom_20of_20kolbjörn_308',['Première série proposée — Kingdom of Kolbjörn',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2kingdom-of-kolbjorn_2preparation.html#autotoc_md801',1,'']]],
  ['première_20série_20proposée_20—_20magocracy_20of_20mage_20tower_309',['Première série proposée — Magocracy of Mage Tower',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2magocracy-of-mage-tower_2preparation.html#autotoc_md807',1,'']]],
  ['première_20série_20proposée_20—_20mystical_20wasteland_310',['Première série proposée — Mystical / Wasteland',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2mystical-wasteland_2preparation.html#autotoc_md814',1,'']]],
  ['première_20série_20proposée_20—_20pénombre_311',['Première série proposée — Pénombre',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2penumbra_2preparation.html#autotoc_md820',1,'']]],
  ['première_20série_20proposée_20—_20republic_20of_20freelands_312',['Première série proposée — Republic of Freelands',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2republic-of-freelands_2preparation.html#autotoc_md826',1,'']]],
  ['première_20série_20proposée_20—_20seashores_313',['Première série proposée — Seashores',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2seashores_2preparation.html#autotoc_md832',1,'']]],
  ['première_20série_20proposée_20—_20sindile_20forest_314',['Première série proposée — Sindile Forest',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2sindile-forest_2preparation.html#autotoc_md838',1,'']]],
  ['première_20série_20proposée_20—_20storm_20islands_315',['Première série proposée — Storm Islands',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2storm-islands_2preparation.html#autotoc_md844',1,'']]],
  ['première_20série_20proposée_20—_20stravian_20domains_316',['Première série proposée — Stravian Domains',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2stravian-domains_2preparation.html#autotoc_md850',1,'']]],
  ['première_20série_20proposée_20—_20taii’maku_317',['Première série proposée — Taii’Maku',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2taii-maku-city-states_2preparation.html#autotoc_md856',1,'']]],
  ['première_20série_20proposée_20—_20theocracy_20of_20kepesh_318',['Première série proposée — Theocracy of Kepesh',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2theocracy-of-kepesh_2preparation.html#autotoc_md862',1,'']]],
  ['première_20série_20proposée_20—_20tsvetan_319',['Première série proposée — Tsvetan',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2tsvetan_2preparation.html#autotoc_md868',1,'']]],
  ['première_20série_20proposée_20—_20undertanares_320',['Première série proposée — Undertanares',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2undertanares_2preparation.html#autotoc_md875',1,'']]],
  ['première_20série_20proposée_20—_20yama_321',['Première série proposée — Yama',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2yama_2preparation.html#autotoc_md881',1,'']]],
  ['premier_322',['Pourquoi purger en premier',['../lot-01.html#autotoc_md299',1,'']]],
  ['premier_20essai_20pnj_20—_2019_20septembre_202026_323',['Premier essai PNJ — 19 septembre 2026',['../md__2home_2runner_2work_2JustAnotherRpgGame_2JustAnotherRpgGame_2Tools_2AssetFactory_2bilan-poc.html',1,'']]],
  ['premier_20lieu_20où_20le_20combat_20est_20tenu_324',['Le premier lieu où le combat est tenu',['../lot-50.html#autotoc_md576',1,'']]],
  ['prennent_20la_20couleur_20des_20jetons_325',['Les contrôles Qt prennent la couleur des jetons',['../guide-conception-qds.html#autotoc_md53',1,'']]],
  ['presentation_2017_326',['Presentation (17)',['../cahiertest.html#autotoc_md25',1,'']]],
  ['preuve_327',['&lt;span class=&quot;tt&quot;&gt;LOT-47&lt;/span&gt; — Socle de classe, et le guerrier comme preuve',['../roadmap.html#lot-47',1,'']]],
  ['preuve_20de_20concept_20_3a_20cinq_20planches_20à_20la_20main_328',['LOT-91 — Preuve de concept : cinq planches à la main',['../lot-91-poc.html',1,'lot-91']]],
  ['principal_329',['Le menu principal',['../manuel-jouer.html#autotoc_md1025',1,'']]],
  ['principal_20maquette_2006_330',['T3.1 — Le menu principal (maquette 06)',['../lot-87.html#autotoc_md676',1,'']]],
  ['principe_20_3a_20ne_20jamais_20coder_20«_20en_20dur_20»_20une_20touche_20dans_20le_20gameplay_331',['Le principe : ne jamais coder « en dur » une touche dans le gameplay',['../guide-entrees.html#autotoc_md98',1,'']]],
  ['principe_20du_20pas_20de_20temps_20fixe_332',['Le principe du pas de temps fixe',['../guide-boucle.html#autotoc_md38',1,'']]],
  ['prises_20en_20route_333',['prises en route',['../lot-11.html#autotoc_md379',1,'Décisions prises en route'],['../lot-21.html#autotoc_md462',1,'Décisions prises en route'],['../lot-22.html#autotoc_md472',1,'Décisions prises en route'],['../lot-23.html#autotoc_md481',1,'Décisions prises en route'],['../lot-24.html#autotoc_md488',1,'Décisions prises en route']]],
  ['prises_20et_20questions_20restantes_334',['8. Décisions prises et questions restantes',['../roadmap.html#autotoc_md932',1,'']]],
  ['problème_335',['problème',['../manuel-partager-niveau.html#autotoc_md1036',1,'En cas de problème'],['../lot-02.html#autotoc_md309',1,'Le problème'],['../lot-03.html#autotoc_md316',1,'Le problème'],['../lot-05.html#autotoc_md329',1,'Le problème'],['../roadmap.html#autotoc_md955',1,'Le problème']]],
  ['problème_20_3a_20éditer_20une_20carte_20sans_20re_20coder_20le_20moteur_336',['Le problème : éditer une carte sans (re)coder le moteur',['../guide-editeur.html#autotoc_md84',1,'']]],
  ['problème_20que_20cette_20classe_20résout_337',['Le problème que cette classe résout',['../classhmi_1_1PendingData.html#autotoc_md1137',1,'']]],
  ['problème_20que_20l_20ecs_20résout_338',['Le problème que l&apos;ECS résout',['../guide-ecs.html#autotoc_md75',1,'']]],
  ['procédural_20fichiers_20et_20replis_339',['Les textures : atlas procédural, fichiers et replis',['../guide-rendu.html#autotoc_md159',1,'']]],
  ['production_340',['production',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2darkall_2preparation.html#autotoc_md788',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2magocracy-of-mage-tower_2preparation.html#autotoc_md806',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2mystical-wasteland_2preparation.html#autotoc_md813',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2penumbra_2preparation.html#autotoc_md819',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2seashores_2preparation.html#autotoc_md831',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2sindile-forest_2preparation.html#autotoc_md837',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2storm-islands_2preparation.html#autotoc_md843',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2stravian-domains_2preparation.html#autotoc_md849',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2taii-maku-city-states_2preparation.html#autotoc_md855',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2theocracy-of-kepesh_2preparation.html#autotoc_md861',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2tsvetan_2preparation.html#autotoc_md867',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2undertanares_2preparation.html#autotoc_md874',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2yama_2preparation.html#autotoc_md880',1,'PNJ — localisateurs, pas liste de production'],['../md__2home_2runner_2work_2JustAnotherRpgGame_2JustAnotherRpgGame_2Tools_2AssetFactory_2rapport-poc.html',1,'PoC Fabrique d’assets — état de production']]],
  ['production_20du_2018_20septembre_202026_341',['La production du 18 septembre 2026',['../lot-93.html#autotoc_md743',1,'']]],
  ['production_20et_20acceptation_342',['Production et acceptation',['../md_Lot_2LOT-CREATION-ASSETS_2tache-00-socle-pilote-pnj.html#autotoc_md887',1,'']]],
  ['production_20et_20acceptation_343',['production et acceptation',['../md_Lot_2LOT-CREATION-ASSETS_2tache-ce-01-martpart-myr.html#autotoc_md892',1,'Préparation, production et acceptation'],['../md_Lot_2LOT-CREATION-ASSETS_2tache-ce-02-arenarea-galender.html#autotoc_md894',1,'Préparation, production et acceptation']]],
  ['production_20observée_344',['Production observée',['../md__2home_2runner_2work_2JustAnotherRpgGame_2JustAnotherRpgGame_2Tools_2AssetFactory_2bilan-poc.html#autotoc_md1150',1,'']]],
  ['produire_345',['Ce que le cahier ne fait pas produire',['../lot-87-cahier-assets.html#lot-87-cahier-exclusions',1,'']]],
  ['produire_20dans_20quel_20ordre_346',['Produire, dans quel ordre',['../lot-87-cahier-assets.html#autotoc_md648',1,'']]],
  ['produire_20selon_20les_20régions_20jouées_347',['LOT-CREATION-ASSETS — Produire selon les régions jouées',['../md_Lot_2LOT-CREATION-ASSETS_2epic.html',1,'']]],
  ['produit_348',['L&apos;éditeur : un outil, pas un produit',['../guide-design-ihm.html#autotoc_md60',1,'']]],
  ['produit_20au_20delà_20du_20moteur_349',['Objectifs produit (au-delà du moteur)',['../spec-vision.html#autotoc_md295',1,'']]],
  ['produit_20pas_350',['Ce que Claude ne produit pas',['../lot-87.html#autotoc_md654',1,'']]],
  ['produit_20tout_20de_20même_20une_20entité_351',['Un type inconnu produit tout de même une entité',['../lot-10.html#autotoc_md369',1,'']]],
  ['produites_352',['produites',['../roadmap.html#autotoc_md939',1,'9.2 Six mécaniques étaient consommées sans être produites'],['../lot-87.html#autotoc_md671',1,'T2.5 — Le manifeste étendu aux images produites'],['../lot-87.html#autotoc_md672',1,'T2.6 — La réception des images produites']]],
  ['produites_2018_20septembre_202026_353',['La réception des images produites (18 septembre 2026)',['../lot-87.html#lot-87-reception',1,'']]],
  ['profondeur_354',['La profondeur',['../ArenaSceneComposer_8h.html#autotoc_md1104',1,'']]],
  ['profondeur_20_3a_20trier_20par_20le_20pied_20lot_2007_355',['La profondeur : trier par le pied (&lt;span class=&quot;tt&quot;&gt;LOT-07&lt;/span&gt;)',['../guide-rendu.html#autotoc_md166',1,'']]],
  ['programme_356',['Programme',['../lots.html#autotoc_md901',1,'']]],
  ['programme_357',['9.3 L&apos;allègement est le geste à plus fort levier du programme',['../roadmap.html#autotoc_md940',1,'']]],
  ['programme_20de_20lots_20proposé_20—_20la_20filière_20contenu_358',['5. Programme de lots proposé — la filière contenu',['../roadmap.html#autotoc_md916',1,'']]],
  ['programme_20en_20six_20phases_359',['Programme, en six phases',['../lot-87.html#autotoc_md655',1,'']]],
  ['progression_360',['4. Progression',['../spec-rpg.html#autotoc_md286',1,'']]],
  ['progression_361',['progression',['../roadmap.html#lot-74',1,'&lt;span class=&quot;tt&quot;&gt;LOT-74&lt;/span&gt; — Expérience et progression'],['../spec-rpg.html',1,'Personnage et progression']]],
  ['progression_20de_20classe_362',['&lt;span class=&quot;tt&quot;&gt;LOT-84&lt;/span&gt; — Les 31 tables de progression de classe',['../roadmap.html#lot-84',1,'']]],
  ['progression_20et_20tâches_363',['Progression et tâches',['../md_Lot_2LOT-CREATION-ASSETS_2epic.html#autotoc_md769',1,'']]],
  ['progressivement_364',['Importer tout, honorer progressivement',['../roadmap.html#autotoc_md917',1,'']]],
  ['projet_365',['1. Récupérer le projet',['../manuel-partager-niveau.html#autotoc_md1031',1,'']]],
  ['projet_20vous_20montre_20et_20ce_20qu_20il_20vous_20cache_366',['Ce que le projet vous montre, et ce qu&apos;il vous cache',['../guide-conception-qds.html#autotoc_md47',1,'']]],
  ['promet_367',['4. Ce qu&apos;une donnée promet',['../spec-contenu.html#autotoc_md193',1,'']]],
  ['prompts_368',['Les prompts',['../lot-87-cahier-assets.html#autotoc_md646',1,'']]],
  ['proposé_20—_20la_20filière_20contenu_369',['5. Programme de lots proposé — la filière contenu',['../roadmap.html#autotoc_md916',1,'']]],
  ['proposée_20—_20central_20empire_370',['Première série proposée — Central Empire',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2central-empire_2preparation.html#autotoc_md782',1,'']]],
  ['proposée_20—_20darkall_371',['Première série proposée — Darkall',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2darkall_2preparation.html#autotoc_md789',1,'']]],
  ['proposée_20—_20imperial_20ben’net_372',['Première série proposée — Imperial Ben’net',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2imperial-benenet_2preparation.html#autotoc_md795',1,'']]],
  ['proposée_20—_20kingdom_20of_20kolbjörn_373',['Première série proposée — Kingdom of Kolbjörn',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2kingdom-of-kolbjorn_2preparation.html#autotoc_md801',1,'']]],
  ['proposée_20—_20magocracy_20of_20mage_20tower_374',['Première série proposée — Magocracy of Mage Tower',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2magocracy-of-mage-tower_2preparation.html#autotoc_md807',1,'']]],
  ['proposée_20—_20mystical_20wasteland_375',['Première série proposée — Mystical / Wasteland',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2mystical-wasteland_2preparation.html#autotoc_md814',1,'']]],
  ['proposée_20—_20pénombre_376',['Première série proposée — Pénombre',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2penumbra_2preparation.html#autotoc_md820',1,'']]],
  ['proposée_20—_20republic_20of_20freelands_377',['Première série proposée — Republic of Freelands',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2republic-of-freelands_2preparation.html#autotoc_md826',1,'']]],
  ['proposée_20—_20seashores_378',['Première série proposée — Seashores',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2seashores_2preparation.html#autotoc_md832',1,'']]],
  ['proposée_20—_20sindile_20forest_379',['Première série proposée — Sindile Forest',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2sindile-forest_2preparation.html#autotoc_md838',1,'']]],
  ['proposée_20—_20storm_20islands_380',['Première série proposée — Storm Islands',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2storm-islands_2preparation.html#autotoc_md844',1,'']]],
  ['proposée_20—_20stravian_20domains_381',['Première série proposée — Stravian Domains',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2stravian-domains_2preparation.html#autotoc_md850',1,'']]],
  ['proposée_20—_20taii’maku_382',['Première série proposée — Taii’Maku',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2taii-maku-city-states_2preparation.html#autotoc_md856',1,'']]],
  ['proposée_20—_20theocracy_20of_20kepesh_383',['Première série proposée — Theocracy of Kepesh',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2theocracy-of-kepesh_2preparation.html#autotoc_md862',1,'']]],
  ['proposée_20—_20tsvetan_384',['Première série proposée — Tsvetan',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2tsvetan_2preparation.html#autotoc_md868',1,'']]],
  ['proposée_20—_20undertanares_385',['Première série proposée — Undertanares',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2undertanares_2preparation.html#autotoc_md875',1,'']]],
  ['proposée_20—_20yama_386',['Première série proposée — Yama',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2yama_2preparation.html#autotoc_md881',1,'']]],
  ['propre_20catégorie_387',['Chaque module a sa propre catégorie',['../guide-journalisation.html#autotoc_md123',1,'']]],
  ['propriétés_20de_20zone_388',['Les propriétés de zone',['../classcore_1_1BattleGrid.html#autotoc_md1054',1,'']]],
  ['propriétés_20de_20zone_20_3a_20un_20crochet_20et_20une_20seule_20lecture_389',['Les propriétés de zone : un crochet, et une seule lecture',['../lot-19.html#autotoc_md438',1,'']]],
  ['propriétés_20libres_390',['Entités et propriétés libres',['../guide-niveaux.html#autotoc_md143',1,'']]],
  ['propriétés_20nommées_20plutôt_20que_20la_20table_20brute_391',['Pourquoi des propriétés nommées plutôt que la table brute',['../classhmi_1_1CharacterSheetModel.html#autotoc_md1127',1,'']]],
  ['propriétés_20pas_20de_20la_20prose_392',['La donnée : des propriétés, pas de la prose',['../lot-22.html#autotoc_md471',1,'']]],
  ['prose_393',['La donnée : des propriétés, pas de la prose',['../lot-22.html#autotoc_md471',1,'']]],
  ['provenance_394',['1. Provenance',['../spec-contenu.html#autotoc_md190',1,'']]],
  ['provenance_395',['Périmètre et provenance',['../md__2home_2runner_2work_2JustAnotherRpgGame_2JustAnotherRpgGame_2Tools_2AssetFactory_2bilan-poc.html#autotoc_md1153',1,'']]],
  ['provenance_20des_20candidats_20du_20pilote_396',['Provenance des candidats du pilote',['../md__2home_2runner_2work_2JustAnotherRpgGame_2JustAnotherRpgGame_2Tools_2AssetFactory_2CREDITS.html',1,'']]],
  ['provisionnement_20_3a_20qt_20multimedia_397',['Provisionnement : Qt Multimedia',['../guide-audio.html#autotoc_md34',1,'']]],
  ['provisoire_398',['Les blocs de Tanares (&lt;span class=&quot;tt&quot;&gt;LOT-46&lt;/span&gt;, relevé provisoire)',['../lot-93.html#autotoc_md749',1,'']]],
  ['provisoire_20et_20dit_20comme_20tel_399',['Le coup d&apos;essai, provisoire et dit comme tel',['../lot-50.html#autotoc_md579',1,'']]],
  ['provisoires_400',['LOT-36 — Espèces, historiques et classes provisoires',['../lot-36.html',1,'lots']]],
  ['provisoires_20et_20le_20déclarent_401',['Les quatre classes sont provisoires, et le déclarent',['../lot-36.html#autotoc_md533',1,'']]],
  ['provisoires_20et_20le_20disent_402',['Les dons sont livrés provisoires, et le disent',['../lot-43.html#autotoc_md571',1,'']]],
  ['publier_20votre_20carte_403',['4. Publier votre carte',['../manuel-partager-niveau.html#autotoc_md1034',1,'']]],
  ['puis_20diffuser_404',['&lt;a class=&quot;el&quot; href=&quot;classcore_1_1Logger.html&quot; title=&quot;core::Logger&quot;&gt;core::Logger&lt;/a&gt; : filtrer puis diffuser',['../guide-journalisation.html#autotoc_md120',1,'']]],
  ['puis_20refermée_405',['La planche gravée : une piste ouverte, puis refermée',['../lot-38.html#autotoc_md549',1,'']]],
  ['puis_20soumettre_406',['Composer, puis soumettre',['../guide-rendu.html#autotoc_md164',1,'']]],
  ['pur_20et_20c_20est_20ce_20qui_20le_20rend_20vérifiable_407',['L&apos;aller-retour est PUR, et c&apos;est ce qui le rend vérifiable',['../lot-18.html#autotoc_md421',1,'']]],
  ['pur_20et_20il_20ne_20s_20arrête_20que_20sur_20une_20réplique_408',['Le runner : pur, et il ne s&apos;arrête que sur une réplique',['../lot-15.html#autotoc_md411',1,'']]],
  ['pure_20et_20c_20est_20tout_20son_20intérêt_409',['Pure, et c&apos;est tout son intérêt',['../classcore_1_1DialogueRunner.html#autotoc_md1086',1,'']]],
  ['purge_20et_20remise_20à_20nu_410',['LOT-01 — Fork, purge et remise à nu',['../lot-01.html',1,'lots']]],
  ['purger_20en_20premier_411',['Pourquoi purger en premier',['../lot-01.html#autotoc_md299',1,'']]]
];
