var searchData=
[
  ['écarté_20à_20la_20relecture_20des_20livres_0',['Écarté à la relecture des livres',['../roadmap.html#autotoc_md765',1,'']]],
  ['échanger_1',['2. Échanger',['../spec-inventaire.html#autotoc_md368',1,'']]],
  ['échantillonner_20plutôt_20que_20réagir_20_3a_20hmi_3a_3ainputstate_20hmi_3a_3ainputstate_2',['Échantillonner plutôt que réagir : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1InputState.html&quot; title=&quot;hmi::InputState&quot;&gt;hmi::InputState&lt;/a&gt;',['../guide-entrees.html#autotoc_md136',1,'']]],
  ['échelles_3',['6. Échelles',['../spec-regles-dnd.html#autotoc_md380',1,'']]],
  ['écrans_20navigation_20et_20boucle_20de_20jeu_4',['Écrans, navigation et boucle de jeu',['../guide-ecrans.html',1,'guide']]],
  ['écrire_20un_20png_20sans_20jamais_20laisser_20de_20fichier_20tronqué_5',['Écrire un PNG sans jamais laisser de fichier tronqué',['../guide-atelier-pixel-art.html#autotoc_md37',1,'']]],
  ['éditer_20un_20écran_20sans_20rien_20reconstruire_6',['Éditer un écran sans rien reconstruire',['../guide-ihm-qt.html#autotoc_md149',1,'']]],
  ['éditeur_7',['2. Éditeur',['../spec-interface-ihm.html#autotoc_md352',1,'']]],
  ['éditeur_20de_20niveaux_8',['Éditeur de niveaux',['../guide-editeur.html',1,'Éditeur de niveaux'],['../spec-editeur.html',1,'Éditeur de niveaux']]],
  ['éditeur_20de_20niveaux_20—_20test_5fparcours_5fedition_20cpp_202_9',['Éditeur de niveaux — &lt;span class=&quot;tt&quot;&gt;test_parcours_edition.cpp&lt;/span&gt; (2)',['../cahiertest.html#autotoc_md35',1,'']]],
  ['éditeur_20multi_20couches_20et_20placement_20d_20entités_10',['LOT-11 — Éditeur multi-couches et placement d&apos;entités',['../roadmap.html#lot-11',1,'']]],
  ['édition_11',['2. Édition',['../spec-decors.html#autotoc_md311',1,'']]],
  ['égalité_20approchée_12',['Égalité approchée',['../guide-maths.html#autotoc_md170',1,'']]],
  ['équilibrage_13',['Équilibrage',['../roadmap.html#autotoc_md849',1,'']]],
  ['équipement_20monnaie_20objets_20magiques_14',['LOT-34 — Équipement, monnaie, objets magiques',['../lot-34.html',1,'lots']]],
  ['étapes_15',['Étapes',['../manuel-telecharger.html#autotoc_md887',1,'']]],
  ['état_20d_20avancement_16',['État d&apos;avancement',['../roadmap.html#roadmap-avancement',1,'']]],
  ['états_20de_20jeu_17',['4. États de jeu',['../spec-gameplay.html#autotoc_md344',1,'']]],
  ['évaluation_20et_20robustesse_18',['4. Évaluation et robustesse',['../spec-ia.html#autotoc_md349',1,'']]],
  ['évolutif_19',['Comment fonctionne la population (algorithme Évolutif)',['../manuel-mode-ia.html#autotoc_md871',1,'']]],
  ['écarté_20',['Le piège, et la façon dont il est écarté',['../lot-14.html#autotoc_md485',1,'']]],
  ['écarté_20et_20pourquoi_21',['Ce qui est écarté, et pourquoi',['../lot-87.html#autotoc_md701',1,'']]],
  ['écartées_20et_20pourquoi_22',['Les deux directions écartées, et pourquoi',['../lot-86.html#autotoc_md675',1,'']]],
  ['échafaudage_20assumé_23',['Le personnage affiché : une donnée, et un échafaudage assumé',['../lot-38.html#autotoc_md591',1,'']]],
  ['échafaudage_20et_20il_20est_20écrit_24',['« Nouvelle partie » : un échafaudage, et il est écrit',['../lot-68.html#autotoc_md645',1,'']]],
  ['échantillonnage_20nearest_25',['Sommets, shaders, et échantillonnage &lt;em&gt;nearest&lt;/em&gt;',['../guide-rendu.html#autotoc_md223',1,'']]],
  ['échelle_26',['2. Repères d&apos;échelle',['../spec-exploration.html#autotoc_md337',1,'']]],
  ['échelle_20d_20affichage_27',['Netteté à toute échelle d&apos;affichage',['../guide-design-ihm.html#autotoc_md82',1,'']]],
  ['échelle_20lot_2066_28',['Deux identités, deux règles d&apos;échelle (LOT-66)',['../guide-design-ihm.html#autotoc_md90',1,'']]],
  ['économie_29',['économie',['../spec-inventaire.html',1,'Inventaire et économie'],['../roadmap.html#lot-26',1,'LOT-26 — Butin, marchands, économie']]],
  ['économie_20d_20action_20est_20une_20liste_30',['L&apos;économie d&apos;action est une liste',['../lot-20.html#autotoc_md520',1,'']]],
  ['écran_31',['écran',['../guide-rendu.html#autotoc_md231',1,'&lt;a class=&quot;el&quot; href=&quot;classhmi_1_1SpriteRenderer.html&quot; title=&quot;hmi::SpriteRenderer&quot;&gt;hmi::SpriteRenderer&lt;/a&gt; : le pont ECS → écran'],['../lot-14.html#autotoc_md488',1,'L&apos;écran'],['../guide-rendu.html',1,'Rendu 2D : de l&apos;ECS à l&apos;écran'],['../lot-68.html#autotoc_md646',1,'Trois défauts d&apos;agencement, trouvés en regardant l&apos;écran']]],
  ['écran_20à_20honorer_32',['Décisions d&apos;écran à honorer',['../lot-86.html#autotoc_md676',1,'']]],
  ['écran_20compose_20et_20ce_20qu_20il_20ne_20compose_20pas_33',['Ce que l&apos;écran compose, et ce qu&apos;il ne compose pas',['../lot-50.html#autotoc_md617',1,'']]],
  ['écran_20est_20donc_20aujourd_20hui_34',['Ce que l&apos;écran est donc aujourd&apos;hui',['../lot-38.html#autotoc_md589',1,'']]],
  ['écran_20et_20non_20par_20l_20appelant_35',['La règle de superposition, portée par l&apos;écran et non par l&apos;appelant',['../lot-68.html#autotoc_md644',1,'']]],
  ['écran_20hmi_3a_3acamera2d_36',['Le rendu (&lt;span class=&quot;tt&quot;&gt;hmi::ParticleRenderer&lt;/span&gt;) et la secousse d&apos;écran (&lt;span class=&quot;tt&quot;&gt;hmi::Camera2D&lt;/span&gt;)',['../guide-rendu.html#autotoc_md248',1,'']]],
  ['écran_20lot_2053_37',['Particules et secousse d&apos;écran (&lt;span class=&quot;tt&quot;&gt;LOT-53&lt;/span&gt;)',['../guide-rendu.html#autotoc_md245',1,'']]],
  ['écran_20sans_20rien_20reconstruire_38',['Éditer un écran sans rien reconstruire',['../guide-ihm-qt.html#autotoc_md149',1,'']]],
  ['écrans_39',['écrans',['../lot-76.html#autotoc_md654',1,'Le titre devient son bandeau, sur les six écrans'],['../lot-87.html#autotoc_md711',1,'Phase 3 — les écrans']]],
  ['écrans_20écrits_20à_20la_20main_40',['Une table, et non huit écrans écrits à la main',['../RpgScreens_8h.html#autotoc_md916',1,'']]],
  ['écrans_20dans_20qt_20design_20studio_41',['Concevoir les écrans dans Qt Design Studio',['../guide-conception-qds.html',1,'guide']]],
  ['écrans_20dessinés_20mais_20pas_20encore_20alimentés_42',['Les écrans dessinés mais pas encore alimentés',['../guide-conception-qds.html#autotoc_md69',1,'']]],
  ['écrans_20du_20jeu_20lot_20h_2068_43',['8. Identité visuelle des écrans du jeu (LOT-H-68)',['../spec-interface-ihm.html#autotoc_md358',1,'']]],
  ['écrans_20du_20rpg_44',['LOT-68 — Le châssis des écrans du RPG',['../lot-68.html',1,'lots']]],
  ['écrans_20du_20rpg_20lot_2068_45',['10. Le châssis des écrans du RPG (LOT-68)',['../spec-interface-ihm.html#autotoc_md360',1,'']]],
  ['écrans_20pour_20les_20dessiner_46',['Ouvrir les écrans pour les dessiner',['../guide-ihm-qt.html#autotoc_md150',1,'']]],
  ['écrire_47',['T1.1 — Le diagnostic, avant d&apos;écrire',['../lot-87.html#autotoc_md693',1,'']]],
  ['écrire_20jamais_20l_20inverse_48',['Enregistrer : valider avant d&apos;écrire, jamais l&apos;inverse',['../guide-editeur.html#autotoc_md124',1,'']]],
  ['écrit_49',['écrit',['../lot-68.html#autotoc_md645',1,'« Nouvelle partie » : un échafaudage, et il est écrit'],['../lot-37.html#autotoc_md579',1,'Le voisinage est déclaré, et c&apos;est écrit']]],
  ['écrit_20comme_20non_20alimenté_50',['Un champ affiché, ou écrit comme non alimenté',['../lot-38.html#autotoc_md585',1,'']]],
  ['écrit_20de_20classdefinition_20_3a_20elle_20existait_20déjà_51',['Le lot n&apos;a pas écrit de &lt;span class=&quot;tt&quot;&gt;ClassDefinition&lt;/span&gt; : elle existait déjà',['../lot-13.html#autotoc_md477',1,'']]],
  ['écrit_20et_20qu_20un_20schéma_20refusait_52',['Trois cas que le livre écrit et qu&apos;un schéma refusait',['../lot-34.html#autotoc_md555',1,'']]],
  ['écrit_20une_20couleur_53',['Les jetons : le seul endroit où s&apos;écrit une couleur',['../guide-conception-qds.html#autotoc_md66',1,'']]],
  ['écrite_54',['écrite',['../lot-14.html#autotoc_md486',1,'Ce que la règle dit, et où elle est écrite'],['../lot-20.html#autotoc_md518',1,'L&apos;initiative : jetée une fois, départagée par une règle écrite']]],
  ['écrites_20là_20où_20on_20les_20lit_55',['Trois décisions de règle, écrites là où on les lit',['../lot-13.html#autotoc_md481',1,'']]],
  ['écrits_20à_20la_20main_56',['Une table, et non huit écrans écrits à la main',['../RpgScreens_8h.html#autotoc_md916',1,'']]],
  ['éditer_20un_20niveau_20sans_20re_20coder_20le_20moteur_57',['Le problème : éditer un niveau sans (re)coder le moteur',['../guide-editeur.html#autotoc_md112',1,'']]],
  ['éditeur_58',['éditeur',['../manuel-partager-niveau.html#autotoc_md879',1,'2. Lancer l&apos;éditeur'],['../spec-decors.html#autotoc_md312',1,'3. Pipeline photo → pixel art (intégré à l&apos;éditeur)'],['../spec-editeur.html#autotoc_md320',1,'4bis. Décors &amp;amp; pixel art (post-MVP, intégré à l&apos;éditeur)'],['../guide-editeur.html#autotoc_md123',1,'Essai immédiat : jouer sans quitter l&apos;éditeur']]],
  ['éditeur_20et_20jeu_59',['Le viewport partagé : éditeur &lt;b&gt;et&lt;/b&gt; jeu',['../guide-ecrans.html#autotoc_md98',1,'']]],
  ['éditeur_20intégré_20»_60',['10. Contrainte « éditeur intégré »',['../spec-architecture.html#autotoc_md269',1,'']]],
  ['éditeur_20lot_2037_20ex_20ihm_20030_20ex_20ihm_20031_61',['Lier des mécanismes dans l&apos;éditeur (&lt;span class=&quot;tt&quot;&gt;LOT-37&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;EX-IHM-030&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;EX-IHM-031&lt;/span&gt;)',['../guide-editeur.html#autotoc_md115',1,'']]],
  ['éditeur_20lot_20h_2057_62',['7. Architecture de l&apos;information de l&apos;éditeur (LOT-H-57)',['../spec-interface-ihm.html#autotoc_md357',1,'']]],
  ['éditeur_20mvp_63',['5. Non-objectifs (éditeur, MVP)',['../spec-editeur.html#autotoc_md321',1,'']]],
  ['édition_20lot_20h_2015_64',['6. Robustesse et confort d&apos;édition (LOT-H-15)',['../spec-editeur.html#autotoc_md322',1,'']]],
  ['égalité_20stricte_20est_20dangereuse_65',['Comparaison flottante : pourquoi l&apos;égalité stricte est dangereuse',['../guide-maths.html#autotoc_md173',1,'']]],
  ['élément_20mobile_66',['L&apos;outil « Parcours » : dessiner la route d&apos;un élément mobile',['../guide-editeur.html#autotoc_md119',1,'']]],
  ['émetteur_20dans_20core_20déterministe_20core_3a_3aparticlesystem_67',['L&apos;émetteur, dans &lt;span class=&quot;tt&quot;&gt;Core&lt;/span&gt;, déterministe (&lt;span class=&quot;tt&quot;&gt;core::ParticleSystem&lt;/span&gt;)',['../guide-rendu.html#autotoc_md246',1,'']]],
  ['énumération_20et_20non_20un_20nom_20de_20fichier_68',['Pourquoi une énumération et non un nom de fichier',['../classhmi_1_1ScreenRouter.html#autotoc_md932',1,'']]],
  ['équipe_20de_20mercenaires_20maquette_2009_69',['T3.7 — L&apos;équipe de mercenaires (maquette 09)',['../lot-87.html#autotoc_md718',1,'']]],
  ['équipe_20et_20quartier_20général_70',['&lt;span class=&quot;tt&quot;&gt;LOT-83&lt;/span&gt; — Compagnie : rangs de Guilde, niveau d&apos;équipe et quartier général',['../roadmap.html#lot-83',1,'']]],
  ['équipement_71',['LOT-14 — Inventaire et équipement',['../lot-14.html',1,'lots']]],
  ['équipement_20maquette_2004_72',['T3.5 — L&apos;inventaire et l&apos;équipement (maquette 04)',['../lot-87.html#autotoc_md716',1,'']]],
  ['été_20fait_73',['T1.2 à T1.4 — Ce qui a été fait',['../lot-87.html#autotoc_md694',1,'']]],
  ['été_20faite_74',['Comment la classification a été faite',['../lot-78.html#autotoc_md663',1,'']]],
  ['été_20retiré_20du_20code_75',['Ce qui a été retiré du code',['../lot-67.html#autotoc_md636',1,'']]],
  ['étaient_20consommées_20sans_20être_20produites_76',['9.2 Six mécaniques étaient consommées sans être produites',['../roadmap.html#autotoc_md770',1,'']]],
  ['était_20périmé_77',['Attention : le texte des maquettes était périmé',['../lot-86.html#autotoc_md674',1,'']]],
  ['étanches_78',['Les jetons : une seule source, deux portées étanches',['../guide-design-ihm.html#autotoc_md78',1,'']]],
  ['état_79',['Détecter les fronts, pas seulement l&apos;état',['../guide-entrees.html#autotoc_md137',1,'']]],
  ['état_20du_20dépôt_80',['9. Ce que l&apos;audit a révélé sur l&apos;état du dépôt',['../roadmap.html#autotoc_md768',1,'']]],
  ['état_20en_20intention_20_3a_20hmi_3a_3atoplayerinput_20hmi_3a_3atoplayerinput_81',['Traduire l&apos;état en intention : &lt;a class=&quot;el&quot; href=&quot;namespacehmi.html#a2c3341857c60f0bef0a01a6cd10ce5f7&quot; title=&quot;hmi::toPlayerInput&quot;&gt;hmi::toPlayerInput&lt;/a&gt;',['../guide-entrees.html#autotoc_md140',1,'']]],
  ['état_20structurée_82',['Une barre d&apos;état structurée',['../guide-design-ihm.html#autotoc_md85',1,'']]],
  ['état_20un_20contrôle_83',['Un état, un contrôle',['../guide-design-ihm.html#autotoc_md87',1,'']]],
  ['états_84',['états',['../roadmap.html#lot-35',1,'&lt;span class=&quot;tt&quot;&gt;LOT-35&lt;/span&gt; — Sorts et états'],['../roadmap.html#lot-21',1,'LOT-21 — Attaques, dégâts et états']]],
  ['états_20_3a_20hmi_3a_3ascreenflow_85',['La machine à états : &lt;span class=&quot;tt&quot;&gt;hmi::ScreenFlow&lt;/span&gt;',['../guide-ecrans.html#autotoc_md95',1,'']]],
  ['étendu_20aux_20images_20produites_86',['T2.5 — Le manifeste étendu aux images produites',['../lot-87.html#autotoc_md707',1,'']]],
  ['éviter_20la_20racine_20carrée_87',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Vector2.html#a5f3517fe219407f73a3ed5542091c31c&quot; title=&quot;core::Vector2::lengthSquared&quot;&gt;lengthSquared&lt;/a&gt; : éviter la racine carrée',['../guide-maths.html#autotoc_md169',1,'']]]
];
