var searchData=
[
  ['télécharger_20et_20lancer_20le_20jeu_0',['Télécharger et lancer le jeu',['../manuel-telecharger.html',1,'manuel']]],
  ['table_20_3a_20hmi_3a_3asoundtriggers_1',['La table : &lt;span class=&quot;tt&quot;&gt;hmi::SoundTriggers&lt;/span&gt;',['../guide-audio.html#autotoc_md45',1,'']]],
  ['tableau_2',['Budget de mouvements et capacités du tableau',['../guide-niveaux.html#autotoc_md176',1,'']]],
  ['tache_2005_3',['Doctrine de profondeur (&lt;span class=&quot;tt&quot;&gt;LOT-65&lt;/span&gt; TACHE-05)',['../spec-niveaux.html#autotoc_md339',1,'']]],
  ['tache_2005_2006_4',['Sélection de niveau et progression persistée (&lt;span class=&quot;tt&quot;&gt;LOT-59&lt;/span&gt; TACHE-05/06)',['../guide-ecrans.html#autotoc_md81',1,'']]],
  ['tactique_20ennemie_5',['LOT-23 — IA tactique ennemie',['../lot-23.html',1,'lots']]],
  ['tactique_20et_20déplacement_6',['LOT-19 — Grille tactique et déplacement',['../lot-19.html',1,'lots']]],
  ['taille_20_3a_20aucun_20écran_20ne_20contraint_20la_20fenêtre_20lot_2073_7',['La taille : aucun écran ne contraint la fenêtre (LOT-73)',['../guide-ihm-qt.html#autotoc_md139',1,'']]],
  ['taille_20de_20niveau_20et_20c_20est_20tout_20le_20problème_8',['Coût : constant en taille de niveau, et c&apos;est tout le problème',['../guide-rendu.html#autotoc_md228',1,'']]],
  ['taille_20de_20suivi_20réglable_20ex_20lvl_20007_20ex_20ren_20017_9',['Mélanger plusieurs tailles de caméra : zones dessinées à la main et taille de suivi réglable (&lt;span class=&quot;tt&quot;&gt;EX-LVL-007&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;EX-REN-017&lt;/span&gt;)',['../guide-rendu.html#autotoc_md207',1,'']]],
  ['taille_20forcément_20conforme_10',['Créer un asset à une taille forcément conforme',['../guide-atelier-pixel-art.html#autotoc_md37',1,'']]],
  ['taille_20lot_2016_11',['7. Niveaux de grande taille (LOT-16)',['../spec-editeur.html#autotoc_md298',1,'']]],
  ['taille_20réactivité_20et_20réglages_20effectifs_20lot_2073_12',['9. Taille, réactivité et réglages effectifs (LOT-73)',['../spec-interface-ihm.html#autotoc_md333',1,'']]],
  ['taille_20réduite_20×0_205_20×0_2025_13',['Blocs à taille réduite (&lt;span class=&quot;tt&quot;&gt;×0.5&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;×0.25&lt;/span&gt;)',['../guide-niveaux.html#autotoc_md174',1,'']]],
  ['tailles_20de_20caméra_20_3a_20zones_20dessinées_20à_20la_20main_20et_20taille_20de_20suivi_20réglable_20ex_20lvl_20007_20ex_20ren_20017_14',['Mélanger plusieurs tailles de caméra : zones dessinées à la main et taille de suivi réglable (&lt;span class=&quot;tt&quot;&gt;EX-LVL-007&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;EX-REN-017&lt;/span&gt;)',['../guide-rendu.html#autotoc_md207',1,'']]],
  ['tailles_20de_20caméra_20dans_20un_20même_20niveau_20mode_20«_20par_20salle_20»_15',['Mélanger plusieurs tailles de caméra dans un même niveau (mode « Par salle »)',['../manuel-partager-niveau.html#autotoc_md552',1,'']]],
  ['tampon_20de_20pixels_16',['Les outils : des fonctions pures sur un tampon de pixels',['../guide-atelier-pixel-art.html#autotoc_md33',1,'']]],
  ['tangente_20verticale_20à_20une_20extrémité_17',['Particularité de l&apos;arrondi : tangente verticale à une extrémité',['../guide-physique.html#autotoc_md193',1,'']]],
  ['tard_18',['Pourquoi maintenant, et pas plus tard',['../lot-04.html#autotoc_md380',1,'']]],
  ['technique_19',['technique',['../spec-rendu-technique.html#autotoc_md341',1,'1. Cible technique'],['../spec-rendu-technique.html',1,'Rendu &amp; cible technique']]],
  ['tel_20quel_20',['Conservé tel quel',['../lot-01.html#autotoc_md359',1,'']]],
  ['temps_21',['3. Boucle &amp;amp; temps',['../spec-rendu-technique.html#autotoc_md343',1,'']]],
  ['temps_20du_20lot_2065_22',['De la couverture à la profondeur (second temps du &lt;span class=&quot;tt&quot;&gt;LOT-65&lt;/span&gt;)',['../guide-niveaux.html#autotoc_md181',1,'']]],
  ['temps_20fixe_23',['temps fixe',['../guide-boucle.html',1,'Boucle de jeu et pas de temps fixe'],['../guide-boucle.html#autotoc_md50',1,'Le principe du pas de temps fixe']]],
  ['tenir_24',['Deux règles à tenir',['../lot-13.html#autotoc_md435',1,'']]],
  ['terminale_20newtonienne_20ex_20gp_20019_25',['Vitesse terminale newtonienne (EX-GP-019)',['../guide-physique.html#autotoc_md195',1,'']]],
  ['test_26',['Cahier de test',['../cahiertest.html',1,'index']]],
  ['test_20de_20non_20régression_20du_20volume_20source_20test_20unit_20hmi_20graphics_20test_5frender_5fbudget_20cpp_27',['Le test de non-régression du volume (&lt;span class=&quot;tt&quot;&gt;Source/Test/Unit/HMI/Graphics/test_render_budget.cpp&lt;/span&gt;)',['../guide-rendu.html#autotoc_md240',1,'']]],
  ['test_20unit_20hmi_20graphics_20test_5frender_5fbudget_20cpp_28',['Le test de non-régression du volume (&lt;span class=&quot;tt&quot;&gt;Source/Test/Unit/HMI/Graphics/test_render_budget.cpp&lt;/span&gt;)',['../guide-rendu.html#autotoc_md240',1,'']]],
  ['test_5fanimation_5fpersonnage_20cpp_2013_29',['Animation Personnage — &lt;span class=&quot;tt&quot;&gt;test_animation_personnage.cpp&lt;/span&gt; (13)',['../cahiertest.html#autotoc_md25',1,'']]],
  ['test_5fboucle_5fsimulation_20cpp_202_30',['Boucle Simulation — &lt;span class=&quot;tt&quot;&gt;test_boucle_simulation.cpp&lt;/span&gt; (2)',['../cahiertest.html#autotoc_md26',1,'']]],
  ['test_5fecs_5fmouvement_20cpp_204_31',['Ecs Mouvement — &lt;span class=&quot;tt&quot;&gt;test_ecs_mouvement.cpp&lt;/span&gt; (4)',['../cahiertest.html#autotoc_md27',1,'']]],
  ['test_5fniveau_5fecs_20cpp_201_32',['Niveau Ecs — &lt;span class=&quot;tt&quot;&gt;test_niveau_ecs.cpp&lt;/span&gt; (1)',['../cahiertest.html#autotoc_md28',1,'']]],
  ['test_5fparcours_5fedition_20cpp_202_33',['Éditeur de niveaux — &lt;span class=&quot;tt&quot;&gt;test_parcours_edition.cpp&lt;/span&gt; (2)',['../cahiertest.html#autotoc_md30',1,'']]],
  ['test_5frender_5fbudget_20cpp_34',['Le test de non-régression du volume (&lt;span class=&quot;tt&quot;&gt;Source/Test/Unit/HMI/Graphics/test_render_budget.cpp&lt;/span&gt;)',['../guide-rendu.html#autotoc_md240',1,'']]],
  ['tester_20exhaustivement_35',['L&apos;invariant à tester exhaustivement',['../lot-22.html#autotoc_md484',1,'']]],
  ['tester_20tout_20le_20trajet_20pas_20seulement_20l_20arrivée_36',['La solution : tester tout le trajet, pas seulement l&apos;arrivée',['../guide-physique.html#autotoc_md185',1,'']]],
  ['tests_37',['8. Tests',['../spec-conventions.html#autotoc_md279',1,'']]],
  ['tests_20d_20intégration_2020_38',['Tests d&apos;intégration (20)',['../cahiertest.html#autotoc_md24',1,'']]],
  ['tests_20système_202_39',['Tests système (2)',['../cahiertest.html#autotoc_md29',1,'']]],
  ['tests_20unitaires_20897_40',['Tests unitaires (897)',['../cahiertest.html#autotoc_md5',1,'']]],
  ['texte_20dans_20la_20scène_20_3a_20hmi_3a_3abitmapfont_20et_20hmi_3a_3atextrenderer_20lot_2052_41',['Le texte dans la scène : &lt;span class=&quot;tt&quot;&gt;hmi::BitmapFont&lt;/span&gt; et &lt;span class=&quot;tt&quot;&gt;hmi::TextRenderer&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;LOT-52&lt;/span&gt;)',['../guide-rendu.html#autotoc_md231',1,'']]],
  ['texturé_42',['&lt;a class=&quot;el&quot; href=&quot;structhmi_1_1SpriteQuad.html&quot; title=&quot;hmi::SpriteQuad&quot;&gt;SpriteQuad&lt;/a&gt; : un rectangle texturé',['../guide-rendu.html#autotoc_md210',1,'']]],
  ['texture_20des_20plans_20lot_2069_43',['Le second axe : la mémoire de texture des plans (&lt;span class=&quot;tt&quot;&gt;LOT-69&lt;/span&gt;)',['../guide-rendu.html#autotoc_md241',1,'']]],
  ['texture_20lot_2041_44',['Deux modes de rendu : Physique et Texture (&lt;span class=&quot;tt&quot;&gt;LOT-41&lt;/span&gt;)',['../guide-rendu.html#autotoc_md221',1,'']]],
  ['textures_20»_20_3a_20auditer_20les_20calques_20sans_20les_20confondre_20avec_20f8_20lot_2051_45',['Le mode « définition des textures » : auditer les calques sans les confondre avec &lt;span class=&quot;tt&quot;&gt;F8&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;LOT-51&lt;/span&gt;)',['../guide-editeur.html#autotoc_md111',1,'']]],
  ['textures_20depuis_20fichiers_20et_20son_20repli_20procédural_46',['Le pipeline de textures depuis fichiers, et son repli procédural',['../guide-rendu.html#autotoc_md214',1,'']]],
  ['textures_20et_20décors_20lot_2040_20→_20lot_2055_47',['11. Habillage par textures et décors (&lt;span class=&quot;tt&quot;&gt;LOT-40&lt;/span&gt; → &lt;span class=&quot;tt&quot;&gt;LOT-55&lt;/span&gt;)',['../spec-editeur.html#autotoc_md302',1,'']]],
  ['thème_20clair_20sombre_48',['Thème clair/sombre',['../guide-design-ihm.html#autotoc_md64',1,'']]],
  ['threading_49',['7. Modèle de threading',['../spec-architecture.html#autotoc_md254',1,'']]],
  ['time_207_50',['Time (7)',['../cahiertest.html#autotoc_md13',1,'']]],
  ['tirage_51',['Le piège du tirage',['../lot-26.html#autotoc_md505',1,'']]],
  ['top_20down_208_20directions_52',['LOT-06 — Déplacement top-down 8 directions',['../lot-06.html',1,'lots']]],
  ['top_20down_20et_20tri_20par_20y_53',['LOT-07 — Rendu top-down et tri par Y',['../lot-07.html',1,'lots']]],
  ['touche_20dans_20le_20gameplay_54',['Le principe : ne jamais coder « en dur » une touche dans le gameplay',['../guide-entrees.html#autotoc_md119',1,'']]],
  ['touches_20et_20boutons_20_3a_20hmi_3a_3agamekeybindings_20gamekeybindings_20hmi_3a_3aeditorkeybindings_20editorkeybindings_20lot_2029_20hmi_3a_3agamepadbindings_20gamepadbindings_20lot_2030_55',['Remapper les touches et boutons : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1GameKeyBindings.html&quot; title=&quot;hmi::GameKeyBindings&quot;&gt;GameKeyBindings&lt;/a&gt;/&lt;a class=&quot;el&quot; href=&quot;classhmi_1_1EditorKeyBindings.html&quot; title=&quot;hmi::EditorKeyBindings&quot;&gt;EditorKeyBindings&lt;/a&gt; (LOT-29), &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1GamepadBindings.html&quot; title=&quot;hmi::GamepadBindings&quot;&gt;GamepadBindings&lt;/a&gt; (LOT-30)',['../guide-entrees.html#autotoc_md127',1,'']]],
  ['tour_56',['LOT-20 — Initiative et tour par tour',['../lot-20.html',1,'lots']]],
  ['tour_20par_20tour_57',['LOT-20 — Initiative et tour par tour',['../lot-20.html',1,'lots']]],
  ['tout_20de_20suite_58',['Pourquoi ce lot peut démarrer tout de suite',['../lot-12.html#autotoc_md428',1,'']]],
  ['tout_20le_20code_20de_20simulation_59',['Conséquence pratique pour tout le code de simulation',['../guide-boucle.html#autotoc_md56',1,'']]],
  ['tout_20le_20problème_60',['Coût : constant en taille de niveau, et c&apos;est tout le problème',['../guide-rendu.html#autotoc_md228',1,'']]],
  ['tout_20le_20trajet_20pas_20seulement_20l_20arrivée_61',['La solution : tester tout le trajet, pas seulement l&apos;arrivée',['../guide-physique.html#autotoc_md185',1,'']]],
  ['toute_20échelle_20d_20affichage_62',['Netteté à toute échelle d&apos;affichage',['../guide-design-ihm.html#autotoc_md63',1,'']]],
  ['traçabilité_63',['Traçabilité',['../spec-architecture.html#autotoc_md259',1,'Traçabilité'],['../spec-controles.html#autotoc_md263',1,'Traçabilité'],['../spec-decors.html#autotoc_md289',1,'Traçabilité'],['../spec-editeur.html#autotoc_md303',1,'Traçabilité'],['../spec-exigences.html#autotoc_md310',1,'Traçabilité'],['../spec-gameplay.html#autotoc_md319',1,'Traçabilité'],['../spec-interface-ihm.html#autotoc_md334',1,'Traçabilité'],['../spec-niveaux.html#autotoc_md340',1,'Traçabilité'],['../spec-rendu-technique.html#autotoc_md346',1,'Traçabilité'],['../spec-vision.html#autotoc_md355',1,'Traçabilité']]],
  ['traces_20du_20moteur_20pendant_20l_20entraînement_64',['Traces du moteur pendant l&apos;entraînement',['../manuel-mode-ia.html#autotoc_md544',1,'']]],
  ['traduire_20l_20état_20en_20intention_20_3a_20hmi_3a_3atoplayerinput_20hmi_3a_3atoplayerinput_65',['Traduire l&apos;état en intention : &lt;a class=&quot;el&quot; href=&quot;namespacehmi.html#a2c3341857c60f0bef0a01a6cd10ce5f7&quot; title=&quot;hmi::toPlayerInput&quot;&gt;hmi::toPlayerInput&lt;/a&gt;',['../guide-entrees.html#autotoc_md124',1,'']]],
  ['trajet_20pas_20seulement_20l_20arrivée_66',['La solution : tester tout le trajet, pas seulement l&apos;arrivée',['../guide-physique.html#autotoc_md185',1,'']]],
  ['tranché_67',['tranché',['../lot-04.html#autotoc_md385',1,'Ce que la réalisation a tranché'],['../lot-05.html#autotoc_md392',1,'Ce que la réalisation a tranché']]],
  ['transitions_68',['LOT-09 — Graphe de cartes et transitions',['../lot-09.html',1,'lots']]],
  ['transitions_20_3a_20hmi_3a_3agameevents_69',['Détection des transitions : &lt;span class=&quot;tt&quot;&gt;hmi::GameEvents&lt;/span&gt;',['../guide-audio.html#autotoc_md44',1,'']]],
  ['transitions_20_3a_20les_20signaux_70',['Qui déclenche les transitions : les signaux',['../guide-ecrans.html#autotoc_md77',1,'']]],
  ['travail_71',['Garde-fous contre la perte de travail',['../guide-editeur.html#autotoc_md109',1,'']]],
  ['travail_20lot_2068_72',['Hiérarchie des surfaces, et espaces de travail (LOT-68)',['../guide-design-ihm.html#autotoc_md73',1,'']]],
  ['tri_20par_20y_73',['LOT-07 — Rendu top-down et tri par Y',['../lot-07.html',1,'lots']]],
  ['trois_74',['Profondeur : deux valeurs, pas trois',['../guide-rendu.html#autotoc_md226',1,'']]],
  ['trois_20espaces_20distincts_75',['3. Coordonnées &amp;amp; unités — trois espaces distincts',['../spec-architecture.html#autotoc_md250',1,'']]],
  ['trois_20fins_76',['Les trois fins',['../lot-20.html#autotoc_md473',1,'']]],
  ['trois_20intentions_77',['Le menu : trois intentions',['../guide-ecrans.html#autotoc_md84',1,'']]],
  ['trois_20modes_20lot_2064_78',['Le cadrage choisi par le niveau : trois modes (&lt;span class=&quot;tt&quot;&gt;LOT-64&lt;/span&gt;)',['../guide-rendu.html#autotoc_md206',1,'']]],
  ['trois_20onglets_79',['Les trois onglets',['../manuel-mode-ia.html#autotoc_md538',1,'']]],
  ['trois_20outils_20une_20même_20grille_20_3a_20hmi_3a_3aeditortool_20editortool_80',['Trois outils, une même grille : &lt;a class=&quot;el&quot; href=&quot;namespacehmi.html#a02048ad8ad69a87a10e8307ac2bd68dd&quot; title=&quot;hmi::EditorTool&quot;&gt;EditorTool&lt;/a&gt;',['../guide-editeur.html#autotoc_md104',1,'']]],
  ['trois_20surfaces_81',['Les commandes : une définition, trois surfaces',['../guide-design-ihm.html#autotoc_md62',1,'']]],
  ['tromper_82',['Les règles à ne pas se tromper',['../lot-21.html#autotoc_md478',1,'']]],
  ['tronqué_83',['Écrire un PNG sans jamais laisser de fichier tronqué',['../guide-atelier-pixel-art.html#autotoc_md32',1,'']]],
  ['tuiles_84',['tuiles',['../spec-gameplay.html#autotoc_md311',1,'1. Monde en tuiles'],['../lot-10.html#autotoc_md416',1,'Pourquoi des entités et pas des tuiles']]],
  ['tuiles_20objets_85',['Format retenu (JSON, liste de tuiles-objets)',['../spec-niveaux.html#autotoc_md336',1,'']]],
  ['tuiles_20rpg_86',['LOT-08 — Vocabulaire de tuiles RPG',['../lot-08.html',1,'lots']]],
  ['tunneling_87',['Le problème : le &lt;em&gt;tunneling&lt;/em&gt;',['../guide-physique.html#autotoc_md184',1,'']]],
  ['typographie_20_3a_20une_20police_20embarquée_20un_20repli_20qui_20n_20invente_20rien_88',['Typographie : une police embarquée, un repli qui n&apos;invente rien',['../guide-design-ihm.html#autotoc_md61',1,'']]]
];
