var searchData=
[
  ['gèle_20et_20pourquoi_0',['Ce que le mode combat gèle, et pourquoi',['../lot-18.html#autotoc_md430',1,'']]],
  ['général_1',['&lt;span class=&quot;tt&quot;&gt;LOT-83&lt;/span&gt; — Compagnie : rangs de Guilde, niveau d&apos;équipe et quartier général',['../roadmap.html#lot-83',1,'']]],
  ['générateur_20de_20terrain_2',['&lt;span class=&quot;tt&quot;&gt;LOT-40&lt;/span&gt; — Générateur de terrain',['../roadmap.html#lot-40',1,'']]],
  ['génération_3',['génération',['../lot-91-poc.html#autotoc_md727',1,'8. Les tours 2 et 3 (nouvelle génération)'],['../lot-33.html#autotoc_md511',1,'Deux contrôles qui arrêtent la génération'],['../lot-33.html#autotoc_md514',1,'Le test lit le livre, pas la génération']]],
  ['géométrie_4',['géométrie',['../lot-19.html#autotoc_md437',1,'L&apos;altitude est un attribut, jamais une géométrie'],['../namespacecore.html#autotoc_md880',1,'L&apos;altitude est un attribut, jamais une géométrie']]],
  ['gérer_20ses_20fichiers_20de_20niveaux_5',['Gérer ses fichiers de niveaux',['../guide-editeur.html#autotoc_md103',1,'']]],
  ['gagner_6',['3. Gagner',['../spec-inventaire.html#autotoc_md268',1,'']]],
  ['gameplay_7',['Gameplay',['../spec-gameplay.html',1,'specifications']]],
  ['gameplay_8',['gameplay',['../spec-vision.html#autotoc_md296',1,'Boucle de gameplay'],['../guide-entrees.html#autotoc_md105',1,'Le principe : ne jamais coder « en dur » une touche dans le gameplay']]],
  ['gameplay_209_9',['Gameplay (9)',['../cahiertest.html#autotoc_md10',1,'']]],
  ['gardé_10',['Ce qui est gardé',['../lot-87.html#autotoc_md666',1,'']]],
  ['garde_20fous_20contre_20la_20perte_20de_20travail_11',['Garde-fous contre la perte de travail',['../guide-editeur.html#autotoc_md101',1,'']]],
  ['gelé_12',['Le monde gelé',['../lot-15.html#autotoc_md416',1,'']]],
  ['geste_20à_20plus_20fort_20levier_20du_20programme_13',['9.3 L&apos;allègement est le geste à plus fort levier du programme',['../roadmap.html#autotoc_md798',1,'']]],
  ['gestes_14',['Les gestes',['../lot-11.html#autotoc_md381',1,'']]],
  ['gestion_20des_20cartes_15',['3. Gestion des cartes',['../spec-interface-ihm.html#autotoc_md253',1,'']]],
  ['gestion_20des_20erreurs_16',['9. Gestion des erreurs',['../spec-conventions.html#autotoc_md224',1,'']]],
  ['gestion_20des_20ressources_17',['9. Gestion des ressources',['../spec-architecture.html#autotoc_md189',1,'']]],
  ['gouttière_20bouge_20d_20une_20page_20à_20l_20autre_18',['Sa gouttière bouge d&apos;une page à l&apos;autre',['../lot-36.html#autotoc_md532',1,'']]],
  ['gouverne_20cette_20classe_19',['La règle qui gouverne cette classe',['../classhmi_1_1OptionsModel.html#autotoc_md951',1,'']]],
  ['gpu_20pas_20un_20changement_20de_20cible_20',['QRhi : une couche d&apos;accès au GPU, pas un changement de cible',['../guide-rendu.html#autotoc_md157',1,'']]],
  ['gpu_20swap_20chain_20back_20buffer_21',['Vocabulaire de base : GPU, swap chain, back buffer',['../guide-rendu.html#autotoc_md156',1,'']]],
  ['graine_20fixée_20_3a_20ce_20que_20cela_20achète_22',['Rejouable à graine fixée : ce que cela achète',['../lot-50.html#autotoc_md580',1,'']]],
  ['graisse_20ment_23',['Le &lt;em&gt;Manuel des Joueurs&lt;/em&gt; est un scan, et sa graisse ment',['../lot-36.html#autotoc_md530',1,'']]],
  ['grande_20que_20la_20fenêtre_24',['Cadrer une carte plus grande que la fenêtre',['../guide-editeur.html#autotoc_md102',1,'']]],
  ['graphe_20de_20cartes_25',['LOT-37 — Atlas des régions et graphe de cartes',['../lot-37.html',1,'lots']]],
  ['graphe_20des_20dépendances_26',['Le graphe des dépendances',['../roadmap.html#autotoc_md785',1,'']]],
  ['graphe_20des_20quartiers_27',['LOT-96 — Martpart et Arenarea se parcourent : le graphe des quartiers',['../lot-96.html',1,'lots']]],
  ['graphe_20ne_20porte_20aucun_20texte_28',['Le graphe ne porte aucun texte',['../lot-15.html#autotoc_md412',1,'']]],
  ['graphics_20126_29',['Graphics (126)',['../cahiertest.html#autotoc_md20',1,'']]],
  ['graphiques_30',['Crédits graphiques',['../md__2home_2runner_2work_2JustAnotherRpgGame_2JustAnotherRpgGame_2Source_2Elements_2Assets_2CREDITS.html',1,'']]],
  ['gravée_20_3a_20une_20piste_20ouverte_20puis_20refermée_31',['La planche gravée : une piste ouverte, puis refermée',['../lot-38.html#autotoc_md552',1,'']]],
  ['gravité_20_3a_20core_3a_3aloglevel_20core_3a_3aloglevel_32',['Les niveaux de gravité : &lt;a class=&quot;el&quot; href=&quot;namespacecore.html#aa9b5a444ee11933c91d5e3235aa5b5e3&quot; title=&quot;core::LogLevel&quot;&gt;core::LogLevel&lt;/a&gt;',['../guide-journalisation.html#autotoc_md126',1,'']]],
  ['grille_33',['&lt;a class=&quot;el&quot; href=&quot;classcore_1_1TileMap.html&quot; title=&quot;core::TileMap&quot;&gt;core::TileMap&lt;/a&gt; : la grille',['../guide-niveaux.html#autotoc_md147',1,'']]],
  ['grille_20_3a_20hmi_3a_3aeditortool_20editortool_34',['Quatre outils, une même grille : &lt;a class=&quot;el&quot; href=&quot;namespacehmi.html#a02048ad8ad69a87a10e8307ac2bd68dd&quot; title=&quot;hmi::EditorTool&quot;&gt;EditorTool&lt;/a&gt;',['../guide-editeur.html#autotoc_md96',1,'']]],
  ['grille_20_3a_20la_20moitié_20d_20une_20case_35',['Sur la grille : la moitié d&apos;une case',['../AreaOfEffect_8h.html#autotoc_md872',1,'']]],
  ['grille_20compte_36',['L&apos;abri : ce que la grille compte',['../lot-22.html#autotoc_md472',1,'']]],
  ['grille_20laissait_20ouverts_37',['Les trois points que la grille laissait ouverts',['../lot-20.html#autotoc_md448',1,'']]],
  ['grille_20le_20mesure_38',['Comment la grille le mesure',['../Flanking_8h.html#autotoc_md896',1,'']]],
  ['grille_20tactique_20et_20déplacement_39',['LOT-19 — Grille tactique et déplacement',['../lot-19.html',1,'lots']]],
  ['groupés_20et_20qui_20suivent_20l_20outil_40',['Des panneaux groupés, et qui suivent l&apos;outil',['../guide-design-ihm.html#autotoc_md69',1,'']]],
  ['groupe_20d_20une_20arme_20n_20est_20pas_20dans_20sa_20rangée_41',['Le groupe d&apos;une arme n&apos;est pas dans sa rangée',['../lot-34.html#autotoc_md520',1,'']]],
  ['groupe_20de_20quatre_20personnages_42',['LOT-29 — Groupe de quatre personnages',['../roadmap.html#lot-29',1,'']]],
  ['groupes_43',['Ordre des groupes',['../spec-conventions.html#autotoc_md214',1,'']]],
  ['guerrier_20comme_20preuve_44',['&lt;span class=&quot;tt&quot;&gt;LOT-47&lt;/span&gt; — Socle de classe, et le guerrier comme preuve',['../roadmap.html#lot-47',1,'']]],
  ['guide_45',['Ce que dit le Guide',['../Flanking_8h.html#autotoc_md895',1,'']]],
  ['guide_46',['guide',['../guide.html#autotoc_md178',1,'Comment lire ce guide'],['../guide.html#autotoc_md180',1,'Plan du guide']]],
  ['guide_20dessine_20ses_20titres_20deux_20fois_47',['Le &lt;em&gt;Player&apos;s Guide&lt;/em&gt; dessine ses titres deux fois',['../lot-36.html#autotoc_md533',1,'']]],
  ['guide_20du_20développeur_48',['Guide du développeur',['../guide.html',1,'index']]],
  ['guide_20du_20maître_20en_20dit_49',['Ce que le &lt;em&gt;Guide du Maître&lt;/em&gt; en dit',['../EnemyAi_8h.html#autotoc_md892',1,'']]],
  ['guide_20et_20où_20chacune_20vit_50',['Les règles du Guide, et où chacune vit',['../lot-23.html#autotoc_md480',1,'']]],
  ['guide_20ne_20dit_20pas_51',['Ce que ce fichier décide, et que le Guide ne dit pas',['../EnemyAi_8h.html#autotoc_md893',1,'']]],
  ['guides_20manuel_52',['4. Spécifications, guides, manuel',['../lot-88.html#autotoc_md703',1,'']]],
  ['guilde_20des_20aventuriers_20_3a_20rangs_20et_20contrats_53',['&lt;span class=&quot;tt&quot;&gt;LOT-45&lt;/span&gt; — Guilde des Aventuriers : rangs et contrats',['../roadmap.html#lot-45',1,'']]],
  ['guilde_20niveau_20d_20équipe_20et_20quartier_20général_54',['&lt;span class=&quot;tt&quot;&gt;LOT-83&lt;/span&gt; — Compagnie : rangs de Guilde, niveau d&apos;équipe et quartier général',['../roadmap.html#lot-83',1,'']]]
];
