var searchData=
[
  ['règle_0',['La règle',['../roadmap-010.html#autotoc_md517',1,'']]],
  ['règle_2012_20empêche_1',['Ce que la règle 12 empêche',['../lot-78.html#autotoc_md490',1,'']]],
  ['règle_20d_20or_20une_20fois_20de_20plus_2',['La règle d&apos;or, une fois de plus',['../guide-audio.html#autotoc_md43',1,'']]],
  ['règle_20de_20déverrouillage_20_3a_20hmi_3a_3aislevelunlocked_3',['La règle de déverrouillage : &lt;span class=&quot;tt&quot;&gt;hmi::isLevelUnlocked&lt;/span&gt;',['../guide-ecrans.html#autotoc_md85',1,'']]],
  ['règle_20de_20performance_20à_20respecter_4',['Une règle de performance à respecter',['../guide-journalisation.html#autotoc_md150',1,'']]],
  ['règle_20qu_20il_20est_20le_20plus_20facile_20d_20implémenter_20de_20travers_5',['Le multiclassage, la règle qu&apos;il est le plus facile d&apos;implémenter de travers',['../lot-43.html#autotoc_md479',1,'']]],
  ['règles_20à_20ne_20pas_20se_20tromper_6',['Les règles à ne pas se tromper',['../roadmap-010.html#autotoc_md603',1,'']]],
  ['règles_20à_20tenir_7',['Deux règles à tenir',['../roadmap-010.html#autotoc_md560',1,'']]],
  ['règles_20d_20échelle_20lot_2068_8',['Deux identités, deux règles d&apos;échelle (LOT-68)',['../guide-design-ihm.html#autotoc_md73',1,'']]],
  ['règles_20d20_9',['Règles d20',['../spec-regles-dnd.html',1,'specifications']]],
  ['règles_20de_20format_10',['Règles de format',['../roadmap-010.html#autotoc_md581',1,'']]],
  ['réécrire_11',['réécrire',['../roadmap-010.html#autotoc_md591',1,'Ce qui existe déjà — à ne pas réécrire'],['../lot-06.html#autotoc_md425',1,'Ce qui existe déjà, et qu&apos;il ne faut pas réécrire']]],
  ['réactivité_12',['3. Réactivité',['../spec-controles.html#autotoc_md276',1,'']]],
  ['réactivité_20et_20réglages_20effectifs_20lot_20h_2073_13',['9. Taille, réactivité et réglages effectifs (LOT-H-73)',['../spec-interface-ihm.html#autotoc_md349',1,'']]],
  ['réagir_20_3a_20hmi_3a_3ainputstate_20hmi_3a_3ainputstate_14',['Échantillonner plutôt que réagir : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1InputState.html&quot; title=&quot;hmi::InputState&quot;&gt;hmi::InputState&lt;/a&gt;',['../guide-entrees.html#autotoc_md122',1,'']]],
  ['réalisation_20a_20tranché_15',['réalisation a tranché',['../lot-04.html#autotoc_md416',1,'Ce que la réalisation a tranché'],['../lot-05.html#autotoc_md423',1,'Ce que la réalisation a tranché'],['../lot-06.html#autotoc_md430',1,'Ce que la réalisation a tranché'],['../lot-08.html#autotoc_md442',1,'Ce que la réalisation a tranché'],['../lot-32.html#autotoc_md462',1,'Ce que la réalisation a tranché'],['../lot-79.html#autotoc_md495',1,'Ce que la réalisation a tranché']]],
  ['réalisation_20a_20vérifié_20et_20ce_20qu_20elle_20a_20démenti_16',['Ce que la réalisation a vérifié, et ce qu&apos;elle a démenti',['../lot-30.html#autotoc_md454',1,'']]],
  ['récapitulatif_20_3a_20qui_20dépend_20de_20qui_17',['Récapitulatif : qui dépend de qui',['../roadmap-010.html#autotoc_md523',1,'']]],
  ['récupération_18',['4. Temps, repos et récupération',['../spec-regles-dnd.html#autotoc_md363',1,'']]],
  ['récupérer_20le_20projet_19',['1. Récupérer le projet',['../manuel-partager-niveau.html#autotoc_md671',1,'']]],
  ['récupérer_20les_20niveaux_20des_20autres_20',['5. Récupérer les niveaux des autres',['../manuel-partager-niveau.html#autotoc_md677',1,'']]],
  ['rédaction_20a_20tranché_21',['Ce que la rédaction a tranché',['../lot-77.html#autotoc_md485',1,'']]],
  ['réduite_20×0_205_20×0_2025_22',['Blocs à taille réduite (&lt;span class=&quot;tt&quot;&gt;×0.5&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;×0.25&lt;/span&gt;)',['../guide-niveaux.html#autotoc_md176',1,'']]],
  ['réel_20_3a_20sinks_20différents_20en_20développement_20et_20en_20release_23',['Bootstrap réel : sinks différents en développement et en Release',['../guide-journalisation.html#autotoc_md153',1,'']]],
  ['référence_20à_20la_20date_20du_20lot_2062_202026_2008_2012_24',['Mesures de référence, à la date du &lt;span class=&quot;tt&quot;&gt;LOT-62&lt;/span&gt; (2026-08-12)',['../guide-rendu.html#autotoc_md244',1,'']]],
  ['référence_20_3a_20un_20repère_20géométrique_20pas_20un_20aperçu_25',['La référence : un repère géométrique, pas un aperçu',['../guide-editeur.html#autotoc_md118',1,'']]],
  ['régénération_26',['&lt;span class=&quot;tt&quot;&gt;Source/Elements/Assets/&lt;/span&gt; : convention et régénération',['../guide-rendu.html#autotoc_md217',1,'']]],
  ['régions_27',['&lt;span class=&quot;tt&quot;&gt;LOT-81&lt;/span&gt; — Descripteurs de terrain des dix régions',['../roadmap-010.html#lot-81',1,'']]],
  ['régions_20et_20graphe_20de_20cartes_28',['&lt;span class=&quot;tt&quot;&gt;LOT-37&lt;/span&gt; — Atlas des régions et graphe de cartes',['../roadmap-010.html#lot-37',1,'']]],
  ['réglable_20ex_20lvl_20007_20ex_20ren_20017_29',['Mélanger plusieurs tailles de caméra : zones dessinées à la main et taille de suivi réglable (&lt;span class=&quot;tt&quot;&gt;EX-LVL-007&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;EX-REN-017&lt;/span&gt;)',['../guide-rendu.html#autotoc_md209',1,'']]],
  ['réglage_20fin_20reporté_20au_20delà_20de_200_201_200_30',['Ressenti (game feel) — ⚠️ réglage fin reporté au-delà de &lt;span class=&quot;tt&quot;&gt;0.1.0&lt;/span&gt;',['../spec-gameplay.html#autotoc_md331',1,'']]],
  ['réglages_31',['Enregistrer et réutiliser des réglages',['../manuel-mode-ia.html#autotoc_md665',1,'']]],
  ['réglages_20de_20l_20onglet_20entraînement_32',['Les réglages de l&apos;onglet Entraînement',['../manuel-mode-ia.html#autotoc_md663',1,'']]],
  ['réglages_20effectifs_20lot_20h_2073_33',['9. Taille, réactivité et réglages effectifs (LOT-H-73)',['../spec-interface-ihm.html#autotoc_md349',1,'']]],
  ['régression_20du_20volume_20source_20test_20unit_20hmi_20graphics_20test_5frender_5fbudget_20cpp_34',['Le test de non-régression du volume (&lt;span class=&quot;tt&quot;&gt;Source/Test/Unit/HMI/Graphics/test_render_budget.cpp&lt;/span&gt;)',['../guide-rendu.html#autotoc_md242',1,'']]],
  ['régulières_35',['L&apos;extraction se fait sur la typographie, pas sur des expressions régulières',['../lot-33.html#autotoc_md468',1,'']]],
  ['résout_36',['Le problème que l&apos;ECS résout',['../guide-ecs.html#autotoc_md89',1,'']]],
  ['résultat_20_3a_20core_3a_3asweepresult_20core_3a_3asweepresult_37',['Lire le résultat : &lt;a class=&quot;el&quot; href=&quot;structcore_1_1SweepResult.html&quot; title=&quot;core::SweepResult&quot;&gt;core::SweepResult&lt;/a&gt;',['../guide-physique.html#autotoc_md190',1,'']]],
  ['résumé_38',['Ordre d&apos;un pas (résumé)',['../guide-physique.html#autotoc_md201',1,'']]],
  ['réutilisée_39',['Jouer un niveau : &lt;span class=&quot;tt&quot;&gt;hmi::GameSession&lt;/span&gt; réutilisée',['../guide-ihm-qt.html#autotoc_md137',1,'']]],
  ['réutilisation_20cohérence_40',['2. Réutilisation &amp;amp; cohérence',['../spec-editeur.html#autotoc_md306',1,'']]],
  ['réutiliser_20des_20réglages_41',['Enregistrer et réutiliser des réglages',['../manuel-mode-ia.html#autotoc_md665',1,'']]],
  ['révélé_42',['Ce que l&apos;ordre a révélé',['../roadmap-010.html#autotoc_md520',1,'']]],
  ['révélé_20sur_20l_20état_20du_20dépôt_43',['9. Ce que l&apos;audit a révélé sur l&apos;état du dépôt',['../roadmap-010.html#autotoc_md531',1,'']]],
  ['raccord_20avant_20de_20l_20avoir_20posé_44',['Voir le raccord avant de l&apos;avoir posé',['../guide-atelier-pixel-art.html#autotoc_md40',1,'']]],
  ['racine_20carrée_45',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Vector2.html#a5f3517fe219407f73a3ed5542091c31c&quot; title=&quot;core::Vector2::lengthSquared&quot;&gt;lengthSquared&lt;/a&gt; : éviter la racine carrée',['../guide-maths.html#autotoc_md157',1,'']]],
  ['raii_20obligatoire_46',['RAII obligatoire',['../spec-conventions.html#autotoc_md288',1,'']]],
  ['rangs_20et_20contrats_47',['&lt;span class=&quot;tt&quot;&gt;LOT-45&lt;/span&gt; — Guilde des Aventuriers : rangs et contrats',['../roadmap-010.html#lot-45',1,'']]],
  ['rater_48',['Le point à ne pas rater',['../lot-04.html#autotoc_md413',1,'']]],
  ['re_20coder_20le_20moteur_49',['Le problème : éditer un niveau sans (re)coder le moteur',['../guide-editeur.html#autotoc_md98',1,'']]],
  ['recouvrements_20_3a_20deux_20patrons_20distincts_50',['Pages empilées et recouvrements : deux patrons distincts',['../guide-ecrans.html#autotoc_md78',1,'']]],
  ['rectangle_20texturé_51',['&lt;a class=&quot;el&quot; href=&quot;structhmi_1_1SpriteQuad.html&quot; title=&quot;hmi::SpriteQuad&quot;&gt;SpriteQuad&lt;/a&gt; : un rectangle texturé',['../guide-rendu.html#autotoc_md212',1,'']]],
  ['refaire_20_3a_20pourquoi_20des_20instantanés_20complets_52',['Annuler/refaire : pourquoi des instantanés complets',['../guide-editeur.html#autotoc_md108',1,'']]],
  ['refaire_20deux_20cibles_53',['Une seule paire Annuler/Refaire, deux cibles',['../guide-atelier-pixel-art.html#autotoc_md41',1,'']]],
  ['refonte_54',['Pourquoi ce lot est un lot d&apos;&lt;b&gt;ajout&lt;/b&gt;, pas une refonte',['../roadmap-010.html#autotoc_md648',1,'']]],
  ['refonte_20—_20socle_20applicatif_20viewport_20direct3d_2011_55',['IHM Qt (refonte) — socle applicatif &amp;amp; viewport Direct3D 11',['../guide-ihm-qt.html',1,'guide']]],
  ['regarder_20l_20ia_20jouer_56',['Regarder l&apos;IA jouer',['../manuel-mode-ia.html',1,'manuel']]],
  ['regroupement_20d_20intention_57',['Le regroupement d&apos;intention',['../roadmap-010.html#autotoc_md519',1,'']]],
  ['rejeu_58',['Rejeu',['../manuel-mode-ia.html#autotoc_md669',1,'']]],
  ['release_59',['Bootstrap réel : sinks différents en développement et en Release',['../guide-journalisation.html#autotoc_md153',1,'']]],
  ['relecture_20n_20aurait_20pas_20vu_60',['Le défaut que les tests ont trouvé, et que la relecture n&apos;aurait pas vu',['../lot-12.html#autotoc_md445',1,'']]],
  ['remapper_20les_20touches_20et_20boutons_20_3a_20hmi_3a_3agamekeybindings_20gamekeybindings_20hmi_3a_3aeditorkeybindings_20editorkeybindings_20lot_2029_20hmi_3a_3agamepadbindings_20gamepadbindings_20lot_2030_61',['Remapper les touches et boutons : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1GameKeyBindings.html&quot; title=&quot;hmi::GameKeyBindings&quot;&gt;GameKeyBindings&lt;/a&gt;/&lt;a class=&quot;el&quot; href=&quot;classhmi_1_1EditorKeyBindings.html&quot; title=&quot;hmi::EditorKeyBindings&quot;&gt;EditorKeyBindings&lt;/a&gt; (LOT-29), &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1GamepadBindings.html&quot; title=&quot;hmi::GamepadBindings&quot;&gt;GamepadBindings&lt;/a&gt; (LOT-30)',['../guide-entrees.html#autotoc_md129',1,'']]],
  ['remarques_62',['Remarques',['../manuel-telecharger.html#autotoc_md681',1,'']]],
  ['remise_20à_20nu_63',['LOT-01 — Fork, purge et remise à nu',['../lot-01.html',1,'lots']]],
  ['ren_20017_64',['Mélanger plusieurs tailles de caméra : zones dessinées à la main et taille de suivi réglable (&lt;span class=&quot;tt&quot;&gt;EX-LVL-007&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;EX-REN-017&lt;/span&gt;)',['../guide-rendu.html#autotoc_md209',1,'']]],
  ['rencontres_20et_20créatures_65',['&lt;span class=&quot;tt&quot;&gt;LOT-41&lt;/span&gt; — Peuplement : rencontres et créatures',['../roadmap-010.html#lot-41',1,'']]],
  ['rendre_20visible_20ici_66',['La contrainte à rendre visible ici',['../roadmap-010.html#autotoc_md555',1,'']]],
  ['rendu_67',['rendu',['../spec-architecture.html#autotoc_md253',1,'4. Frontière simulation ↔ rendu'],['../spec-architecture.html#autotoc_md255',1,'6. Abstraction de rendu']]],
  ['rendu_202d_68',['2. Rendu 2D',['../spec-rendu-technique.html#autotoc_md367',1,'']]],
  ['rendu_202d_20_3a_20de_20l_20ecs_20à_20l_20écran_69',['Rendu 2D : de l&apos;ECS à l&apos;écran',['../guide-rendu.html',1,'guide']]],
  ['rendu_20_3a_20physique_20et_20texture_20lot_2041_70',['Deux modes de rendu : Physique et Texture (&lt;span class=&quot;tt&quot;&gt;LOT-41&lt;/span&gt;)',['../guide-rendu.html#autotoc_md223',1,'']]],
  ['rendu_20cible_20technique_71',['Rendu &amp;amp; cible technique',['../spec-rendu-technique.html',1,'specifications']]],
  ['rendu_20hmi_3a_3aparticlerenderer_20et_20la_20secousse_20d_20écran_20hmi_3a_3acamera2d_72',['Le rendu (&lt;span class=&quot;tt&quot;&gt;hmi::ParticleRenderer&lt;/span&gt;) et la secousse d&apos;écran (&lt;span class=&quot;tt&quot;&gt;hmi::Camera2D&lt;/span&gt;)',['../guide-rendu.html#autotoc_md238',1,'']]],
  ['rendu_20mesuré_20lot_2062_73',['Budget de rendu mesuré (&lt;span class=&quot;tt&quot;&gt;LOT-62&lt;/span&gt;)',['../guide-rendu.html#autotoc_md241',1,'']]],
  ['rendu_20top_20down_20et_20tri_20par_20y_74',['LOT-07 — Rendu top-down et tri par Y',['../lot-07.html',1,'lots']]],
  ['repère_75',['Conventions d&apos;unités et de repère',['../guide-maths.html#autotoc_md160',1,'']]],
  ['repère_20géométrique_20pas_20un_20aperçu_76',['La référence : un repère géométrique, pas un aperçu',['../guide-editeur.html#autotoc_md118',1,'']]],
  ['repères_20d_20échelle_77',['2. Repères d&apos;échelle',['../spec-exploration.html#autotoc_md326',1,'']]],
  ['repli_20procédural_78',['Le pipeline de textures depuis fichiers, et son repli procédural',['../guide-rendu.html#autotoc_md216',1,'']]],
  ['repli_20qui_20n_20invente_20rien_79',['Typographie : une police embarquée, un repli qui n&apos;invente rien',['../guide-design-ihm.html#autotoc_md63',1,'']]],
  ['reporté_20au_20delà_20de_200_201_200_80',['Ressenti (game feel) — ⚠️ réglage fin reporté au-delà de &lt;span class=&quot;tt&quot;&gt;0.1.0&lt;/span&gt;',['../spec-gameplay.html#autotoc_md331',1,'']]],
  ['repos_20dans_20le_20monde_81',['&lt;span class=&quot;tt&quot;&gt;LOT-75&lt;/span&gt; — Campement et repos dans le monde',['../roadmap-010.html#lot-75',1,'']]],
  ['repos_20et_20récupération_82',['4. Temps, repos et récupération',['../spec-regles-dnd.html#autotoc_md363',1,'']]],
  ['représentation_20des_20niveaux_83',['1. Représentation des niveaux',['../spec-niveaux.html#autotoc_md354',1,'']]],
  ['reproductibilité_84',['4. Portabilité &amp;amp; reproductibilité',['../spec-exigences.html#autotoc_md321',1,'']]],
  ['respecter_85',['Une règle de performance à respecter',['../guide-journalisation.html#autotoc_md150',1,'']]],
  ['ressenti_20game_20feel_20—_20⚠️_20réglage_20fin_20reporté_20au_20delà_20de_200_201_200_86',['Ressenti (game feel) — ⚠️ réglage fin reporté au-delà de &lt;span class=&quot;tt&quot;&gt;0.1.0&lt;/span&gt;',['../spec-gameplay.html#autotoc_md331',1,'']]],
  ['ressources_87',['9. Gestion des ressources',['../spec-architecture.html#autotoc_md258',1,'']]],
  ['restantes_88',['8. Décisions prises et questions restantes',['../roadmap-010.html#autotoc_md527',1,'']]],
  ['reste_20ce_20qui_20commande_20est_20unique_89',['Architecture de l&apos;information : ce qui informe reste, ce qui commande est unique',['../guide-design-ihm.html#autotoc_md67',1,'']]],
  ['restitution_20n_20est_20pas_20un_20journal_20c_20est_20une_20exigence_90',['La restitution n&apos;est pas un journal, c&apos;est une exigence',['../lot-12.html#autotoc_md448',1,'']]],
  ['retenu_20—_20et_20pourquoi_20il_20n_20est_20pas_20«_20une_20seule_20hmilib_20»_91',['Le découpage retenu — et pourquoi il n&apos;est pas « une seule &lt;span class=&quot;tt&quot;&gt;HmiLib&lt;/span&gt; »',['../lot-02.html#autotoc_md399',1,'']]],
  ['retenu_20json_20liste_20de_20tuiles_20objets_92',['Format retenu (JSON, liste de tuiles-objets)',['../spec-niveaux.html#autotoc_md355',1,'']]],
  ['retenue_20_3a_20balayage_20par_20axe_20avec_20clamp_20direct_93',['Méthode retenue : balayage &lt;b&gt;par axe&lt;/b&gt; avec clamp direct',['../guide-physique.html#autotoc_md188',1,'']]],
  ['retirées_94',['Exigences retirées',['../spec-decors.html#dec-retirees',1,'']]],
  ['retrait_20de_20l_20atelier_20pixel_20art_95',['&lt;span class=&quot;tt&quot;&gt;LOT-69&lt;/span&gt; — Retrait de l&apos;atelier pixel art',['../roadmap-010.html#lot-69',1,'']]],
  ['riche_96',['LOT-17 — Sauvegarde riche',['../roadmap-010.html#lot-17',1,'']]],
  ['rien_97',['Typographie : une police embarquée, un repli qui n&apos;invente rien',['../guide-design-ihm.html#autotoc_md63',1,'']]],
  ['rien_20n_20est_20construit_98',['10. Ce qu&apos;il faut anticiper, tant que rien n&apos;est construit',['../roadmap-010.html#autotoc_md538',1,'']]],
  ['robustesse_99',['5. Robustesse',['../spec-exigences.html#autotoc_md322',1,'']]],
  ['robustesse_100',['4. Évaluation et robustesse',['../spec-ia.html#autotoc_md339',1,'']]],
  ['robustesse_20et_20confort_20d_20édition_20lot_20h_2015_101',['6. Robustesse et confort d&apos;édition (LOT-H-15)',['../spec-editeur.html#autotoc_md311',1,'']]],
  ['route_102',['Feuille de route',['../lots.html#autotoc_md498',1,'']]],
  ['route_200_201_200_103',['Feuille de route 0.1.0',['../roadmap-010.html',1,'lots']]],
  ['route_20d_20un_20élément_20mobile_104',['L&apos;outil « Parcours » : dessiner la route d&apos;un élément mobile',['../guide-editeur.html#autotoc_md105',1,'']]],
  ['rpg_105',['RPG',['../roadmap-010.html#lot-67',1,'&lt;span class=&quot;tt&quot;&gt;LOT-67&lt;/span&gt; — Menus et vocabulaire d&apos;un RPG'],['../roadmap-010.html#lot-68',1,'&lt;span class=&quot;tt&quot;&gt;LOT-68&lt;/span&gt; — Le châssis des écrans RPG'],['../lot-08.html',1,'LOT-08 — Vocabulaire de tuiles RPG'],['../lot-32.html',1,'LOT-32 — Schémas de données RPG']]],
  ['rpg_2031_106',['Rpg (31)',['../cahiertest.html#autotoc_md14',1,'']]],
  ['rpg_20de_20la_20spécification_107',['LOT-77 — La moitié RPG de la spécification',['../lot-77.html',1,'lots']]],
  ['rules_20est_20attesté_20pas_20saisi_108',['Le complément des &lt;em&gt;Basic Rules&lt;/em&gt; est attesté, pas saisi',['../lot-30.html#autotoc_md455',1,'']]]
];
