var searchData=
[
  ['règle_20d_20or_20une_20fois_20de_20plus_0',['La règle d&apos;or, une fois de plus',['../guide-audio.html#autotoc_md41',1,'']]],
  ['règle_20de_20déverrouillage_20_3a_20hmi_3a_3aislevelunlocked_1',['La règle de déverrouillage : &lt;span class=&quot;tt&quot;&gt;hmi::isLevelUnlocked&lt;/span&gt;',['../guide-ecrans.html#autotoc_md83',1,'']]],
  ['règle_20de_20performance_20à_20respecter_2',['Une règle de performance à respecter',['../guide-journalisation.html#autotoc_md148',1,'']]],
  ['règles_20à_20ne_20pas_20se_20tromper_3',['Les règles à ne pas se tromper',['../lot-21.html#autotoc_md476',1,'']]],
  ['règles_20à_20tenir_4',['Deux règles à tenir',['../lot-13.html#autotoc_md433',1,'']]],
  ['règles_20d_20échelle_20lot_2068_5',['Deux identités, deux règles d&apos;échelle (LOT-68)',['../guide-design-ihm.html#autotoc_md71',1,'']]],
  ['règles_20de_20format_6',['Règles de format',['../lot-17.html#autotoc_md454',1,'']]],
  ['réécrire_7',['réécrire',['../lot-19.html#autotoc_md464',1,'Ce qui existe déjà — à ne pas réécrire'],['../lot-06.html#autotoc_md392',1,'Ce qui existe déjà, et qu&apos;il ne faut pas réécrire']]],
  ['réactivité_8',['3. Réactivité',['../spec-controles.html#autotoc_md262',1,'']]],
  ['réactivité_20et_20réglages_20effectifs_20lot_2073_9',['9. Taille, réactivité et réglages effectifs (LOT-73)',['../spec-interface-ihm.html#autotoc_md333',1,'']]],
  ['réagir_20_3a_20hmi_3a_3ainputstate_20hmi_3a_3ainputstate_10',['Échantillonner plutôt que réagir : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1InputState.html&quot; title=&quot;hmi::InputState&quot;&gt;hmi::InputState&lt;/a&gt;',['../guide-entrees.html#autotoc_md120',1,'']]],
  ['récupérer_20le_20projet_11',['1. Récupérer le projet',['../manuel-partager-niveau.html#autotoc_md546',1,'']]],
  ['récupérer_20les_20niveaux_20des_20autres_12',['5. Récupérer les niveaux des autres',['../manuel-partager-niveau.html#autotoc_md552',1,'']]],
  ['réduite_20×0_205_20×0_2025_13',['Blocs à taille réduite (&lt;span class=&quot;tt&quot;&gt;×0.5&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;×0.25&lt;/span&gt;)',['../guide-niveaux.html#autotoc_md174',1,'']]],
  ['réel_20_3a_20sinks_20différents_20en_20développement_20et_20en_20release_14',['Bootstrap réel : sinks différents en développement et en Release',['../guide-journalisation.html#autotoc_md151',1,'']]],
  ['référence_20à_20la_20date_20du_20lot_2062_202026_2008_2012_15',['Mesures de référence, à la date du &lt;span class=&quot;tt&quot;&gt;LOT-62&lt;/span&gt; (2026-08-12)',['../guide-rendu.html#autotoc_md242',1,'']]],
  ['référence_20_3a_20un_20repère_20géométrique_20pas_20un_20aperçu_16',['La référence : un repère géométrique, pas un aperçu',['../guide-editeur.html#autotoc_md116',1,'']]],
  ['régénération_17',['&lt;span class=&quot;tt&quot;&gt;Source/Elements/Assets/&lt;/span&gt; : convention et régénération',['../guide-rendu.html#autotoc_md215',1,'']]],
  ['réglable_20ex_20lvl_20007_20ex_20ren_20017_18',['Mélanger plusieurs tailles de caméra : zones dessinées à la main et taille de suivi réglable (&lt;span class=&quot;tt&quot;&gt;EX-LVL-007&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;EX-REN-017&lt;/span&gt;)',['../guide-rendu.html#autotoc_md207',1,'']]],
  ['réglage_20fin_20reporté_20au_20delà_20de_200_201_200_19',['Ressenti (game feel) — ⚠️ réglage fin reporté au-delà de &lt;span class=&quot;tt&quot;&gt;0.1.0&lt;/span&gt;',['../spec-gameplay.html#autotoc_md315',1,'']]],
  ['réglages_20',['Enregistrer et réutiliser des réglages',['../manuel-mode-ia.html#autotoc_md540',1,'']]],
  ['réglages_20de_20l_20onglet_20entraînement_21',['Les réglages de l&apos;onglet Entraînement',['../manuel-mode-ia.html#autotoc_md538',1,'']]],
  ['réglages_20effectifs_20lot_2073_22',['9. Taille, réactivité et réglages effectifs (LOT-73)',['../spec-interface-ihm.html#autotoc_md333',1,'']]],
  ['régression_20du_20volume_20source_20test_20unit_20hmi_20graphics_20test_5frender_5fbudget_20cpp_23',['Le test de non-régression du volume (&lt;span class=&quot;tt&quot;&gt;Source/Test/Unit/HMI/Graphics/test_render_budget.cpp&lt;/span&gt;)',['../guide-rendu.html#autotoc_md240',1,'']]],
  ['résout_24',['Le problème que l&apos;ECS résout',['../guide-ecs.html#autotoc_md87',1,'']]],
  ['résultat_20_3a_20core_3a_3asweepresult_20core_3a_3asweepresult_25',['Lire le résultat : &lt;a class=&quot;el&quot; href=&quot;structcore_1_1SweepResult.html&quot; title=&quot;core::SweepResult&quot;&gt;core::SweepResult&lt;/a&gt;',['../guide-physique.html#autotoc_md188',1,'']]],
  ['résumé_26',['Ordre d&apos;un pas (résumé)',['../guide-physique.html#autotoc_md199',1,'']]],
  ['réutilisée_27',['Jouer un niveau : &lt;span class=&quot;tt&quot;&gt;hmi::GameSession&lt;/span&gt; réutilisée',['../guide-ihm-qt.html#autotoc_md135',1,'']]],
  ['réutilisation_20cohérence_28',['2. Réutilisation &amp;amp; cohérence',['../spec-editeur.html#autotoc_md292',1,'']]],
  ['réutiliser_20des_20réglages_29',['Enregistrer et réutiliser des réglages',['../manuel-mode-ia.html#autotoc_md540',1,'']]],
  ['raccord_20avant_20de_20l_20avoir_20posé_30',['Voir le raccord avant de l&apos;avoir posé',['../guide-atelier-pixel-art.html#autotoc_md38',1,'']]],
  ['racine_20carrée_31',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Vector2.html#a5f3517fe219407f73a3ed5542091c31c&quot; title=&quot;core::Vector2::lengthSquared&quot;&gt;lengthSquared&lt;/a&gt; : éviter la racine carrée',['../guide-maths.html#autotoc_md155',1,'']]],
  ['raii_20obligatoire_32',['RAII obligatoire',['../spec-conventions.html#autotoc_md274',1,'']]],
  ['rater_33',['Le point à ne pas rater',['../lot-04.html#autotoc_md382',1,'']]],
  ['re_20coder_20le_20moteur_34',['Le problème : éditer un niveau sans (re)coder le moteur',['../guide-editeur.html#autotoc_md96',1,'']]],
  ['recouvrements_20_3a_20deux_20patrons_20distincts_35',['Pages empilées et recouvrements : deux patrons distincts',['../guide-ecrans.html#autotoc_md76',1,'']]],
  ['rectangle_20texturé_36',['&lt;a class=&quot;el&quot; href=&quot;structhmi_1_1SpriteQuad.html&quot; title=&quot;hmi::SpriteQuad&quot;&gt;SpriteQuad&lt;/a&gt; : un rectangle texturé',['../guide-rendu.html#autotoc_md210',1,'']]],
  ['refaire_20_3a_20pourquoi_20des_20instantanés_20complets_37',['Annuler/refaire : pourquoi des instantanés complets',['../guide-editeur.html#autotoc_md106',1,'']]],
  ['refaire_20deux_20cibles_38',['Une seule paire Annuler/Refaire, deux cibles',['../guide-atelier-pixel-art.html#autotoc_md39',1,'']]],
  ['refonte_39',['Pourquoi ce lot est un lot d&apos;&lt;b&gt;ajout&lt;/b&gt;, pas une refonte',['../lot-29.html#autotoc_md521',1,'']]],
  ['refonte_20—_20socle_20applicatif_20viewport_20direct3d_2011_40',['IHM Qt (refonte) — socle applicatif &amp;amp; viewport Direct3D 11',['../guide-ihm-qt.html',1,'guide']]],
  ['regarder_20l_20ia_20jouer_41',['Regarder l&apos;IA jouer',['../manuel-mode-ia.html',1,'manuel']]],
  ['rejeu_42',['Rejeu',['../manuel-mode-ia.html#autotoc_md544',1,'']]],
  ['release_43',['Bootstrap réel : sinks différents en développement et en Release',['../guide-journalisation.html#autotoc_md151',1,'']]],
  ['remapper_20les_20touches_20et_20boutons_20_3a_20hmi_3a_3agamekeybindings_20gamekeybindings_20hmi_3a_3aeditorkeybindings_20editorkeybindings_20lot_2029_20hmi_3a_3agamepadbindings_20gamepadbindings_20lot_2030_44',['Remapper les touches et boutons : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1GameKeyBindings.html&quot; title=&quot;hmi::GameKeyBindings&quot;&gt;GameKeyBindings&lt;/a&gt;/&lt;a class=&quot;el&quot; href=&quot;classhmi_1_1EditorKeyBindings.html&quot; title=&quot;hmi::EditorKeyBindings&quot;&gt;EditorKeyBindings&lt;/a&gt; (LOT-29), &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1GamepadBindings.html&quot; title=&quot;hmi::GamepadBindings&quot;&gt;GamepadBindings&lt;/a&gt; (LOT-30)',['../guide-entrees.html#autotoc_md127',1,'']]],
  ['remarques_45',['Remarques',['../manuel-telecharger.html#autotoc_md556',1,'']]],
  ['remise_20à_20nu_46',['LOT-01 — Fork, purge et remise à nu',['../lot-01.html',1,'lots']]],
  ['ren_20017_47',['Mélanger plusieurs tailles de caméra : zones dessinées à la main et taille de suivi réglable (&lt;span class=&quot;tt&quot;&gt;EX-LVL-007&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;EX-REN-017&lt;/span&gt;)',['../guide-rendu.html#autotoc_md207',1,'']]],
  ['rendre_20visible_20ici_48',['La contrainte à rendre visible ici',['../lot-11.html#autotoc_md422',1,'']]],
  ['rendu_49',['rendu',['../spec-architecture.html#autotoc_md251',1,'4. Frontière simulation ↔ rendu'],['../spec-architecture.html#autotoc_md253',1,'6. Abstraction de rendu']]],
  ['rendu_202d_50',['2. Rendu 2D',['../spec-rendu-technique.html#autotoc_md342',1,'']]],
  ['rendu_202d_20_3a_20de_20l_20ecs_20à_20l_20écran_51',['Rendu 2D : de l&apos;ECS à l&apos;écran',['../guide-rendu.html',1,'guide']]],
  ['rendu_20_3a_20physique_20et_20texture_20lot_2041_52',['Deux modes de rendu : Physique et Texture (&lt;span class=&quot;tt&quot;&gt;LOT-41&lt;/span&gt;)',['../guide-rendu.html#autotoc_md221',1,'']]],
  ['rendu_20cible_20technique_53',['Rendu &amp;amp; cible technique',['../spec-rendu-technique.html',1,'specifications']]],
  ['rendu_20hmi_3a_3aparticlerenderer_20et_20la_20secousse_20d_20écran_20hmi_3a_3acamera2d_54',['Le rendu (&lt;span class=&quot;tt&quot;&gt;hmi::ParticleRenderer&lt;/span&gt;) et la secousse d&apos;écran (&lt;span class=&quot;tt&quot;&gt;hmi::Camera2D&lt;/span&gt;)',['../guide-rendu.html#autotoc_md236',1,'']]],
  ['rendu_20mesuré_20lot_2062_55',['Budget de rendu mesuré (&lt;span class=&quot;tt&quot;&gt;LOT-62&lt;/span&gt;)',['../guide-rendu.html#autotoc_md239',1,'']]],
  ['rendu_20top_20down_20et_20tri_20par_20y_56',['LOT-07 — Rendu top-down et tri par Y',['../lot-07.html',1,'lots']]],
  ['repère_57',['Conventions d&apos;unités et de repère',['../guide-maths.html#autotoc_md158',1,'']]],
  ['repère_20géométrique_20pas_20un_20aperçu_58',['La référence : un repère géométrique, pas un aperçu',['../guide-editeur.html#autotoc_md116',1,'']]],
  ['repli_20procédural_59',['Le pipeline de textures depuis fichiers, et son repli procédural',['../guide-rendu.html#autotoc_md214',1,'']]],
  ['repli_20qui_20n_20invente_20rien_60',['Typographie : une police embarquée, un repli qui n&apos;invente rien',['../guide-design-ihm.html#autotoc_md61',1,'']]],
  ['reporté_20au_20delà_20de_200_201_200_61',['Ressenti (game feel) — ⚠️ réglage fin reporté au-delà de &lt;span class=&quot;tt&quot;&gt;0.1.0&lt;/span&gt;',['../spec-gameplay.html#autotoc_md315',1,'']]],
  ['représentation_20des_20niveaux_62',['1. Représentation des niveaux',['../spec-niveaux.html#autotoc_md335',1,'']]],
  ['reproductibilité_63',['4. Portabilité &amp;amp; reproductibilité',['../spec-exigences.html#autotoc_md307',1,'']]],
  ['respecter_64',['Une règle de performance à respecter',['../guide-journalisation.html#autotoc_md148',1,'']]],
  ['ressenti_20game_20feel_20—_20⚠️_20réglage_20fin_20reporté_20au_20delà_20de_200_201_200_65',['Ressenti (game feel) — ⚠️ réglage fin reporté au-delà de &lt;span class=&quot;tt&quot;&gt;0.1.0&lt;/span&gt;',['../spec-gameplay.html#autotoc_md315',1,'']]],
  ['ressources_66',['9. Gestion des ressources',['../spec-architecture.html#autotoc_md256',1,'']]],
  ['reste_20ce_20qui_20commande_20est_20unique_67',['Architecture de l&apos;information : ce qui informe reste, ce qui commande est unique',['../guide-design-ihm.html#autotoc_md65',1,'']]],
  ['retenu_20—_20et_20pourquoi_20il_20n_20est_20pas_20«_20une_20seule_20hmilib_20»_68',['Le découpage retenu — et pourquoi il n&apos;est pas « une seule &lt;span class=&quot;tt&quot;&gt;HmiLib&lt;/span&gt; »',['../lot-02.html#autotoc_md368',1,'']]],
  ['retenu_20json_20liste_20de_20tuiles_20objets_69',['Format retenu (JSON, liste de tuiles-objets)',['../spec-niveaux.html#autotoc_md336',1,'']]],
  ['retenue_20_3a_20balayage_20par_20axe_20avec_20clamp_20direct_70',['Méthode retenue : balayage &lt;b&gt;par axe&lt;/b&gt; avec clamp direct',['../guide-physique.html#autotoc_md186',1,'']]],
  ['retirées_71',['Exigences retirées',['../spec-decors.html#dec-retirees',1,'']]],
  ['riche_72',['LOT-17 — Sauvegarde riche',['../lot-17.html',1,'lots']]],
  ['rien_73',['Typographie : une police embarquée, un repli qui n&apos;invente rien',['../guide-design-ihm.html#autotoc_md61',1,'']]],
  ['robustesse_74',['5. Robustesse',['../spec-exigences.html#autotoc_md308',1,'']]],
  ['robustesse_75',['4. Évaluation et robustesse',['../spec-ia.html#autotoc_md323',1,'']]],
  ['robustesse_20et_20confort_20d_20édition_20lot_2015_76',['6. Robustesse et confort d&apos;édition (LOT-15)',['../spec-editeur.html#autotoc_md297',1,'']]],
  ['route_20d_20un_20élément_20mobile_77',['L&apos;outil « Parcours » : dessiner la route d&apos;un élément mobile',['../guide-editeur.html#autotoc_md103',1,'']]],
  ['rpg_78',['LOT-08 — Vocabulaire de tuiles RPG',['../lot-08.html',1,'lots']]]
];
