var searchData=
[
  ['mécaniques_20étaient_20consommées_20sans_20être_20produites_0',['9.2 Six mécaniques étaient consommées sans être produites',['../roadmap-010.html#autotoc_md563',1,'']]],
  ['mécaniques_20aériennes_20avancées_20au_20delà_20du_20mvp_1',['Mécaniques aériennes avancées (au-delà du MVP)',['../spec-gameplay.html#autotoc_md330',1,'']]],
  ['mécaniques_20ex_20lvl_20015_20lot_2065_2',['Garde-fou de couverture des mécaniques (&lt;span class=&quot;tt&quot;&gt;EX-LVL-015&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;LOT-65&lt;/span&gt;)',['../guide-niveaux.html#autotoc_md182',1,'']]],
  ['mécanismes_3',['4. Liens de mécanismes',['../spec-interface-ihm.html#autotoc_md344',1,'']]],
  ['mécanismes_20_3a_20qui_20a_20le_20droit_20de_20se_20lier_20à_20qui_4',['Mécanismes : qui a le droit de se lier à qui',['../guide-editeur.html#autotoc_md100',1,'']]],
  ['mécanismes_20budgets_5',['Niveaux : modèle, chargement, mécanismes, budgets',['../guide-niveaux.html',1,'guide']]],
  ['mécanismes_20déclencheur_20↔_20porte_6',['Mécanismes déclencheur ↔ porte',['../guide-niveaux.html#autotoc_md173',1,'']]],
  ['mécanismes_20dans_20l_20éditeur_20lot_2037_20ex_20ihm_20030_20ex_20ihm_20031_7',['Lier des mécanismes dans l&apos;éditeur (&lt;span class=&quot;tt&quot;&gt;LOT-37&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;EX-IHM-030&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;EX-IHM-031&lt;/span&gt;)',['../guide-editeur.html#autotoc_md101',1,'']]],
  ['mécanismes_20de_20puzzle_8',['3. Mécanismes de puzzle',['../spec-gameplay.html#autotoc_md332',1,'']]],
  ['mécanismes_20lot_2037_9',['&lt;a class=&quot;el&quot; href=&quot;structhmi_1_1LineQuad.html&quot; title=&quot;hmi::LineQuad&quot;&gt;LineQuad&lt;/a&gt; : un segment orienté (liens de mécanismes, &lt;span class=&quot;tt&quot;&gt;LOT-37&lt;/span&gt;)',['../guide-rendu.html#autotoc_md214',1,'']]],
  ['mécanismes_20lot_2037_20et_20unification_20des_20menus_20lot_2038_10',['Liens de mécanismes (LOT-37) et unification des menus (LOT-38)',['../guide-ihm-qt.html#autotoc_md140',1,'']]],
  ['mélanger_20plusieurs_20tailles_20de_20caméra_20_3a_20zones_20dessinées_20à_20la_20main_20et_20taille_20de_20suivi_20réglable_20ex_20lvl_20007_20ex_20ren_20017_11',['Mélanger plusieurs tailles de caméra : zones dessinées à la main et taille de suivi réglable (&lt;span class=&quot;tt&quot;&gt;EX-LVL-007&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;EX-REN-017&lt;/span&gt;)',['../guide-rendu.html#autotoc_md209',1,'']]],
  ['mélanger_20plusieurs_20tailles_20de_20caméra_20dans_20un_20même_20niveau_20mode_20«_20par_20salle_20»_12',['Mélanger plusieurs tailles de caméra dans un même niveau (mode « Par salle »)',['../manuel-partager-niveau.html#autotoc_md694',1,'']]],
  ['mémoire_13',['Le modèle en mémoire',['../guide-niveaux.html#autotoc_md163',1,'']]],
  ['mémoire_20de_20texture_20des_20plans_20lot_2069_14',['Le second axe : la mémoire de texture des plans (&lt;span class=&quot;tt&quot;&gt;LOT-69&lt;/span&gt;)',['../guide-rendu.html#autotoc_md243',1,'']]],
  ['mémoire_20jamais_20de_20cadrage_15',['Densité : un compromis de mémoire, jamais de cadrage',['../guide-rendu.html#autotoc_md227',1,'']]],
  ['méthode_16',['Note de méthode',['../roadmap-010.html#autotoc_md663',1,'']]],
  ['méthode_20retenue_20_3a_20balayage_20par_20axe_20avec_20clamp_20direct_17',['Méthode retenue : balayage &lt;b&gt;par axe&lt;/b&gt; avec clamp direct',['../guide-physique.html#autotoc_md188',1,'']]],
  ['même_20atlas_18',['Les images du personnage : pourquoi elles vivent dans le même atlas',['../guide-rendu.html#autotoc_md218',1,'']]],
  ['même_20grille_20_3a_20hmi_3a_3aeditortool_20editortool_19',['Trois outils, une même grille : &lt;a class=&quot;el&quot; href=&quot;namespacehmi.html#a02048ad8ad69a87a10e8307ac2bd68dd&quot; title=&quot;hmi::EditorTool&quot;&gt;EditorTool&lt;/a&gt;',['../guide-editeur.html#autotoc_md106',1,'']]],
  ['même_20niveau_20mode_20«_20par_20salle_20»_20',['Mélanger plusieurs tailles de caméra dans un même niveau (mode « Par salle »)',['../manuel-partager-niveau.html#autotoc_md694',1,'']]],
  ['même_20une_20entité_21',['Un type inconnu produit tout de même une entité',['../lot-10.html#autotoc_md448',1,'']]],
  ['maîtrise_22',['2. Caractéristiques et maîtrise',['../spec-regles-dnd.html#autotoc_md361',1,'']]],
  ['machine_20à_20états_20_3a_20hmi_3a_3ascreenflow_23',['La machine à états : &lt;span class=&quot;tt&quot;&gt;hmi::ScreenFlow&lt;/span&gt;',['../guide-ecrans.html#autotoc_md77',1,'']]],
  ['macros_20de_20journalisation_20par_20catégorie_24',['Les macros de journalisation, par catégorie',['../guide-journalisation.html#autotoc_md148',1,'']]],
  ['magiques_25',['&lt;span class=&quot;tt&quot;&gt;LOT-34&lt;/span&gt; — Équipement, monnaie, objets magiques',['../roadmap-010.html#lot-34',1,'']]],
  ['main_20et_20taille_20de_20suivi_20réglable_20ex_20lvl_20007_20ex_20ren_20017_26',['Mélanger plusieurs tailles de caméra : zones dessinées à la main et taille de suivi réglable (&lt;span class=&quot;tt&quot;&gt;EX-LVL-007&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;EX-REN-017&lt;/span&gt;)',['../guide-rendu.html#autotoc_md209',1,'']]],
  ['maintenabilité_27',['2. Architecture &amp;amp; maintenabilité',['../spec-exigences.html#autotoc_md319',1,'']]],
  ['maintenant_20et_20pas_20plus_20tard_28',['Pourquoi maintenant, et pas plus tard',['../lot-04.html#autotoc_md411',1,'']]],
  ['mais_20trois_20préconditions_20manquent_29',['9.4 Le socle technique tient, mais trois préconditions manquent',['../roadmap-010.html#autotoc_md565',1,'']]],
  ['manette_20_3a_20une_20seconde_20source_20fusionnée_20en_20lecture_20ex_20ctrl_20002_20lot_2020_30',['La manette : une seconde source, fusionnée en lecture (EX-CTRL-002, LOT-20)',['../guide-entrees.html#autotoc_md127',1,'']]],
  ['manquent_31',['9.4 Le socle technique tient, mais trois préconditions manquent',['../roadmap-010.html#autotoc_md565',1,'']]],
  ['manuel_20des_20joueurs_20est_20un_20scan_20et_20sa_20graisse_20ment_32',['Le &lt;em&gt;Manuel des Joueurs&lt;/em&gt; est un scan, et sa graisse ment',['../lot-36.html#autotoc_md495',1,'']]],
  ['manuel_20utilisateur_33',['Manuel utilisateur',['../manuel.html',1,'index']]],
  ['mapping_20logique_34',['2. Actions du jeu (mapping logique)',['../spec-controles.html#autotoc_md275',1,'']]],
  ['maquette_20et_20interface_35',['&lt;span class=&quot;tt&quot;&gt;LOT-38&lt;/span&gt; — Fiche de personnage : maquette et interface',['../roadmap-010.html#lot-38',1,'']]],
  ['marchands_20économie_36',['LOT-26 — Butin, marchands, économie',['../roadmap-010.html#lot-26',1,'']]],
  ['marchands_20et_20quêtes_37',['&lt;span class=&quot;tt&quot;&gt;LOT-82&lt;/span&gt; — Peuplement civil : PNJ, marchands et quêtes',['../roadmap-010.html#lot-82',1,'']]],
  ['mathématiques_20dans_20core_38',['5. Mathématiques dans Core',['../spec-architecture.html#autotoc_md254',1,'']]],
  ['mathématiques_20du_20moteur_39',['Mathématiques du moteur',['../guide-maths.html',1,'guide']]],
  ['math_2026_40',['Math (26)',['../cahiertest.html#autotoc_md12',1,'']]],
  ['ment_41',['Le &lt;em&gt;Manuel des Joueurs&lt;/em&gt; est un scan, et sa graisse ment',['../lot-36.html#autotoc_md495',1,'']]],
  ['menu_20_3a_20trois_20intentions_42',['Le menu : trois intentions',['../guide-ecrans.html#autotoc_md86',1,'']]],
  ['menu_20d_20options_43',['Le menu d&apos;options',['../manuel-jouer.html#autotoc_md677',1,'']]],
  ['menu_20d_20options_20_3a_20hmi_3a_3aoptionspage_20hmi_3a_3aoptionspage_44',['Le menu d&apos;options : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1OptionsPage.html&quot; title=&quot;hmi::OptionsPage&quot;&gt;hmi::OptionsPage&lt;/a&gt;',['../guide-entrees.html#autotoc_md128',1,'']]],
  ['menu_20principal_45',['Le menu principal',['../manuel-jouer.html#autotoc_md672',1,'']]],
  ['menus_20et_20vocabulaire_20d_20un_20rpg_46',['&lt;span class=&quot;tt&quot;&gt;LOT-67&lt;/span&gt; — Menus et vocabulaire d&apos;un RPG',['../roadmap-010.html#lot-67',1,'']]],
  ['menus_20lot_2038_47',['Liens de mécanismes (LOT-37) et unification des menus (LOT-38)',['../guide-ihm-qt.html#autotoc_md140',1,'']]],
  ['menus_20options_20unification_48',['5. Menus, options, unification',['../spec-interface-ihm.html#autotoc_md345',1,'']]],
  ['messages_49',['Les sinks : où finissent les messages',['../guide-journalisation.html#autotoc_md147',1,'']]],
  ['mesuré_20lot_2062_50',['Budget de rendu mesuré (&lt;span class=&quot;tt&quot;&gt;LOT-62&lt;/span&gt;)',['../guide-rendu.html#autotoc_md241',1,'']]],
  ['mesures_20de_20référence_20à_20la_20date_20du_20lot_2062_202026_2008_2012_51',['Mesures de référence, à la date du &lt;span class=&quot;tt&quot;&gt;LOT-62&lt;/span&gt; (2026-08-12)',['../guide-rendu.html#autotoc_md244',1,'']]],
  ['minimal_20au_20lancement_52',['Configurer le niveau minimal au lancement',['../guide-journalisation.html#autotoc_md152',1,'']]],
  ['mis_20au_20jour_53',['mis au jour',['../lot-33.html#autotoc_md488',1,'Cinq défauts du lexique que les 94 noms ont mis au jour'],['../lot-43.html#autotoc_md508',1,'Trois défauts du corpus que ce lot a mis au jour']]],
  ['mise_20en_20forme_54',['3. Mise en forme',['../spec-conventions.html#autotoc_md281',1,'']]],
  ['mise_20en_20page_20hors_20code_55',['IHM Qt : le moins de code possible, la mise en page hors code',['../spec-conventions.html#autotoc_md286',1,'']]],
  ['mobile_56',['L&apos;outil « Parcours » : dessiner la route d&apos;un élément mobile',['../guide-editeur.html#autotoc_md105',1,'']]],
  ['mobiles_20ex_20gp_20026_20lot_2063_57',['Plateformes mobiles (&lt;span class=&quot;tt&quot;&gt;EX-GP-026&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;LOT-63&lt;/span&gt;)',['../guide-niveaux.html#autotoc_md177',1,'']]],
  ['modèle_20_3a_20hmi_3a_3aprogression_58',['Le modèle : &lt;span class=&quot;tt&quot;&gt;hmi::Progression&lt;/span&gt;',['../guide-ecrans.html#autotoc_md84',1,'']]],
  ['modèle_20chargement_20mécanismes_20budgets_59',['Niveaux : modèle, chargement, mécanismes, budgets',['../guide-niveaux.html',1,'guide']]],
  ['modèle_20d_20entités_20_3a_20ecs_60',['2. Modèle d&apos;entités : ECS',['../spec-architecture.html#autotoc_md251',1,'']]],
  ['modèle_20de_20threading_61',['7. Modèle de threading',['../spec-architecture.html#autotoc_md256',1,'']]],
  ['modèle_20en_20mémoire_62',['Le modèle en mémoire',['../guide-niveaux.html#autotoc_md163',1,'']]],
  ['mode_20«_20définition_20des_20textures_20»_20_3a_20auditer_20les_20calques_20sans_20les_20confondre_20avec_20f8_20lot_2051_63',['Le mode « définition des textures » : auditer les calques sans les confondre avec &lt;span class=&quot;tt&quot;&gt;F8&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;LOT-51&lt;/span&gt;)',['../guide-editeur.html#autotoc_md113',1,'']]],
  ['mode_20«_20par_20salle_20»_64',['Mélanger plusieurs tailles de caméra dans un même niveau (mode « Par salle »)',['../manuel-partager-niveau.html#autotoc_md694',1,'']]],
  ['mode_20création_65',['Peindre un plan : le mode création',['../guide-rendu.html#autotoc_md231',1,'']]],
  ['mode_20création_20_3a_20peindre_20le_20décor_20du_20niveau_20lot_2069_66',['Le mode création : peindre le décor du niveau (&lt;span class=&quot;tt&quot;&gt;LOT-69&lt;/span&gt;)',['../guide-editeur.html#autotoc_md114',1,'']]],
  ['mode_20ia_20_3a_20enveloppe_20d_20identité_20contenu_20d_20outil_67',['Le Mode IA : enveloppe d&apos;identité, contenu d&apos;outil',['../guide-design-ihm.html#autotoc_md72',1,'']]],
  ['modes_20de_20jeu_68',['LOT-05 — Modes de jeu',['../lot-05.html',1,'lots']]],
  ['modes_20de_20rendu_20_3a_20physique_20et_20texture_20lot_2041_69',['Deux modes de rendu : Physique et Texture (&lt;span class=&quot;tt&quot;&gt;LOT-41&lt;/span&gt;)',['../guide-rendu.html#autotoc_md223',1,'']]],
  ['modes_20lot_2064_70',['Le cadrage choisi par le niveau : trois modes (&lt;span class=&quot;tt&quot;&gt;LOT-64&lt;/span&gt;)',['../guide-rendu.html#autotoc_md208',1,'']]],
  ['module_20a_20sa_20propre_20catégorie_71',['Chaque module a sa propre catégorie',['../guide-journalisation.html#autotoc_md149',1,'']]],
  ['modules_72',['5. Architecture (dépendances entre modules)',['../spec-conventions.html#autotoc_md285',1,'']]],
  ['modules_20dépendances_73',['1. Modules &amp;amp; dépendances',['../spec-architecture.html#autotoc_md250',1,'']]],
  ['moins_20de_20code_20possible_20la_20mise_20en_20page_20hors_20code_74',['IHM Qt : le moins de code possible, la mise en page hors code',['../spec-conventions.html#autotoc_md286',1,'']]],
  ['moitié_20du_20travail_75',['Le choix de la source est la moitié du travail',['../lot-43.html#autotoc_md507',1,'']]],
  ['moitié_20rpg_20de_20la_20spécification_76',['LOT-77 — La moitié RPG de la spécification',['../lot-77.html',1,'lots']]],
  ['monde_77',['monde',['../guide-maths.html#autotoc_md156',1,'&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Vector2.html&quot; title=&quot;core::Vector2&quot;&gt;Vector2&lt;/a&gt; : un point ou une direction dans le monde'],['../roadmap-010.html#lot-42',1,'&lt;span class=&quot;tt&quot;&gt;LOT-42&lt;/span&gt; — Voyage et carte du monde'],['../roadmap-010.html#lot-75',1,'&lt;span class=&quot;tt&quot;&gt;LOT-75&lt;/span&gt; — Campement et repos dans le monde'],['../roadmap-010.html#lot-16',1,'LOT-16 — Quêtes et drapeaux de monde']]],
  ['monde_20en_20tuiles_78',['1. Monde en tuiles',['../spec-gameplay.html#autotoc_md327',1,'']]],
  ['monde_20et_20pixels_20_3a_20hmi_3a_3acamera2d_20hmi_3a_3acamera2d_79',['Unités monde et pixels : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1Camera2D.html&quot; title=&quot;hmi::Camera2D&quot;&gt;hmi::Camera2D&lt;/a&gt;',['../guide-rendu.html#autotoc_md206',1,'']]],
  ['monnaie_20objets_20magiques_80',['&lt;span class=&quot;tt&quot;&gt;LOT-34&lt;/span&gt; — Équipement, monnaie, objets magiques',['../roadmap-010.html#lot-34',1,'']]],
  ['mort_81',['mort',['../spec-combat.html#autotoc_md266',1,'5. Agonie et mort'],['../roadmap-010.html#lot-72',1,'&lt;span class=&quot;tt&quot;&gt;LOT-72&lt;/span&gt; — Conditions, agonie et mort']]],
  ['mort_20»_82',['La « spirale de la mort »',['../guide-boucle.html#autotoc_md55',1,'']]],
  ['moteur_83',['moteur',['../guide-editeur.html#autotoc_md98',1,'Le problème : éditer un niveau sans (re)coder le moteur'],['../guide-maths.html',1,'Mathématiques du moteur'],['../spec-vision.html#autotoc_md383',1,'Objectifs produit (au-delà du moteur)']]],
  ['moteur_20pendant_20l_20entraînement_84',['Traces du moteur pendant l&apos;entraînement',['../manuel-mode-ia.html#autotoc_md686',1,'']]],
  ['mouvement_20—_20test_5fecs_5fmouvement_20cpp_204_85',['Ecs Mouvement — &lt;span class=&quot;tt&quot;&gt;test_ecs_mouvement.cpp&lt;/span&gt; (4)',['../cahiertest.html#autotoc_md29',1,'']]],
  ['mouvement_20_3a_20hmi_3a_3apreviousposition_20et_20le_20facteur_20d_20interpolation_86',['Interpoler le mouvement : &lt;span class=&quot;tt&quot;&gt;hmi::PreviousPosition&lt;/span&gt; et le facteur d&apos;interpolation',['../guide-rendu.html#autotoc_md225',1,'']]],
  ['mouvements_20et_20capacités_20du_20tableau_87',['Budget de mouvements et capacités du tableau',['../guide-niveaux.html#autotoc_md178',1,'']]],
  ['multi_20couches_88',['LOT-04 — Format de carte `version: 3`, multi-couches',['../lot-04.html',1,'lots']]],
  ['multi_20couches_20et_20placement_20d_20entités_89',['LOT-11 — Éditeur multi-couches et placement d&apos;entités',['../roadmap-010.html#lot-11',1,'']]],
  ['multiclassage_20compétences_20langues_90',['LOT-43 — Options de personnage : dons, multiclassage, compétences, langues',['../lot-43.html',1,'lots']]],
  ['multiclassage_20la_20règle_20qu_20il_20est_20le_20plus_20facile_20d_20implémenter_20de_20travers_91',['Le multiclassage, la règle qu&apos;il est le plus facile d&apos;implémenter de travers',['../lot-43.html#autotoc_md509',1,'']]],
  ['multimedia_92',['Provisionnement : Qt Multimedia',['../guide-audio.html#autotoc_md48',1,'']]],
  ['mur_20adjacent_20correction_20du_20balayage_20horizontal_93',['Le piège du mur adjacent (correction du balayage horizontal)',['../guide-physique.html#autotoc_md194',1,'']]],
  ['mvp_94',['MVP',['../spec-editeur.html#autotoc_md310',1,'5. Non-objectifs (éditeur, MVP)'],['../spec-gameplay.html#autotoc_md330',1,'Mécaniques aériennes avancées (au-delà du MVP)']]],
  ['mvp_20intégré_20à_20l_20éditeur_95',['4bis. Décors &amp;amp; pixel art (post-MVP, intégré à l&apos;éditeur)',['../spec-editeur.html#autotoc_md309',1,'']]]
];
