var searchData=
[
  ['sélection_20de_20niveau_0',['Progression et sélection de niveau',['../manuel-jouer.html#autotoc_md676',1,'']]],
  ['sélection_20de_20niveau_20et_20progression_20persistée_20lot_2059_20tache_2005_2006_1',['Sélection de niveau et progression persistée (&lt;span class=&quot;tt&quot;&gt;LOT-59&lt;/span&gt; TACHE-05/06)',['../guide-ecrans.html#autotoc_md83',1,'']]],
  ['séparés_20du_20canevas_2',['La palette et les outils : des panneaux Qt séparés du canevas',['../guide-editeur.html#autotoc_md104',1,'']]],
  ['séquence_3',['Fin de niveau et fin de séquence',['../guide-ecrans.html#autotoc_md82',1,'']]],
  ['séquence_20de_20niveaux_20donnée_20de_20contenu_20lot_2059_4',['Séquence de niveaux (donnée de contenu, &lt;span class=&quot;tt&quot;&gt;LOT-59&lt;/span&gt;)',['../guide-niveaux.html#autotoc_md181',1,'']]],
  ['séquencement_5',['4. Périmètre &amp;amp; séquencement',['../spec-decors.html#autotoc_md302',1,'']]],
  ['s_20auto_20teste_6',['Ce que le contrôle vérifie, et pourquoi il s&apos;auto-teste',['../lot-30.html#autotoc_md473',1,'']]],
  ['s_20auto_20teste_20faute_20de_20données_20à_20valider_7',['Le validateur s&apos;auto-teste, faute de données à valider',['../lot-32.html#autotoc_md480',1,'']]],
  ['s_20guide_20dessine_20ses_20titres_20deux_20fois_8',['Le &lt;em&gt;Player&apos;s Guide&lt;/em&gt; dessine ses titres deux fois',['../lot-36.html#autotoc_md498',1,'']]],
  ['s_20insère_20dans_20la_20boucle_9',['Où ça s&apos;insère dans la boucle',['../guide-ecrans.html#autotoc_md87',1,'']]],
  ['sa_20gouttière_20bouge_20d_20une_20page_20à_20l_20autre_10',['Sa gouttière bouge d&apos;une page à l&apos;autre',['../lot-36.html#autotoc_md497',1,'']]],
  ['sa_20graisse_20ment_11',['Le &lt;em&gt;Manuel des Joueurs&lt;/em&gt; est un scan, et sa graisse ment',['../lot-36.html#autotoc_md495',1,'']]],
  ['sa_20propre_20catégorie_12',['Chaque module a sa propre catégorie',['../guide-journalisation.html#autotoc_md149',1,'']]],
  ['sable_20dans_20l_20univers_20entier_13',['La cible : un bac à sable dans l&apos;univers entier',['../roadmap-010.html#autotoc_md543',1,'']]],
  ['sable_20de_20combat_14',['&lt;span class=&quot;tt&quot;&gt;LOT-50&lt;/span&gt; — Le Colisée : bac à sable de combat',['../roadmap-010.html#lot-50',1,'']]],
  ['saisi_15',['Le complément des &lt;em&gt;Basic Rules&lt;/em&gt; est attesté, pas saisi',['../lot-30.html#autotoc_md472',1,'']]],
  ['sait_20pas_20faire_16',['Ce qu&apos;une feuille de style ne sait pas faire',['../guide-design-ihm.html#autotoc_md74',1,'']]],
  ['salle_20»_17',['Mélanger plusieurs tailles de caméra dans un même niveau (mode « Par salle »)',['../manuel-partager-niveau.html#autotoc_md694',1,'']]],
  ['salles_20lot_20h_2032_18',['10. Niveaux à salles (&lt;span class=&quot;tt&quot;&gt;LOT-H-32&lt;/span&gt;)',['../spec-editeur.html#autotoc_md315',1,'']]],
  ['sans_20être_20produites_19',['9.2 Six mécaniques étaient consommées sans être produites',['../roadmap-010.html#autotoc_md563',1,'']]],
  ['sans_20dupliquer_20la_20logique_20de_20peinture_20_3a_20core_3a_3aleveldraft_3a_3apaintregion_20leveldraft_3a_3apaintregion_20',['Peindre par lot sans dupliquer la logique de peinture : &lt;a class=&quot;el&quot; href=&quot;classcore_1_1LevelDraft.html#a7fb667e044067f5e9bf16f747d3f5f8e&quot; title=&quot;core::LevelDraft::paintRegion&quot;&gt;LevelDraft::paintRegion&lt;/a&gt;',['../guide-editeur.html#autotoc_md107',1,'']]],
  ['sans_20jamais_20laisser_20de_20fichier_20tronqué_21',['Écrire un PNG sans jamais laisser de fichier tronqué',['../guide-atelier-pixel-art.html#autotoc_md34',1,'']]],
  ['sans_20les_20confondre_20avec_20f8_20lot_2051_22',['Le mode « définition des textures » : auditer les calques sans les confondre avec &lt;span class=&quot;tt&quot;&gt;F8&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;LOT-51&lt;/span&gt;)',['../guide-editeur.html#autotoc_md113',1,'']]],
  ['sans_20ligne_20de_20commande_23',['Créer et partager un niveau (sans ligne de commande)',['../manuel-partager-niveau.html',1,'manuel']]],
  ['sans_20pas_20de_20simulation_20et_20les_20entrées_24',['Les frames sans pas de simulation et les entrées',['../guide-boucle.html#autotoc_md57',1,'']]],
  ['sans_20perdre_20un_20pas_25',['Pause : suspendre sans perdre un pas',['../guide-ecrans.html#autotoc_md81',1,'']]],
  ['sans_20quitter_20l_20éditeur_26',['Essai immédiat : jouer sans quitter l&apos;éditeur',['../guide-editeur.html#autotoc_md109',1,'']]],
  ['sans_20re_20coder_20le_20moteur_27',['Le problème : éditer un niveau sans (re)coder le moteur',['../guide-editeur.html#autotoc_md98',1,'']]],
  ['saut_20et_20game_20feel_28',['4. Saut et &lt;em&gt;game feel&lt;/em&gt;',['../guide-physique.html#autotoc_md198',1,'']]],
  ['sauvegarde_29',['Validation &amp;amp; sauvegarde',['../manuel-mode-ia.html#autotoc_md687',1,'']]],
  ['sauvegarde_20riche_30',['LOT-17 — Sauvegarde riche',['../roadmap-010.html#lot-17',1,'']]],
  ['scène_20_3a_20hmi_3a_3abitmapfont_20et_20hmi_3a_3atextrenderer_20lot_2052_31',['Le texte dans la scène : &lt;span class=&quot;tt&quot;&gt;hmi::BitmapFont&lt;/span&gt; et &lt;span class=&quot;tt&quot;&gt;hmi::TextRenderer&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;LOT-52&lt;/span&gt;)',['../guide-rendu.html#autotoc_md233',1,'']]],
  ['scan_20et_20sa_20graisse_20ment_32',['Le &lt;em&gt;Manuel des Joueurs&lt;/em&gt; est un scan, et sa graisse ment',['../lot-36.html#autotoc_md495',1,'']]],
  ['schéma_20ne_20peut_20pas_20dire_33',['Ce que le schéma ne peut pas dire',['../lot-36.html#autotoc_md500',1,'']]],
  ['schéma_20ne_20peut_20pas_20dire_20et_20qui_20n_20est_20pas_20perdu_20pour_20autant_34',['Ce que le schéma ne peut pas dire, et qui n&apos;est pas perdu pour autant',['../lot-33.html#autotoc_md487',1,'']]],
  ['schémas_20de_20données_20rpg_35',['LOT-32 — Schémas de données RPG',['../lot-32.html',1,'lots']]],
  ['se_20fait_20sur_20la_20typographie_20pas_20sur_20des_20expressions_20régulières_36',['L&apos;extraction se fait sur la typographie, pas sur des expressions régulières',['../lot-33.html#autotoc_md485',1,'']]],
  ['se_20lier_20à_20qui_37',['Mécanismes : qui a le droit de se lier à qui',['../guide-editeur.html#autotoc_md100',1,'']]],
  ['se_20pose_20sous_20la_20valeur_20jamais_20dessus_38',['Un seuil de corps se pose sous la valeur, jamais dessus',['../lot-36.html#autotoc_md502',1,'']]],
  ['se_20tromper_39',['Les règles à ne pas se tromper',['../roadmap-010.html#autotoc_md622',1,'']]],
  ['se_20vérifie_20sur_20le_20diff_20pas_20sur_20l_20intention_40',['« Aucune valeur de règle dans le C++ » se vérifie sur le diff, pas sur l&apos;intention',['../lot-13.html#autotoc_md463',1,'']]],
  ['se_20voient_20pas_41',['Deux arrondis qui ne se voient pas',['../lot-12.html#autotoc_md454',1,'']]],
  ['se_20voit_20_3a_20le_20culling_20lot_2040_42',['Ne dessiner que ce qui se voit : le culling (&lt;span class=&quot;tt&quot;&gt;LOT-40&lt;/span&gt;)',['../guide-rendu.html#autotoc_md222',1,'']]],
  ['second_20axe_20_3a_20la_20mémoire_20de_20texture_20des_20plans_20lot_2069_43',['Le second axe : la mémoire de texture des plans (&lt;span class=&quot;tt&quot;&gt;LOT-69&lt;/span&gt;)',['../guide-rendu.html#autotoc_md243',1,'']]],
  ['second_20temps_20du_20lot_2065_44',['De la couverture à la profondeur (second temps du &lt;span class=&quot;tt&quot;&gt;LOT-65&lt;/span&gt;)',['../guide-niveaux.html#autotoc_md183',1,'']]],
  ['seconde_20source_20fusionnée_20en_20lecture_20ex_20ctrl_20002_20lot_2020_45',['La manette : une seconde source, fusionnée en lecture (EX-CTRL-002, LOT-20)',['../guide-entrees.html#autotoc_md127',1,'']]],
  ['secousse_20d_20écran_20hmi_3a_3acamera2d_46',['Le rendu (&lt;span class=&quot;tt&quot;&gt;hmi::ParticleRenderer&lt;/span&gt;) et la secousse d&apos;écran (&lt;span class=&quot;tt&quot;&gt;hmi::Camera2D&lt;/span&gt;)',['../guide-rendu.html#autotoc_md238',1,'']]],
  ['secousse_20d_20écran_20lot_2053_47',['Particules et secousse d&apos;écran (&lt;span class=&quot;tt&quot;&gt;LOT-53&lt;/span&gt;)',['../guide-rendu.html#autotoc_md235',1,'']]],
  ['segment_20orienté_20liens_20de_20mécanismes_20lot_2037_48',['&lt;a class=&quot;el&quot; href=&quot;structhmi_1_1LineQuad.html&quot; title=&quot;hmi::LineQuad&quot;&gt;LineQuad&lt;/a&gt; : un segment orienté (liens de mécanismes, &lt;span class=&quot;tt&quot;&gt;LOT-37&lt;/span&gt;)',['../guide-rendu.html#autotoc_md214',1,'']]],
  ['ses_20fichiers_20de_20niveaux_49',['Gérer ses fichiers de niveaux',['../guide-editeur.html#autotoc_md119',1,'']]],
  ['ses_20titres_20deux_20fois_50',['Le &lt;em&gt;Player&apos;s Guide&lt;/em&gt; dessine ses titres deux fois',['../lot-36.html#autotoc_md498',1,'']]],
  ['set_20core_3a_3acomponentpool_51',['Le stockage : sparse set (core::ComponentPool&amp;lt;T&amp;gt;)',['../guide-ecs.html#autotoc_md92',1,'']]],
  ['seuil_20de_20corps_20se_20pose_20sous_20la_20valeur_20jamais_20dessus_52',['Un seuil de corps se pose sous la valeur, jamais dessus',['../lot-36.html#autotoc_md502',1,'']]],
  ['seule_20cible_20_3a_20l_20application_20qt_53',['Une seule cible : l&apos;application Qt',['../guide-ihm-qt.html#autotoc_md133',1,'']]],
  ['seule_20hmilib_20»_54',['Le découpage retenu — et pourquoi il n&apos;est pas « une seule &lt;span class=&quot;tt&quot;&gt;HmiLib&lt;/span&gt; »',['../lot-02.html#autotoc_md399',1,'']]],
  ['seule_20paire_20annuler_20refaire_20deux_20cibles_55',['Une seule paire Annuler/Refaire, deux cibles',['../guide-atelier-pixel-art.html#autotoc_md41',1,'']]],
  ['seule_20source_20deux_20portées_20étanches_56',['Les jetons : une seule source, deux portées étanches',['../guide-design-ihm.html#autotoc_md61',1,'']]],
  ['seulement_20là_20où_20la_20caméra_20défile_57',['Parallaxe : portée par le plan, bornée, et seulement là où la caméra défile',['../guide-rendu.html#autotoc_md229',1,'']]],
  ['seulement_20l_20état_58',['Détecter les fronts, pas seulement l&apos;état',['../guide-entrees.html#autotoc_md123',1,'']]],
  ['seulement_20l_20arrivée_59',['La solution : tester tout le trajet, pas seulement l&apos;arrivée',['../guide-physique.html#autotoc_md187',1,'']]],
  ['shaders_20et_20échantillonnage_20nearest_60',['Sommets, shaders, et échantillonnage &lt;em&gt;nearest&lt;/em&gt;',['../guide-rendu.html#autotoc_md213',1,'']]],
  ['signaux_61',['Qui déclenche les transitions : les signaux',['../guide-ecrans.html#autotoc_md79',1,'']]],
  ['simples_20dans_20le_20cpp_62',['Doxygen dans le header, commentaires simples // dans le .cpp',['../spec-conventions.html#autotoc_md290',1,'']]],
  ['simulation_63',['Conséquence pratique pour tout le code de simulation',['../guide-boucle.html#autotoc_md58',1,'']]],
  ['simulation_20—_20test_5fboucle_5fsimulation_20cpp_202_64',['Boucle Simulation — &lt;span class=&quot;tt&quot;&gt;test_boucle_simulation.cpp&lt;/span&gt; (2)',['../cahiertest.html#autotoc_md28',1,'']]],
  ['simulation_20↔_20rendu_65',['4. Frontière simulation ↔ rendu',['../spec-architecture.html#autotoc_md253',1,'']]],
  ['simulation_20et_20les_20entrées_66',['Les frames sans pas de simulation et les entrées',['../guide-boucle.html#autotoc_md57',1,'']]],
  ['singleton_20joueur_67',['&lt;span class=&quot;tt&quot;&gt;CharacterSheet&lt;/span&gt; est un objet autonome, jamais un singleton joueur',['../lot-13.html#autotoc_md464',1,'']]],
  ['sinks_20_3a_20où_20finissent_20les_20messages_68',['Les sinks : où finissent les messages',['../guide-journalisation.html#autotoc_md147',1,'']]],
  ['sinks_20différents_20en_20développement_20et_20en_20release_69',['Bootstrap réel : sinks différents en développement et en Release',['../guide-journalisation.html#autotoc_md153',1,'']]],
  ['six_20mécaniques_20étaient_20consommées_20sans_20être_20produites_70',['9.2 Six mécaniques étaient consommées sans être produites',['../roadmap-010.html#autotoc_md563',1,'']]],
  ['slice_71',['slice',['../spec-vision.html#autotoc_md384',1,'Hors périmètre (&lt;em&gt;vertical slice&lt;/em&gt;)'],['../roadmap-010.html#autotoc_md551',1,'Le chemin critique jusqu&apos;au &lt;em&gt;vertical slice&lt;/em&gt;'],['../roadmap-010.html#lot-27',1,'LOT-27 — Contenu du &lt;em&gt;vertical slice&lt;/em&gt;'],['../spec-vision.html#autotoc_md382',1,'Objectifs (&lt;em&gt;vertical slice&lt;/em&gt;)']]],
  ['slide_72',['6. Wall jump et wall slide',['../guide-physique.html#autotoc_md200',1,'']]],
  ['socle_20_3a_20hmi_3a_3aaudioengine_73',['Le socle : &lt;span class=&quot;tt&quot;&gt;hmi::AudioEngine&lt;/span&gt;',['../guide-audio.html#autotoc_md44',1,'']]],
  ['socle_20applicatif_74',['1. Socle applicatif',['../spec-interface-ihm.html#autotoc_md341',1,'']]],
  ['socle_20applicatif_20viewport_20direct3d_2011_75',['IHM Qt (refonte) — socle applicatif &amp;amp; viewport Direct3D 11',['../guide-ihm-qt.html',1,'guide']]],
  ['socle_20de_20chargement_20de_20données_76',['LOT-79 — Socle de chargement de données',['../lot-79.html',1,'lots']]],
  ['socle_20de_20classe_20et_20le_20guerrier_20comme_20preuve_77',['&lt;span class=&quot;tt&quot;&gt;LOT-47&lt;/span&gt; — Socle de classe, et le guerrier comme preuve',['../roadmap-010.html#lot-47',1,'']]],
  ['socle_20technique_20tient_20mais_20trois_20préconditions_20manquent_78',['9.4 Le socle technique tient, mais trois préconditions manquent',['../roadmap-010.html#autotoc_md565',1,'']]],
  ['solide_79',['Pourquoi une pente (ou un arrondi) n&apos;est jamais solide',['../guide-physique.html#autotoc_md192',1,'']]],
  ['solution_20_3a_20tester_20tout_20le_20trajet_20pas_20seulement_20l_20arrivée_80',['La solution : tester tout le trajet, pas seulement l&apos;arrivée',['../guide-physique.html#autotoc_md187',1,'']]],
  ['solveur_20ia_81',['Solveur IA',['../spec-ia.html',1,'specifications']]],
  ['sombre_82',['Thème clair/sombre',['../guide-design-ihm.html#autotoc_md66',1,'']]],
  ['sommeil_83',['3. Licences : contrainte en sommeil',['../roadmap-010.html#autotoc_md537',1,'']]],
  ['sommets_20shaders_20et_20échantillonnage_20nearest_84',['Sommets, shaders, et échantillonnage &lt;em&gt;nearest&lt;/em&gt;',['../guide-rendu.html#autotoc_md213',1,'']]],
  ['son_20repli_20procédural_85',['Le pipeline de textures depuis fichiers, et son repli procédural',['../guide-rendu.html#autotoc_md216',1,'']]],
  ['sont_20fantômes_20—_20le_20lint_20le_20dit_20désormais_86',['9.1 Cinq familles d&apos;exigences sont fantômes — le lint le dit désormais',['../roadmap-010.html#autotoc_md562',1,'']]],
  ['sont_20livrés_20provisoires_20et_20le_20disent_87',['Les dons sont livrés provisoires, et le disent',['../lot-43.html#autotoc_md510',1,'']]],
  ['sont_20provisoires_20et_20le_20déclarent_88',['Les quatre classes sont provisoires, et le déclarent',['../lot-36.html#autotoc_md501',1,'']]],
  ['sortir_20de_20l_20identité_20pixel_20art_89',['&lt;span class=&quot;tt&quot;&gt;LOT-66&lt;/span&gt; — Charte visuelle : sortir de l&apos;identité pixel art',['../roadmap-010.html#lot-66',1,'']]],
  ['sorts_90',['6. Sorts',['../spec-rpg.html#autotoc_md377',1,'']]],
  ['sorts_20et_20états_91',['&lt;span class=&quot;tt&quot;&gt;LOT-35&lt;/span&gt; — Sorts et états',['../roadmap-010.html#lot-35',1,'']]],
  ['sorts_20et_20capacités_20de_20classe_92',['LOT-25 — Sorts et capacités de classe',['../roadmap-010.html#lot-25',1,'']]],
  ['source_93',['Chemins complets depuis Source/',['../spec-conventions.html#autotoc_md283',1,'']]],
  ['source_20deux_20portées_20étanches_94',['Les jetons : une seule source, deux portées étanches',['../guide-design-ihm.html#autotoc_md61',1,'']]],
  ['source_20elements_20assets_20_3a_20convention_20et_20régénération_95',['&lt;span class=&quot;tt&quot;&gt;Source/Elements/Assets/&lt;/span&gt; : convention et régénération',['../guide-rendu.html#autotoc_md217',1,'']]],
  ['source_20est_20la_20moitié_20du_20travail_96',['Le choix de la source est la moitié du travail',['../lot-43.html#autotoc_md507',1,'']]],
  ['source_20fusionnée_20en_20lecture_20ex_20ctrl_20002_20lot_2020_97',['La manette : une seconde source, fusionnée en lecture (EX-CTRL-002, LOT-20)',['../guide-entrees.html#autotoc_md127',1,'']]],
  ['source_20test_20unit_20hmi_20graphics_20test_5frender_5fbudget_20cpp_98',['Le test de non-régression du volume (&lt;span class=&quot;tt&quot;&gt;Source/Test/Unit/HMI/Graphics/test_render_budget.cpp&lt;/span&gt;)',['../guide-rendu.html#autotoc_md242',1,'']]],
  ['sous_20la_20valeur_20jamais_20dessus_99',['Un seuil de corps se pose sous la valeur, jamais dessus',['../lot-36.html#autotoc_md502',1,'']]],
  ['souvent_20oublié_100',['Le critère qui est souvent oublié',['../roadmap-010.html#autotoc_md639',1,'']]],
  ['spécification_101',['LOT-77 — La moitié RPG de la spécification',['../lot-77.html',1,'lots']]],
  ['spécifications_102',['Spécifications',['../specifications.html',1,'index']]],
  ['sparse_20set_20core_3a_3acomponentpool_103',['Le stockage : sparse set (core::ComponentPool&amp;lt;T&amp;gt;)',['../guide-ecs.html#autotoc_md92',1,'']]],
  ['spirale_20de_20la_20mort_20»_104',['La « spirale de la mort »',['../guide-boucle.html#autotoc_md55',1,'']]],
  ['sprite_20à_20la_20fois_105',['Pourquoi « batcher » plutôt que dessiner un sprite à la fois',['../guide-rendu.html#autotoc_md211',1,'']]],
  ['spritequad_20_3a_20un_20rectangle_20texturé_106',['&lt;a class=&quot;el&quot; href=&quot;structhmi_1_1SpriteQuad.html&quot; title=&quot;hmi::SpriteQuad&quot;&gt;SpriteQuad&lt;/a&gt; : un rectangle texturé',['../guide-rendu.html#autotoc_md212',1,'']]],
  ['sprites_20_3a_20hmi_3a_3aspritebatch_20hmi_3a_3aspritebatch_107',['Le pipeline de dessin de sprites : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1SpriteBatch.html&quot; title=&quot;hmi::SpriteBatch&quot;&gt;hmi::SpriteBatch&lt;/a&gt;',['../guide-rendu.html#autotoc_md210',1,'']]],
  ['spritesheet_20chargé_20depuis_20un_20fichier_108',['&lt;a class=&quot;el&quot; href=&quot;classhmi_1_1TextureAtlas.html&quot; title=&quot;hmi::TextureAtlas&quot;&gt;hmi::TextureAtlas&lt;/a&gt; : un spritesheet, chargé depuis un fichier',['../guide-rendu.html#autotoc_md215',1,'']]],
  ['spritesheet_20externe_20et_20découplage_20image_20hitbox_109',['&lt;span class=&quot;tt&quot;&gt;LOT-48&lt;/span&gt; : spritesheet externe et découplage image/hitbox',['../guide-rendu.html#autotoc_md219',1,'']]],
  ['standard_110',['1. Langage &amp;amp; standard',['../spec-conventions.html#autotoc_md279',1,'']]],
  ['stats_20csv_111',['Le fichier &lt;span class=&quot;tt&quot;&gt;stats.csv&lt;/span&gt;',['../manuel-mode-ia.html#autotoc_md685',1,'']]],
  ['stockage_20_3a_20sparse_20set_20core_3a_3acomponentpool_112',['Le stockage : sparse set (core::ComponentPool&amp;lt;T&amp;gt;)',['../guide-ecs.html#autotoc_md92',1,'']]],
  ['stricte_20est_20dangereuse_113',['Comparaison flottante : pourquoi l&apos;égalité stricte est dangereuse',['../guide-maths.html#autotoc_md161',1,'']]],
  ['structurée_114',['Une barre d&apos;état structurée',['../guide-design-ihm.html#autotoc_md68',1,'']]],
  ['structure_20ce_20lot_115',['La décision qui structure ce lot',['../roadmap-010.html#autotoc_md604',1,'']]],
  ['style_20ne_20sait_20pas_20faire_116',['Ce qu&apos;une feuille de style ne sait pas faire',['../guide-design-ihm.html#autotoc_md74',1,'']]],
  ['suit_20le_20joueur_117',['Choisir comment la caméra suit le joueur',['../manuel-partager-niveau.html#autotoc_md693',1,'']]],
  ['suite_118',['Où lire la suite',['../roadmap-010.html#autotoc_md548',1,'']]],
  ['suivent_20l_20outil_119',['Des panneaux groupés, et qui suivent l&apos;outil',['../guide-design-ihm.html#autotoc_md69',1,'']]],
  ['suivi_20de_20pente_20et_20d_20arrondi_20ex_20gp_20003_20ex_20gp_20004_120',['2. Suivi de pente et d&apos;arrondi (EX-GP-003, EX-GP-004)',['../guide-physique.html#autotoc_md191',1,'']]],
  ['suivi_20réglable_20ex_20lvl_20007_20ex_20ren_20017_121',['Mélanger plusieurs tailles de caméra : zones dessinées à la main et taille de suivi réglable (&lt;span class=&quot;tt&quot;&gt;EX-LVL-007&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;EX-REN-017&lt;/span&gt;)',['../guide-rendu.html#autotoc_md209',1,'']]],
  ['suppression_20_3a_20swap_20and_20pop_122',['Ajout et suppression : &lt;em&gt;swap-and-pop&lt;/em&gt;',['../guide-ecs.html#autotoc_md93',1,'']]],
  ['supprimé_123',['Supprimé',['../lot-01.html#autotoc_md391',1,'']]],
  ['sur_20des_20expressions_20régulières_124',['L&apos;extraction se fait sur la typographie, pas sur des expressions régulières',['../lot-33.html#autotoc_md485',1,'']]],
  ['sur_20l_20état_20du_20dépôt_125',['9. Ce que l&apos;audit a révélé sur l&apos;état du dépôt',['../roadmap-010.html#autotoc_md561',1,'']]],
  ['sur_20l_20intention_126',['« Aucune valeur de règle dans le C++ » se vérifie sur le diff, pas sur l&apos;intention',['../lot-13.html#autotoc_md463',1,'']]],
  ['sur_20la_20typographie_20pas_20sur_20des_20expressions_20régulières_127',['L&apos;extraction se fait sur la typographie, pas sur des expressions régulières',['../lot-33.html#autotoc_md485',1,'']]],
  ['sur_20le_20diff_20pas_20sur_20l_20intention_128',['« Aucune valeur de règle dans le C++ » se vérifie sur le diff, pas sur l&apos;intention',['../lot-13.html#autotoc_md463',1,'']]],
  ['sur_20un_20tampon_20de_20pixels_129',['Les outils : des fonctions pures sur un tampon de pixels',['../guide-atelier-pixel-art.html#autotoc_md35',1,'']]],
  ['surface_20de_20dessin_20_3a_20le_20viewport_20qt_20hmi_3a_3agameviewport_130',['La surface de dessin : le viewport Qt (&lt;span class=&quot;tt&quot;&gt;hmi::GameViewport&lt;/span&gt;)',['../guide-rendu.html#autotoc_md205',1,'']]],
  ['surfaces_131',['Les commandes : une définition, trois surfaces',['../guide-design-ihm.html#autotoc_md64',1,'']]],
  ['surfaces_20et_20espaces_20de_20travail_20lot_2068_132',['Hiérarchie des surfaces, et espaces de travail (LOT-68)',['../guide-design-ihm.html#autotoc_md75',1,'']]],
  ['suspendre_20sans_20perdre_20un_20pas_133',['Pause : suspendre sans perdre un pas',['../guide-ecrans.html#autotoc_md81',1,'']]],
  ['swap_20and_20pop_134',['Ajout et suppression : &lt;em&gt;swap-and-pop&lt;/em&gt;',['../guide-ecs.html#autotoc_md93',1,'']]],
  ['swap_20chain_20back_20buffer_135',['Vocabulaire de base : GPU, swap chain, back buffer',['../guide-rendu.html#autotoc_md203',1,'']]],
  ['swept_20aabb_136',['1. Collision par balayage continu (swept AABB)',['../guide-physique.html#autotoc_md185',1,'']]],
  ['système_202_137',['Tests système (2)',['../cahiertest.html#autotoc_md31',1,'']]],
  ['système_20de_20design_138',['Pourquoi un système de design',['../guide-design-ihm.html#autotoc_md60',1,'']]],
  ['système_20de_20design_20et_20architecture_20de_20l_20information_139',['Système de design et architecture de l&apos;information',['../guide-design-ihm.html',1,'guide']]],
  ['système_20de_20design_20et_20habillage_20lot_20h_2056_140',['6. Système de design et habillage (LOT-H-56)',['../spec-interface-ihm.html#autotoc_md346',1,'']]],
  ['systèmes_141',['systèmes',['../spec-architecture.html#autotoc_md257',1,'8. Communication inter-systèmes'],['../guide-ecs.html',1,'ECS : entités, composants, systèmes']]],
  ['systèmes_20de_20coordonnées_20à_20ne_20pas_20confondre_142',['Deux systèmes de coordonnées à ne pas confondre',['../guide-niveaux.html#autotoc_md164',1,'']]],
  ['systèmes_20et_20l_20ordre_20d_20exécution_143',['Les systèmes et l&apos;ordre d&apos;exécution',['../guide-ecs.html#autotoc_md96',1,'']]]
];
