var searchData=
[
  ['bac_20à_20sable_20dans_20l_20univers_20entier_0',['La cible : un bac à sable dans l&apos;univers entier',['../roadmap.html#autotoc_md790',1,'']]],
  ['bac_20à_20sable_20de_20combat_1',['LOT-50 — Le Colisée : bac à sable de combat',['../lot-50.html',1,'lots']]],
  ['bac_20à_20sable_20de_20tanares_2',['Feuille de route — le bac à sable de Tanares',['../roadmap.html',1,'lots']]],
  ['back_20buffer_3',['Vocabulaire de base : GPU, swap chain, back buffer',['../guide-rendu.html#autotoc_md156',1,'']]],
  ['bandeau_20sur_20les_20six_20écrans_4',['Le titre devient son bandeau, sur les six écrans',['../lot-76.html#autotoc_md621',1,'']]],
  ['bandeaux_5',['Plaques et bandeaux',['../lot-87-cahier-assets.html#lot-87-cahier-plate',1,'']]],
  ['barre_20d_20état_20structurée_6',['Une barre d&apos;état structurée',['../guide-design-ihm.html#autotoc_md68',1,'']]],
  ['barre_20d_20outils_20n_20est_20pas_20un_20menu_7',['La barre d&apos;outils n&apos;est pas un menu',['../guide-design-ihm.html#autotoc_md73',1,'']]],
  ['bascule_8',['1. Bascule',['../spec-combat.html#autotoc_md191',1,'']]],
  ['bascule_20exploration_20↔_20combat_9',['LOT-18 — Bascule exploration ↔ combat',['../lot-18.html',1,'lots']]],
  ['base_10',['LOT-33 — Bestiaire de base',['../lot-33.html',1,'lots']]],
  ['base_20_3a_20gpu_20swap_20chain_20back_20buffer_11',['Vocabulaire de base : GPU, swap chain, back buffer',['../guide-rendu.html#autotoc_md156',1,'']]],
  ['basic_20rules_20est_20attesté_20pas_20saisi_12',['Le complément des &lt;em&gt;Basic Rules&lt;/em&gt; est attesté, pas saisi',['../lot-30.html#autotoc_md497',1,'']]],
  ['batcher_20»_20plutôt_20que_20dessiner_20un_20sprite_20à_20la_20fois_13',['Pourquoi « batcher » plutôt que dessiner un sprite à la fois',['../guide-rendu.html#autotoc_md162',1,'']]],
  ['bestiaire_20de_20base_14',['LOT-33 — Bestiaire de base',['../lot-33.html',1,'lots']]],
  ['bestiaire_20depuis_20le_20texte_20seul_15',['LOT-93 — Atelier des monstres : les figurines du bestiaire, depuis le texte seul',['../lot-93.html',1,'lots']]],
  ['bestiaire_20du_20srd_20lot_2033_16',['Le bestiaire du SRD (&lt;span class=&quot;tt&quot;&gt;LOT-33&lt;/span&gt;)',['../lot-93.html#autotoc_md751',1,'']]],
  ['bibliothèque_20de_20composants_17',['La bibliothèque de composants',['../guide-conception-qds.html#autotoc_md54',1,'']]],
  ['bibliothèque_20hmilib_18',['LOT-02 — Bibliothèque `HmiLib`',['../lot-02.html',1,'lots']]],
  ['bien_20plus_20large_20qu_20estimé_19',['9.5 La collision de numéros est bloquante, et bien plus large qu&apos;estimé',['../roadmap.html#autotoc_md814',1,'']]],
  ['bilingue_20',['LOT-30 — Chaîne d&apos;extraction du corpus et lexique bilingue',['../lot-30.html',1,'lots']]],
  ['binaires_21',['Pourquoi deux binaires',['../guide-ihm-qt.html#autotoc_md115',1,'']]],
  ['bloc_20a_22',['3. Le style commun v1 (étape E2, bloc A)',['../lot-91-poc.html#autotoc_md722',1,'']]],
  ['blocs_23',['Les blocs',['../lot-93.html#autotoc_md749',1,'']]],
  ['blocs_20de_20tanares_20lot_2046_20relevé_20provisoire_24',['Les blocs de Tanares (&lt;span class=&quot;tt&quot;&gt;LOT-46&lt;/span&gt;, relevé provisoire)',['../lot-93.html#autotoc_md752',1,'']]],
  ['bloquante_20et_20bien_20plus_20large_20qu_20estimé_25',['9.5 La collision de numéros est bloquante, et bien plus large qu&apos;estimé',['../roadmap.html#autotoc_md814',1,'']]],
  ['bloque_26',['Couches : ce qu&apos;on voit n&apos;est pas ce qui bloque',['../guide-niveaux.html#autotoc_md149',1,'']]],
  ['bonnes_20pratiques_27',['7. Bonnes pratiques',['../spec-conventions.html#autotoc_md222',1,'']]],
  ['booléen_28',['Un ennemi vaincu est un drapeau de monde, pas un booléen',['../lot-18.html#autotoc_md426',1,'']]],
  ['bootstrap_20réel_20_3a_20sinks_20différents_20en_20développement_20et_20en_20release_29',['Bootstrap réel : sinks différents en développement et en Release',['../guide-journalisation.html#autotoc_md134',1,'']]],
  ['bord_20assumé_30',['Effet de bord assumé',['../lot-37.html#autotoc_md548',1,'']]],
  ['boucle_31',['Où ça s&apos;insère dans la boucle',['../guide-ecrans.html#autotoc_md80',1,'']]],
  ['boucle_20de_20gameplay_32',['Boucle de gameplay',['../spec-vision.html#autotoc_md296',1,'']]],
  ['boucle_20de_20jeu_33',['boucle de jeu',['../guide-ecrans.html',1,'Écrans, navigation et boucle de jeu'],['../guide-boucle.html#autotoc_md36',1,'Qu&apos;est-ce qu&apos;une boucle de jeu ?']]],
  ['boucle_20de_20jeu_20et_20pas_20de_20temps_20fixe_34',['Boucle de jeu et pas de temps fixe',['../guide-boucle.html',1,'guide']]],
  ['boucle_20temps_35',['3. Boucle &amp;amp; temps',['../spec-rendu-technique.html#autotoc_md281',1,'']]],
  ['bouge_20d_20une_20page_20à_20l_20autre_36',['Sa gouttière bouge d&apos;une page à l&apos;autre',['../lot-36.html#autotoc_md532',1,'']]],
  ['boutons_37',['Boutons',['../lot-87-cahier-assets.html#lot-87-cahier-button',1,'']]],
  ['brancher_38',['Comment on retrouve ce qu&apos;il reste à brancher',['../classhmi_1_1PendingData.html#autotoc_md977',1,'']]],
  ['bref_39',['En bref',['../index.html#autotoc_md1',1,'']]],
  ['briques_20de_20la_20charte_20v2_40',['T2.7 — Les briques de la charte v2',['../lot-87.html#autotoc_md676',1,'']]],
  ['brute_41',['Pourquoi des propriétés nommées plutôt que la table brute',['../classhmi_1_1CharacterSheetModel.html#autotoc_md965',1,'']]],
  ['budget_20s_20arrondit_20à_20la_20case_20inférieure_42',['Le budget s&apos;arrondit à la case inférieure',['../lot-19.html#autotoc_md440',1,'']]],
  ['buffer_43',['Vocabulaire de base : GPU, swap chain, back buffer',['../guide-rendu.html#autotoc_md156',1,'']]],
  ['build_20dépendances_44',['6. Build &amp;amp; dépendances',['../spec-exigences.html#autotoc_md242',1,'']]],
  ['butin_20marchands_20économie_45',['LOT-26 — Butin, marchands, économie',['../roadmap.html#lot-26',1,'']]]
];
