var searchData=
[
  ['aériennes_20avancées_20au_20delà_20du_20mvp_0',['Mécaniques aériennes avancées (au-delà du MVP)',['../spec-gameplay.html#autotoc_md341',1,'']]],
  ['a_20été_20fait_1',['T1.2 à T1.4 — Ce qui a été fait',['../lot-87.html#autotoc_md670',1,'']]],
  ['a_20été_20faite_2',['Comment la classification a été faite',['../lot-78.html#autotoc_md639',1,'']]],
  ['a_20été_20retiré_20du_20code_3',['Ce qui a été retiré du code',['../lot-67.html#autotoc_md612',1,'']]],
  ['a_20appris_4',['4. Ce que l&apos;extraction a appris',['../roadmap.html#autotoc_md719',1,'']]],
  ['a_20arrêtée_5',['Ce qui l&apos;a arrêtée',['../lot-38.html#autotoc_md575',1,'']]],
  ['a_20changé_20et_20pourquoi_6',['Ce qui a changé, et pourquoi',['../spec-interface-ihm.html#autotoc_md361',1,'']]],
  ['a_20démenti_7',['Ce que la réalisation a vérifié, et ce qu&apos;elle a démenti',['../lot-30.html#autotoc_md517',1,'']]],
  ['a_20le_20droit_20de_20se_20lier_20à_20qui_8',['Mécanismes : qui a le droit de se lier à qui',['../guide-editeur.html#autotoc_md114',1,'']]],
  ['a_20mis_20au_20jour_9',['Trois défauts du corpus que ce lot a mis au jour',['../lot-43.html#autotoc_md593',1,'']]],
  ['a_20pas_20écrit_20de_20classdefinition_20_3a_20elle_20existait_20déjà_10',['Le lot n&apos;a pas écrit de &lt;span class=&quot;tt&quot;&gt;ClassDefinition&lt;/span&gt; : elle existait déjà',['../lot-13.html#autotoc_md477',1,'']]],
  ['a_20pas_20tenu_11',['Ce que la feuille de route supposait, et qui n&apos;a pas tenu',['../lot-19.html#autotoc_md504',1,'']]],
  ['a_20révélé_12',['Ce que l&apos;ordre a révélé',['../roadmap.html#autotoc_md732',1,'']]],
  ['a_20révélé_20sur_20l_20état_20du_20dépôt_13',['9. Ce que l&apos;audit a révélé sur l&apos;état du dépôt',['../roadmap.html#autotoc_md744',1,'']]],
  ['a_20retiré_14',['a retiré',['../guide-ecrans.html#autotoc_md100',1,'Ce que le &lt;span class=&quot;tt&quot;&gt;LOT-67&lt;/span&gt; a retiré'],['../guide-niveaux.html#autotoc_md193',1,'Ce que le &lt;span class=&quot;tt&quot;&gt;LOT-67&lt;/span&gt; a retiré']]],
  ['a_20sa_20propre_20catégorie_15',['Chaque module a sa propre catégorie',['../guide-journalisation.html#autotoc_md161',1,'']]],
  ['a_20tranché_16',['a tranché',['../lot-87-cahier-assets.html#autotoc_md659',1,'Ce que la lecture des maquettes a tranché'],['../lot-04.html#autotoc_md431',1,'Ce que la réalisation a tranché'],['../lot-05.html#autotoc_md438',1,'Ce que la réalisation a tranché'],['../lot-06.html#autotoc_md445',1,'Ce que la réalisation a tranché'],['../lot-08.html#autotoc_md457',1,'Ce que la réalisation a tranché'],['../lot-32.html#autotoc_md525',1,'Ce que la réalisation a tranché'],['../lot-79.html#autotoc_md645',1,'Ce que la réalisation a tranché'],['../lot-77.html#autotoc_md635',1,'Ce que la rédaction a tranché']]],
  ['a_20vérifié_20et_20ce_20qu_20elle_20a_20démenti_17',['Ce que la réalisation a vérifié, et ce qu&apos;elle a démenti',['../lot-30.html#autotoc_md517',1,'']]],
  ['aabb_18',['1. Collision par balayage continu (swept AABB)',['../guide-physique.html#autotoc_md195',1,'']]],
  ['aabb_20_3a_20la_20boîte_20englobante_20alignée_20aux_20axes_19',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Aabb.html&quot; title=&quot;core::Aabb&quot;&gt;Aabb&lt;/a&gt; : la boîte englobante alignée aux axes',['../guide-maths.html#autotoc_md171',1,'']]],
  ['abord_20le_20widget_20ensuite_20',['Le canevas : la géométrie d&apos;abord, le widget ensuite',['../guide-atelier-pixel-art.html#autotoc_md40',1,'']]],
  ['abstraction_20de_20rendu_21',['6. Abstraction de rendu',['../spec-architecture.html#autotoc_md265',1,'']]],
  ['accès_20au_20gpu_20pas_20un_20changement_20de_20cible_22',['QRhi : une couche d&apos;accès au GPU, pas un changement de cible',['../guide-rendu.html#autotoc_md214',1,'']]],
  ['accentué_20reste_20tracé_20à_20l_20ancienne_20et_20ce_20n_20est_20pas_20un_20oubli_23',['L&apos;accentué reste tracé à l&apos;ancienne, et ce n&apos;est pas un oubli',['../lot-76.html#autotoc_md629',1,'']]],
  ['acceptation_24',['acceptation',['../lot-01.html#autotoc_md411',1,'Critères d&apos;acceptation'],['../lot-02.html#autotoc_md418',1,'Critères d&apos;acceptation'],['../lot-03.html#autotoc_md424',1,'Critères d&apos;acceptation'],['../lot-04.html#autotoc_md430',1,'Critères d&apos;acceptation'],['../lot-05.html#autotoc_md437',1,'Critères d&apos;acceptation'],['../lot-06.html#autotoc_md444',1,'Critères d&apos;acceptation'],['../lot-07.html#autotoc_md451',1,'Critères d&apos;acceptation'],['../lot-08.html#autotoc_md456',1,'Critères d&apos;acceptation'],['../lot-10.html#autotoc_md465',1,'Critères d&apos;acceptation'],['../lot-12.html#autotoc_md474',1,'Critères d&apos;acceptation'],['../lot-13.html#autotoc_md483',1,'Critères d&apos;acceptation'],['../lot-14.html#autotoc_md490',1,'Critères d&apos;acceptation'],['../lot-18.html#autotoc_md501',1,'Critères d&apos;acceptation'],['../lot-19.html#autotoc_md513',1,'Critères d&apos;acceptation'],['../lot-30.html#autotoc_md521',1,'Critères d&apos;acceptation'],['../lot-32.html#autotoc_md528',1,'Critères d&apos;acceptation'],['../lot-33.html#autotoc_md537',1,'Critères d&apos;acceptation'],['../lot-34.html#autotoc_md547',1,'Critères d&apos;acceptation'],['../lot-36.html#autotoc_md560',1,'Critères d&apos;acceptation'],['../lot-38.html#autotoc_md581',1,'Critères d&apos;acceptation'],['../lot-39.html#autotoc_md589',1,'Critères d&apos;acceptation'],['../lot-43.html#autotoc_md597',1,'Critères d&apos;acceptation'],['../lot-66.html#autotoc_md608',1,'Critères d&apos;acceptation'],['../lot-67.html#autotoc_md616',1,'Critères d&apos;acceptation'],['../lot-68.html#autotoc_md624',1,'Critères d&apos;acceptation'],['../lot-76.html#autotoc_md632',1,'Critères d&apos;acceptation'],['../lot-77.html#autotoc_md636',1,'Critères d&apos;acceptation'],['../lot-78.html#autotoc_md641',1,'Critères d&apos;acceptation'],['../lot-79.html#autotoc_md646',1,'Critères d&apos;acceptation'],['../lot-86.html#autotoc_md655',1,'Critères d&apos;acceptation'],['../roadmap.html#autotoc_md759',1,'Critères d&apos;acceptation'],['../roadmap.html#autotoc_md766',1,'Critères d&apos;acceptation'],['../roadmap.html#autotoc_md771',1,'Critères d&apos;acceptation'],['../roadmap.html#autotoc_md776',1,'Critères d&apos;acceptation'],['../roadmap.html#autotoc_md782',1,'Critères d&apos;acceptation'],['../roadmap.html#autotoc_md787',1,'Critères d&apos;acceptation'],['../roadmap.html#autotoc_md794',1,'Critères d&apos;acceptation'],['../roadmap.html#autotoc_md799',1,'Critères d&apos;acceptation'],['../roadmap.html#autotoc_md805',1,'Critères d&apos;acceptation'],['../roadmap.html#autotoc_md810',1,'Critères d&apos;acceptation'],['../roadmap.html#autotoc_md815',1,'Critères d&apos;acceptation'],['../roadmap.html#autotoc_md820',1,'Critères d&apos;acceptation'],['../roadmap.html#autotoc_md825',1,'Critères d&apos;acceptation'],['../roadmap.html#autotoc_md834',1,'Critères d&apos;acceptation'],['../roadmap.html#autotoc_md840',1,'Critères d&apos;acceptation']]],
  ['acceptation_20de_20la_20phase_200_25',['Critères d&apos;acceptation de la phase 0',['../lot-87.html#autotoc_md705',1,'']]],
  ['accommodation_20dimensionnante_26',['11. Décors dynamiques (accommodation dimensionnante)',['../spec-architecture.html#autotoc_md270',1,'']]],
  ['accumulateur_20_3a_20core_3a_3afixedtimestep_20core_3a_3afixedtimestep_27',['L&apos;accumulateur : &lt;a class=&quot;el&quot; href=&quot;classcore_1_1FixedTimestep.html&quot; title=&quot;core::FixedTimestep&quot;&gt;core::FixedTimestep&lt;/a&gt;',['../guide-boucle.html#autotoc_md56',1,'']]],
  ['acquiert_28',['Seule une victoire l&apos;acquiert',['../lot-18.html#autotoc_md496',1,'']]],
  ['actions_20du_20jeu_20mapping_20logique_29',['2. Actions du jeu (mapping logique)',['../spec-controles.html#autotoc_md286',1,'']]],
  ['actions_20logiques_30',['Entrées et actions logiques',['../guide-entrees.html',1,'guide']]],
  ['adjacent_20correction_20du_20balayage_20horizontal_31',['Le piège du mur adjacent (correction du balayage horizontal)',['../guide-physique.html#autotoc_md204',1,'']]],
  ['adversaire_32',['6. L&apos;adversaire',['../spec-combat.html#autotoc_md277',1,'']]],
  ['affiché_20_3a_20une_20donnée_20et_20un_20échafaudage_20assumé_33',['Le personnage affiché : une donnée, et un échafaudage assumé',['../lot-38.html#autotoc_md578',1,'']]],
  ['affiché_20ou_20écrit_20comme_20non_20alimenté_34',['Un champ affiché, ou écrit comme non alimenté',['../lot-38.html#autotoc_md572',1,'']]],
  ['affichage_35',['Netteté à toute échelle d&apos;affichage',['../guide-design-ihm.html#autotoc_md82',1,'']]],
  ['agencement_20trouvés_20en_20regardant_20l_20écran_36',['Trois défauts d&apos;agencement, trouvés en regardant l&apos;écran',['../lot-68.html#autotoc_md622',1,'']]],
  ['agonie_20et_20mort_37',['5. Agonie et mort',['../spec-combat.html#autotoc_md276',1,'']]],
  ['agonie_20et_20mort_38',['&lt;span class=&quot;tt&quot;&gt;LOT-72&lt;/span&gt; — Conditions, agonie et mort',['../roadmap.html#lot-72',1,'']]],
  ['agrégat_20leveldata_39',['LOT-03 — Agrégat `LevelData`',['../lot-03.html',1,'lots']]],
  ['agrandissement_40',['Le facteur d&apos;agrandissement',['../guide-conception-qds.html#autotoc_md67',1,'']]],
  ['agrandissement_20reste_20entier_20pour_20une_20autre_20raison_41',['Le facteur d&apos;agrandissement reste entier, pour une autre raison',['../lot-66.html#autotoc_md603',1,'']]],
  ['ailleurs_20qu_20en_20dur_42',['Ce qui est figé ailleurs qu&apos;en dur',['../lot-12.html#autotoc_md472',1,'']]],
  ['ajoutées_20le_207_20septembre_202026_43',['Les ressources de table virtuelle (ajoutées le 7 septembre 2026)',['../roadmap.html#autotoc_md714',1,'']]],
  ['ajout_20et_20suppression_20_3a_20swap_20and_20pop_44',['Ajout et suppression : &lt;em&gt;swap-and-pop&lt;/em&gt;',['../guide-ecs.html#autotoc_md107',1,'']]],
  ['ajout_20pas_20une_20refonte_45',['Pourquoi ce lot est un lot d&apos;&lt;b&gt;ajout&lt;/b&gt;, pas une refonte',['../roadmap.html#autotoc_md836',1,'']]],
  ['aléatoires_20et_20contenu_20d_20ambiance_46',['&lt;span class=&quot;tt&quot;&gt;LOT-44&lt;/span&gt; — Noms, tables aléatoires et contenu d&apos;ambiance',['../roadmap.html#lot-44',1,'']]],
  ['algorithme_47',['Le départage est une règle, et elle ne dépend pas de l&apos;algorithme',['../lot-19.html#autotoc_md505',1,'']]],
  ['algorithme_20évolutif_48',['Comment fonctionne la population (algorithme Évolutif)',['../manuel-mode-ia.html#autotoc_md852',1,'']]],
  ['algorithmes_20d_20apprentissage_49',['3. Algorithmes d&apos;apprentissage',['../spec-ia.html#autotoc_md348',1,'']]],
  ['alignée_20aux_20axes_50',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Aabb.html&quot; title=&quot;core::Aabb&quot;&gt;Aabb&lt;/a&gt; : la boîte englobante alignée aux axes',['../guide-maths.html#autotoc_md171',1,'']]],
  ['alimenté_51',['Un champ affiché, ou écrit comme non alimenté',['../lot-38.html#autotoc_md572',1,'']]],
  ['alimentés_52',['Les écrans dessinés mais pas encore alimentés',['../guide-conception-qds.html#autotoc_md69',1,'']]],
  ['allègement_20est_20le_20geste_20à_20plus_20fort_20levier_20du_20programme_53',['9.3 L&apos;allègement est le geste à plus fort levier du programme',['../roadmap.html#autotoc_md747',1,'']]],
  ['aller_20retour_20est_20pur_20et_20c_20est_20ce_20qui_20le_20rend_20vérifiable_54',['L&apos;aller-retour est PUR, et c&apos;est ce qui le rend vérifiable',['../lot-18.html#autotoc_md493',1,'']]],
  ['altitude_20est_20un_20attribut_20jamais_20une_20géométrie_55',['altitude est un attribut jamais une géométrie',['../lot-19.html#autotoc_md506',1,'L&apos;altitude est un attribut, jamais une géométrie'],['../namespacecore.html#autotoc_md870',1,'L&apos;altitude est un attribut, jamais une géométrie']]],
  ['ambiance_56',['&lt;span class=&quot;tt&quot;&gt;LOT-44&lt;/span&gt; — Noms, tables aléatoires et contenu d&apos;ambiance',['../roadmap.html#lot-44',1,'']]],
  ['ancienne_20charte_57',['T5.2 — L&apos;ancienne charte',['../lot-87.html#autotoc_md702',1,'']]],
  ['ancienne_20et_20ce_20n_20est_20pas_20un_20oubli_58',['L&apos;accentué reste tracé à l&apos;ancienne, et ce n&apos;est pas un oubli',['../lot-76.html#autotoc_md629',1,'']]],
  ['and_20pop_59',['Ajout et suppression : &lt;em&gt;swap-and-pop&lt;/em&gt;',['../guide-ecs.html#autotoc_md107',1,'']]],
  ['animation_20_3a_20des_20clips_20en_20données_20une_20progression_20générale_20lot_2046_60',['L&apos;animation : des clips en données, une progression générale (&lt;span class=&quot;tt&quot;&gt;LOT-46&lt;/span&gt;)',['../guide-rendu.html#autotoc_md230',1,'']]],
  ['animation_20personnage_20—_20test_5fanimation_5fpersonnage_20cpp_206_61',['Animation Personnage — &lt;span class=&quot;tt&quot;&gt;test_animation_personnage.cpp&lt;/span&gt; (6)',['../cahiertest.html#autotoc_md30',1,'']]],
  ['annuler_20refaire_20_3a_20pourquoi_20des_20instantanés_20complets_62',['Annuler/refaire : pourquoi des instantanés complets',['../guide-editeur.html#autotoc_md122',1,'']]],
  ['annuler_20refaire_20deux_20cibles_63',['Une seule paire Annuler/Refaire, deux cibles',['../guide-atelier-pixel-art.html#autotoc_md44',1,'']]],
  ['anticiper_20tant_20que_20rien_20n_20est_20construit_64',['10. Ce qu&apos;il faut anticiper, tant que rien n&apos;est construit',['../roadmap.html#autotoc_md752',1,'']]],
  ['aperçu_65',['La référence : un repère géométrique, pas un aperçu',['../guide-editeur.html#autotoc_md132',1,'']]],
  ['appelant_66',['La règle de superposition, portée par l&apos;écran et non par l&apos;appelant',['../lot-68.html#autotoc_md620',1,'']]],
  ['applicatif_67',['1. Socle applicatif',['../spec-interface-ihm.html#autotoc_md351',1,'']]],
  ['application_20habillée_68',['De jetons purs à une application habillée',['../guide-design-ihm.html#autotoc_md79',1,'']]],
  ['application_20pour_20changer_20un_20pixel_69',['Le problème : quitter l&apos;application pour changer un pixel',['../guide-atelier-pixel-art.html#autotoc_md36',1,'']]],
  ['applications_20deux_20technologies_70',['IHM Qt — deux applications, deux technologies',['../guide-ihm-qt.html',1,'guide']]],
  ['applique_20quand_71',['Ce qui s&apos;applique quand',['../classhmi_1_1OptionsModel.html#autotoc_md894',1,'']]],
  ['apporte_20chiffré_72',['Ce que chaque document apporte, chiffré',['../roadmap.html#autotoc_md715',1,'']]],
  ['apprentissage_73',['3. Algorithmes d&apos;apprentissage',['../spec-ia.html#autotoc_md348',1,'']]],
  ['appris_74',['4. Ce que l&apos;extraction a appris',['../roadmap.html#autotoc_md719',1,'']]],
  ['approchée_75',['Égalité approchée',['../guide-maths.html#autotoc_md170',1,'']]],
  ['approche_20d_20implémentation_20décidée_76',['4. Approche d&apos;implémentation (décidée)',['../spec-editeur.html#autotoc_md319',1,'']]],
  ['après_20la_20sortie_20du_20pixel_20art_77',['Pourquoi le facteur reste entier après la sortie du pixel art',['../guide-design-ihm.html#autotoc_md91',1,'']]],
  ['arête_20n_20est_20contrôlée_20qu_20une_20fois_78',['Le triangle, et pourquoi chaque arête n&apos;est contrôlée qu&apos;une fois',['../lot-32.html#autotoc_md524',1,'']]],
  ['arborescence_20cible_79',['7. Arborescence cible',['../roadmap.html#autotoc_md737',1,'']]],
  ['architecture_20décisions_20dimensionnantes_80',['Architecture (décisions dimensionnantes)',['../spec-architecture.html',1,'specifications']]],
  ['architecture_20dépendances_20entre_20modules_81',['5. Architecture (dépendances entre modules)',['../spec-conventions.html#autotoc_md296',1,'']]],
  ['architecture_20de_20l_20information_82',['Système de design et architecture de l&apos;information',['../guide-design-ihm.html',1,'guide']]],
  ['architecture_20de_20l_20information_20_3a_20ce_20qui_20informe_20reste_20ce_20qui_20commande_20est_20unique_83',['Architecture de l&apos;information : ce qui informe reste, ce qui commande est unique',['../guide-design-ihm.html#autotoc_md84',1,'']]],
  ['architecture_20de_20l_20information_20de_20l_20éditeur_20lot_20h_2057_84',['7. Architecture de l&apos;information de l&apos;éditeur (LOT-H-57)',['../spec-interface-ihm.html#autotoc_md357',1,'']]],
  ['architecture_20en_20deux_20couches_85',['Architecture en deux couches',['../guide.html#autotoc_md258',1,'']]],
  ['architecture_20maintenabilité_86',['2. Architecture &amp;amp; maintenabilité',['../spec-exigences.html#autotoc_md330',1,'']]],
  ['arme_20n_20est_20pas_20dans_20sa_20rangée_87',['Le groupe d&apos;une arme n&apos;est pas dans sa rangée',['../lot-34.html#autotoc_md541',1,'']]],
  ['arrêtée_88',['Ce qui l&apos;a arrêtée',['../lot-38.html#autotoc_md575',1,'']]],
  ['arrêtent_20la_20génération_89',['Deux contrôles qui arrêtent la génération',['../lot-33.html#autotoc_md532',1,'']]],
  ['arrêter_90',['Traverser n&apos;est pas s&apos;arrêter',['../lot-19.html#autotoc_md508',1,'']]],
  ['arrivée_91',['La solution : tester tout le trajet, pas seulement l&apos;arrivée',['../guide-physique.html#autotoc_md197',1,'']]],
  ['arrondi_20_3a_20tangente_20verticale_20à_20une_20extrémité_92',['Particularité de l&apos;arrondi : tangente verticale à une extrémité',['../guide-physique.html#autotoc_md205',1,'']]],
  ['arrondi_20ex_20gp_20003_20ex_20gp_20004_93',['2. Suivi de pente et d&apos;arrondi (EX-GP-003, EX-GP-004)',['../guide-physique.html#autotoc_md201',1,'']]],
  ['arrondi_20n_20est_20jamais_20solide_94',['Pourquoi une pente (ou un arrondi) n&apos;est jamais solide',['../guide-physique.html#autotoc_md202',1,'']]],
  ['arrondis_20qui_20ne_20se_20voient_20pas_95',['Deux arrondis qui ne se voient pas',['../lot-12.html#autotoc_md469',1,'']]],
  ['arrondit_20à_20la_20case_20inférieure_96',['Le budget s&apos;arrondit à la case inférieure',['../lot-19.html#autotoc_md509',1,'']]],
  ['art_97',['art',['../roadmap.html#lot-69',1,'&lt;span class=&quot;tt&quot;&gt;LOT-69&lt;/span&gt; — Retrait de l&apos;atelier pixel art'],['../lot-66.html',1,'LOT-66 — Charte visuelle : sortir de l&apos;identité pixel art'],['../spec-decors.html',1,'Plans picturaux &amp; pipeline pixel art'],['../guide-design-ihm.html#autotoc_md91',1,'Pourquoi le facteur reste entier après la sortie du pixel art']]],
  ['art_20intégré_98',['Atelier pixel art intégré',['../guide-atelier-pixel-art.html',1,'guide']]],
  ['art_20intégré_20à_20l_20éditeur_99',['3. Pipeline photo → pixel art (intégré à l&apos;éditeur)',['../spec-decors.html#autotoc_md312',1,'']]],
  ['art_20post_20mvp_20intégré_20à_20l_20éditeur_100',['4bis. Décors &amp;amp; pixel art (post-MVP, intégré à l&apos;éditeur)',['../spec-editeur.html#autotoc_md320',1,'']]],
  ['artiste_20passé_20le_2012_20septembre_202026_101',['T1.5 — Le test de l&apos;artiste, passé le 12 septembre 2026',['../lot-87.html#autotoc_md671',1,'']]],
  ['artistique_20reprise_20des_20maquettes_20supprimées_102',['La direction artistique, reprise des maquettes supprimées',['../lot-86.html#autotoc_md649',1,'']]],
  ['assemblé_103',['&lt;a class=&quot;el&quot; href=&quot;classcore_1_1Level.html&quot; title=&quot;core::Level&quot;&gt;core::Level&lt;/a&gt; : le niveau assemblé',['../guide-niveaux.html#autotoc_md179',1,'']]],
  ['assembler_20la_20frame_20complète_104',['Assembler la frame complète',['../guide-rendu.html#autotoc_md249',1,'']]],
  ['assertions_105',['Journalisation et assertions',['../guide-journalisation.html',1,'guide']]],
  ['assertions_20_3a_20jadg_5fassert_20jadg_5fassert_20un_20outil_20différent_106',['Assertions : &lt;a class=&quot;el&quot; href=&quot;Assert_8h.html#a2811f3d423b22f1a90179b4ed095f054&quot; title=&quot;JADG_ASSERT&quot;&gt;JADG_ASSERT&lt;/a&gt;, un outil différent',['../guide-journalisation.html#autotoc_md166',1,'']]],
  ['assertions_20journalisation_107',['10. Assertions &amp;amp; journalisation',['../spec-conventions.html#autotoc_md306',1,'']]],
  ['asset_20à_20une_20taille_20forcément_20conforme_108',['Créer un asset à une taille forcément conforme',['../guide-atelier-pixel-art.html#autotoc_md42',1,'']]],
  ['asset_20sert_20à_20déroger_109',['La clé se déduit ; le champ &lt;span class=&quot;tt&quot;&gt;asset&lt;/span&gt; sert à déroger',['../lot-39.html#autotoc_md584',1,'']]],
  ['assets_110',['5. Assets',['../spec-contenu.html#autotoc_md282',1,'']]],
  ['assets_111',['assets',['../lot-39.html',1,'LOT-39 — Plomberie des clés d&apos;assets'],['../lot-87.html#autotoc_md682',1,'T2.4 — Le cahier des assets']]],
  ['assets_20_3a_20convention_20et_20régénération_112',['&lt;span class=&quot;tt&quot;&gt;Source/Elements/Assets/&lt;/span&gt; : convention et régénération',['../guide-rendu.html#autotoc_md227',1,'']]],
  ['assets_20de_20la_20charte_20v2_113',['LOT-87 — Cahier des assets de la charte v2',['../lot-87-cahier-assets.html',1,'lot-87']]],
  ['assumé_114',['assumé',['../lot-37.html#autotoc_md569',1,'Effet de bord assumé'],['../lot-38.html#autotoc_md578',1,'Le personnage affiché : une donnée, et un échafaudage assumé']]],
  ['assumé_20pas_20subi_115',['Le renversement est assumé, pas subi',['../lot-66.html#autotoc_md606',1,'']]],
  ['assumée_116',['Conséquence assumée',['../lot-01.html#autotoc_md408',1,'']]],
  ['assumée_20sur_20la_20liste_20de_20suppressions_117',['Une déviation assumée sur la liste de suppressions',['../lot-66.html#autotoc_md604',1,'']]],
  ['atelier_20pixel_20art_118',['&lt;span class=&quot;tt&quot;&gt;LOT-69&lt;/span&gt; — Retrait de l&apos;atelier pixel art',['../roadmap.html#lot-69',1,'']]],
  ['atelier_20pixel_20art_20intégré_119',['Atelier pixel art intégré',['../guide-atelier-pixel-art.html',1,'guide']]],
  ['atlas_120',['Les images du personnage : pourquoi elles vivent dans le même atlas',['../guide-rendu.html#autotoc_md228',1,'']]],
  ['atlas_20des_20régions_20et_20graphe_20de_20cartes_121',['LOT-37 — Atlas des régions et graphe de cartes',['../lot-37.html',1,'lots']]],
  ['atlas_20du_20monde_122',['7. Atlas du monde',['../spec-contenu.html#autotoc_md284',1,'']]],
  ['attaque_20et_20dégâts_123',['4. Attaque et dégâts',['../spec-combat.html#autotoc_md275',1,'']]],
  ['attaques_20dégâts_20et_20états_124',['LOT-21 — Attaques, dégâts et états',['../roadmap.html#lot-21',1,'']]],
  ['atteignent_125',['Les réglages, et ce qu&apos;ils atteignent',['../guide-ihm-qt.html#autotoc_md153',1,'']]],
  ['attente_20—_20deux_20décisions_126',['Conservé contre l&apos;attente — deux décisions',['../lot-01.html#autotoc_md407',1,'']]],
  ['attention_20_3a_20le_20texte_20des_20maquettes_20était_20périmé_127',['Attention : le texte des maquettes était périmé',['../lot-86.html#autotoc_md650',1,'']]],
  ['attesté_20pas_20saisi_128',['Le complément des &lt;em&gt;Basic Rules&lt;/em&gt; est attesté, pas saisi',['../lot-30.html#autotoc_md518',1,'']]],
  ['attribut_20jamais_20une_20géométrie_129',['attribut jamais une géométrie',['../lot-19.html#autotoc_md506',1,'L&apos;altitude est un attribut, jamais une géométrie'],['../namespacecore.html#autotoc_md870',1,'L&apos;altitude est un attribut, jamais une géométrie']]],
  ['au_20canevas_20et_20nommé_130',['L&apos;historique : local au canevas, et nommé',['../guide-atelier-pixel-art.html#autotoc_md39',1,'']]],
  ['au_20delà_20de_200_201_200_131',['Ressenti (game feel) — ⚠️ réglage fin reporté au-delà de &lt;span class=&quot;tt&quot;&gt;0.1.0&lt;/span&gt;',['../spec-gameplay.html#autotoc_md342',1,'']]],
  ['au_20delà_20du_20moteur_132',['Objectifs produit (au-delà du moteur)',['../spec-vision.html#autotoc_md398',1,'']]],
  ['au_20delà_20du_20mvp_133',['Mécaniques aériennes avancées (au-delà du MVP)',['../spec-gameplay.html#autotoc_md341',1,'']]],
  ['au_20gpu_20pas_20un_20changement_20de_20cible_134',['QRhi : une couche d&apos;accès au GPU, pas un changement de cible',['../guide-rendu.html#autotoc_md214',1,'']]],
  ['au_20jeu_20et_20outillage_135',['5. Intégration au jeu et outillage',['../spec-ia.html#autotoc_md350',1,'']]],
  ['au_20jour_136',['au jour',['../lot-33.html#autotoc_md534',1,'Cinq défauts du lexique que les 94 noms ont mis au jour'],['../lot-43.html#autotoc_md593',1,'Trois défauts du corpus que ce lot a mis au jour']]],
  ['au_20lancement_137',['Configurer le niveau minimal au lancement',['../guide-journalisation.html#autotoc_md164',1,'']]],
  ['au_20moteur_20—_20relecture_20du_2014_20septembre_202026_138',['4bis. Ce que les deux livres imposent au moteur — relecture du 14 septembre 2026',['../roadmap.html#autotoc_md721',1,'']]],
  ['au_20vertical_20slice_139',['Le chemin critique jusqu&apos;au &lt;em&gt;vertical slice&lt;/em&gt;',['../roadmap.html#autotoc_md733',1,'']]],
  ['aucune_20statistique_20n_20est_20stockée_20ici_140',['Aucune statistique n&apos;est stockée ici',['../structcore_1_1Inventory.html#autotoc_md879',1,'']]],
  ['aucune_20valeur_20de_20règle_20dans_20le_20c_20»_20se_20vérifie_20sur_20le_20diff_20pas_20sur_20l_20intention_141',['« Aucune valeur de règle dans le C++ » se vérifie sur le diff, pas sur l&apos;intention',['../lot-13.html#autotoc_md478',1,'']]],
  ['audio_142',['Audio',['../spec-rendu-technique.html#autotoc_md385',1,'5. Audio'],['../guide-audio.html',1,'Audio'],['../roadmap.html#autotoc_md828',1,'Audio']]],
  ['audio_143',['Crédits audio',['../md__2home_2runner_2work_2JustAnotherDnDGame_2JustAnotherDnDGame_2Source_2Elements_2Audio_2CREDITS.html',1,'']]],
  ['audio_2014_144',['Audio (14)',['../cahiertest.html#autotoc_md20',1,'']]],
  ['audio_20effets_20et_20version_200_200_201_145',['LOT-28 — Audio, effets et version &lt;span class=&quot;tt&quot;&gt;0.0.1&lt;/span&gt;',['../roadmap.html#lot-28',1,'']]],
  ['audit_2014_20septembre_202026_20_3a_20ce_20qui_20avait_20dérivé_20en_20dix_20jours_146',['9.6 Second audit, 14 septembre 2026 : ce qui avait dérivé en dix jours',['../roadmap.html#autotoc_md750',1,'']]],
  ['audit_20_3a_20hmi_3a_3alayervisibility_20lot_2051_147',['Isoler un calque pour l&apos;audit : &lt;span class=&quot;tt&quot;&gt;hmi::LayerVisibility&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;LOT-51&lt;/span&gt;)',['../guide-rendu.html#autotoc_md234',1,'']]],
  ['audit_20a_20révélé_20sur_20l_20état_20du_20dépôt_148',['9. Ce que l&apos;audit a révélé sur l&apos;état du dépôt',['../roadmap.html#autotoc_md744',1,'']]],
  ['auditer_20les_20calques_20sans_20les_20confondre_20avec_20f8_20lot_2051_149',['Le mode « définition des textures » : auditer les calques sans les confondre avec &lt;span class=&quot;tt&quot;&gt;F8&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;LOT-51&lt;/span&gt;)',['../guide-editeur.html#autotoc_md127',1,'']]],
  ['aujourd_20hui_150',['Ce que l&apos;écran est donc aujourd&apos;hui',['../lot-38.html#autotoc_md576',1,'']]],
  ['aurait_20pas_20vu_151',['Le défaut que les tests ont trouvé, et que la relecture n&apos;aurait pas vu',['../lot-12.html#autotoc_md468',1,'']]],
  ['aussi_152',['aussi',['../guide-atelier-pixel-art.html#autotoc_md45',1,'Voir aussi'],['../guide-audio.html#autotoc_md52',1,'Voir aussi'],['../guide-boucle.html#autotoc_md62',1,'Voir aussi'],['../guide-conception-qds.html#autotoc_md76',1,'Voir aussi'],['../guide-design-ihm.html#autotoc_md94',1,'Voir aussi'],['../guide-ecrans.html#autotoc_md102',1,'Voir aussi'],['../guide-ecs.html#autotoc_md111',1,'Voir aussi'],['../guide-editeur.html#autotoc_md134',1,'Voir aussi'],['../guide-entrees.html#autotoc_md145',1,'Voir aussi'],['../guide-ihm-qt.html#autotoc_md155',1,'Voir aussi'],['../guide-journalisation.html#autotoc_md167',1,'Voir aussi'],['../guide-maths.html#autotoc_md174',1,'Voir aussi'],['../guide-niveaux.html#autotoc_md194',1,'Voir aussi'],['../guide-physique.html#autotoc_md212',1,'Voir aussi'],['../guide-rendu.html#autotoc_md256',1,'Voir aussi']]],
  ['autant_153',['Ce que le schéma ne peut pas dire, et qui n&apos;est pas perdu pour autant',['../lot-33.html#autotoc_md533',1,'']]],
  ['auto_20teste_154',['Ce que le contrôle vérifie, et pourquoi il s&apos;auto-teste',['../lot-30.html#autotoc_md519',1,'']]],
  ['auto_20teste_20faute_20de_20données_20à_20valider_155',['Le validateur s&apos;auto-teste, faute de données à valider',['../lot-32.html#autotoc_md526',1,'']]],
  ['automatisé_156',['11. Outillage qualité (automatisé)',['../spec-conventions.html#autotoc_md307',1,'']]],
  ['autonome_20jamais_20un_20singleton_20joueur_157',['&lt;span class=&quot;tt&quot;&gt;CharacterSheet&lt;/span&gt; est un objet autonome, jamais un singleton joueur',['../lot-13.html#autotoc_md479',1,'']]],
  ['autre_158',['Sa gouttière bouge d&apos;une page à l&apos;autre',['../lot-36.html#autotoc_md553',1,'']]],
  ['autre_20chose_20que_20des_20intentions_159',['Ce qui rend ces exigences autre chose que des intentions',['../spec-interface-ihm.html#autotoc_md364',1,'']]],
  ['autre_20raison_160',['Le facteur d&apos;agrandissement reste entier, pour une autre raison',['../lot-66.html#autotoc_md603',1,'']]],
  ['autrement_161',['Ce que le corpus dit, et que la feuille de route disait autrement',['../lot-36.html#autotoc_md555',1,'']]],
  ['autres_162',['5. Récupérer les niveaux des autres',['../manuel-partager-niveau.html#autotoc_md865',1,'']]],
  ['aux_20axes_163',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Aabb.html&quot; title=&quot;core::Aabb&quot;&gt;Aabb&lt;/a&gt; : la boîte englobante alignée aux axes',['../guide-maths.html#autotoc_md171',1,'']]],
  ['aux_20entités_20_3a_20core_3a_3abuildlevelscene_20buildlevelscene_164',['De la grille aux entités : &lt;a class=&quot;el&quot; href=&quot;namespacecore.html#a69ac6b2c5ca32686a14824d1f1c04b2a&quot; title=&quot;core::buildLevelScene&quot;&gt;buildLevelScene&lt;/a&gt;',['../guide-niveaux.html#autotoc_md184',1,'']]],
  ['aux_20images_20produites_165',['T2.5 — Le manifeste étendu aux images produites',['../lot-87.html#autotoc_md683',1,'']]],
  ['avait_20dérivé_20en_20dix_20jours_166',['9.6 Second audit, 14 septembre 2026 : ce qui avait dérivé en dix jours',['../roadmap.html#autotoc_md750',1,'']]],
  ['avancées_20au_20delà_20du_20mvp_167',['Mécaniques aériennes avancées (au-delà du MVP)',['../spec-gameplay.html#autotoc_md341',1,'']]],
  ['avancés_20lot_2031_168',['Dangers avancés (&lt;span class=&quot;tt&quot;&gt;LOT-31&lt;/span&gt;)',['../guide-niveaux.html#autotoc_md191',1,'']]],
  ['avancés_20lot_20h_2031_169',['avancés LOT H 31',['../spec-editeur.html#autotoc_md325',1,'9. Dangers avancés (&lt;span class=&quot;tt&quot;&gt;LOT-H-31&lt;/span&gt;)'],['../spec-gameplay.html#autotoc_md339',1,'Dangers avancés (&lt;span class=&quot;tt&quot;&gt;LOT-H-31&lt;/span&gt;)']]],
  ['avancement_170',['Avancement',['../index.html#autotoc_md3',1,'']]],
  ['avancement_171',['État d&apos;avancement',['../roadmap.html#roadmap-avancement',1,'']]],
  ['avant_20d_20écrire_172',['T1.1 — Le diagnostic, avant d&apos;écrire',['../lot-87.html#autotoc_md669',1,'']]],
  ['avant_20d_20écrire_20jamais_20l_20inverse_173',['Enregistrer : valider avant d&apos;écrire, jamais l&apos;inverse',['../guide-editeur.html#autotoc_md124',1,'']]],
  ['avant_20de_20l_20avoir_20posé_174',['Voir le raccord avant de l&apos;avoir posé',['../guide-atelier-pixel-art.html#autotoc_md43',1,'']]],
  ['avant_20données_175',['2. Contrats avant données',['../spec-contenu.html#autotoc_md279',1,'']]],
  ['avec_20clamp_20direct_176',['Méthode retenue : balayage &lt;b&gt;par axe&lt;/b&gt; avec clamp direct',['../guide-physique.html#autotoc_md198',1,'']]],
  ['avec_20eux_177',['Les ornements restent tracés, et &lt;span class=&quot;tt&quot;&gt;EX-IHM-075&lt;/span&gt; avec eux',['../spec-interface-ihm.html#autotoc_md363',1,'']]],
  ['avec_20f8_20lot_2051_178',['Le mode « définition des textures » : auditer les calques sans les confondre avec &lt;span class=&quot;tt&quot;&gt;F8&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;LOT-51&lt;/span&gt;)',['../guide-editeur.html#autotoc_md127',1,'']]],
  ['avec_20le_20jeu_20et_20observabilité_179',['2. Pont avec le jeu et observabilité',['../spec-ia.html#autotoc_md347',1,'']]],
  ['avec_20un_20piège_180',['&lt;a class=&quot;el&quot; href=&quot;classcore_1_1LevelWriter.html&quot; title=&quot;core::LevelWriter&quot;&gt;core::LevelWriter&lt;/a&gt; : l&apos;inverse du chargement, avec un piège',['../guide-editeur.html#autotoc_md116',1,'']]],
  ['aventuriers_20_3a_20rangs_20et_20contrats_181',['&lt;span class=&quot;tt&quot;&gt;LOT-45&lt;/span&gt; — Guilde des Aventuriers : rangs et contrats',['../roadmap.html#lot-45',1,'']]],
  ['avoir_20posé_182',['Voir le raccord avant de l&apos;avoir posé',['../guide-atelier-pixel-art.html#autotoc_md43',1,'']]],
  ['axe_20_3a_20la_20mémoire_20de_20texture_20des_20plans_20lot_2069_183',['Le second axe : la mémoire de texture des plans (&lt;span class=&quot;tt&quot;&gt;LOT-69&lt;/span&gt;)',['../guide-rendu.html#autotoc_md253',1,'']]],
  ['axe_20avec_20clamp_20direct_184',['Méthode retenue : balayage &lt;b&gt;par axe&lt;/b&gt; avec clamp direct',['../guide-physique.html#autotoc_md198',1,'']]],
  ['axes_185',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Aabb.html&quot; title=&quot;core::Aabb&quot;&gt;Aabb&lt;/a&gt; : la boîte englobante alignée aux axes',['../guide-maths.html#autotoc_md171',1,'']]]
];
