var searchData=
[
  ['un_20élément_20mobile_0',['L&apos;outil « Parcours » : dessiner la route d&apos;un élément mobile',['../guide-editeur.html#autotoc_md104',1,'']]],
  ['un_20état_20un_20contrôle_1',['Un état, un contrôle',['../guide-design-ihm.html#autotoc_md69',1,'']]],
  ['un_20aperçu_2',['La référence : un repère géométrique, pas un aperçu',['../guide-editeur.html#autotoc_md117',1,'']]],
  ['un_20arrondi_20n_20est_20jamais_20solide_3',['Pourquoi une pente (ou un arrondi) n&apos;est jamais solide',['../guide-physique.html#autotoc_md191',1,'']]],
  ['un_20asset_20à_20une_20taille_20forcément_20conforme_4',['Créer un asset à une taille forcément conforme',['../guide-atelier-pixel-art.html#autotoc_md38',1,'']]],
  ['un_20bac_20à_20sable_20dans_20l_20univers_20entier_5',['La cible : un bac à sable dans l&apos;univers entier',['../roadmap-010.html#autotoc_md471',1,'']]],
  ['un_20calque_20pour_20l_20audit_20_3a_20hmi_3a_3alayervisibility_20lot_2051_6',['Isoler un calque pour l&apos;audit : &lt;span class=&quot;tt&quot;&gt;hmi::LayerVisibility&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;LOT-51&lt;/span&gt;)',['../guide-rendu.html#autotoc_md223',1,'']]],
  ['un_20changement_20de_20cible_7',['QRhi : une couche d&apos;accès au GPU, pas un changement de cible',['../guide-rendu.html#autotoc_md203',1,'']]],
  ['un_20compromis_20de_20mémoire_20jamais_20de_20cadrage_8',['Densité : un compromis de mémoire, jamais de cadrage',['../guide-rendu.html#autotoc_md226',1,'']]],
  ['un_20contenu_20plus_20grand_20que_20la_20fenêtre_20_3a_20fitzoom_20et_20hmi_3a_3aroomgrid_9',['Cadrer un contenu plus grand que la fenêtre : &lt;span class=&quot;tt&quot;&gt;fitZoom&lt;/span&gt; et &lt;span class=&quot;tt&quot;&gt;hmi::RoomGrid&lt;/span&gt;',['../guide-rendu.html#autotoc_md206',1,'']]],
  ['un_20contrôle_10',['Un état, un contrôle',['../guide-design-ihm.html#autotoc_md69',1,'']]],
  ['un_20fichier_11',['&lt;a class=&quot;el&quot; href=&quot;classhmi_1_1TextureAtlas.html&quot; title=&quot;hmi::TextureAtlas&quot;&gt;hmi::TextureAtlas&lt;/a&gt; : un spritesheet, chargé depuis un fichier',['../guide-rendu.html#autotoc_md214',1,'']]],
  ['un_20jeu_20vidéo_12',['Pourquoi journaliser dans un jeu vidéo',['../guide-journalisation.html#autotoc_md143',1,'']]],
  ['un_20lot_20d_20ajout_20pas_20une_20refonte_13',['Pourquoi ce lot est un lot d&apos;&lt;b&gt;ajout&lt;/b&gt;, pas une refonte',['../roadmap-010.html#autotoc_md608',1,'']]],
  ['un_20même_20niveau_20mode_20«_20par_20salle_20»_14',['Mélanger plusieurs tailles de caméra dans un même niveau (mode « Par salle »)',['../manuel-partager-niveau.html#autotoc_md635',1,'']]],
  ['un_20niveau_15',['un niveau',['../manuel-partager-niveau.html#autotoc_md633',1,'3. Créer un niveau'],['../manuel-jouer.html#autotoc_md615',1,'Objectif d&apos;un niveau']]],
  ['un_20niveau_20_3a_20hmi_3a_3agamesession_20réutilisée_16',['Jouer un niveau : &lt;span class=&quot;tt&quot;&gt;hmi::GameSession&lt;/span&gt; réutilisée',['../guide-ihm-qt.html#autotoc_md136',1,'']]],
  ['un_20niveau_20plus_20grand_20que_20la_20fenêtre_17',['Cadrer un niveau plus grand que la fenêtre',['../guide-editeur.html#autotoc_md111',1,'']]],
  ['un_20niveau_20qu_20on_20peut_20défaire_18',['&lt;a class=&quot;el&quot; href=&quot;classcore_1_1LevelDraft.html&quot; title=&quot;core::LevelDraft&quot;&gt;core::LevelDraft&lt;/a&gt; : un niveau qu&apos;on peut défaire',['../guide-editeur.html#autotoc_md98',1,'']]],
  ['un_20niveau_20sans_20ligne_20de_20commande_19',['Créer et partager un niveau (sans ligne de commande)',['../manuel-partager-niveau.html',1,'manuel']]],
  ['un_20niveau_20sans_20re_20coder_20le_20moteur_20',['Le problème : éditer un niveau sans (re)coder le moteur',['../guide-editeur.html#autotoc_md97',1,'']]],
  ['un_20outil_20différent_21',['Assertions : &lt;a class=&quot;el&quot; href=&quot;Assert_8h.html#a2811f3d423b22f1a90179b4ed095f054&quot; title=&quot;JADG_ASSERT&quot;&gt;JADG_ASSERT&lt;/a&gt;, un outil différent',['../guide-journalisation.html#autotoc_md153',1,'']]],
  ['un_20pas_22',['Pause : suspendre sans perdre un pas',['../guide-ecrans.html#autotoc_md80',1,'']]],
  ['un_20pas_20résumé_23',['Ordre d&apos;un pas (résumé)',['../guide-physique.html#autotoc_md200',1,'']]],
  ['un_20piège_24',['&lt;a class=&quot;el&quot; href=&quot;classcore_1_1LevelWriter.html&quot; title=&quot;core::LevelWriter&quot;&gt;core::LevelWriter&lt;/a&gt; : l&apos;inverse du chargement, avec un piège',['../guide-editeur.html#autotoc_md101',1,'']]],
  ['un_20pixel_25',['Le problème : quitter l&apos;application pour changer un pixel',['../guide-atelier-pixel-art.html#autotoc_md32',1,'']]],
  ['un_20pixel_20en_20case_26',['Peindre, c&apos;est convertir un pixel en case',['../guide-editeur.html#autotoc_md102',1,'']]],
  ['un_20plan_20_3a_20le_20mode_20création_27',['Peindre un plan : le mode création',['../guide-rendu.html#autotoc_md230',1,'']]],
  ['un_20png_20sans_20jamais_20laisser_20de_20fichier_20tronqué_28',['Écrire un PNG sans jamais laisser de fichier tronqué',['../guide-atelier-pixel-art.html#autotoc_md33',1,'']]],
  ['un_20point_20ou_20une_20direction_20dans_20le_20monde_29',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Vector2.html&quot; title=&quot;core::Vector2&quot;&gt;Vector2&lt;/a&gt; : un point ou une direction dans le monde',['../guide-maths.html#autotoc_md155',1,'']]],
  ['un_20rectangle_20texturé_30',['&lt;a class=&quot;el&quot; href=&quot;structhmi_1_1SpriteQuad.html&quot; title=&quot;hmi::SpriteQuad&quot;&gt;SpriteQuad&lt;/a&gt; : un rectangle texturé',['../guide-rendu.html#autotoc_md211',1,'']]],
  ['un_20repère_20géométrique_20pas_20un_20aperçu_31',['La référence : un repère géométrique, pas un aperçu',['../guide-editeur.html#autotoc_md117',1,'']]],
  ['un_20repli_20qui_20n_20invente_20rien_32',['Typographie : une police embarquée, un repli qui n&apos;invente rien',['../guide-design-ihm.html#autotoc_md62',1,'']]],
  ['un_20rpg_33',['&lt;span class=&quot;tt&quot;&gt;LOT-67&lt;/span&gt; — Menus et vocabulaire d&apos;un RPG',['../roadmap-010.html#lot-67',1,'']]],
  ['un_20segment_20orienté_20liens_20de_20mécanismes_20lot_2037_34',['&lt;a class=&quot;el&quot; href=&quot;structhmi_1_1LineQuad.html&quot; title=&quot;hmi::LineQuad&quot;&gt;LineQuad&lt;/a&gt; : un segment orienté (liens de mécanismes, &lt;span class=&quot;tt&quot;&gt;LOT-37&lt;/span&gt;)',['../guide-rendu.html#autotoc_md213',1,'']]],
  ['un_20sprite_20à_20la_20fois_35',['Pourquoi « batcher » plutôt que dessiner un sprite à la fois',['../guide-rendu.html#autotoc_md210',1,'']]],
  ['un_20spritesheet_20chargé_20depuis_20un_20fichier_36',['&lt;a class=&quot;el&quot; href=&quot;classhmi_1_1TextureAtlas.html&quot; title=&quot;hmi::TextureAtlas&quot;&gt;hmi::TextureAtlas&lt;/a&gt; : un spritesheet, chargé depuis un fichier',['../guide-rendu.html#autotoc_md214',1,'']]],
  ['un_20système_20de_20design_37',['Pourquoi un système de design',['../guide-design-ihm.html#autotoc_md59',1,'']]],
  ['un_20tampon_20de_20pixels_38',['Les outils : des fonctions pures sur un tampon de pixels',['../guide-atelier-pixel-art.html#autotoc_md34',1,'']]],
  ['une_20application_20habillée_39',['De jetons purs à une application habillée',['../guide-design-ihm.html#autotoc_md61',1,'']]],
  ['une_20barre_20d_20état_20structurée_40',['Une barre d&apos;état structurée',['../guide-design-ihm.html#autotoc_md67',1,'']]],
  ['une_20boucle_20de_20jeu_41',['Qu&apos;est-ce qu&apos;une boucle de jeu ?',['../guide-boucle.html#autotoc_md49',1,'']]],
  ['une_20classe_20par_20lot_42',['&lt;span class=&quot;tt&quot;&gt;LOT-51&lt;/span&gt; à &lt;span class=&quot;tt&quot;&gt;LOT-65&lt;/span&gt; — une classe par lot',['../roadmap-010.html#lot-51',1,'']]],
  ['une_20couche_20d_20accès_20au_20gpu_20pas_20un_20changement_20de_20cible_43',['QRhi : une couche d&apos;accès au GPU, pas un changement de cible',['../guide-rendu.html#autotoc_md203',1,'']]],
  ['une_20définition_20trois_20surfaces_44',['Les commandes : une définition, trois surfaces',['../guide-design-ihm.html#autotoc_md63',1,'']]],
  ['une_20direction_20dans_20le_20monde_45',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Vector2.html&quot; title=&quot;core::Vector2&quot;&gt;Vector2&lt;/a&gt; : un point ou une direction dans le monde',['../guide-maths.html#autotoc_md155',1,'']]],
  ['une_20donnée_20promet_46',['4. Ce qu&apos;une donnée promet',['../spec-contenu.html#autotoc_md270',1,'']]],
  ['une_20extrémité_47',['Particularité de l&apos;arrondi : tangente verticale à une extrémité',['../guide-physique.html#autotoc_md194',1,'']]],
  ['une_20fenêtre_20qt_48',['Le viewport : Direct3D 11 dans une fenêtre Qt',['../guide-ihm-qt.html#autotoc_md133',1,'']]],
  ['une_20feuille_20de_20style_20ne_20sait_20pas_20faire_49',['Ce qu&apos;une feuille de style ne sait pas faire',['../guide-design-ihm.html#autotoc_md73',1,'']]],
  ['une_20feuille_20par_20portée_20et_20pourquoi_20lot_2073_50',['Une feuille par portée, et pourquoi (LOT-73)',['../guide-design-ihm.html#autotoc_md70',1,'']]],
  ['une_20fois_20de_20plus_51',['La règle d&apos;or, une fois de plus',['../guide-audio.html#autotoc_md42',1,'']]],
  ['une_20frame_52',['Le cycle d&apos;une frame',['../guide-entrees.html#autotoc_md123',1,'']]],
  ['une_20ligne_20_3a_20core_3a_3aformatlogline_20core_3a_3aformatlogline_53',['Le format d&apos;une ligne : &lt;a class=&quot;el&quot; href=&quot;namespacecore.html#aafa85d91ee91c84b123fff01f147615e&quot; title=&quot;core::formatLogLine&quot;&gt;core::formatLogLine&lt;/a&gt;',['../guide-journalisation.html#autotoc_md150',1,'']]],
  ['une_20même_20grille_20_3a_20hmi_3a_3aeditortool_20editortool_54',['Trois outils, une même grille : &lt;a class=&quot;el&quot; href=&quot;namespacehmi.html#a02048ad8ad69a87a10e8307ac2bd68dd&quot; title=&quot;hmi::EditorTool&quot;&gt;EditorTool&lt;/a&gt;',['../guide-editeur.html#autotoc_md105',1,'']]],
  ['une_20pente_20ou_20un_20arrondi_20n_20est_20jamais_20solide_55',['Pourquoi une pente (ou un arrondi) n&apos;est jamais solide',['../guide-physique.html#autotoc_md191',1,'']]],
  ['une_20phrase_56',['Ce que fait l&apos;IA, en une phrase',['../manuel-mode-ia.html#autotoc_md620',1,'']]],
  ['une_20police_20embarquée_20un_20repli_20qui_20n_20invente_20rien_57',['Typographie : une police embarquée, un repli qui n&apos;invente rien',['../guide-design-ihm.html#autotoc_md62',1,'']]],
  ['une_20progression_20générale_20lot_2046_58',['L&apos;animation : des clips en données, une progression générale (&lt;span class=&quot;tt&quot;&gt;LOT-46&lt;/span&gt;)',['../guide-rendu.html#autotoc_md219',1,'']]],
  ['une_20règle_20de_20performance_20à_20respecter_59',['Une règle de performance à respecter',['../guide-journalisation.html#autotoc_md149',1,'']]],
  ['une_20refonte_60',['Pourquoi ce lot est un lot d&apos;&lt;b&gt;ajout&lt;/b&gt;, pas une refonte',['../roadmap-010.html#autotoc_md608',1,'']]],
  ['une_20seconde_20source_20fusionnée_20en_20lecture_20ex_20ctrl_20002_20lot_2020_61',['La manette : une seconde source, fusionnée en lecture (EX-CTRL-002, LOT-20)',['../guide-entrees.html#autotoc_md126',1,'']]],
  ['une_20seule_20cible_20_3a_20l_20application_20qt_62',['Une seule cible : l&apos;application Qt',['../guide-ihm-qt.html#autotoc_md132',1,'']]],
  ['une_20seule_20hmilib_20»_63',['Le découpage retenu — et pourquoi il n&apos;est pas « une seule &lt;span class=&quot;tt&quot;&gt;HmiLib&lt;/span&gt; »',['../lot-02.html#autotoc_md398',1,'']]],
  ['une_20seule_20paire_20annuler_20refaire_20deux_20cibles_64',['Une seule paire Annuler/Refaire, deux cibles',['../guide-atelier-pixel-art.html#autotoc_md40',1,'']]],
  ['une_20seule_20source_20deux_20portées_20étanches_65',['Les jetons : une seule source, deux portées étanches',['../guide-design-ihm.html#autotoc_md60',1,'']]],
  ['une_20taille_20forcément_20conforme_66',['Créer un asset à une taille forcément conforme',['../guide-atelier-pixel-art.html#autotoc_md38',1,'']]],
  ['une_20touche_20dans_20le_20gameplay_67',['Le principe : ne jamais coder « en dur » une touche dans le gameplay',['../guide-entrees.html#autotoc_md120',1,'']]],
  ['unification_68',['5. Menus, options, unification',['../spec-interface-ihm.html#autotoc_md344',1,'']]],
  ['unification_20des_20menus_20lot_2038_69',['Liens de mécanismes (LOT-37) et unification des menus (LOT-38)',['../guide-ihm-qt.html#autotoc_md139',1,'']]],
  ['unique_70',['Architecture de l&apos;information : ce qui informe reste, ce qui commande est unique',['../guide-design-ihm.html#autotoc_md66',1,'']]],
  ['unités_20—_20trois_20espaces_20distincts_71',['3. Coordonnées &amp;amp; unités — trois espaces distincts',['../spec-architecture.html#autotoc_md251',1,'']]],
  ['unités_20et_20de_20repère_72',['Conventions d&apos;unités et de repère',['../guide-maths.html#autotoc_md159',1,'']]],
  ['unités_20monde_20et_20pixels_20_3a_20hmi_3a_3acamera2d_20hmi_3a_3acamera2d_73',['Unités monde et pixels : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1Camera2D.html&quot; title=&quot;hmi::Camera2D&quot;&gt;hmi::Camera2D&lt;/a&gt;',['../guide-rendu.html#autotoc_md205',1,'']]],
  ['unit_20hmi_20graphics_20test_5frender_5fbudget_20cpp_74',['Le test de non-régression du volume (&lt;span class=&quot;tt&quot;&gt;Source/Test/Unit/HMI/Graphics/test_render_budget.cpp&lt;/span&gt;)',['../guide-rendu.html#autotoc_md241',1,'']]],
  ['unitaires_20923_75',['Tests unitaires (923)',['../cahiertest.html#autotoc_md5',1,'']]],
  ['univers_20entier_76',['La cible : un bac à sable dans l&apos;univers entier',['../roadmap-010.html#autotoc_md471',1,'']]],
  ['usages_77',['3. Trois jets, trois usages',['../spec-regles-dnd.html#autotoc_md361',1,'']]],
  ['utilisateur_78',['Manuel utilisateur',['../manuel.html',1,'index']]],
  ['utilisateur_20ihm_79',['Interface utilisateur (IHM)',['../spec-interface-ihm.html',1,'specifications']]]
];
