var searchData=
[
  ['aériennes_20avancées_20au_20delà_20du_20mvp_0',['Mécaniques aériennes avancées (au-delà du MVP)',['../spec-gameplay.html#autotoc_md328',1,'']]],
  ['a_20appris_1',['4. Ce que l&apos;extraction a appris',['../roadmap-010.html#autotoc_md456',1,'']]],
  ['a_20le_20droit_20de_20se_20lier_20à_20qui_2',['Mécanismes : qui a le droit de se lier à qui',['../guide-editeur.html#autotoc_md98',1,'']]],
  ['a_20révélé_20sur_20l_20état_20du_20dépôt_3',['9. Ce que l&apos;audit a révélé sur l&apos;état du dépôt',['../roadmap-010.html#autotoc_md474',1,'']]],
  ['a_20sa_20propre_20catégorie_4',['Chaque module a sa propre catégorie',['../guide-journalisation.html#autotoc_md147',1,'']]],
  ['a_20tranché_5',['a tranché',['../lot-04.html#autotoc_md414',1,'Ce que la réalisation a tranché'],['../lot-05.html#autotoc_md421',1,'Ce que la réalisation a tranché'],['../lot-06.html#autotoc_md428',1,'Ce que la réalisation a tranché'],['../lot-08.html#autotoc_md440',1,'Ce que la réalisation a tranché'],['../lot-77.html#autotoc_md443',1,'Ce que la rédaction a tranché']]],
  ['aabb_6',['1. Collision par balayage continu (swept AABB)',['../guide-physique.html#autotoc_md183',1,'']]],
  ['aabb_20_3a_20la_20boîte_20englobante_20alignée_20aux_20axes_7',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Aabb.html&quot; title=&quot;core::Aabb&quot;&gt;Aabb&lt;/a&gt; : la boîte englobante alignée aux axes',['../guide-maths.html#autotoc_md157',1,'']]],
  ['abord_20le_20widget_20ensuite_8',['Le canevas : la géométrie d&apos;abord, le widget ensuite',['../guide-atelier-pixel-art.html#autotoc_md35',1,'']]],
  ['abstraction_20de_20rendu_9',['6. Abstraction de rendu',['../spec-architecture.html#autotoc_md253',1,'']]],
  ['accès_20au_20gpu_20pas_20un_20changement_20de_20cible_10',['QRhi : une couche d&apos;accès au GPU, pas un changement de cible',['../guide-rendu.html#autotoc_md202',1,'']]],
  ['acceptation_11',['acceptation',['../lot-01.html#autotoc_md394',1,'Critères d&apos;acceptation'],['../lot-02.html#autotoc_md401',1,'Critères d&apos;acceptation'],['../lot-03.html#autotoc_md407',1,'Critères d&apos;acceptation'],['../lot-04.html#autotoc_md413',1,'Critères d&apos;acceptation'],['../lot-05.html#autotoc_md420',1,'Critères d&apos;acceptation'],['../lot-06.html#autotoc_md427',1,'Critères d&apos;acceptation'],['../lot-07.html#autotoc_md434',1,'Critères d&apos;acceptation'],['../lot-08.html#autotoc_md439',1,'Critères d&apos;acceptation'],['../lot-77.html#autotoc_md444',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md488',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md494',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md500',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md506',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md511',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md516',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md521',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md526',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md532',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md538',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md544',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md549',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md555',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md560',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md566',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md571',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md576',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md581',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md586',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md595',1,'Critères d&apos;acceptation'],['../roadmap-010.html#autotoc_md601',1,'Critères d&apos;acceptation']]],
  ['accommodation_20dimensionnante_12',['11. Décors dynamiques (accommodation dimensionnante)',['../spec-architecture.html#autotoc_md258',1,'']]],
  ['accumulateur_20_3a_20core_3a_3afixedtimestep_20core_3a_3afixedtimestep_13',['L&apos;accumulateur : &lt;a class=&quot;el&quot; href=&quot;classcore_1_1FixedTimestep.html&quot; title=&quot;core::FixedTimestep&quot;&gt;core::FixedTimestep&lt;/a&gt;',['../guide-boucle.html#autotoc_md51',1,'']]],
  ['actions_20du_20jeu_20mapping_20logique_14',['2. Actions du jeu (mapping logique)',['../spec-controles.html#autotoc_md273',1,'']]],
  ['actions_20logiques_15',['Entrées et actions logiques',['../guide-entrees.html',1,'guide']]],
  ['adjacent_20correction_20du_20balayage_20horizontal_16',['Le piège du mur adjacent (correction du balayage horizontal)',['../guide-physique.html#autotoc_md192',1,'']]],
  ['adversaire_17',['6. L&apos;adversaire',['../spec-combat.html#autotoc_md265',1,'']]],
  ['affichage_18',['Netteté à toute échelle d&apos;affichage',['../guide-design-ihm.html#autotoc_md63',1,'']]],
  ['agonie_20et_20mort_19',['5. Agonie et mort',['../spec-combat.html#autotoc_md264',1,'']]],
  ['agonie_20et_20mort_20',['&lt;span class=&quot;tt&quot;&gt;LOT-72&lt;/span&gt; — Conditions, agonie et mort',['../roadmap-010.html#lot-72',1,'']]],
  ['agrégat_20leveldata_21',['LOT-03 — Agrégat `LevelData`',['../lot-03.html',1,'lots']]],
  ['ajout_20et_20suppression_20_3a_20swap_20and_20pop_22',['Ajout et suppression : &lt;em&gt;swap-and-pop&lt;/em&gt;',['../guide-ecs.html#autotoc_md91',1,'']]],
  ['ajout_20pas_20une_20refonte_23',['Pourquoi ce lot est un lot d&apos;&lt;b&gt;ajout&lt;/b&gt;, pas une refonte',['../roadmap-010.html#autotoc_md597',1,'']]],
  ['aléatoires_20et_20contenu_20d_20ambiance_24',['&lt;span class=&quot;tt&quot;&gt;LOT-44&lt;/span&gt; — Noms, tables aléatoires et contenu d&apos;ambiance',['../roadmap-010.html#lot-44',1,'']]],
  ['algorithme_20évolutif_25',['Comment fonctionne la population (algorithme Évolutif)',['../manuel-mode-ia.html#autotoc_md613',1,'']]],
  ['algorithmes_20d_20apprentissage_26',['3. Algorithmes d&apos;apprentissage',['../spec-ia.html#autotoc_md336',1,'']]],
  ['alignée_20aux_20axes_27',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Aabb.html&quot; title=&quot;core::Aabb&quot;&gt;Aabb&lt;/a&gt; : la boîte englobante alignée aux axes',['../guide-maths.html#autotoc_md157',1,'']]],
  ['allègement_20est_20le_20geste_20à_20plus_20fort_20levier_20du_20programme_28',['9.3 L&apos;allègement est le geste à plus fort levier du programme',['../roadmap-010.html#autotoc_md477',1,'']]],
  ['ambiance_29',['&lt;span class=&quot;tt&quot;&gt;LOT-44&lt;/span&gt; — Noms, tables aléatoires et contenu d&apos;ambiance',['../roadmap-010.html#lot-44',1,'']]],
  ['and_20pop_30',['Ajout et suppression : &lt;em&gt;swap-and-pop&lt;/em&gt;',['../guide-ecs.html#autotoc_md91',1,'']]],
  ['animation_20_3a_20des_20clips_20en_20données_20une_20progression_20générale_20lot_2046_31',['L&apos;animation : des clips en données, une progression générale (&lt;span class=&quot;tt&quot;&gt;LOT-46&lt;/span&gt;)',['../guide-rendu.html#autotoc_md218',1,'']]],
  ['animation_20personnage_20—_20test_5fanimation_5fpersonnage_20cpp_206_32',['Animation Personnage — &lt;span class=&quot;tt&quot;&gt;test_animation_personnage.cpp&lt;/span&gt; (6)',['../cahiertest.html#autotoc_md25',1,'']]],
  ['annuler_20refaire_20_3a_20pourquoi_20des_20instantanés_20complets_33',['Annuler/refaire : pourquoi des instantanés complets',['../guide-editeur.html#autotoc_md106',1,'']]],
  ['annuler_20refaire_20deux_20cibles_34',['Une seule paire Annuler/Refaire, deux cibles',['../guide-atelier-pixel-art.html#autotoc_md39',1,'']]],
  ['anticiper_20tant_20que_20rien_20n_20est_20construit_35',['10. Ce qu&apos;il faut anticiper, tant que rien n&apos;est construit',['../roadmap-010.html#autotoc_md481',1,'']]],
  ['aperçu_36',['La référence : un repère géométrique, pas un aperçu',['../guide-editeur.html#autotoc_md116',1,'']]],
  ['applicatif_37',['1. Socle applicatif',['../spec-interface-ihm.html#autotoc_md339',1,'']]],
  ['applicatif_20viewport_20direct3d_2011_38',['IHM Qt (refonte) — socle applicatif &amp;amp; viewport Direct3D 11',['../guide-ihm-qt.html',1,'guide']]],
  ['application_20habillée_39',['De jetons purs à une application habillée',['../guide-design-ihm.html#autotoc_md60',1,'']]],
  ['application_20pour_20changer_20un_20pixel_40',['Le problème : quitter l&apos;application pour changer un pixel',['../guide-atelier-pixel-art.html#autotoc_md31',1,'']]],
  ['application_20qt_41',['Une seule cible : l&apos;application Qt',['../guide-ihm-qt.html#autotoc_md131',1,'']]],
  ['apporte_20chiffré_42',['Ce que chaque document apporte, chiffré',['../roadmap-010.html#autotoc_md452',1,'']]],
  ['apprentissage_43',['3. Algorithmes d&apos;apprentissage',['../spec-ia.html#autotoc_md336',1,'']]],
  ['appris_44',['4. Ce que l&apos;extraction a appris',['../roadmap-010.html#autotoc_md456',1,'']]],
  ['approchée_45',['Égalité approchée',['../guide-maths.html#autotoc_md156',1,'']]],
  ['approche_20d_20implémentation_20décidée_46',['4. Approche d&apos;implémentation (décidée)',['../spec-editeur.html#autotoc_md306',1,'']]],
  ['arborescence_20cible_47',['7. Arborescence cible',['../roadmap-010.html#autotoc_md468',1,'']]],
  ['architecture_20décisions_20dimensionnantes_48',['Architecture (décisions dimensionnantes)',['../spec-architecture.html',1,'specifications']]],
  ['architecture_20dépendances_20entre_20modules_49',['5. Architecture (dépendances entre modules)',['../spec-conventions.html#autotoc_md283',1,'']]],
  ['architecture_20de_20l_20information_50',['Système de design et architecture de l&apos;information',['../guide-design-ihm.html',1,'guide']]],
  ['architecture_20de_20l_20information_20_3a_20ce_20qui_20informe_20reste_20ce_20qui_20commande_20est_20unique_51',['Architecture de l&apos;information : ce qui informe reste, ce qui commande est unique',['../guide-design-ihm.html#autotoc_md65',1,'']]],
  ['architecture_20de_20l_20information_20de_20l_20éditeur_20lot_2057_52',['7. Architecture de l&apos;information de l&apos;éditeur (LOT-57)',['../spec-interface-ihm.html#autotoc_md345',1,'']]],
  ['architecture_20en_20deux_20couches_53',['Architecture en deux couches',['../guide.html#autotoc_md246',1,'']]],
  ['architecture_20maintenabilité_54',['2. Architecture &amp;amp; maintenabilité',['../spec-exigences.html#autotoc_md317',1,'']]],
  ['arrivée_55',['La solution : tester tout le trajet, pas seulement l&apos;arrivée',['../guide-physique.html#autotoc_md185',1,'']]],
  ['arrondi_20_3a_20tangente_20verticale_20à_20une_20extrémité_56',['Particularité de l&apos;arrondi : tangente verticale à une extrémité',['../guide-physique.html#autotoc_md193',1,'']]],
  ['arrondi_20ex_20gp_20003_20ex_20gp_20004_57',['2. Suivi de pente et d&apos;arrondi (EX-GP-003, EX-GP-004)',['../guide-physique.html#autotoc_md189',1,'']]],
  ['arrondi_20n_20est_20jamais_20solide_58',['Pourquoi une pente (ou un arrondi) n&apos;est jamais solide',['../guide-physique.html#autotoc_md190',1,'']]],
  ['art_59',['art',['../roadmap-010.html#lot-66',1,'&lt;span class=&quot;tt&quot;&gt;LOT-66&lt;/span&gt; — Charte visuelle : sortir de l&apos;identité pixel art'],['../roadmap-010.html#lot-69',1,'&lt;span class=&quot;tt&quot;&gt;LOT-69&lt;/span&gt; — Retrait de l&apos;atelier pixel art'],['../spec-decors.html',1,'Plans picturaux &amp; pipeline pixel art']]],
  ['art_20intégré_60',['Atelier pixel art intégré',['../guide-atelier-pixel-art.html',1,'guide']]],
  ['art_20intégré_20à_20l_20éditeur_61',['3. Pipeline photo → pixel art (intégré à l&apos;éditeur)',['../spec-decors.html#autotoc_md299',1,'']]],
  ['art_20post_20mvp_20intégré_20à_20l_20éditeur_62',['4bis. Décors &amp;amp; pixel art (post-MVP, intégré à l&apos;éditeur)',['../spec-editeur.html#autotoc_md307',1,'']]],
  ['assemblé_63',['&lt;a class=&quot;el&quot; href=&quot;classcore_1_1Level.html&quot; title=&quot;core::Level&quot;&gt;core::Level&lt;/a&gt; : le niveau assemblé',['../guide-niveaux.html#autotoc_md165',1,'']]],
  ['assembler_20la_20frame_20complète_64',['Assembler la frame complète',['../guide-rendu.html#autotoc_md237',1,'']]],
  ['assertions_65',['Journalisation et assertions',['../guide-journalisation.html',1,'guide']]],
  ['assertions_20_3a_20jadg_5fassert_20jadg_5fassert_20un_20outil_20différent_66',['Assertions : &lt;a class=&quot;el&quot; href=&quot;Assert_8h.html#a2811f3d423b22f1a90179b4ed095f054&quot; title=&quot;JADG_ASSERT&quot;&gt;JADG_ASSERT&lt;/a&gt;, un outil différent',['../guide-journalisation.html#autotoc_md152',1,'']]],
  ['assertions_20journalisation_67',['10. Assertions &amp;amp; journalisation',['../spec-conventions.html#autotoc_md293',1,'']]],
  ['asset_20à_20une_20taille_20forcément_20conforme_68',['Créer un asset à une taille forcément conforme',['../guide-atelier-pixel-art.html#autotoc_md37',1,'']]],
  ['assets_69',['5. Assets',['../spec-contenu.html#autotoc_md270',1,'']]],
  ['assets_70',['&lt;span class=&quot;tt&quot;&gt;LOT-39&lt;/span&gt; — Plomberie des clés d&apos;assets',['../roadmap-010.html#lot-39',1,'']]],
  ['assets_20_3a_20convention_20et_20régénération_71',['&lt;span class=&quot;tt&quot;&gt;Source/Elements/Assets/&lt;/span&gt; : convention et régénération',['../guide-rendu.html#autotoc_md215',1,'']]],
  ['assumée_72',['Conséquence assumée',['../lot-01.html#autotoc_md391',1,'']]],
  ['atelier_20pixel_20art_73',['&lt;span class=&quot;tt&quot;&gt;LOT-69&lt;/span&gt; — Retrait de l&apos;atelier pixel art',['../roadmap-010.html#lot-69',1,'']]],
  ['atelier_20pixel_20art_20intégré_74',['Atelier pixel art intégré',['../guide-atelier-pixel-art.html',1,'guide']]],
  ['atlas_75',['Les images du personnage : pourquoi elles vivent dans le même atlas',['../guide-rendu.html#autotoc_md216',1,'']]],
  ['atlas_20des_20régions_20et_20graphe_20de_20cartes_76',['&lt;span class=&quot;tt&quot;&gt;LOT-37&lt;/span&gt; — Atlas des régions et graphe de cartes',['../roadmap-010.html#lot-37',1,'']]],
  ['attaque_20et_20dégâts_77',['4. Attaque et dégâts',['../spec-combat.html#autotoc_md263',1,'']]],
  ['attaques_20dégâts_20et_20états_78',['LOT-21 — Attaques, dégâts et états',['../roadmap-010.html#lot-21',1,'']]],
  ['attente_20—_20deux_20décisions_79',['Conservé contre l&apos;attente — deux décisions',['../lot-01.html#autotoc_md390',1,'']]],
  ['au_20canevas_20et_20nommé_80',['L&apos;historique : local au canevas, et nommé',['../guide-atelier-pixel-art.html#autotoc_md34',1,'']]],
  ['au_20delà_20de_200_201_200_81',['Ressenti (game feel) — ⚠️ réglage fin reporté au-delà de &lt;span class=&quot;tt&quot;&gt;0.1.0&lt;/span&gt;',['../spec-gameplay.html#autotoc_md329',1,'']]],
  ['au_20delà_20du_20moteur_82',['Objectifs produit (au-delà du moteur)',['../spec-vision.html#autotoc_md381',1,'']]],
  ['au_20delà_20du_20mvp_83',['Mécaniques aériennes avancées (au-delà du MVP)',['../spec-gameplay.html#autotoc_md328',1,'']]],
  ['au_20gpu_20pas_20un_20changement_20de_20cible_84',['QRhi : une couche d&apos;accès au GPU, pas un changement de cible',['../guide-rendu.html#autotoc_md202',1,'']]],
  ['au_20jeu_20et_20outillage_85',['5. Intégration au jeu et outillage',['../spec-ia.html#autotoc_md338',1,'']]],
  ['au_20lancement_86',['Configurer le niveau minimal au lancement',['../guide-journalisation.html#autotoc_md150',1,'']]],
  ['au_20vertical_20slice_87',['Le chemin critique jusqu&apos;au &lt;em&gt;vertical slice&lt;/em&gt;',['../roadmap-010.html#autotoc_md464',1,'']]],
  ['aucun_20écran_20ne_20contraint_20la_20fenêtre_20lot_2073_88',['La taille : aucun écran ne contraint la fenêtre (LOT-73)',['../guide-ihm-qt.html#autotoc_md139',1,'']]],
  ['audio_89',['Audio',['../spec-rendu-technique.html#autotoc_md368',1,'5. Audio'],['../guide-audio.html',1,'Audio'],['../roadmap-010.html#autotoc_md589',1,'Audio']]],
  ['audio_90',['Crédits audio',['../md__2home_2runner_2work_2JustAnotherDnDGame_2JustAnotherDnDGame_2Source_2Elements_2Audio_2CREDITS.html',1,'']]],
  ['audio_2014_91',['Audio (14)',['../cahiertest.html#autotoc_md16',1,'']]],
  ['audio_20effets_20et_20version_200_202_200_92',['LOT-28 — Audio, effets et version &lt;span class=&quot;tt&quot;&gt;0.2.0&lt;/span&gt;',['../roadmap-010.html#lot-28',1,'']]],
  ['audit_20_3a_20hmi_3a_3alayervisibility_20lot_2051_93',['Isoler un calque pour l&apos;audit : &lt;span class=&quot;tt&quot;&gt;hmi::LayerVisibility&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;LOT-51&lt;/span&gt;)',['../guide-rendu.html#autotoc_md222',1,'']]],
  ['audit_20a_20révélé_20sur_20l_20état_20du_20dépôt_94',['9. Ce que l&apos;audit a révélé sur l&apos;état du dépôt',['../roadmap-010.html#autotoc_md474',1,'']]],
  ['auditer_20les_20calques_20sans_20les_20confondre_20avec_20f8_20lot_2051_95',['Le mode « définition des textures » : auditer les calques sans les confondre avec &lt;span class=&quot;tt&quot;&gt;F8&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;LOT-51&lt;/span&gt;)',['../guide-editeur.html#autotoc_md111',1,'']]],
  ['aussi_96',['aussi',['../guide-atelier-pixel-art.html#autotoc_md40',1,'Voir aussi'],['../guide-audio.html#autotoc_md47',1,'Voir aussi'],['../guide-boucle.html#autotoc_md57',1,'Voir aussi'],['../guide-design-ihm.html#autotoc_md74',1,'Voir aussi'],['../guide-ecrans.html#autotoc_md86',1,'Voir aussi'],['../guide-ecs.html#autotoc_md95',1,'Voir aussi'],['../guide-editeur.html#autotoc_md118',1,'Voir aussi'],['../guide-entrees.html#autotoc_md129',1,'Voir aussi'],['../guide-ihm-qt.html#autotoc_md141',1,'Voir aussi'],['../guide-journalisation.html#autotoc_md153',1,'Voir aussi'],['../guide-maths.html#autotoc_md160',1,'Voir aussi'],['../guide-niveaux.html#autotoc_md182',1,'Voir aussi'],['../guide-physique.html#autotoc_md200',1,'Voir aussi'],['../guide-rendu.html#autotoc_md244',1,'Voir aussi']]],
  ['automatisé_97',['11. Outillage qualité (automatisé)',['../spec-conventions.html#autotoc_md294',1,'']]],
  ['autres_98',['5. Récupérer les niveaux des autres',['../manuel-partager-niveau.html#autotoc_md626',1,'']]],
  ['aux_20axes_99',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Aabb.html&quot; title=&quot;core::Aabb&quot;&gt;Aabb&lt;/a&gt; : la boîte englobante alignée aux axes',['../guide-maths.html#autotoc_md157',1,'']]],
  ['aux_20entités_20_3a_20core_3a_3abuildlevelscene_20buildlevelscene_100',['De la grille aux entités : &lt;a class=&quot;el&quot; href=&quot;namespacecore.html#a69ac6b2c5ca32686a14824d1f1c04b2a&quot; title=&quot;core::buildLevelScene&quot;&gt;buildLevelScene&lt;/a&gt;',['../guide-niveaux.html#autotoc_md170',1,'']]],
  ['avancées_20au_20delà_20du_20mvp_101',['Mécaniques aériennes avancées (au-delà du MVP)',['../spec-gameplay.html#autotoc_md328',1,'']]],
  ['avancés_20lot_2031_102',['avancés LOT 31',['../spec-editeur.html#autotoc_md312',1,'9. Dangers avancés (&lt;span class=&quot;tt&quot;&gt;LOT-31&lt;/span&gt;)'],['../guide-niveaux.html#autotoc_md177',1,'Dangers avancés (&lt;span class=&quot;tt&quot;&gt;LOT-31&lt;/span&gt;)'],['../spec-gameplay.html#autotoc_md326',1,'Dangers avancés (&lt;span class=&quot;tt&quot;&gt;LOT-31&lt;/span&gt;)']]],
  ['avancement_103',['Avancement',['../index.html#autotoc_md3',1,'']]],
  ['avant_20d_20écrire_20jamais_20l_20inverse_104',['Enregistrer : valider avant d&apos;écrire, jamais l&apos;inverse',['../guide-editeur.html#autotoc_md108',1,'']]],
  ['avant_20de_20l_20avoir_20posé_105',['Voir le raccord avant de l&apos;avoir posé',['../guide-atelier-pixel-art.html#autotoc_md38',1,'']]],
  ['avant_20données_106',['2. Contrats avant données',['../spec-contenu.html#autotoc_md267',1,'']]],
  ['avec_20clamp_20direct_107',['Méthode retenue : balayage &lt;b&gt;par axe&lt;/b&gt; avec clamp direct',['../guide-physique.html#autotoc_md186',1,'']]],
  ['avec_20f8_20lot_2051_108',['Le mode « définition des textures » : auditer les calques sans les confondre avec &lt;span class=&quot;tt&quot;&gt;F8&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;LOT-51&lt;/span&gt;)',['../guide-editeur.html#autotoc_md111',1,'']]],
  ['avec_20le_20jeu_20et_20observabilité_109',['2. Pont avec le jeu et observabilité',['../spec-ia.html#autotoc_md335',1,'']]],
  ['avec_20un_20piège_110',['&lt;a class=&quot;el&quot; href=&quot;classcore_1_1LevelWriter.html&quot; title=&quot;core::LevelWriter&quot;&gt;core::LevelWriter&lt;/a&gt; : l&apos;inverse du chargement, avec un piège',['../guide-editeur.html#autotoc_md100',1,'']]],
  ['aventuriers_20_3a_20rangs_20et_20contrats_111',['&lt;span class=&quot;tt&quot;&gt;LOT-45&lt;/span&gt; — Guilde des Aventuriers : rangs et contrats',['../roadmap-010.html#lot-45',1,'']]],
  ['avoir_20posé_112',['Voir le raccord avant de l&apos;avoir posé',['../guide-atelier-pixel-art.html#autotoc_md38',1,'']]],
  ['axe_20_3a_20la_20mémoire_20de_20texture_20des_20plans_20lot_2069_113',['Le second axe : la mémoire de texture des plans (&lt;span class=&quot;tt&quot;&gt;LOT-69&lt;/span&gt;)',['../guide-rendu.html#autotoc_md241',1,'']]],
  ['axe_20avec_20clamp_20direct_114',['Méthode retenue : balayage &lt;b&gt;par axe&lt;/b&gt; avec clamp direct',['../guide-physique.html#autotoc_md186',1,'']]],
  ['axes_115',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Aabb.html&quot; title=&quot;core::Aabb&quot;&gt;Aabb&lt;/a&gt; : la boîte englobante alignée aux axes',['../guide-maths.html#autotoc_md157',1,'']]]
];
