var searchData=
[
  ['sélection_20de_20niveau_0',['Progression et sélection de niveau',['../manuel-jouer.html#autotoc_md537',1,'']]],
  ['sélection_20de_20niveau_20et_20progression_20persistée_20lot_2059_20tache_2005_2006_1',['Sélection de niveau et progression persistée (&lt;span class=&quot;tt&quot;&gt;LOT-59&lt;/span&gt; TACHE-05/06)',['../guide-ecrans.html#autotoc_md81',1,'']]],
  ['séparés_20du_20canevas_2',['La palette et les outils : des panneaux Qt séparés du canevas',['../guide-editeur.html#autotoc_md102',1,'']]],
  ['séquence_3',['Fin de niveau et fin de séquence',['../guide-ecrans.html#autotoc_md80',1,'']]],
  ['séquence_20de_20niveaux_20donnée_20de_20contenu_20lot_2059_4',['Séquence de niveaux (donnée de contenu, &lt;span class=&quot;tt&quot;&gt;LOT-59&lt;/span&gt;)',['../guide-niveaux.html#autotoc_md179',1,'']]],
  ['séquencement_5',['4. Périmètre &amp;amp; séquencement',['../spec-decors.html#autotoc_md288',1,'']]],
  ['s_20insère_20dans_20la_20boucle_6',['Où ça s&apos;insère dans la boucle',['../guide-ecrans.html#autotoc_md85',1,'']]],
  ['sa_20propre_20catégorie_7',['Chaque module a sa propre catégorie',['../guide-journalisation.html#autotoc_md147',1,'']]],
  ['sait_20pas_20faire_8',['Ce qu&apos;une feuille de style ne sait pas faire',['../guide-design-ihm.html#autotoc_md72',1,'']]],
  ['salle_20»_9',['Mélanger plusieurs tailles de caméra dans un même niveau (mode « Par salle »)',['../manuel-partager-niveau.html#autotoc_md555',1,'']]],
  ['salles_20lot_2032_10',['10. Niveaux à salles (&lt;span class=&quot;tt&quot;&gt;LOT-32&lt;/span&gt;)',['../spec-editeur.html#autotoc_md301',1,'']]],
  ['sans_20dupliquer_20la_20logique_20de_20peinture_20_3a_20core_3a_3aleveldraft_3a_3apaintregion_20leveldraft_3a_3apaintregion_11',['Peindre par lot sans dupliquer la logique de peinture : &lt;a class=&quot;el&quot; href=&quot;classcore_1_1LevelDraft.html#a7fb667e044067f5e9bf16f747d3f5f8e&quot; title=&quot;core::LevelDraft::paintRegion&quot;&gt;LevelDraft::paintRegion&lt;/a&gt;',['../guide-editeur.html#autotoc_md105',1,'']]],
  ['sans_20jamais_20laisser_20de_20fichier_20tronqué_12',['Écrire un PNG sans jamais laisser de fichier tronqué',['../guide-atelier-pixel-art.html#autotoc_md32',1,'']]],
  ['sans_20les_20confondre_20avec_20f8_20lot_2051_13',['Le mode « définition des textures » : auditer les calques sans les confondre avec &lt;span class=&quot;tt&quot;&gt;F8&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;LOT-51&lt;/span&gt;)',['../guide-editeur.html#autotoc_md111',1,'']]],
  ['sans_20ligne_20de_20commande_14',['Créer et partager un niveau (sans ligne de commande)',['../manuel-partager-niveau.html',1,'manuel']]],
  ['sans_20pas_20de_20simulation_20et_20les_20entrées_15',['Les frames sans pas de simulation et les entrées',['../guide-boucle.html#autotoc_md55',1,'']]],
  ['sans_20perdre_20un_20pas_16',['Pause : suspendre sans perdre un pas',['../guide-ecrans.html#autotoc_md79',1,'']]],
  ['sans_20quitter_20l_20éditeur_17',['Essai immédiat : jouer sans quitter l&apos;éditeur',['../guide-editeur.html#autotoc_md107',1,'']]],
  ['sans_20re_20coder_20le_20moteur_18',['Le problème : éditer un niveau sans (re)coder le moteur',['../guide-editeur.html#autotoc_md96',1,'']]],
  ['saut_20et_20game_20feel_19',['4. Saut et &lt;em&gt;game feel&lt;/em&gt;',['../guide-physique.html#autotoc_md196',1,'']]],
  ['sauvegarde_20',['Validation &amp;amp; sauvegarde',['../manuel-mode-ia.html#autotoc_md548',1,'']]],
  ['sauvegarde_20riche_21',['LOT-17 — Sauvegarde riche',['../lot-17.html',1,'lots']]],
  ['scène_20_3a_20hmi_3a_3abitmapfont_20et_20hmi_3a_3atextrenderer_20lot_2052_22',['Le texte dans la scène : &lt;span class=&quot;tt&quot;&gt;hmi::BitmapFont&lt;/span&gt; et &lt;span class=&quot;tt&quot;&gt;hmi::TextRenderer&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;LOT-52&lt;/span&gt;)',['../guide-rendu.html#autotoc_md231',1,'']]],
  ['se_20lier_20à_20qui_23',['Mécanismes : qui a le droit de se lier à qui',['../guide-editeur.html#autotoc_md98',1,'']]],
  ['se_20tromper_24',['Les règles à ne pas se tromper',['../lot-21.html#autotoc_md481',1,'']]],
  ['se_20voit_20_3a_20le_20culling_20lot_2040_25',['Ne dessiner que ce qui se voit : le culling (&lt;span class=&quot;tt&quot;&gt;LOT-40&lt;/span&gt;)',['../guide-rendu.html#autotoc_md220',1,'']]],
  ['second_20axe_20_3a_20la_20mémoire_20de_20texture_20des_20plans_20lot_2069_26',['Le second axe : la mémoire de texture des plans (&lt;span class=&quot;tt&quot;&gt;LOT-69&lt;/span&gt;)',['../guide-rendu.html#autotoc_md241',1,'']]],
  ['second_20temps_20du_20lot_2065_27',['De la couverture à la profondeur (second temps du &lt;span class=&quot;tt&quot;&gt;LOT-65&lt;/span&gt;)',['../guide-niveaux.html#autotoc_md181',1,'']]],
  ['seconde_20source_20fusionnée_20en_20lecture_20ex_20ctrl_20002_20lot_2020_28',['La manette : une seconde source, fusionnée en lecture (EX-CTRL-002, LOT-20)',['../guide-entrees.html#autotoc_md125',1,'']]],
  ['secousse_20d_20écran_20hmi_3a_3acamera2d_29',['Le rendu (&lt;span class=&quot;tt&quot;&gt;hmi::ParticleRenderer&lt;/span&gt;) et la secousse d&apos;écran (&lt;span class=&quot;tt&quot;&gt;hmi::Camera2D&lt;/span&gt;)',['../guide-rendu.html#autotoc_md236',1,'']]],
  ['secousse_20d_20écran_20lot_2053_30',['Particules et secousse d&apos;écran (&lt;span class=&quot;tt&quot;&gt;LOT-53&lt;/span&gt;)',['../guide-rendu.html#autotoc_md233',1,'']]],
  ['segment_20orienté_20liens_20de_20mécanismes_20lot_2037_31',['&lt;a class=&quot;el&quot; href=&quot;structhmi_1_1LineQuad.html&quot; title=&quot;hmi::LineQuad&quot;&gt;LineQuad&lt;/a&gt; : un segment orienté (liens de mécanismes, &lt;span class=&quot;tt&quot;&gt;LOT-37&lt;/span&gt;)',['../guide-rendu.html#autotoc_md212',1,'']]],
  ['ses_20fichiers_20de_20niveaux_32',['Gérer ses fichiers de niveaux',['../guide-editeur.html#autotoc_md117',1,'']]],
  ['set_20core_3a_3acomponentpool_33',['Le stockage : sparse set (core::ComponentPool&amp;lt;T&amp;gt;)',['../guide-ecs.html#autotoc_md90',1,'']]],
  ['seule_20cible_20_3a_20l_20application_20qt_34',['Une seule cible : l&apos;application Qt',['../guide-ihm-qt.html#autotoc_md131',1,'']]],
  ['seule_20hmilib_20»_35',['Le découpage retenu — et pourquoi il n&apos;est pas « une seule &lt;span class=&quot;tt&quot;&gt;HmiLib&lt;/span&gt; »',['../lot-02.html#autotoc_md370',1,'']]],
  ['seule_20paire_20annuler_20refaire_20deux_20cibles_36',['Une seule paire Annuler/Refaire, deux cibles',['../guide-atelier-pixel-art.html#autotoc_md39',1,'']]],
  ['seule_20source_20deux_20portées_20étanches_37',['Les jetons : une seule source, deux portées étanches',['../guide-design-ihm.html#autotoc_md59',1,'']]],
  ['seulement_20là_20où_20la_20caméra_20défile_38',['Parallaxe : portée par le plan, bornée, et seulement là où la caméra défile',['../guide-rendu.html#autotoc_md227',1,'']]],
  ['seulement_20l_20état_39',['Détecter les fronts, pas seulement l&apos;état',['../guide-entrees.html#autotoc_md121',1,'']]],
  ['seulement_20l_20arrivée_40',['La solution : tester tout le trajet, pas seulement l&apos;arrivée',['../guide-physique.html#autotoc_md185',1,'']]],
  ['shaders_20et_20échantillonnage_20nearest_41',['Sommets, shaders, et échantillonnage &lt;em&gt;nearest&lt;/em&gt;',['../guide-rendu.html#autotoc_md211',1,'']]],
  ['signaux_42',['Qui déclenche les transitions : les signaux',['../guide-ecrans.html#autotoc_md77',1,'']]],
  ['simples_20dans_20le_20cpp_43',['Doxygen dans le header, commentaires simples // dans le .cpp',['../spec-conventions.html#autotoc_md276',1,'']]],
  ['simulation_44',['Conséquence pratique pour tout le code de simulation',['../guide-boucle.html#autotoc_md56',1,'']]],
  ['simulation_20—_20test_5fboucle_5fsimulation_20cpp_202_45',['Boucle Simulation — &lt;span class=&quot;tt&quot;&gt;test_boucle_simulation.cpp&lt;/span&gt; (2)',['../cahiertest.html#autotoc_md26',1,'']]],
  ['simulation_20↔_20rendu_46',['4. Frontière simulation ↔ rendu',['../spec-architecture.html#autotoc_md251',1,'']]],
  ['simulation_20et_20les_20entrées_47',['Les frames sans pas de simulation et les entrées',['../guide-boucle.html#autotoc_md55',1,'']]],
  ['sinks_20_3a_20où_20finissent_20les_20messages_48',['Les sinks : où finissent les messages',['../guide-journalisation.html#autotoc_md145',1,'']]],
  ['sinks_20différents_20en_20développement_20et_20en_20release_49',['Bootstrap réel : sinks différents en développement et en Release',['../guide-journalisation.html#autotoc_md151',1,'']]],
  ['slice_50',['slice',['../spec-vision.html#autotoc_md355',1,'Hors périmètre (&lt;em&gt;vertical slice&lt;/em&gt;)'],['../lot-27.html',1,'LOT-27 — Contenu du *vertical slice*'],['../spec-vision.html#autotoc_md353',1,'Objectifs (&lt;em&gt;vertical slice&lt;/em&gt;)']]],
  ['slide_51',['6. Wall jump et wall slide',['../guide-physique.html#autotoc_md198',1,'']]],
  ['socle_20_3a_20hmi_3a_3aaudioengine_52',['Le socle : &lt;span class=&quot;tt&quot;&gt;hmi::AudioEngine&lt;/span&gt;',['../guide-audio.html#autotoc_md42',1,'']]],
  ['socle_20applicatif_53',['1. Socle applicatif',['../spec-interface-ihm.html#autotoc_md327',1,'']]],
  ['socle_20applicatif_20viewport_20direct3d_2011_54',['IHM Qt (refonte) — socle applicatif &amp;amp; viewport Direct3D 11',['../guide-ihm-qt.html',1,'guide']]],
  ['socle_20déterministe_55',['Le socle déterministe',['../lot-12.html#autotoc_md433',1,'']]],
  ['solide_56',['Pourquoi une pente (ou un arrondi) n&apos;est jamais solide',['../guide-physique.html#autotoc_md190',1,'']]],
  ['solution_20_3a_20tester_20tout_20le_20trajet_20pas_20seulement_20l_20arrivée_57',['La solution : tester tout le trajet, pas seulement l&apos;arrivée',['../guide-physique.html#autotoc_md185',1,'']]],
  ['solveur_20ia_58',['Solveur IA',['../spec-ia.html',1,'specifications']]],
  ['sombre_59',['Thème clair/sombre',['../guide-design-ihm.html#autotoc_md64',1,'']]],
  ['sommets_20shaders_20et_20échantillonnage_20nearest_60',['Sommets, shaders, et échantillonnage &lt;em&gt;nearest&lt;/em&gt;',['../guide-rendu.html#autotoc_md211',1,'']]],
  ['son_20repli_20procédural_61',['Le pipeline de textures depuis fichiers, et son repli procédural',['../guide-rendu.html#autotoc_md214',1,'']]],
  ['sorts_20et_20capacités_20de_20classe_62',['LOT-25 — Sorts et capacités de classe',['../lot-25.html',1,'lots']]],
  ['source_63',['Chemins complets depuis Source/',['../spec-conventions.html#autotoc_md269',1,'']]],
  ['source_20deux_20portées_20étanches_64',['Les jetons : une seule source, deux portées étanches',['../guide-design-ihm.html#autotoc_md59',1,'']]],
  ['source_20elements_20assets_20_3a_20convention_20et_20régénération_65',['&lt;span class=&quot;tt&quot;&gt;Source/Elements/Assets/&lt;/span&gt; : convention et régénération',['../guide-rendu.html#autotoc_md215',1,'']]],
  ['source_20fusionnée_20en_20lecture_20ex_20ctrl_20002_20lot_2020_66',['La manette : une seconde source, fusionnée en lecture (EX-CTRL-002, LOT-20)',['../guide-entrees.html#autotoc_md125',1,'']]],
  ['source_20test_20unit_20hmi_20graphics_20test_5frender_5fbudget_20cpp_67',['Le test de non-régression du volume (&lt;span class=&quot;tt&quot;&gt;Source/Test/Unit/HMI/Graphics/test_render_budget.cpp&lt;/span&gt;)',['../guide-rendu.html#autotoc_md240',1,'']]],
  ['souvent_20oublié_68',['Le critère qui est souvent oublié',['../lot-24.html#autotoc_md498',1,'']]],
  ['spécifications_69',['Spécifications',['../specifications.html',1,'index']]],
  ['sparse_20set_20core_3a_3acomponentpool_70',['Le stockage : sparse set (core::ComponentPool&amp;lt;T&amp;gt;)',['../guide-ecs.html#autotoc_md90',1,'']]],
  ['spirale_20de_20la_20mort_20»_71',['La « spirale de la mort »',['../guide-boucle.html#autotoc_md53',1,'']]],
  ['sprite_20à_20la_20fois_72',['Pourquoi « batcher » plutôt que dessiner un sprite à la fois',['../guide-rendu.html#autotoc_md209',1,'']]],
  ['spritequad_20_3a_20un_20rectangle_20texturé_73',['&lt;a class=&quot;el&quot; href=&quot;structhmi_1_1SpriteQuad.html&quot; title=&quot;hmi::SpriteQuad&quot;&gt;SpriteQuad&lt;/a&gt; : un rectangle texturé',['../guide-rendu.html#autotoc_md210',1,'']]],
  ['sprites_20_3a_20hmi_3a_3aspritebatch_20hmi_3a_3aspritebatch_74',['Le pipeline de dessin de sprites : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1SpriteBatch.html&quot; title=&quot;hmi::SpriteBatch&quot;&gt;hmi::SpriteBatch&lt;/a&gt;',['../guide-rendu.html#autotoc_md208',1,'']]],
  ['spritesheet_20chargé_20depuis_20un_20fichier_75',['&lt;a class=&quot;el&quot; href=&quot;classhmi_1_1TextureAtlas.html&quot; title=&quot;hmi::TextureAtlas&quot;&gt;hmi::TextureAtlas&lt;/a&gt; : un spritesheet, chargé depuis un fichier',['../guide-rendu.html#autotoc_md213',1,'']]],
  ['spritesheet_20externe_20et_20découplage_20image_20hitbox_76',['&lt;span class=&quot;tt&quot;&gt;LOT-48&lt;/span&gt; : spritesheet externe et découplage image/hitbox',['../guide-rendu.html#autotoc_md217',1,'']]],
  ['standard_77',['1. Langage &amp;amp; standard',['../spec-conventions.html#autotoc_md265',1,'']]],
  ['stats_20csv_78',['Le fichier &lt;span class=&quot;tt&quot;&gt;stats.csv&lt;/span&gt;',['../manuel-mode-ia.html#autotoc_md546',1,'']]],
  ['stockage_20_3a_20sparse_20set_20core_3a_3acomponentpool_79',['Le stockage : sparse set (core::ComponentPool&amp;lt;T&amp;gt;)',['../guide-ecs.html#autotoc_md90',1,'']]],
  ['stricte_20est_20dangereuse_80',['Comparaison flottante : pourquoi l&apos;égalité stricte est dangereuse',['../guide-maths.html#autotoc_md159',1,'']]],
  ['structurée_81',['Une barre d&apos;état structurée',['../guide-design-ihm.html#autotoc_md66',1,'']]],
  ['structure_20ce_20lot_82',['La décision qui structure ce lot',['../lot-18.html#autotoc_md463',1,'']]],
  ['style_20ne_20sait_20pas_20faire_83',['Ce qu&apos;une feuille de style ne sait pas faire',['../guide-design-ihm.html#autotoc_md72',1,'']]],
  ['suit_20le_20joueur_84',['Choisir comment la caméra suit le joueur',['../manuel-partager-niveau.html#autotoc_md554',1,'']]],
  ['suite_85',['Pourquoi ce lot peut démarrer tout de suite',['../lot-12.html#autotoc_md431',1,'']]],
  ['suivent_20l_20outil_86',['Des panneaux groupés, et qui suivent l&apos;outil',['../guide-design-ihm.html#autotoc_md67',1,'']]],
  ['suivi_20de_20pente_20et_20d_20arrondi_20ex_20gp_20003_20ex_20gp_20004_87',['2. Suivi de pente et d&apos;arrondi (EX-GP-003, EX-GP-004)',['../guide-physique.html#autotoc_md189',1,'']]],
  ['suivi_20réglable_20ex_20lvl_20007_20ex_20ren_20017_88',['Mélanger plusieurs tailles de caméra : zones dessinées à la main et taille de suivi réglable (&lt;span class=&quot;tt&quot;&gt;EX-LVL-007&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;EX-REN-017&lt;/span&gt;)',['../guide-rendu.html#autotoc_md207',1,'']]],
  ['suppression_20_3a_20swap_20and_20pop_89',['Ajout et suppression : &lt;em&gt;swap-and-pop&lt;/em&gt;',['../guide-ecs.html#autotoc_md91',1,'']]],
  ['supprimé_90',['Supprimé',['../lot-01.html#autotoc_md362',1,'']]],
  ['sur_20un_20tampon_20de_20pixels_91',['Les outils : des fonctions pures sur un tampon de pixels',['../guide-atelier-pixel-art.html#autotoc_md33',1,'']]],
  ['surface_20de_20dessin_20_3a_20le_20viewport_20qt_20hmi_3a_3agameviewport_92',['La surface de dessin : le viewport Qt (&lt;span class=&quot;tt&quot;&gt;hmi::GameViewport&lt;/span&gt;)',['../guide-rendu.html#autotoc_md203',1,'']]],
  ['surfaces_93',['Les commandes : une définition, trois surfaces',['../guide-design-ihm.html#autotoc_md62',1,'']]],
  ['surfaces_20et_20espaces_20de_20travail_20lot_2068_94',['Hiérarchie des surfaces, et espaces de travail (LOT-68)',['../guide-design-ihm.html#autotoc_md73',1,'']]],
  ['suspendre_20sans_20perdre_20un_20pas_95',['Pause : suspendre sans perdre un pas',['../guide-ecrans.html#autotoc_md79',1,'']]],
  ['swap_20and_20pop_96',['Ajout et suppression : &lt;em&gt;swap-and-pop&lt;/em&gt;',['../guide-ecs.html#autotoc_md91',1,'']]],
  ['swap_20chain_20back_20buffer_97',['Vocabulaire de base : GPU, swap chain, back buffer',['../guide-rendu.html#autotoc_md201',1,'']]],
  ['swept_20aabb_98',['1. Collision par balayage continu (swept AABB)',['../guide-physique.html#autotoc_md183',1,'']]],
  ['système_202_99',['Tests système (2)',['../cahiertest.html#autotoc_md29',1,'']]],
  ['système_20de_20design_100',['Pourquoi un système de design',['../guide-design-ihm.html#autotoc_md58',1,'']]],
  ['système_20de_20design_20et_20architecture_20de_20l_20information_101',['Système de design et architecture de l&apos;information',['../guide-design-ihm.html',1,'guide']]],
  ['système_20de_20design_20et_20habillage_20lot_2056_102',['6. Système de design et habillage (LOT-56)',['../spec-interface-ihm.html#autotoc_md332',1,'']]],
  ['systèmes_103',['systèmes',['../spec-architecture.html#autotoc_md255',1,'8. Communication inter-systèmes'],['../guide-ecs.html',1,'ECS : entités, composants, systèmes']]],
  ['systèmes_20de_20coordonnées_20à_20ne_20pas_20confondre_104',['Deux systèmes de coordonnées à ne pas confondre',['../guide-niveaux.html#autotoc_md162',1,'']]],
  ['systèmes_20et_20l_20ordre_20d_20exécution_105',['Les systèmes et l&apos;ordre d&apos;exécution',['../guide-ecs.html#autotoc_md94',1,'']]]
];
