var searchData=
[
  ['f8_20lot_2051_0',['Le mode « définition des textures » : auditer les calques sans les confondre avec &lt;span class=&quot;tt&quot;&gt;F8&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;LOT-51&lt;/span&gt;)',['../guide-editeur.html#autotoc_md112',1,'']]],
  ['f9_1',['Compteur de diagnostic en jeu (&lt;span class=&quot;tt&quot;&gt;F9&lt;/span&gt;)',['../guide-rendu.html#autotoc_md244',1,'']]],
  ['facteur_20d_20interpolation_2',['Interpoler le mouvement : &lt;span class=&quot;tt&quot;&gt;hmi::PreviousPosition&lt;/span&gt; et le facteur d&apos;interpolation',['../guide-rendu.html#autotoc_md224',1,'']]],
  ['factions_20panthéon_20et_20organisations_3',['&lt;span class=&quot;tt&quot;&gt;LOT-80&lt;/span&gt; — Factions, panthéon et organisations',['../roadmap-010.html#lot-80',1,'']]],
  ['faire_4',['Ce qu&apos;une feuille de style ne sait pas faire',['../guide-design-ihm.html#autotoc_md73',1,'']]],
  ['fait_20l_20ia_20en_20une_20phrase_5',['Ce que fait l&apos;IA, en une phrase',['../manuel-mode-ia.html#autotoc_md625',1,'']]],
  ['fait_20la_20qualité_20de_20ce_20lot_6',['Ce qui fait la qualité de ce lot',['../roadmap-010.html#autotoc_md535',1,'']]],
  ['faite_7',['Comment la classification a été faite',['../lot-78.html#autotoc_md448',1,'']]],
  ['familles_20d_20exigences_20sont_20fantômes_20—_20le_20lint_20le_20dit_20désormais_8',['9.1 Cinq familles d&apos;exigences sont fantômes — le lint le dit désormais',['../roadmap-010.html#autotoc_md491',1,'']]],
  ['fantômes_20—_20le_20lint_20le_20dit_20désormais_9',['9.1 Cinq familles d&apos;exigences sont fantômes — le lint le dit désormais',['../roadmap-010.html#autotoc_md491',1,'']]],
  ['faut_20anticiper_20tant_20que_20rien_20n_20est_20construit_10',['10. Ce qu&apos;il faut anticiper, tant que rien n&apos;est construit',['../roadmap-010.html#autotoc_md497',1,'']]],
  ['faut_20pas_20réécrire_11',['Ce qui existe déjà, et qu&apos;il ne faut pas réécrire',['../lot-06.html#autotoc_md424',1,'']]],
  ['feel_12',['4. Saut et &lt;em&gt;game feel&lt;/em&gt;',['../guide-physique.html#autotoc_md197',1,'']]],
  ['feel_20—_20⚠️_20réglage_20fin_20reporté_20au_20delà_20de_200_201_200_13',['Ressenti (game feel) — ⚠️ réglage fin reporté au-delà de &lt;span class=&quot;tt&quot;&gt;0.1.0&lt;/span&gt;',['../spec-gameplay.html#autotoc_md330',1,'']]],
  ['fenêtre_14',['Cadrer un niveau plus grand que la fenêtre',['../guide-editeur.html#autotoc_md111',1,'']]],
  ['fenêtre_20_3a_20fitzoom_20et_20hmi_3a_3aroomgrid_15',['Cadrer un contenu plus grand que la fenêtre : &lt;span class=&quot;tt&quot;&gt;fitZoom&lt;/span&gt; et &lt;span class=&quot;tt&quot;&gt;hmi::RoomGrid&lt;/span&gt;',['../guide-rendu.html#autotoc_md206',1,'']]],
  ['fenêtre_20lot_2073_16',['La taille : aucun écran ne contraint la fenêtre (LOT-73)',['../guide-ihm-qt.html#autotoc_md140',1,'']]],
  ['fenêtre_20qt_17',['Le viewport : Direct3D 11 dans une fenêtre Qt',['../guide-ihm-qt.html#autotoc_md133',1,'']]],
  ['feuille_20de_20route_18',['Feuille de route',['../lots.html#autotoc_md457',1,'']]],
  ['feuille_20de_20route_200_201_200_19',['Feuille de route 0.1.0',['../roadmap-010.html',1,'lots']]],
  ['feuille_20de_20style_20ne_20sait_20pas_20faire_20',['Ce qu&apos;une feuille de style ne sait pas faire',['../guide-design-ihm.html#autotoc_md73',1,'']]],
  ['feuille_20par_20portée_20et_20pourquoi_20lot_2073_21',['Une feuille par portée, et pourquoi (LOT-73)',['../guide-design-ihm.html#autotoc_md70',1,'']]],
  ['fiche_22',['1. La fiche',['../spec-rpg.html#autotoc_md371',1,'']]],
  ['fiche_20de_20personnage_23',['LOT-13 — Fiche de personnage',['../roadmap-010.html#lot-13',1,'']]],
  ['fiche_20de_20personnage_20_3a_20maquette_20et_20interface_24',['&lt;span class=&quot;tt&quot;&gt;LOT-38&lt;/span&gt; — Fiche de personnage : maquette et interface',['../roadmap-010.html#lot-38',1,'']]],
  ['fichier_25',['&lt;a class=&quot;el&quot; href=&quot;classhmi_1_1TextureAtlas.html&quot; title=&quot;hmi::TextureAtlas&quot;&gt;hmi::TextureAtlas&lt;/a&gt; : un spritesheet, chargé depuis un fichier',['../guide-rendu.html#autotoc_md214',1,'']]],
  ['fichier_20stats_20csv_26',['Le fichier &lt;span class=&quot;tt&quot;&gt;stats.csv&lt;/span&gt;',['../manuel-mode-ia.html#autotoc_md631',1,'']]],
  ['fichier_20tronqué_27',['Écrire un PNG sans jamais laisser de fichier tronqué',['../guide-atelier-pixel-art.html#autotoc_md33',1,'']]],
  ['fichiers_28',['Cycle de vie des fichiers',['../guide-editeur.html#autotoc_md115',1,'']]],
  ['fichiers_20de_20niveaux_29',['Gérer ses fichiers de niveaux',['../guide-editeur.html#autotoc_md118',1,'']]],
  ['fichiers_20et_20son_20repli_20procédural_30',['Le pipeline de textures depuis fichiers, et son repli procédural',['../guide-rendu.html#autotoc_md215',1,'']]],
  ['filière_20contenu_31',['5. Programme de lots proposé — la filière contenu',['../roadmap-010.html#autotoc_md470',1,'']]],
  ['filtrer_20puis_20diffuser_32',['&lt;a class=&quot;el&quot; href=&quot;classcore_1_1Logger.html&quot; title=&quot;core::Logger&quot;&gt;core::Logger&lt;/a&gt; : filtrer puis diffuser',['../guide-journalisation.html#autotoc_md145',1,'']]],
  ['fin_20de_20niveau_33',['4. Conditions de fin de niveau',['../spec-gameplay.html#autotoc_md332',1,'']]],
  ['fin_20de_20niveau_20et_20fin_20de_20séquence_34',['Fin de niveau et fin de séquence',['../guide-ecrans.html#autotoc_md81',1,'']]],
  ['fin_20de_20séquence_35',['Fin de niveau et fin de séquence',['../guide-ecrans.html#autotoc_md81',1,'']]],
  ['fin_20reporté_20au_20delà_20de_200_201_200_36',['Ressenti (game feel) — ⚠️ réglage fin reporté au-delà de &lt;span class=&quot;tt&quot;&gt;0.1.0&lt;/span&gt;',['../spec-gameplay.html#autotoc_md330',1,'']]],
  ['finissent_20les_20messages_37',['Les sinks : où finissent les messages',['../guide-journalisation.html#autotoc_md146',1,'']]],
  ['fins_38',['Les trois fins',['../roadmap-010.html#autotoc_md563',1,'']]],
  ['fitzoom_20et_20hmi_3a_3aroomgrid_39',['Cadrer un contenu plus grand que la fenêtre : &lt;span class=&quot;tt&quot;&gt;fitZoom&lt;/span&gt; et &lt;span class=&quot;tt&quot;&gt;hmi::RoomGrid&lt;/span&gt;',['../guide-rendu.html#autotoc_md206',1,'']]],
  ['fixe_40',['fixe',['../guide-boucle.html',1,'Boucle de jeu et pas de temps fixe'],['../guide-boucle.html#autotoc_md51',1,'Le principe du pas de temps fixe']]],
  ['fixe_20est_20préservé_41',['La boucle : Qt pilote, le pas fixe est préservé',['../guide-ihm-qt.html#autotoc_md134',1,'']]],
  ['flottante_20_3a_20pourquoi_20l_20égalité_20stricte_20est_20dangereuse_42',['Comparaison flottante : pourquoi l&apos;égalité stricte est dangereuse',['../guide-maths.html#autotoc_md160',1,'']]],
  ['fois_43',['Pourquoi « batcher » plutôt que dessiner un sprite à la fois',['../guide-rendu.html#autotoc_md210',1,'']]],
  ['fois_20de_20plus_44',['La règle d&apos;or, une fois de plus',['../guide-audio.html#autotoc_md42',1,'']]],
  ['fonctionne_20la_20population_20algorithme_20évolutif_45',['Comment fonctionne la population (algorithme Évolutif)',['../manuel-mode-ia.html#autotoc_md629',1,'']]],
  ['fonctionnelles_46',['fonctionnelles',['../spec-editeur.html#autotoc_md304',1,'1. Exigences fonctionnelles'],['../spec-exigences.html',1,'Exigences non fonctionnelles']]],
  ['fonctions_20libres_47',['Classes plutôt que fonctions libres',['../spec-conventions.html#autotoc_md286',1,'']]],
  ['fonctions_20pures_20sur_20un_20tampon_20de_20pixels_48',['Les outils : des fonctions pures sur un tampon de pixels',['../guide-atelier-pixel-art.html#autotoc_md34',1,'']]],
  ['fondations_20numériques_49',['1. Fondations numériques',['../spec-ia.html#autotoc_md335',1,'']]],
  ['forcément_20conforme_50',['Créer un asset à une taille forcément conforme',['../guide-atelier-pixel-art.html#autotoc_md38',1,'']]],
  ['fork_20purge_20et_20remise_20à_20nu_51',['LOT-01 — Fork, purge et remise à nu',['../lot-01.html',1,'lots']]],
  ['format_52',['Règles de format',['../roadmap-010.html#autotoc_md546',1,'']]],
  ['format_20d_20une_20ligne_20_3a_20core_3a_3aformatlogline_20core_3a_3aformatlogline_53',['Le format d&apos;une ligne : &lt;a class=&quot;el&quot; href=&quot;namespacecore.html#aafa85d91ee91c84b123fff01f147615e&quot; title=&quot;core::formatLogLine&quot;&gt;core::formatLogLine&lt;/a&gt;',['../guide-journalisation.html#autotoc_md150',1,'']]],
  ['format_20de_20carte_20version_3a_203_20multi_20couches_54',['LOT-04 — Format de carte `version: 3`, multi-couches',['../lot-04.html',1,'lots']]],
  ['format_20retenu_20json_20liste_20de_20tuiles_20objets_55',['Format retenu (JSON, liste de tuiles-objets)',['../spec-niveaux.html#autotoc_md354',1,'']]],
  ['forme_56',['3. Mise en forme',['../spec-conventions.html#autotoc_md280',1,'']]],
  ['fort_20levier_20du_20programme_57',['9.3 L&apos;allègement est le geste à plus fort levier du programme',['../roadmap-010.html#autotoc_md493',1,'']]],
  ['fou_20de_20couverture_20des_20mécaniques_20ex_20lvl_20015_20lot_2065_58',['Garde-fou de couverture des mécaniques (&lt;span class=&quot;tt&quot;&gt;EX-LVL-015&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;LOT-65&lt;/span&gt;)',['../guide-niveaux.html#autotoc_md181',1,'']]],
  ['fous_20contre_20la_20perte_20de_20travail_59',['Garde-fous contre la perte de travail',['../guide-editeur.html#autotoc_md110',1,'']]],
  ['fréquentes_60',['Questions fréquentes',['../manuel-mode-ia.html#autotoc_md635',1,'']]],
  ['frame_61',['Le cycle d&apos;une frame',['../guide-entrees.html#autotoc_md123',1,'']]],
  ['frame_20complète_62',['Assembler la frame complète',['../guide-rendu.html#autotoc_md238',1,'']]],
  ['framerate_20variable_63',['Le piège du framerate variable',['../guide-boucle.html#autotoc_md50',1,'']]],
  ['frames_20sans_20pas_20de_20simulation_20et_20les_20entrées_64',['Les frames sans pas de simulation et les entrées',['../guide-boucle.html#autotoc_md56',1,'']]],
  ['frontière_20simulation_20↔_20rendu_65',['4. Frontière simulation ↔ rendu',['../spec-architecture.html#autotoc_md252',1,'']]],
  ['fronts_20pas_20seulement_20l_20état_66',['Détecter les fronts, pas seulement l&apos;état',['../guide-entrees.html#autotoc_md122',1,'']]],
  ['fusionnée_20en_20lecture_20ex_20ctrl_20002_20lot_2020_67',['La manette : une seconde source, fusionnée en lecture (EX-CTRL-002, LOT-20)',['../guide-entrees.html#autotoc_md126',1,'']]]
];
