name: Temporary CMake Gate

on:
  push:
    branches:
      - fix/qt-designer-6.8.7-compatibility

permissions:
  contents: read

jobs:
  configure-build-test:
    runs-on: windows-2022
    env:
      QT_VERSION: '6.11.2'
      AQT_SOURCE: 'git+https://github.com/miurahr/aqtinstall.git@16db45a70b5905ad596941b223469bc86a56901e'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: windows
          target: desktop
          arch: win64_msvc2022_64
          modules: qtmultimedia qtshadertools qtcanvaspainter
          cache: true
          aqtsource: ${{ env.AQT_SOURCE }}

      - name: Configure Ninja
        shell: cmd
        run: cmake --preset ninja
        env:
          CMAKE_PREFIX_PATH: ${{ env.QT_ROOT_DIR }}

      - name: Build Ninja
        run: cmake --build --preset ninja

      - name: Test Ninja
        run: ctest --preset ninja
